typetools/checker-framework

- checker/manual/creating-a-checker.tex
vs RBCommons's diff, I've added some minor typo fixes and a link to chapter 29.6 (Visitor: Type rules) which states the basic typing rules applied by the BaseTypeVisitor.
> CF Manual Create a Checker Chapter Update

- framework/src/org/checkerframework/common/basetype/BaseTypeVisitor.java
- framework/src/org/checkerframework/framework/type/GenericAnnotatedTypeFactory.java
- framework/src/org/checkerframework/qualframework/base/QualifiedTypeFactoryAdapter.java
This is a tiny change, but this is my first github pull request and I wanted to submit something the "official" way! I noticed that some comments were out of date, so this change fixes that.
> Updated comments according to an earlier rename.

- checker/tests/nullness/generics/Issue459.java
- framework/src/org/checkerframework/framework/util/typeinference/DefaultTypeArgumentInference.java
- framework/src/org/checkerframework/framework/util/typeinference/solver/SubtypesSolver.java
- framework/src/org/checkerframework/framework/util/typeinference/solver/SupertypesSolver.java
…erring type arguments without an assignment context.  Fix for issue 459
> Fix for Issue 459

- checker/build.xml
- checker/examples/units-extension/Demo.java
- checker/examples/units-extension/Expected.txt
- checker/examples/units-extension/FrequencyRelations.java
- checker/examples/units-extension/Makefile
- checker/examples/units-extension/README
- checker/examples/units-extension/kHz.java
- checker/src/org/checkerframework/checker/units/UnitsAnnotatedTypeFactory.java
- checker/src/org/checkerframework/checker/units/UnitsAnnotatedTypeFormatter.java
- checker/src/org/checkerframework/checker/units/UnitsRelations.java
- checker/src/org/checkerframework/checker/units/UnitsRelationsDefault.java
- checker/src/org/checkerframework/checker/units/UnitsRelationsTools.java
- checker/src/org/checkerframework/checker/units/UnitsTools.java
- checker/src/org/checkerframework/checker/units/qual/MixedUnits.java
- checker/tests/units-extension
- checker/tests/units/BasicUnits.java
- framework/src/org/checkerframework/framework/type/DefaultAnnotatedTypeFormatter.java
- framework/src/org/checkerframework/framework/util/MultiGraphQualifierHierarchy.java
- Fixed a bug where units checker extension projects' UnitsRelations classes were not being loaded properly
- Updated units-extension demo project with correct implementation of FrequencyRelations, added an additional test case to ensure that scalar/second results in @Hz annotation
- Fixed reference issues to the set of units relations in Units ATF
> Fixed units-extension bugs and Units ATF reference

- framework/src/org/checkerframework/framework/qual/DefaultQualifier.java
- framework/src/org/checkerframework/framework/util/defaults/QualifierDefaults.java
- release/release.xml
- release/release_build.py
- release/release_push.py
- release/release_utils.py
- release/release_vars.py
- release/types.htaccess
I probably only need @jthaine to look at this but others are welcome.
> Update release scripts from last release

- checker/tests/nullness/java8/Issue448.java
This adds a test to demonstrate Issue #448. The command and stacktrace for the error are as follows:
```bash
> $CHECKERFRAMEWORK/checker/bin-devel/javac -processor org.checkerframework.checker.nullness.NullnessChecker -implicit:class Issue448.java
```
```
error: SourceChecker.typeProcess: unexpected Throwable (NullPointerException) while processing Issue448.java
Compilation unit: Issue448.java
Exception: java.lang.NullPointerException; Stack trace: org.checkerframework.framework.type.GenericAnnotatedTypeFactory.getStoreBefore(GenericAnnotatedTypeFactory.java:539)
org.checkerframework.checker.nullness.KeyForAnnotatedTypeFactory.canonicalizeKeyForValues(KeyForAnnotatedTypeFactory.java:475)
org.checkerframework.checker.nullness.KeyForAnnotatedTypeFactory.canonicalizeKeyForValuesGetAnnotationM …
```
> Add test for Issue #448.

- checker/manual/troubleshooting.tex
Added a note on using bin-devel in PATH variable for developers.
Made it a bit more clear regarding the purpose of adding the jars to the classpath.
> Compile From Source Chapter Update

- framework/tests/flow2/Purity.java
- framework/tests/purity-suggestions/Test.java
Test coverage for some warnings issued by purity checking was missing.
> Add missing purity checking test coverage

- checker/jtreg/nullness/issue257/Module-err.out
- checker/jtreg/nullness/issue257/Module.java
(And it no longer does now that #511 is fixed)
> According to #257 this test case should not issue a warning.

- checker/build.xml
- checker/manual/advanced-features.tex
- checker/manual/introduction.tex
- checker/tests/nullness-safedefaultsbytecode/BasicTest.java
- checker/tests/nullness-safedefaultssourcecode/BasicTest.java
- checker/tests/nullness-safedefaultssourcecodelib/Lib.java
- checker/tests/src/tests/NullnessSafeDefaultsBytecodeTest.java
- checker/tests/src/tests/NullnessSafeDefaultsSourceCodeLibTest.java
- checker/tests/src/tests/NullnessSafeDefaultsSourceCodeTest.java
- framework/build.xml
- framework/jtreg/BinaryDefaultTest.java
- framework/src/org/checkerframework/common/value/ValueAnnotatedTypeFactory.java
- framework/src/org/checkerframework/framework/qual/AnnotatedFor.java
- framework/src/org/checkerframework/framework/qual/DefaultInUncheckedCodeFor.java
- framework/src/org/checkerframework/framework/qual/DefaultQualifierInHierarchyInUncheckedCode.java
- framework/src/org/checkerframework/framework/source/SourceChecker.java
- framework/src/org/checkerframework/framework/type/GenericAnnotatedTypeFactory.java
- framework/src/org/checkerframework/framework/util/defaults/QualifierDefaults.java
- framework/src/org/checkerframework/qualframework/base/QualifiedTypeFactoryAdapter.java
- framework/tests/src/tests/AnnotatedForTest.java
1. Corrected standard unchecked code defaults
2. Renamed/merged old command line options to useDefaultsForUncheckedCode
> Unchecked code default changes 

- checker/src/org/checkerframework/checker/lock/LockStore.java
- checker/src/org/checkerframework/checker/nullness/KeyForAnnotatedTypeFactory.java
- dataflow/src/org/checkerframework/dataflow/analysis/FlowExpressions.java
- framework/src/org/checkerframework/common/basetype/BaseTypeVisitor.java
- framework/src/org/checkerframework/framework/flow/CFAbstractStore.java
- tutorial/tests/ant.xml
This change fixes issue 524 by wrapping VarSymbol in the
FlowExpressions.LocalVariable class which implements hashCode()
(VarSymbol does not implement hashCode()).
> Fix issue #524

- checker/manual/advanced-features.tex
- checker/src/org/checkerframework/checker/fenum/FenumAnnotatedTypeFactory.java
- checker/src/org/checkerframework/checker/fenum/qual/FenumUnqualified.java
- checker/src/org/checkerframework/checker/igj/qual/Mutable.java
- checker/src/org/checkerframework/checker/initialization/qual/Initialized.java
- checker/src/org/checkerframework/checker/javari/qual/Mutable.java
- checker/src/org/checkerframework/checker/nullness/qual/NonNull.java
- checker/src/org/checkerframework/checker/nullness/qual/NonRaw.java
- checker/src/org/checkerframework/checker/nullness/qual/Nullable.java
- checker/src/org/checkerframework/checker/oigj/ImmutabilityAnnotatedTypeFactory.java
- checker/src/org/checkerframework/checker/oigj/OIGJMutabilityBottom.java
- checker/src/org/checkerframework/checker/oigj/OwnershipAnnotatedTypeFactory.java
- checker/src/org/checkerframework/checker/oigj/qual/Modifier.java
- checker/src/org/checkerframework/checker/oigj/qual/Mutable.java
- checker/src/org/checkerframework/checker/oigj/qual/OIGJMutabilityBottom.java
- framework/src/org/checkerframework/common/value/ValueAnnotatedTypeFactory.java
- framework/src/org/checkerframework/framework/qual/DefaultQualifierInHierarchy.java
- framework/src/org/checkerframework/framework/type/GenericAnnotatedTypeFactory.java
- framework/src/org/checkerframework/framework/util/defaults/QualifierDefaults.java
Rebased the changes from PR #561
> CLIMB standard defaults (rebased)

- checker/jdk/nullness/src/java/lang/Process.java
> Correct Process get*Stream nullness annotations

- checker/manual/annotating-libraries.tex
- checker/manual/introduction.tex
- checker/tests/nullness-extra/Makefile
- checker/tests/nullness-extra/issue559/Expected.txt
- checker/tests/nullness-extra/issue559/Issue559.java
- checker/tests/nullness-extra/issue559/Makefile
- checker/tests/nullness-extra/issue559/myjdk.astub
- framework/src/org/checkerframework/framework/source/SourceChecker.java
- framework/src/org/checkerframework/framework/stub/StubParser.java
Add a test for Issue #559. Fix it by adding StubParser.handleExistingAnnotations.
Code can be improved once the StubParser understands '@AnnotatedFor`.
> Add test and fix for Issue #559

- framework/src/org/checkerframework/framework/source/SourceChecker.java
- framework/src/org/checkerframework/framework/type/AnnotatedTypeFactory.java
atfDoNotReadCache (don't read AnnotatedTypeFactory caches)
atfDoNotCache (don't put things in AnnotatedTypeFactory caches)
atfCacheSize=int (Set the AnnotatedTypeFactory caches' size)
> Add three new debugging options:

- framework/src/org/checkerframework/framework/source/SourceChecker.java
- framework/src/org/checkerframework/framework/type/AnnotatedTypeFactory.java
Reverts typetools/checker-framework#597
> Revert "Add three new debugging options:"

- checker/manual/figures/lock-guardedby.svg
- checker/manual/lock-checker.tex
- checker/src/org/checkerframework/checker/lock/LockAnnotatedTypeFactory.java
- checker/src/org/checkerframework/checker/lock/LockTransfer.java
- checker/src/org/checkerframework/checker/lock/LockVisitor.java
- checker/src/org/checkerframework/checker/lock/qual/GuardSatisfied.java
- checker/src/org/checkerframework/checker/lock/qual/GuardedBy.java
- checker/src/org/checkerframework/checker/lock/qual/GuardedByUnknown.java
- checker/src/org/checkerframework/checker/lock/qual/PolyGuardedBy.java
- checker/src/org/checkerframework/checker/lock/qual/ReleasesNoLocks.java
- checker/tests/lock-safedefaults/BasicTest.java
- checker/tests/lock/ChapterExamples.java
- checker/tests/lock/TestTreeKinds.java
- framework/tests/all-systems/GenericNull.java
@GuardedByUnknown, and make small improvements to the Lock Checker chapter.
The changes to manually review are in lock-checker.tex and ReleasesNoLocks.java. The remaining changes are due to the rename of @GuardedByInaccessible to @GuardedByUnknown.
> Update javadoc for @ReleasesNoLocks, rename @GuardedByInaccessible to

- release/release.xml
Tested these changes and they seem to work as intended.
> Update the CF version in the Gradle examples

- checker/tests/nullness-extra/Makefile
- checker/tests/nullness-extra/issue607/Issue607.java
- checker/tests/nullness-extra/issue607/Issue607Interface.java
- checker/tests/nullness-extra/issue607/Issue607SuperClass.java
- checker/tests/nullness-extra/issue607/Makefile
> add test case for issue607

- framework/src/org/checkerframework/framework/source/SourceChecker.java
- framework/src/org/checkerframework/framework/type/AnnotatedTypeFactory.java
- framework/src/org/checkerframework/framework/type/GenericAnnotatedTypeFactory.java
Also, refactor the code that sends stub files to the stub parser
to make easier to read.
> Rename "indexType" to names with "stubFile" in them

- checker/src/org/checkerframework/checker/lock/LockVisitor.java
- checker/tests/lock/Simple.java
Refactor check field or array access code
> (Merging into Lock Checker branch) Refactor check field or array access code

- checker/tests/nullness/InferTypeArgsCondtionalExpression.java
- checker/tests/nullness/Issue579Error.java
- checker/tests/nullness/java8/Issue579.java
- framework/src/org/checkerframework/framework/type/DefaultRawnessComparer.java
- framework/tests/all-systems/InferTypeArgsCondtionalExpression.java
(Continuation of PR #628.  Comments there have been addressed here.)
> Fixes 579 and related crash

- checker/tests/nullness/Issue580.java
- framework/src/org/checkerframework/framework/flow/CFAbstractAnalysis.java
Must fully scan the type and set every annotation postion to the top annotations
> Fixes #580

- checker/tests/nullness/java8/lambda/Issue572.java
- framework/src/org/checkerframework/framework/type/AnnotatedTypeFactory.java
> Issue #572: Skip parenthesized trees.

- framework/src/org/checkerframework/framework/type/AnnotatedTypeFactory.java
- framework/src/org/checkerframework/framework/type/GenericAnnotatedTypeFactory.java
- framework/src/org/checkerframework/framework/type/TypeFromExpressionVisitor.java
> (Rebased) AnnotatedTypeFactory: reduce number of public methods and improve Javadocs

- checker/manual/external-tools.tex
> Add instructions for Android plugin for Gradle

- javacutil/src/org/checkerframework/javacutil/Resolver.java
(The diff looks funny because I moved some code, but the smaller diff was code that I didn't move.)
> Make variables static, set in static initializer block

- release/checker-excludes
- release/checker-includes
- release/release.xml
- release/release_build.py
- release/release_utils.py
Clean the repos on every release_build run unless told otherwise by the user, and
move files from zipfileset tags in release.xml to the includes/excludes files.
> Release scripts fixes

- checker/tests/nullness/Issue391.java
- javacutil/src/org/checkerframework/javacutil/Resolver.java
This is ready for review, but please don't merge yet - I need to push a fix to Daikon first.
> Fix issue #391 for retrieval of fields only

- checker/tests/nullness/Issue471.java
- checker/tests/nullness/generics/Issue783b.java
- framework/src/org/checkerframework/framework/util/element/TypeVarUseApplier.java
The problem was  that `javax.annotation.Nullable` is a declaration annotation and declaration annotations  on type variables were not applied to AnnotatedTypeVariables.
> Fixes #471

- checker/tests/nullness/Issue759.java
- framework/src/org/checkerframework/framework/type/DefaultTypeHierarchy.java
- framework/tests/all-systems/Issue759.java
> Fixes 759: Correct isSubtype for two wildcards

- checker/tests/nullness/Issue764.java
- framework/src/org/checkerframework/framework/util/FlowExpressionParseUtil.java
Note that this pull request is against branch issue657, since that is the branch that the issue reproduces on.
> Fix issue #764: Flow Expression parser: cannot parse expression referring to static field of outer class

- framework/src/org/checkerframework/framework/util/typeinference/TypeArgInferenceUtil.java
- framework/tests/all-systems/Issue808.java
> Type argument inference: handle varargs

- javacutil/src/org/checkerframework/javacutil/TypesUtils.java
add method `boolean isAnonymous(TypeMirror type)` to check whether a TypeMirror is Anonymous type.
> add isAnonymous

- changelog.txt
> Improve changelog

- checker/tests/nullness/Issue829.java
- framework/src/org/checkerframework/framework/type/TypeFromExpressionVisitor.java
> Ternary expressions with null and primitive (Fixes #829)

- checker/jtreg/nullness/issue820/Class1.java
- checker/jtreg/nullness/issue820/Class1Min.java
- checker/jtreg/nullness/issue820/Class2Class1-err.out
- checker/jtreg/nullness/issue820/Error.java
- checker/tests/lock/ChapterExamples.java
- checker/tests/nullness/AssertIfChecked.java
- checker/tests/nullness/AssertIfClient.java
- checker/tests/nullness/EnsuresNonNullIfTest3.java
- checker/tests/nullness/FinalVar.java
- checker/tests/nullness/java8/lambda/FinalLocalVariables.java
- framework/tests/flow2/MetaPrecondition.java
- framework/tests/flow2/ParamFlowExpr.java
- framework/tests/flow2/Precondition.java
- javacutil/src/org/checkerframework/javacutil/AbstractTypeProcessor.java
Adapt the compile policy when errors exist.
> Fix Issue #820

- checker/tests/regex/Issue809.java
- framework/src/org/checkerframework/qualframework/base/TypeVariableSubstitutorAdapter.java
> Fixes 809 (Regex Checker Crash)

- framework/src/org/checkerframework/common/value/ValueAnnotatedTypeFactory.java
- framework/src/org/checkerframework/framework/type/GenericAnnotatedTypeFactory.java
Removed Value Checker specific work around for #867 and add a more general one.
> Work around for #867 (Postfixed increments and decrements)

- framework/src/org/checkerframework/common/basetype/BaseTypeVisitor.java
- framework/src/org/checkerframework/framework/util/QualifierPolymorphism.java
- framework/tests/all-systems/java8/memberref/Issue871.java
- framework/tests/all-systems/java8/memberref/VarArgs.java
> Fixes #871 (Method reference crash)

- checker/src/org/checkerframework/checker/compilermsgs/CompilerMessagesAnnotatedTypeFactory.java
- checker/src/org/checkerframework/checker/compilermsgs/qual/CompilerMessageKeyBottom.java
- checker/src/org/checkerframework/checker/compilermsgs/qual/UnknownCompilerMessageKey.java
- checker/src/org/checkerframework/checker/i18n/LocalizableKeyAnnotatedTypeFactory.java
- checker/src/org/checkerframework/checker/i18n/qual/LocalizableKeyBottom.java
- checker/src/org/checkerframework/checker/i18n/qual/UnknownLocalizableKey.java
- checker/src/org/checkerframework/checker/propkey/PropertyKeyAnnotatedTypeFactory.java
- checker/src/org/checkerframework/checker/propkey/qual/PropertyKeyBottom.java
to the I18n and Compiler Message Key Checkers. Overall the code got much nicer.
I didn't see any changes in the manual, but maybe somebody else sees a place where these changes should be documented.
> Address Issue 857 by adding additional qualifiers

- framework/src/org/checkerframework/framework/type/DefaultTypeHierarchy.java
- javacutil/src/org/checkerframework/javacutil/InternalUtils.java
> Correct subtyping for captured wildcard and uncaptured wildcard (Issue 870)

- checker/src/org/checkerframework/checker/units/UnitsAnnotatedTypeFactory.java
- checker/src/org/checkerframework/checker/units/qual/UnitsRelations.java
(This is a pre-step to fixing #863)
> Make qual/UnitsRelations not depend on classes outside of checker-qual

- framework/src/org/checkerframework/framework/util/typeinference/DefaultTypeArgumentInference.java
- framework/tests/all-systems/Issue888.java
> Box type arguments inferred to be primitives (Fixes #888)

- checker/jdk/lock/src/java/lang/String.java
This fixes the daikon typecheck failure.
> Add annotations for the Lock Checker to String class

- checker/tests/nullness/flow/Issue818.java
- dataflow/src/org/checkerframework/dataflow/cfg/CFGBuilder.java
- dataflow/src/org/checkerframework/dataflow/cfg/node/ClassNameNode.java
> Fixes #818 (Static fields in dataflow)

- build.xml
- checker/tests/nullness/Issue764.java
- framework/src/org/checkerframework/framework/util/FlowExpressionParseUtil.java
Fixes #764.
(Merge codespecs/daikon#75 after this is merged.)
> Fixes #764 (Flow expression parsing of static fields)

- checker/jtreg/tainting/classes/Issue919.java
- checker/jtreg/tainting/classes/Issue919B.java
- checker/jtreg/tainting/test/Issue919.java
- framework/src/org/checkerframework/framework/type/AnnotatedTypeFactory.java
> Clear tree caches when the compilation unit changes (Fixes #919)

- checker/src/org/checkerframework/checker/lock/LockVisitor.java
- framework/src/org/checkerframework/common/basetype/BaseTypeVisitor.java
- framework/src/org/checkerframework/framework/flow/CFAbstractTransfer.java
- framework/src/org/checkerframework/framework/util/ContractsUtils.java
Tested with daikon-typecheck https://travis-ci.org/smillst/daikon-typecheck/builds/176187223
> Refactor pre and post condition code to reduce code duplication.

- checker/tests/nullness/java8/lambda/Issue953b.java
- framework/src/org/checkerframework/framework/util/typeinference/solver/SupertypesSolver.java
This fixes the second example in #953.
> Fix type argument inference crash

- framework/src/org/checkerframework/common/basetype/BaseTypeVisitor.java
- framework/src/org/checkerframework/framework/type/visitor/SimpleAnnotatedTypeScanner.java
> Improve check for whether the found and required types should be printed verbosely.

- framework/src/org/checkerframework/framework/type/TypeFromExpressionVisitor.java
- framework/tests/all-systems/FieldAccess.java
- framework/tests/all-systems/Issue1003.java
Fixes #1003 and two other crashes related to field access on intersections and union types.
> Allow more field accesses. (Fixes 1003)

- checker/src/org/checkerframework/checker/index/samelen/SameLenAnnotatedTypeFactory.java
Make order of string arguments to `@SameLen` deterministic.
> Deterministic same len

- checker/src/org/checkerframework/checker/index/IndexMethodIdentifier.java
- checker/src/org/checkerframework/checker/index/upperbound/UpperBoundAnnotatedTypeFactory.java
- checker/tests/upperbound/RandomTest.java
This handles [this issue](https://github.com/kelloggm/checker-framework/issues/46) in my fork. See the conversation about the issue for why this needed to be solved with a special case in the checker instead of a JDK annotation, as was originally proposed.
> Add random special case to UBC

- checker/src/org/checkerframework/checker/index/qual/LTEqLengthOf.java
- checker/src/org/checkerframework/checker/index/qual/LTLengthOf.java
- checker/src/org/checkerframework/checker/index/qual/LTOMLengthOf.java
- checker/src/org/checkerframework/checker/index/qual/SameLen.java
- checker/src/org/checkerframework/checker/index/samelen/SameLenAnnotatedTypeFactory.java
- checker/src/org/checkerframework/checker/index/upperbound/UpperBoundAnnotatedTypeFactory.java
- checker/src/org/checkerframework/checker/lock/LockAnnotatedTypeFactory.java
- checker/src/org/checkerframework/checker/lock/qual/GuardedBy.java
- checker/src/org/checkerframework/checker/nullness/KeyForAnnotatedTypeFactory.java
- checker/src/org/checkerframework/checker/nullness/qual/KeyFor.java
- docs/manual/creating-a-checker.tex
- framework/src/org/checkerframework/framework/qual/JavaExpression.java
- framework/src/org/checkerframework/framework/type/GenericAnnotatedTypeFactory.java
- framework/src/org/checkerframework/framework/util/dependenttypes/DependentTypesHelper.java
- framework/tests/src/testlib/flowexpression/FlowExpressionAnnotatedTypeFactory.java
- framework/tests/src/testlib/flowexpression/qual/FlowExp.java
Add an annotation to indicate that an annotation element is a Java expression.
> Adds a dependent type meta-annotation

- checker/src/org/checkerframework/checker/index/Checker-dependencies.txt
Explains the dependencies between the various index checker components. Helpful as documentation, requested by Mike.
> Dependency explanation

- framework/tests/all-systems/Issue1043.java
- javacutil/src/org/checkerframework/javacutil/TreeUtils.java
> Fix Issue #1043 by using the right assignment context for

- checker/tests/nullness/Issue1059.java
- javacutil/src/org/checkerframework/javacutil/Resolver.java
Handle exceptions when getting the scope in a hacky way.
> Test case and fix for Issue #1059.

- checker/src/org/checkerframework/checker/index/qual/LTLengthOf.java
- docs/manual/index-checker.tex
Still needs to be documented in the manual.
> Index Checker: Document offset in @LTLengthOf

- checker/src/org/checkerframework/checker/index/upperbound/UpperBoundTransfer.java
- checker/tests/index/LessThanLen.java
If the expression is known to be the length of some array and the other operand is nonnegative or positive.
Fixes kelloggm/issue#88
> Index Checker: Refine the operands of multiplication expressions.

- framework/src/org/checkerframework/framework/util/AtmLubVisitor.java
- framework/tests/all-systems/Issue1049.java
> Avoid stack overflow

- framework/src/org/checkerframework/framework/type/DefaultAnnotatedTypeFormatter.java
> Use , between type parameters.

- checker/src/org/checkerframework/checker/guieffect/GuiEffectVisitor.java
- checker/src/org/checkerframework/checker/initialization/InitializationVisitor.java
- checker/src/org/checkerframework/checker/interning/InterningVisitor.java
- checker/src/org/checkerframework/checker/lock/LockVisitor.java
- framework/src/org/checkerframework/common/basetype/BaseTypeVisitor.java
- framework/src/org/checkerframework/common/util/debug/TypeOutputtingChecker.java
- framework/src/org/checkerframework/common/util/report/ReportVisitor.java
> Make subclasses of BaseTypeVisitor obey skipDefs.

- checker/tests/nullness/Issue1046.java
- checker/tests/nullness/java8/Issue1046.java
- framework/src/org/checkerframework/framework/type/AsSuperVisitor.java
> Correct asSuper for lower bounded wildcards

- checker/tests/nullness/java8inference/Issue402.java
- framework/src/org/checkerframework/framework/type/DefaultTypeHierarchy.java
- framework/src/org/checkerframework/framework/util/AtmLubVisitor.java
- framework/src/org/checkerframework/framework/util/QualifierPolymorphism.java
- framework/tests/all-systems/Issue1006.java
> Fix problems with superbounded wildcards

- checker/tests/nullness/generics/InferMethod.java
- checker/tests/nullness/generics/Issue134.java
- framework/src/org/checkerframework/framework/type/AnnotatedTypeCopier.java
- framework/src/org/checkerframework/framework/type/AnnotatedTypeMirror.java
- framework/src/org/checkerframework/framework/type/DefaultAnnotatedTypeFormatter.java
- framework/src/org/checkerframework/framework/util/AnnotatedTypes.java
- framework/src/org/checkerframework/framework/util/QualifierPolymorphism.java
- framework/tests/all-systems/Issue263.java
- framework/tests/all-systems/Issue437.java
- framework/tests/all-systems/Issue577.java
- framework/tests/framework/GenericTest4.java
arguments of enclosing classes, output enclosing classes in error
messages, and enable and add related tests.
> Improvements to handling of nested classes: correctly populate type

- checker/build.xml
- docs/api
> Create symlink after link directory is built

- checker/src/org/checkerframework/checker/nullness/NullnessVisitor.java
- checker/tests/nullness/Boxing.java
- checker/tests/nullness/Casts.java
- checker/tests/nullness/TypeVarPrimitives.java
- checker/tests/nullness/Unboxing.java
> Issue unboxing.of.nullable in more places

- checker/jdk/index/src/java/lang/String.java
I'm pretty sure they're all commented out now.
> Comment out more annotations in String.

- checker/tests/nullness/Issue1102.java
- framework/src/org/checkerframework/framework/util/typeinference/constraint/AFReducingVisitor.java
- framework/tests/all-systems/Issue1102.java
Includes a general and a specific test case.
> Fix #1102 by covering the typevar - intersection combination.

- checker/src/org/checkerframework/checker/index/upperbound/UBQualifier.java
- checker/src/org/checkerframework/checker/index/upperbound/UpperBoundVisitor.java
- checker/tests/index/ConstantArrays.java
> Index Checker: update common assignment checks to properly descend into constant arrays

- checker/jdk/index/src/java/util/AbstractList.java
- checker/jdk/index/src/java/util/AbstractMap.java
- checker/jdk/index/src/java/util/Deque.java
- checker/jdk/index/src/java/util/Dictionary.java
- checker/jdk/index/src/java/util/HashSet.java
- checker/jdk/index/src/java/util/Set.java
- checker/jdk/index/src/java/util/TreeMap.java
- checker/jdk/index/src/java/util/TreeSet.java
Fixes kelloggm#114 (hopefully).
> Updates to jdk so that common classes with size() methods are annotated

- checker/jtreg/nullness/preciseErrorMsg/Class1.java
- checker/jtreg/nullness/preciseErrorMsg/Class1.out
- checker/tests/nullness/RequiresNonNullTest.java
- framework/src/org/checkerframework/framework/flow/CFAbstractTransfer.java
> Only report error in Pre/Post condition expression once.

- checker/src/org/checkerframework/checker/index/lowerbound/LowerBoundAnnotatedTypeFactory.java
- checker/src/org/checkerframework/checker/index/upperbound/UpperBoundAnnotatedTypeFactory.java
- checker/tests/index/AndExample.java
- checker/tests/index/IntroAnd.java
> Correct semantics for &

- checker/src/org/checkerframework/checker/index/lowerbound/LowerBoundAnnotatedTypeFactory.java
- checker/src/org/checkerframework/checker/index/minlen/MinLenAnnotatedTypeFactory.java
- checker/tests/index/Polymorphic.java
Fixes kelloggm/checker-framework#129
> Account for @PolyMinLen in more places

- checker/src/org/checkerframework/checker/index/samelen/SameLenTransfer.java
- checker/tests/index/SameLenTripleThreat.java
> Fixes SameLen bug with multiple arrays

- checker/src/org/checkerframework/checker/index/samelen/SameLenAnnotatedTypeFactory.java
- checker/src/org/checkerframework/checker/index/upperbound/UBQualifier.java
- checker/src/org/checkerframework/checker/index/upperbound/UpperBoundAnnotatedTypeFactory.java
- checker/src/org/checkerframework/checker/index/upperbound/UpperBoundVisitor.java
- checker/tests/index/ArrayAssignmentSameLen.java
- checker/tests/index/ArrayAssignmentSameLenComplex.java
Fixes kelloggm#124's simple form. I opened kelloggm#127 to describe the more complex version.
> Adds SameLen check to UBC common assignment check

- checker/src/org/checkerframework/checker/fenum/FenumAnnotatedTypeFactory.java
- checker/src/org/checkerframework/checker/formatter/FormatterAnnotatedTypeFactory.java
- checker/src/org/checkerframework/checker/i18nformatter/I18nFormatterAnnotatedTypeFactory.java
- checker/src/org/checkerframework/checker/index/minlen/MinLenAnnotatedTypeFactory.java
- checker/src/org/checkerframework/checker/index/samelen/SameLenAnnotatedTypeFactory.java
- checker/src/org/checkerframework/checker/index/upperbound/UpperBoundAnnotatedTypeFactory.java
- checker/src/org/checkerframework/checker/lock/LockAnnotatedTypeFactory.java
- checker/src/org/checkerframework/checker/nullness/KeyForAnnotatedTypeFactory.java
- checker/src/org/checkerframework/checker/nullness/NullnessAnnotatedTypeFactory.java
- checker/src/org/checkerframework/checker/regex/RegexAnnotatedTypeFactory.java
- checker/src/org/checkerframework/checker/units/UnitsAnnotatedTypeFactory.java
- framework/src/org/checkerframework/common/aliasing/AliasingAnnotatedTypeFactory.java
- framework/src/org/checkerframework/common/reflection/ClassValAnnotatedTypeFactory.java
- framework/src/org/checkerframework/common/reflection/MethodValAnnotatedTypeFactory.java
- framework/src/org/checkerframework/common/value/ValueAnnotatedTypeFactory.java
- framework/src/org/checkerframework/framework/type/GeneralAnnotatedTypeFactory.java
- framework/src/org/checkerframework/framework/type/QualifierHierarchy.java
- framework/src/org/checkerframework/framework/util/MultiGraphQualifierHierarchy.java
- framework/tests/src/testlib/util/FlowTestAnnotatedTypeFactory.java
- framework/tests/src/testlib/wholeprograminference/WholeProgramInferenceTestAnnotatedTypeFactory.java
> Parameter names in isSubtype methods should be subAnnno/superAnno,

- framework/src/org/checkerframework/common/value/ValueAnnotatedTypeFactory.java
Various code clean up and documentation improvements to the Const. Value Checker.
> Value checker cleanups

- checker/src/org/checkerframework/checker/index/upperbound/UpperBoundTransfer.java
- checker/tests/index/ParserOffsetTest.java
> Index Checker: subterm offsets

- docs/manual/generics.tex
- framework/src/org/checkerframework/framework/source/SourceChecker.java
have been removed a while ago.
> Remove option and documentation for qualifier parameters, which

- checker/jdk/nullness/src/java/util/TreeSet.java
- checker/tests/nullness/TreeSetTest.java
Minor changes to fix certain missed warnings.
> minor fixes to TreeSet.java class

- .travis-build-without-test.sh
- .travis-build.sh
- .travis.yml
Partially reverts commit 705cd1e41a66360bb0c778b7219a6c3e2d6d712c .
> Rebuild instead of downloading annotated JDK.

- framework/src/org/checkerframework/common/reflection/MethodValAnnotatedTypeFactory.java
- framework/src/org/checkerframework/framework/type/AnnotatedTypeFactory.java
Method isn't used much, so I'm directly changing it.
> Fix typo in method name.

- checker/tests/index/Index132.java
This test comes from kelloggm#132 (which, though it mentions this test, is about something more fundamental). It was fixed in typetools#1163, so it should be in the regression suite.
> Index Checker: Add new test

- checker/jtreg/stubs/wildcards/NonN.astub
- checker/jtreg/stubs/wildcards/NonN.java
- checker/jtreg/stubs/wildcards/Wildcards.java
- framework/src/org/checkerframework/framework/stub/StubParser.java
I still need to add the test case (unless it's already somewhere...) but want to see whether anything breaks.
> Fix #1055 by adding type parameter elements when parsing stub files.

- framework/src/org/checkerframework/common/value/ValueTransfer.java
- framework/tests/value/StringValCrash.java
Fixes a crash uncovered by @as56 in the Index Checker case study.
> Fix crash in Value Checker

- framework/src/org/checkerframework/common/value/ValueAnnotatedTypeFactory.java
- framework/src/org/checkerframework/common/value/ValueVisitor.java
- framework/src/org/checkerframework/common/value/messages.properties
- framework/tests/value/EmptyAnnotationArgument.java
- framework/tests/value/NegativeArrayLen.java
- javacutil/src/org/checkerframework/javacutil/InternalUtils.java
Also, issue a warning if an explicit array len has a negative value.  I refactored the code that issue warnings on explicit annotations to use AnnotationMirror so that the code is easier to read.
> Convert @ArrayLen with negative numbers  to bottom

- .travis-build.sh
- .travis.yml
- build-common.properties
- checker/build.xml
- dataflow/src/org/checkerframework/dataflow/analysis/FlowExpressions.java
- framework/src/org/checkerframework/common/basetype/BaseTypeChecker.java
- framework/src/org/checkerframework/common/basetype/BaseTypeVisitor.java
- framework/src/org/checkerframework/common/value/ValueAnnotatedTypeFactory.java
- framework/src/org/checkerframework/framework/flow/CFAbstractAnalysis.java
- framework/src/org/checkerframework/framework/flow/CFAbstractTransfer.java
- framework/src/org/checkerframework/framework/type/GenericAnnotatedTypeFactory.java
- framework/src/org/checkerframework/framework/util/AtmLubVisitor.java
- framework/src/org/checkerframework/framework/util/dependenttypes/DependentTypesHelper.java
- framework/tests/all-systems/LubRawTypes.java
- stubparser/src/org/checkerframework/stubparser/ast/visitor/DumpVisitor.java
Most fixes are simply adding default branches to switches.
However, it also uncovered a real issue in the logic in framework/src/org/checkerframework/framework/util/AtmLubVisitor.java . I simplified the code; let's see whether the tests still work.
> Update error-prone, fix reported issues, and run on travis

- framework/src/org/checkerframework/common/value/ValueAnnotatedTypeFactory.java
- framework/tests/value/LubToRange.java
If the lub exceeds the max number of values, convert to IntRange or ArrayLenRange.
> Correct Lub of IntVal and ArrayLen

- docs/manual/Makefile
- docs/manual/creating-a-checker.tex
These changes clarify some points that I think are confusing for new developers.
> Documentation improvements for "How to create a new checker"

- checker/jdk/index/src/java/io/BufferedWriter.java
- checker/jdk/index/src/java/io/FileSystem.java
- checker/jdk/index/src/java/io/FilterWriter.java
- checker/jdk/index/src/java/io/OutputStreamWriter.java
- checker/jdk/index/src/java/io/PrintWriter.java
- checker/jdk/index/src/java/io/StringWriter.java
- checker/jdk/index/src/java/io/Writer.java
- checker/jdk/index/src/java/lang/CharSequence.java
- checker/jdk/index/src/java/lang/Character.java
- checker/jdk/index/src/java/lang/String.java
- checker/jdk/index/src/java/lang/StringBuffer.java
- checker/jdk/index/src/java/lang/StringBuilder.java
- checker/src/org/checkerframework/checker/index/qual/IndexFor.java
- checker/src/org/checkerframework/checker/index/qual/IndexOrHigh.java
- checker/src/org/checkerframework/checker/index/qual/IndexOrLow.java
- checker/src/org/checkerframework/checker/index/qual/LengthOf.java
Also update JDK annotations in comments so that they're compatible with the new targets.
> Index Checker: add in appropriate annotation targets to Index annotations

- framework/src/org/checkerframework/common/value/ValueTransfer.java
- framework/src/org/checkerframework/common/value/util/ByteMath.java
- framework/src/org/checkerframework/common/value/util/IntegerMath.java
- framework/src/org/checkerframework/common/value/util/LongMath.java
- framework/src/org/checkerframework/common/value/util/NumberMath.java
- framework/src/org/checkerframework/common/value/util/ShortMath.java
- framework/tests/value/DivideByZero.java
> Fix Value Checker crash when dividing by zero.

- checker/jdk/index/src/java/lang/String.java
- checker/jdk/index/src/java/util/regex/Pattern.java
- framework/src/org/checkerframework/common/value/statically-executable.astub
- framework/src/org/checkerframework/framework/stub/StubParser.java
> Move Value annotations out of the Index JDK

- framework/src/org/checkerframework/common/value/ReflectiveEvaluator.java
- framework/src/org/checkerframework/common/value/ValueAnnotatedTypeFactory.java
- framework/src/org/checkerframework/common/value/ValueTransfer.java
- framework/src/org/checkerframework/common/value/util/Range.java
1. In Range, check for NOTHING in more places.
2. Return null if a method fails to be evalutated.
> Value Checker fixes:

- checker/jdk/Makefile.jdk
- checker/jdk/index/Makefile
- checker/jdk/lock/Makefile
- checker/jdk/nullness/Makefile
- docs/manual/annotating-libraries.tex
> Use Makefile include directives instead of symlinks

- checker/tests/index/Index118.java
- checker/tests/index/Index118NoLoop.java
Test cases are from kelloggm#118, and now should pass. This issue was solved by the introduction of range analyses and flow-sensitive refinement in the Value Checker.
> Adds test cases

- framework/src/org/checkerframework/framework/util/AnnotatedTypes.java
- framework/src/org/checkerframework/framework/util/typeinference/DefaultTypeArgumentInference.java
- framework/src/org/checkerframework/framework/util/typeinference/TypeArgInferenceUtil.java
- framework/src/org/checkerframework/framework/util/typeinference/TypeArgumentInference.java
00b24e4 removed the code that used this hack.
> Remove type infer hack

- framework/build.xml
- framework/src/org/checkerframework/common/value/qual/UnknownVal.java
- framework/tests/src/tests/ValueUncheckedDefaultsTest.java
> Correct unchecked defaults for the Value Checker.

- checker/tests/index/SizeVsLength.java
kelloggm#91 contains a test case which passes. This PR adds that test case, so that the old issue can be closed.
> Add test case from old issue to Index Checker test suite

- framework/src/org/checkerframework/framework/util/AnnotatedTypes.java
- framework/tests/all-systems/java8inference/Issue1334.java
> Correctly expand varags (Issue #1334)

- framework/src/org/checkerframework/framework/type/DefaultTypeHierarchy.java
- framework/src/org/checkerframework/framework/util/typeinference/DefaultTypeArgumentInference.java
- framework/src/org/checkerframework/framework/util/typeinference/TypeArgInferenceUtil.java
- framework/tests/all-systems/java8inference/Issue1308.java
- framework/tests/all-systems/java8inference/Issue1312.java
- framework/tests/all-systems/java8inference/Issue1313.java
- framework/tests/all-systems/java8inference/Issue1331.java
- framework/tests/all-systems/java8inference/Issue1332.java
Fixes #1308, Fixes #1312, Fixes  #1313, Fixes #1331, Fixes  #1332
> Return uninferred type arguments when inference fails.

- checker/src/org/checkerframework/checker/initialization/InitializationAnnotatedTypeFactory.java
- checker/src/org/checkerframework/checker/initialization/InitializationTransfer.java
- checker/src/org/checkerframework/checker/nullness/NullnessAnnotatedTypeFactory.java
- checker/tests/nullness/init/Issue1347.java
> Call hasFieldInvariantAnnotation instead of checking annotations.

- framework/src/org/checkerframework/framework/type/treeannotator/PropagationTreeAnnotator.java
- framework/tests/all-systems/java8inference/Issue1397.java
> Fix compound assignment crash (#1397)

- checker/tests/nullness-extra/issue309/Lib.astub
- checker/tests/nullness-extra/issue309/Makefile
- framework/src/org/checkerframework/common/basetype/BaseTypeChecker.java
> Avoid NPE when issuing warnings.

- build-common.properties
- checker/build.xml
- checker/src/org/checkerframework/checker/index/IndexAbstractTransfer.java
- checker/src/org/checkerframework/checker/index/IndexRefinementInfo.java
- checker/src/org/checkerframework/checker/index/samelen/SameLenTransfer.java
- checker/src/org/checkerframework/checker/lock/LockStore.java
- checker/src/org/checkerframework/checker/lock/LockTransfer.java
- checker/src/org/checkerframework/checker/nullness/NullnessTransfer.java
- framework/src/org/checkerframework/common/value/ValueTransfer.java
- framework/src/org/checkerframework/framework/util/typeinference/constraint/FIsA.java
And fix a few errors it points out.
> Upgrade error-prone to version 2.1.0

- docs/examples/GradleExamples/GradleJava7Example/build.gradle
- docs/manual/external-tools.tex
> Update instructions for generating Java 7 bytecode and using

- checker/jtreg/stubs/issue1456/Lib.astub
- checker/jtreg/stubs/issue1456/Main.java
- checker/jtreg/stubs/issue1456lib/Lib.java
- framework/src/org/checkerframework/framework/stub/StubParser.java
> Correctly apply annotations in stub files to types of fields.

- checker/build.xml
- checker/jdk/index/src/java/lang/Math.java
- checker/tests/index/MinMaxIndex.java
I merged #1468 apparently incorrectly, since the tests failed after I reset the JDK. I suspect that I just did it wrong. Assigning this to @smillst who knows how to do it without breaking everything.
> Reopening #1468

- framework/src/org/checkerframework/framework/type/DefaultTypeHierarchy.java
- framework/tests/all-systems/Issue1506.java
> Add Union_Wildcard to isSubtype

- checker/tests/nullness/java8inference/Issue1464.java
- framework/src/org/checkerframework/framework/type/AnnotatedTypeFactory.java
> Correct ground target type of lambdas

- changelog.txt
- framework/src/org/checkerframework/common/aliasing/AliasingVisitor.java
- framework/src/org/checkerframework/common/basetype/BaseTypeVisitor.java
- framework/src/org/checkerframework/framework/type/AnnotatedTypeFactory.java
- framework/src/org/checkerframework/framework/type/AnnotatedTypeMirror.java
- framework/src/org/checkerframework/framework/type/VisitorState.java
- framework/src/org/checkerframework/framework/util/MultiGraphQualifierHierarchy.java
- javacutil/src/org/checkerframework/javacutil/AnnotationBuilder.java
- javacutil/src/org/checkerframework/javacutil/AnnotationUtils.java
More radical approach to fix #1482.
> Cleanup caching

- checker/src/org/checkerframework/checker/index/upperbound/UpperBoundAnnotatedTypeFactory.java
- checker/src/org/checkerframework/checker/initialization/InitializationVisitor.java
- dataflow/src/org/checkerframework/dataflow/analysis/FlowExpressions.java
- dataflow/src/org/checkerframework/dataflow/cfg/CFGBuilder.java
- framework/src/org/checkerframework/common/basetype/BaseTypeChecker.java
- framework/src/org/checkerframework/common/basetype/BaseTypeVisitor.java
- framework/src/org/checkerframework/framework/source/Result.java
- framework/src/org/checkerframework/framework/source/SourceChecker.java
- framework/src/org/checkerframework/framework/stub/AddAnnotatedFor.java
- framework/src/org/checkerframework/framework/stub/ToIndexFileConverter.java
- framework/src/org/checkerframework/framework/test/PerDirectorySuite.java
- framework/src/org/checkerframework/framework/test/PerFileSuite.java
- framework/src/org/checkerframework/framework/type/AnnotatedTypeFactory.java
- framework/src/org/checkerframework/framework/type/AnnotatedTypeMirror.java
- framework/src/org/checkerframework/framework/type/GenericAnnotatedTypeFactory.java
- framework/src/org/checkerframework/framework/type/typeannotator/IrrelevantTypeAnnotator.java
- framework/src/org/checkerframework/framework/util/AnnotatedTypes.java
- javacutil/src/org/checkerframework/javacutil/ElementUtils.java
- javacutil/src/org/checkerframework/javacutil/TypeAnnotationUtils.java
- javacutil/src/org/checkerframework/javacutil/trees/TreeBuilder.java
- javacutil/src/org/checkerframework/javacutil/trees/TreeParser.java
> Cleanup: take advantage of Java 8 enhanced target typing and remove

- docs/examples/MavenExample/Makefile
- docs/examples/MavenExample/pom.xml
- docs/manual/external-tools.tex
- docs/manual/manual.bbl
> Correct Maven instructions

- docs/examples/GradleExamples/GradleJava7Example/build.gradle
- docs/examples/GradleExamples/GradleJava8Example/build.gradle
- docs/manual/external-tools.tex
- docs/manual/manual.bbl
Correction suggested by @tmtron in https://github.com/typetools/checker-framework/issues/1459#issuecomment-329709206.
Fixes #1459.
> Correct Gradle build instructions.

- checker/src/org/checkerframework/checker/nullness/NullnessUtil.java
- checker/tests/nullness/Issue1555.java
> Change the signature of castNonNull to work around false positive

- checker/tests/index/EndsWith2.java
The issue kelloggm#168 has been fixed by merging #1578. This PR enables the corresponding test.
Fixes kelloggm#168.
> Enable passing Index Checker test

- framework/src/org/checkerframework/common/value/RangeOrListOfValues.java
- framework/src/org/checkerframework/common/value/ValueAnnotatedTypeFactory.java
- framework/tests/value/Issue1579.java
> Fix crash in convertToRange() (Issue 1579)

- checker/build.xml
- checker/jdk/index/src/java/lang/String.java
Interning a String does not change its length.
> Add PolyLength annotations to String.intern()

- framework/src/org/checkerframework/framework/flow/CFAbstractTransfer.java
So that both postconditions and conditional postconditions use the same code.  But keep the override points seperate.
> Refactor postcondition code.

- checker/tests/nullness/NullnessFieldInvar.java
- framework/src/org/checkerframework/framework/type/AnnotatedTypeFactory.java
- framework/tests/value/Issue1580.java
> Handle field invariants for fields accessed via type variables.

- checker/tests/index/ArrayLengthLBC.java
- checker/tests/index/ExampleUsage.java
- checker/tests/index/SpecialTransfersForEquality.java
- framework/tests/all-systems/ConditionalExpressions.java
- framework/tests/all-systems/IsSubarrayEq.java
- framework/tests/all-systems/Issue887.java
- framework/tests/all-systems/PolyAllTypeVar.java
- framework/tests/all-systems/RawTypeAssignment.java
- framework/tests/all-systems/StateMatch.java
- framework/tests/all-systems/Throw.java
Based on some stale suppress warnings that Mike noticed.
> Remove spurious suppress warnings in index tests

- checker/jtreg/stubs/issue1456/Lib.astub
- checker/jtreg/stubs/issue1456/Main.java
- checker/jtreg/stubs/issue1456/WithOutStub.out
- checker/jtreg/stubs/issue1456/WithStub.out
- checker/jtreg/stubs/issue1456lib/Lib.java
- framework/src/org/checkerframework/framework/stub/StubParser.java
Also, refactor some of the code so that it is clearer.
(The diffs make it hard to see the changes.  I recommend using the "split" view.)
> Reduce duplicated code in the stubparser

- checker/build.xml
- checker/jdk/index/src/java/util/AbstractList.java
- checker/jdk/index/src/java/util/List.java
- checker/jdk/index/src/java/util/ListIterator.java
- checker/tests/index/ListLowerBound.java
Adds lower bound annotations (`@GTENegativeOne` and `@NonNegative`) to `java.util.List`, `java.util.AbstractList` and `java.util.ListIterator`.
> Add lower bound annotations to List, AbstractList and ListIterator

- framework/src/org/checkerframework/framework/type/BoundsInitializer.java
- framework/tests/all-systems/Issue1690.java
> Fix crash on raw types.

- framework/src/org/checkerframework/framework/util/AtmLubVisitor.java
- framework/tests/all-systems/Issue1708.java
> Don't create new type arguments for raw types.

- .lgtm.yml
Java code wasn't automatically discovered.
> Experiment with lgtm.com support.

- framework/src/org/checkerframework/framework/type/AnnotatedTypeFactory.java
- framework/tests/all-systems/java8inference/Issue1715.java
> Work around uninferred type arguments.

- framework/src/org/checkerframework/framework/type/DefaultTypeHierarchy.java
- framework/tests/all-systems/Issue1709.java
> Correct covariant check

- checker/jtreg/stubs/issue1356/MyClass.astub
- checker/jtreg/stubs/issue1356/mypackage/MyClass.java
- framework/src/org/checkerframework/framework/stub/StubUtil.java
Issued submitted here: https://groups.google.com/d/msg/checker-framework-discuss/kNSqOIkPpZM/Aw2ASYXIDwAJ
> Fix StubParser two dimensional array bug. 

- dataflow/manual/content.tex
Also some slight grammatical cleanup
> Link to NullAway in the dataflow manual

- framework/tests/all-systems/Issue1749.java
> Add a regression test for #1749

- checker/tests/index/GenericAssignment.java
- framework/src/org/checkerframework/common/value/ValueAnnotatedTypeFactory.java
- framework/src/org/checkerframework/common/value/ValueVisitor.java
> Fix Value Checker generic bug.

- checker/src/org/checkerframework/checker/index/IndexMethodIdentifier.java
- checker/src/org/checkerframework/checker/index/IndexUtil.java
- checker/src/org/checkerframework/checker/index/lowerbound/LowerBoundAnnotatedTypeFactory.java
- checker/src/org/checkerframework/checker/index/qual/LengthOf.java
- checker/src/org/checkerframework/checker/index/samelen/SameLenAnnotatedTypeFactory.java
- checker/src/org/checkerframework/checker/index/samelen/SameLenTransfer.java
- checker/src/org/checkerframework/checker/index/upperbound/UpperBoundAnnotatedTypeFactory.java
- checker/src/org/checkerframework/checker/index/upperbound/UpperBoundTransfer.java
- checker/tests/index/Issue194.java
- docs/manual/index-checker.tex
Treat a method annotated with @Length("this") the same as `String#length`.
This fixes kelloggm#194.
> Expand support for custom collections.

- checker/src/org/checkerframework/checker/index/upperbound/UpperBoundTransfer.java
- checker/tests/index/LessThanLen.java
- checker/tests/index/LessThanLenBug.java
> Correct unsoundness in LTLengthOf inference

- checker/src/org/checkerframework/checker/index/lowerbound/LowerBoundAnnotatedTypeFactory.java
- checker/src/org/checkerframework/checker/index/upperbound/UpperBoundAnnotatedTypeFactory.java
- checker/tests/index/Modulo.java
Fixes kelloggm#218 exactly as described there.
> Infer upper bounds for modulo operator

- framework/src/org/checkerframework/common/basetype/BaseTypeVisitor.java
- framework/tests/all-systems/java8/memberref/Issue946.java
> Correct inner class constructor method references.

- framework/src/org/checkerframework/framework/flow/CFCFGBuilder.java
- framework/tests/all-systems/java8inference/Issue1775.java
> Avoid uninferred wildcard crash.

- docs/manual/advanced-features.tex
- docs/manual/faq.tex
- docs/manual/introduction.tex
- docs/manual/manual.tex
Uncomment references to the Index Checker in the manual.  Did I miss any?  (@mernst already wrote the change log entry.)
> Put the Index Checker in the manual.

- framework/src/org/checkerframework/framework/type/TypeFromMemberVisitor.java
- framework/tests/all-systems/java8inference/Issue1815.java
> Fix implicitly typed lambda crash

- docs/manual/external-tools.tex
Work on the NetBeans plug-in in #1592 is abandoned.
> Clarify NetBeans restrictions.

- docs/manual/faq.tex
> docs: fix typo

- framework/src/org/checkerframework/common/basetype/BaseTypeVisitor.java
> Use annotated type mirror verbose toString method more places

- docs/developer/gsoc-ideas.html
This PR is only for discoverability - I'm going to merge it myself.
> Add Index Checker enhancements to GSOC ideas list

- checker/tests/nullness/Issue1847.java
- checker/tests/nullness/Issue1847B.java
- dataflow/src/org/checkerframework/dataflow/analysis/FlowExpressions.java
> Use pos for comparing local variable flow expressions

- checker/src/main/java/org/checkerframework/checker/index/upperbound/messages.properties
- checker/tests/index/Issue1984.java
> Fix Invalid format string.

- framework/src/main/java/org/checkerframework/common/value/statically-executable.astub
- framework/tests/value/LongAndIntegerBitsMethods.java
- jdk8/build.gradle
Also provided test case in framework/tests/value/LongAndIntegerBitsMethods.java
@kelloggm @panacekcz Please take a look, thank you.
> Add IntRange annotations to Long and Integer class in statically-executable.astub

- checker/jdk/Makefile
- jdk8/build.gradle
>  Don't remake jdk8.jar unless it is out of date

- .travis-build-without-test.sh
- .travis-build.sh
- build.gradle
- checker/build.gradle
- checker/jdk/Makefile.jdk
- docs/manual/annotating-libraries.tex
Also, updated the README in https://github.com/typetools/annotated-libraries/pull/5/files.
> Correct build jdk.jar and using it in Gradle tasks.

- checker/build.gradle
- checker/jdk/index/src/java/nio/Buffer.java
- checker/jdk/index/src/java/nio/ByteBuffer.java
Please review and let me know if any changes are needed.
@panacekcz @kelloggm
> Add annotated ByteBuffer and Buffer to jdk

- .travis-build-without-test.sh
- build.gradle
This should be merged in conjunction with https://github.com/typetools/annotation-tools/pull/179.
> Download jsr308-langtools rather than cloning and building.

- checker/jdk/nullness/src/java/lang/ClassLoader.java
to work around another instance of
https://github.com/typetools/checker-framework/issues/1863.
> Comment out an annotation

- framework/src/main/java/org/checkerframework/framework/util/AnnotationMirrorMap.java
- framework/src/main/java/org/checkerframework/framework/util/AnnotationMirrorSet.java
> Add some methods to AnnotationMirrorMap and AnnotationMirrorSet.

- docs/developer/release/README-release-process.html
- docs/developer/release/release_build.py
Improve release docs based on Werner's feedback.  (I still need to fix the bugs in the release scripts that Werner found.)
> Improve release documentation

- checker/jdk/nullness/src/java/util/jar/Attributes.java
- framework/src/main/java/org/checkerframework/common/basetype/messages.properties
Also fix formatting of the error message.
> Fix Issue #2240 by using correct parameter syntax.

- checker/src/main/java/org/checkerframework/checker/lock/LockAnnotatedTypeFactory.java
- framework/src/main/java/org/checkerframework/common/wholeprograminference/WholeProgramInferenceScenesHelper.java
- javacutil/src/main/java/org/checkerframework/javacutil/AnnotationBuilder.java
- javacutil/src/main/java/org/checkerframework/javacutil/AnnotationUtils.java
> Improve documentation in AnnotationBuilder

- framework/src/main/java/org/checkerframework/common/basetype/BaseTypeVisitor.java
This will make a feature addition much simpler.
Review the diffs with a `diff` program that ignores whitespace -- they are smaller than they look, but are bloated by indentation changes.
> Refactor shouldPrintVerbose

- framework/src/main/java/org/checkerframework/common/basetype/BaseTypeVisitor.java
Alternative to #2297 that doesn't make the fields non-final.
> Remove duplication between constructors.

- changelog.txt
- checker/src/main/java/org/checkerframework/checker/nullness/NullnessAnnotatedTypeFactory.java
- docs/manual/nullness-checker.tex
See https://github.com/ReactiveX/RxJava/blob/2.x/src/main/java/io/reactivex/annotations/Nullable.java and https://github.com/ReactiveX/RxJava/blob/2.x/src/main/java/io/reactivex/annotations/NonNull.java.
Also fix a comment typo.
> Add RxJava nullness annotations as aliases

- checker/src/main/java/org/checkerframework/checker/nullness/NullnessAnnotatedTypeFactory.java
This does not fix issue #599, but it fixes part of it and is worth merging on its own.
> Prefer @Initialized to @FBCBottom for array component types

- changelog.txt
- checker/jtreg/nullness/issue2318/RequireCheckerPrefix.java
- checker/jtreg/nullness/issue2318/RequireCheckerPrefix.out
- docs/manual/introduction.tex
- docs/manual/warnings.tex
- framework/src/main/java/org/checkerframework/framework/source/SourceChecker.java
>  Add option to require checker name in warning suppression. (Fixes 2318)

- build.gradle
ci.adaptopenjdk is currently down
> Download jtreg from checkerframework.org

- checker/tests/tainting/TaintingDiamondInference.java
> Don't skip fixed test case.

- build.gradle
Also don't delete docs/api in the requireJavadoc and requireJavadocPrivate tasks.
> If property saveJavadoc is set, then don't delete docs/api 

- checker/src/main/java/org/checkerframework/checker/index/samelen/SameLenTransfer.java
- checker/tests/index/Issue2420.java
> Fix problem with refining equals in SameLen

- checker/src/main/java/org/checkerframework/checker/index/inequality/LessThanTransfer.java
- checker/tests/index/Issue2030.java
> Don't create LessThan annotations with double value

- framework/src/main/java/org/checkerframework/framework/type/AnnotatedTypeFactory.java
- framework/tests/all-systems/Issue2446.java
> Check erased types in AnnotatedTypeFactory#widenToUpperBound

- checker/src/main/java/org/checkerframework/checker/interning/InterningVisitor.java
- checker/src/main/java/org/checkerframework/checker/signedness/SignednessAnnotatedTypeFactory.java
- checker/src/main/java/org/checkerframework/checker/signedness/qual/Constant.java
- checker/tests/signedness/ValueIntegration.java
`@Comment` should be renamed to `@SignednessEither`.
> Treat signed positive values as `@Constant`

- checker/jdk/nullness/src/java/util/Map.java
> Add @Nullable according to JDK javadoc

- docs/manual/external-tools.tex
Fixes https://github.com/typetools/checker-framework/issues/2406.
> Update the IntelliJ instructions.

- checker/tests/index/Issue2494.java
> Enable a test that shouldn't have been skipped

- changelog.txt
- docs/manual/creating-a-checker.tex
With an example! The example is here: https://github.com/typetools/templatefora-checker
> Add text to the manual about where to put a custom checker

- checker/src/main/java/org/checkerframework/checker/signedness/SignednessVisitor.java
- checker/tests/signedness/MaskedShifts.java
- javacutil/src/main/java/org/checkerframework/javacutil/TreeUtils.java
Also add test case for fixed bug.
> Abstract out TreeUtils.enclosingNonParen

- checker/src/main/java/org/checkerframework/checker/index/IndexMethodIdentifier.java
> Change names of some variables that were confusing

- maven-artifacts/poms/localInstall.sh
There is no `maven-artifacts/poms/compilerPom.xml` file.
> Remove broken compilerPom installation.

- changelog.txt
- framework/src/main/java/org/checkerframework/common/basetype/BaseTypeVisitor.java
- framework/src/main/java/org/checkerframework/framework/type/GenericAnnotatedTypeFactory.java
- framework/src/main/java/org/checkerframework/framework/type/poly/AbstractQualifierPolymorphism.java
- framework/src/main/java/org/checkerframework/framework/type/poly/QualifierPolymorphism.java
> Renamed QualifierPolymorphism#annotate methods to resolve.

- changelog.txt
- framework/src/main/java/org/checkerframework/common/aliasing/AliasingVisitor.java
- framework/src/main/java/org/checkerframework/common/basetype/BaseTypeVisitor.java
- framework/src/main/java/org/checkerframework/framework/type/poly/AbstractQualifierPolymorphism.java
- javacutil/src/main/java/org/checkerframework/javacutil/TreeUtils.java
> Rename TreeUtils.isSuperCall and TreeUtils.isThisCall

- checker/tests/index/Issue2505.java
The test case for this issue typechecks.
Fixes #2505 
@kelloggm
> Added issue2505 test case

- checker/tests/nullness/Issue2470.java
- dataflow/src/main/java/org/checkerframework/dataflow/analysis/FlowExpressions.java
> FlowExpression.Receivers for constructor calls are never equal.

- dataflow/src/main/java/org/checkerframework/dataflow/analysis/FlowExpressions.java
- framework/tests/flow2/Equal.java
> Long.valueOf(constant) is not deterministic so don't treat it as such

- docs/manual/external-checkers.tex
This section is referenced from in https://checkerframework.org/manual/#publications.
> Add section about the old Nullness Rawness Checker.

- .travis-build.sh
- build.gradle
- checker/jtreg/multipleexecutions/Main.java
- framework/jtreg/issue845/test/Test.java
- framework/src/main/java/org/checkerframework/framework/type/AnnotationClassLoader.java
This fixes the 4 jtreg test failures.
> Fix the framework jtreg tests on JDK 11

- framework/src/main/java/org/checkerframework/common/basetype/BaseTypeVisitor.java
- framework/src/main/java/org/checkerframework/framework/util/CheckerMain.java
Also, don't check for javac.jar when using 9+.
> Only check for jdk8.jar not jdk11.jar.

- docs/manual/external-tools.tex
> Update Android instructions

- LICENSE.txt
- build.gradle
> Put LICENSE.txt in META-INF for checker.jar.

- framework/src/main/java/org/checkerframework/framework/flow/CFAbstractStore.java
When assignments of FieldAccess/ArrayAccess/LocalVariable don't affect existing information, we end up creating new containers with the same information.
This avoids doing so by looping through the containers using iterator and removing the values if there is conflict.
> Avoid unnecessary removal/re-addition of same values in `removeConflicting`

- framework/src/main/java/org/checkerframework/framework/util/defaults/QualifierDefaults.java
1. Remove unneeded {}
2. Extract common expression to local so it's purpose is clear.
> Clean up part of QualifierDefaults.

- framework/src/main/java/org/checkerframework/common/value/ValueAnnotatedTypeFactory.java
fewer returns in function body
> #2900 Minor syntax changes for source code readability 

- checker/src/main/java/org/checkerframework/checker/formatter/FormatterVisitor.java
- checker/src/main/java/org/checkerframework/checker/i18nformatter/I18nFormatUtil.java
- checker/src/main/java/org/checkerframework/checker/initialization/InitializationAnnotatedTypeFactory.java
- dataflow/src/main/java/org/checkerframework/dataflow/cfg/node/ValueLiteralNode.java
- framework/src/main/java/org/checkerframework/common/reflection/DefaultReflectionResolver.java
- framework/src/main/java/org/checkerframework/common/value/ValueAnnotatedTypeFactory.java
- framework/src/main/java/org/checkerframework/framework/type/BoundsInitializer.java
- framework/src/main/java/org/checkerframework/framework/util/typeinference/constraint/AFReducingVisitor.java
These are the true positives that the Interning Checker found.
> Small fixes found by running the Interning Checker

- build.gradle
> Actually run the Interning Checker.

- framework/src/main/java/org/checkerframework/common/value/RangeOrListOfValues.java
- framework/src/main/java/org/checkerframework/common/value/ValueAnnotatedTypeFactory.java
- framework/src/main/java/org/checkerframework/common/value/ValueCheckerUtils.java
- framework/src/main/java/org/checkerframework/common/value/util/Range.java
- framework/src/main/java/org/checkerframework/framework/type/GenericAnnotatedTypeFactory.java
Minor improvement on client code that uses new Range() by use of new convenience constructors
> #2905 Issue2905 use new Range() constructors

- framework/src/main/java/org/checkerframework/common/value/util/Range.java
valueOf(constant) were turned into static finals;  
8 x valueOf() reduced to 4 x valueOf() on times();
createRangeOrEverything() is an analog to the existing createRangeOrNothing() already present
> Refactored bigRangeToLongRangeFewer and fewer BigInteger.valueOf()

- docs/developer/gsoc-ideas.html
> Fixed typo in GSoC documentation

- framework/src/main/java/org/checkerframework/common/value/ValueAnnotatedTypeFactory.java
- framework/src/main/java/org/checkerframework/common/value/util/Range.java
The constants were already in place. They needed to be used.
Also it becomes evident that isWithinInteger() was being reinvented in client invocations when all that was needed was for it to be public.
> Enforce static finals

- checker/src/main/java/org/checkerframework/checker/index/inequality/LessThanAnnotatedTypeFactory.java
Tiny improvement by not wasting evaluation.
> only evaluate when necessary

- changelog.txt
- framework/src/main/java/org/checkerframework/framework/type/AnnotationClassLoader.java
- framework/src/main/java/org/checkerframework/framework/util/AnnotatedTypes.java
- javacutil/src/main/java/org/checkerframework/javacutil/AnnotationUtils.java
Deprecated AnnotatedTypes#isTypeAnnotation and AnnotatedTypes#hasTypeQualifierElementTypes.
> Move hasTypeQualifierElementTypes to AnnotationUtils

- javacutil/src/main/java/org/checkerframework/javacutil/AnnotationUtils.java
When testing the changes in #2987, I verified that these comments are incorrect.
> Remove incorrect comments.

- checker/tests/interning/InternMethodTest.java
- framework/src/main/java/org/checkerframework/framework/stub/StubParser.java
- javacutil/src/main/java/org/checkerframework/javacutil/AnnotationBuilder.java
This does the first half of the refactoring needed by #2970.
> Don't use AnnotationBuilder.fromName in StubParser

- framework/src/main/java/org/checkerframework/common/basetype/BaseTypeVisitor.java
- framework/src/main/java/org/checkerframework/framework/source/SourceVisitor.java
- framework/src/main/java/org/checkerframework/framework/stub/StubParser.java
- javacutil/src/main/java/org/checkerframework/javacutil/AnnotationBuilder.java
- javacutil/src/main/java/org/checkerframework/javacutil/AnnotationUtils.java
Add Javadoc found missing in #2986.
> Add Javadoc.

- javacutil/src/main/java/org/checkerframework/javacutil/AnnotationBuilder.java
- javacutil/src/main/java/org/checkerframework/javacutil/AnnotationUtils.java
#2989 adds the missing Javadoc that is cause the misc failure.
> Remove AnnotationBuilder static cache

- build.gradle
- docs/manual/introduction.tex
- framework/src/main/java/org/checkerframework/framework/source/SourceChecker.java
Error on JDK versions below 8 and above 12.
> Warn when using JDK version 9, 10, or 12.

- dataflow/src/main/java/org/checkerframework/dataflow/analysis/Analysis.java
This constructor was removed in #2949.
> Add Analysis constructor back and deprecate it

- checker/tests/nullness/Issue3022.java
- framework/src/main/java/org/checkerframework/framework/type/AnnotatedTypeFactory.java
- framework/tests/all-systems/java8inference/Issue2975.java
- javacutil/src/main/java/org/checkerframework/javacutil/TreeUtils.java
> Correct enclosing class for NewClassTrees. (Fixes #3022 and #2975)

- framework/src/main/java/org/checkerframework/framework/stub/StubParser.java
- framework/src/main/java/org/checkerframework/framework/util/FlowExpressionParseUtil.java
https://github.com/typetools/stubparser/pull/29
> [Updating Stubparser] Don't use deprecated javaparser methods.

- checker/build.gradle
> Don't always clone the JDK repository.

- framework/src/main/java/org/checkerframework/common/value/ValueAnnotatedTypeFactory.java
- framework/src/main/java/org/checkerframework/common/value/util/NumberUtils.java
- framework/src/main/java/org/checkerframework/common/value/util/Range.java
- framework/src/test/java/tests/RangeTest.java
The repository in #2942 isn't available anymore. This PR tries to finish that work.
> Reuse existing functions for TypeKind unboxing and range determination

- framework/src/main/java/org/checkerframework/common/basetype/BaseTypeChecker.java
This makes the code more structurally similar to other methods.
> Clarify logic

- checker/build.gradle
- checker/jdk/nullness/src/java/lang/Boolean.java
- checker/jdk/nullness/src/java/lang/Byte.java
- checker/jdk/nullness/src/java/lang/Character.java
- checker/jdk/nullness/src/java/lang/Class.java
- checker/jdk/nullness/src/java/lang/Double.java
- checker/jdk/nullness/src/java/lang/Enum.java
- checker/jdk/nullness/src/java/lang/Float.java
- checker/jdk/nullness/src/java/lang/Integer.java
- checker/jdk/nullness/src/java/lang/Long.java
- checker/jdk/nullness/src/java/lang/Short.java
- checker/jdk/nullness/src/java/lang/StackTraceElement.java
- checker/jdk/nullness/src/java/lang/String.java
- checker/jdk/nullness/src/java/lang/reflect/Constructor.java
- checker/jdk/nullness/src/java/lang/reflect/Field.java
Merge together with https://github.com/typetools/jdk/pull/31
> Remove unnecessary annotations that are inherited; fixes #2793

- checker/jdk/nullness/src/java/lang/AssertionError.java
Corresponding to https://github.com/typetools/jdk/pull/28
> Add AssertionError(String, Throwable) annotations

- docs/developer/developer-manual.html
> Add note about using JDK 11 in IDE.

- framework/src/main/java/org/checkerframework/framework/type/AnnotationClassLoader.java
@msridhar This implements the change suggested in #2893, but I have no way to test whether this actually does any good.
Could you try whether this fixes your original issue?
> Fall back to getURLFromClasspaths (Fixes #2893)

- checker/jdk/nullness/src/java/util/regex/Matcher.java
`checker-framework` version of https://github.com/typetools/jdk/pull/41
> Add `@Nullable` to the `String` overload of `group`.

- checker/jdk/nullness/src/java/lang/ref/PhantomReference.java
- checker/jdk/nullness/src/java/lang/ref/SoftReference.java
- checker/jdk/nullness/src/java/lang/ref/WeakReference.java
- checker/jdk/nullness/src/java/lang/reflect/ParameterizedType.java
- checker/jdk/nullness/src/java/net/URL.java
- checker/jdk/nullness/src/java/util/HashMap.java
- checker/jdk/nullness/src/java/util/Map.java
- checker/jdk/nullness/src/java/util/Objects.java
- checker/jdk/nullness/src/java/util/PriorityQueue.java
- checker/jdk/nullness/src/java/util/SortedMap.java
- checker/jdk/nullness/src/java/util/SortedSet.java
- checker/jdk/nullness/src/java/util/Spliterator.java
- checker/jdk/nullness/src/java/util/TreeMap.java
- checker/jdk/nullness/src/java/util/TreeSet.java
- checker/jdk/nullness/src/java/util/concurrent/ConcurrentSkipListSet.java
- checker/jdk/nullness/src/java/util/regex/Matcher.java
Merge together with https://github.com/typetools/jdk/pull/42
> Add nullability annotations to some JDK APIs

- checker/src/main/java/org/checkerframework/checker/index/qual/EnsuresLTLengthOf.java
- checker/src/main/java/org/checkerframework/checker/index/qual/EnsuresLTLengthOfIf.java
- checker/src/main/java/org/checkerframework/checker/lock/qual/EnsuresLockHeld.java
- checker/src/main/java/org/checkerframework/checker/lock/qual/EnsuresLockHeldIf.java
- checker/src/main/java/org/checkerframework/checker/nullness/qual/EnsuresKeyFor.java
- checker/src/main/java/org/checkerframework/checker/nullness/qual/EnsuresKeyForIf.java
- checker/src/main/java/org/checkerframework/checker/nullness/qual/EnsuresNonNull.java
- checker/src/main/java/org/checkerframework/checker/nullness/qual/EnsuresNonNullIf.java
- dataflow/src/main/java/org/checkerframework/dataflow/analysis/Analysis.java
- framework/src/main/java/org/checkerframework/common/value/qual/EnsuresMinLenIf.java
- framework/src/main/java/org/checkerframework/framework/qual/EnsuresQualifier.java
- framework/src/main/java/org/checkerframework/framework/qual/EnsuresQualifierIf.java
- framework/src/main/java/org/checkerframework/framework/qual/RequiresQualifier.java
- framework/src/main/java/org/checkerframework/framework/type/AnnotatedTypeFactory.java
@wmdietl This pull request is for you to take a quick look at the Javadoc changes I extracted from https://github.com/typetools/checker-framework/pull/3138 at your request.
> Javadoc fixes

- docs/developer/release/release.xml
- docs/developer/release/release_build.py
- docs/developer/release/release_push.py
- docs/developer/release/release_vars.py
- docs/developer/release/sanity_checks.py
Delete code that used to deploy the Maven artifacts.
> Use the new Gradle tasks to deploy Maven artifacts in the release scripts

- checker/src/main/java/org/checkerframework/checker/nullness/NullnessAnnotatedTypeFactory.java
- docs/manual/nullness-checker.tex
> Added RxJava3 annotations

- azure-pipelines.yml
follow-up of https://github.com/typetools/checker-framework/pull/3098 and https://github.com/typetools/checker-framework-inference/pull/151
> Build and test CF Inference under JDK11

- checker/src/test/java/tests/ParseAllJdkTest.java
- checker/tests/parse-all-jdk/Test.java
- docs/manual/creating-a-checker.tex
- docs/manual/introduction.tex
- framework/src/main/java/org/checkerframework/framework/source/SourceChecker.java
- framework/src/main/java/org/checkerframework/framework/stub/StubParser.java
- framework/src/main/java/org/checkerframework/framework/stub/StubTypes.java
Also, add a tests that used that option.
> Add -AparseAllJdk option

- docs/manual/purity-checker.tex
``org.checkerframework.util.PurityChecker`` -> ``org.checkerframework.framework.util.PurityChecker``
> Fix error in manual to solve issue3258

- framework/src/main/java/org/checkerframework/common/value/ValueTypeAnnotator.java
- framework/tests/value/Issue3307.java
> Be more careful with how NumberUtils#isIntegral is called in the Value Checker

- framework/src/main/java/org/checkerframework/framework/stub/JavaStubifier.java
Merge with https://github.com/typetools/stubparser/pull/32.
> Use new JavaParser method.

- framework/tests/value/MyTree.java
mytree.java contains one false positive and cannot be resolved now. Marked for attention.
Added 2 more test cases to help future dev.
> ValueTest mytree.java update

- checker/tests/nullness/ArrayIndex.java
- dataflow/src/main/java/org/checkerframework/dataflow/analysis/FlowExpressions.java
Added binary access to flow expression to handle binary operation in the array index
> Added binary access to flow expression to handle binary operation in the array index

- docs/manual/creating-a-checker.tex
- Fixes casing in suggested section name
- Adds a period
- Corrects a grammar mistake
> Fixes in creating a checker chapter of manual

- framework/src/main/java/org/checkerframework/common/wholeprograminference/SceneToStubWriter.java
- framework/tests/whole-program-inference/non-annotated/MultidimensionalAnnotatedArray.java
> Fix null-pointer crash in Ainfer=stubs

- framework/src/main/java/org/checkerframework/common/wholeprograminference/SceneToStubWriter.java
- framework/tests/whole-program-inference/non-annotated/OuterClassWithTypeParam.java
> Print type parameters correctly for outer classes using -Ainfer=stubs

- checker/src/main/java/org/checkerframework/checker/initialization/InitializationAnnotatedTypeFactory.java
- checker/tests/nullness-safedefaultssourcecode/Issue3449.java
> Default array.length to @Initialized.

- LICENSE.txt
- checker-qual-android/build.gradle
- checker-qual/build.gradle
but exclude it from checker-qual-android.jar.
>  Add SignednessUtilExtra to checker-qual.jar

- azure-pipelines.yml
Reduces time to completion for failed jobs.
Increases time to completion for successful jobs.
> Add dependencies to Azure Pipelines jobs

- checker/tests/nullness/java8/Issue1633.java
Merge with https://github.com/typetools/jdk/pull/66
> Adapt to JDK `@Covariant` annotations

- framework/src/main/java/org/checkerframework/framework/source/SourceChecker.java
> Improve option handling (Fixes #3528)

- framework/src/main/java/org/checkerframework/framework/type/AnnotatedTypeFactory.java
- framework/tests/all-systems/Issue3570.java
> Wildcard upperbound might be null.

- checker/tests/tainting/Issue3562.java
- framework/src/main/java/org/checkerframework/framework/type/TypeFromMemberVisitor.java
- framework/src/main/java/org/checkerframework/framework/util/AnnotatedTypes.java
> Decode annotations on enclosing types correctly

- checker/tests/interning/Issue3594.java
- framework/src/main/java/org/checkerframework/framework/type/AnnotatedTypeFactory.java
> Read inherited declaration annotations from stub files.

- framework/src/main/java/org/checkerframework/framework/type/AnnotatedTypeFactory.java
- framework/src/main/java/org/checkerframework/framework/util/AnnotatedTypes.java
- framework/tests/all-systems/Issue3598.java
- javacutil/src/main/java/org/checkerframework/javacutil/ElementUtils.java
- javacutil/src/main/java/org/checkerframework/javacutil/TypesUtils.java
> Correctly determine if a constructor has a receiver.

- checker/tests/nullness/KeyForStaticField.java
This Pull request was to fix the Testcase for Issue 877: `checker/tests/nullness/KeyForStaticField.java`
> Fixed Testcase for Issue 877

- dataflow/src/main/java/org/checkerframework/dataflow/cfg/AbstractCFGVisualizer.java
* visualizeBlockTransferInputBeforeHelper
* visualizeBlockTransferInputAfterHelper
> Make method implementations more similar

- checker/build.gradle
- checker/src/main/java/org/checkerframework/checker/nullness/NullnessStore.java
- checker/src/main/java/org/checkerframework/checker/nullness/NullnessValue.java
- dataflow/build.gradle
- dataflow/src/main/java/org/checkerframework/dataflow/analysis/AnalysisResult.java
- dataflow/src/main/java/org/checkerframework/dataflow/analysis/TransferInput.java
- framework-test/build.gradle
- framework/build.gradle
- framework/src/main/java/org/checkerframework/framework/flow/CFAbstractStore.java
- javacutil/build.gradle
This helps to correlate logging against final output.
> Add unique ID to some printed representations

- framework/src/main/java/org/checkerframework/common/basetype/BaseTypeVisitor.java
- framework/src/main/java/org/checkerframework/common/basetype/messages.properties
Fixes https://github.com/typetools/checker-framework/issues/3619
> Improve error messages for preconditions and postconditions

- dataflow/src/main/java/org/checkerframework/dataflow/cfg/AbstractCFGVisualizer.java
- dataflow/src/main/java/org/checkerframework/dataflow/cfg/DOTCFGVisualizer.java
- dataflow/src/main/java/org/checkerframework/dataflow/cfg/StringCFGVisualizer.java
Replaces:
* visualizeBlockTransferInputBeforeHelper
* visualizeBlockTransferInputAfterHelper
> New method visualizeBlockTransferInputHelper

- checker/tests/nullness/Issue3622.java
- dataflow/src/main/java/org/checkerframework/dataflow/analysis/ForwardAnalysisImpl.java
- dataflow/src/main/java/org/checkerframework/dataflow/analysis/Store.java
- dataflow/src/main/java/org/checkerframework/dataflow/cfg/CFGBuilder.java
- framework/src/main/java/org/checkerframework/framework/flow/CFAbstractTransfer.java
> Propagate conditional stores through ?: conditional expressions

- checker/tests/nullness/MonotonicNonNullFieldTest.java
This issue has been fixed.  Closes #553.
> Add passing test for issue 553

- checker/src/main/java/org/checkerframework/checker/signedness/SignednessVisitor.java
- checker/tests/signedness/UnsignedRightShiftTest.java
- docs/manual/signedness-checker.tex
> Handle unannotated casts like annotated casts

- changelog.txt
- checker/src/main/java/org/checkerframework/checker/signedness/SignednessAnnotatedTypeFactory.java
- dataflow/src/main/java/org/checkerframework/dataflow/cfg/CFGBuilder.java
- framework/src/main/java/org/checkerframework/common/value/ValueAnnotatedTypeFactory.java
- framework/src/main/java/org/checkerframework/common/value/ValueTransfer.java
- framework/src/main/java/org/checkerframework/common/value/ValueTypeAnnotator.java
- framework/src/main/java/org/checkerframework/common/value/ValueVisitor.java
- framework/src/main/java/org/checkerframework/common/value/util/NumberUtils.java
- javacutil/src/main/java/org/checkerframework/javacutil/AnnotationBuilder.java
- javacutil/src/main/java/org/checkerframework/javacutil/TypeKindUtils.java
- javacutil/src/main/java/org/checkerframework/javacutil/TypesUtils.java
The diff in `changelog.txt` explains the main changes (besides addition of some new methods).
The messy diff in `TypesUtils.java` is mostly rearranging existing methods to bring related methods near one another.
> Refactor TypesUtils and NumberUtils; add TypeKindUtils

- dataflow/src/main/java/org/checkerframework/dataflow/analysis/TransferInput.java
This makes it easier to debug problems with TransferInputs.
> Route TransferInput construction through a single constructor

- .editorconfig
> Add .editorconfig for automatic IDE configuration

- checker/bin-devel/test-misc.sh
- framework-test/src/main/java/org/checkerframework/framework/test/TypecheckResult.java
Reinstate Javadoc checking after merging this pull request.
> Eliminate field `testFailed`

- checker/tests/nullness/Issue3792.java
- framework/src/main/java/org/checkerframework/framework/util/FlowExpressionParseUtil.java
> Add support of boolean literals to the FlowExpression parser.

- checker/src/main/java/org/checkerframework/checker/nullness/NullnessTransfer.java
- framework/src/main/java/org/checkerframework/framework/flow/CFAbstractTransfer.java
Also fixes a bug in strengthenAnnotationOfEqualTo
> Override both versions of finishValue

- checker/src/main/java/org/checkerframework/checker/formatter/FormatterVisitor.java
Merge together with, or after, https://github.com/codespecs/daikon/pull/288.
> Fix logic bug in comparing arguments to parameters

- framework/src/main/java/org/checkerframework/framework/type/AnnotatedTypeFactory.java
- framework/src/main/java/org/checkerframework/framework/type/AnnotatedTypeMirror.java
- framework/src/main/java/org/checkerframework/framework/type/DefaultTypeHierarchy.java
> Reset uninferredTypeArgumentScanner.

- checker/src/main/java/org/checkerframework/checker/formatter/FormatterVisitor.java
- checker/src/main/java/org/checkerframework/checker/guieffect/GuiEffectVisitor.java
- checker/src/main/java/org/checkerframework/checker/i18nformatter/I18nFormatterVisitor.java
- framework/src/main/java/org/checkerframework/common/basetype/BaseTypeVisitor.java
- javacutil/src/main/java/org/checkerframework/javacutil/ElementUtils.java
I'm not thrilled about the method name; suggestions for improving it are welcome.
> New method ElementUtils.getSimpleNameOrDescription

- changelog.txt
- docs/manual/external-tools.tex
- docs/manual/introduction.tex
Thanks to Suminda Sirinath Salpitikorala Dharmasena.
Fixes #3862.
> How to build with sbt

- docs/manual/accumulation-checker.tex
- framework/src/test/java/org/checkerframework/framework/testchecker/testaccumulation/qual/TestAccumulationPredicate.java
(Also removes a redundant sentence.)
> How to enforce accumulation-related properties

- framework/src/main/java/org/checkerframework/framework/type/DefaultTypeHierarchy.java
I don't know whether this optimization is worthwhile.
(The documentation changes are probably worthwhile even if the optimization is not.)
> Make an implicit behavior explicit

- framework/src/main/java/org/checkerframework/common/wholeprograminference/WholeProgramInferenceScenesStorage.java
Also reorders arguments for consistency
> Rename update methods

- changelog.txt
- dataflow/src/main/java/org/checkerframework/dataflow/analysis/Analysis.java
- dataflow/src/main/java/org/checkerframework/dataflow/analysis/AnalysisResult.java
- dataflow/src/main/java/org/checkerframework/dataflow/analysis/BackwardAnalysisImpl.java
- dataflow/src/main/java/org/checkerframework/dataflow/analysis/ForwardAnalysisImpl.java
- dataflow/src/main/java/org/checkerframework/dataflow/analysis/Store.java
- framework/src/main/java/org/checkerframework/framework/type/GenericAnnotatedTypeFactory.java
> Change boolean to enum for readability; fixes #3390

- checker/build.gradle
- checker/src/test/java/org/checkerframework/checker/test/junit/CalledMethodsAutoValueTest.java
- checker/src/test/java/org/checkerframework/checker/test/junit/CalledMethodsDisableframeworksTest.java
- checker/src/test/java/org/checkerframework/checker/test/junit/CalledMethodsLombokTest.java
- checker/src/test/java/org/checkerframework/checker/test/junit/CalledMethodsTest.java
- checker/src/test/java/org/checkerframework/checker/test/junit/CalledMethodsUseValueCheckerTest.java
Also update com.amazonaws:aws-java-sdk-bom.
> Move CalledMethods Checker test to the correct location.

- docs/developer/release/release_build.py
- docs/developer/release/release_push.py
- docs/developer/release/release_utils.py
- docs/developer/release/release_vars.py
- docs/developer/release/sanity_checks.py
This is all I intend to commit before the next release.  I will do just a bit of refactoring after each of the next 4 releases.
> Eliminate variables that are used 0 or 1 times

- framework/src/main/java/org/checkerframework/framework/stub/AnnotationFileParser.java
Having this as a field will allow alternate traversal methods of a compilation unit that go into anonymous classes.
> Make packageAnnos a field in AnnotationFileParser

- checker/jtreg/stubs/issue1585/ParseError.out
- docs/manual/signature-checker.tex
Merge with https://github.com/typetools/stubparser/pull/43.
> Adapt to StubParser changes

- checker/jtreg/stubs/issue1585/ParseError.out
- checker/src/main/java/org/checkerframework/checker/formatter/FormatterAnnotatedTypeFactory.java
- docs/manual/signature-checker.tex
Merge after https://github.com/typetools/checker-framework/pull/4029.
Merge with https://github.com/typetools/stubparser/pull/44.
> Test case of class annotation without package declaration

- dataflow/src/main/java/org/checkerframework/dataflow/analysis/AbstractAnalysis.java
It seems that the underlying issue causing the crash in #765 has since been fixed.  
Fixes #765.
> Revert workaround for #765

- checker/tests/nullness/Issue3681.java
- framework/src/main/java/org/checkerframework/framework/type/TypeFromTypeTreeVisitor.java
- framework/tests/all-systems/Issue3377.java
> Don't initialize type arguments of types with diamonds.

- framework/src/main/java/org/checkerframework/framework/stub/AnnotationFileParser.java
Reduces diff with ajava2 branch.
> Make annotationFileAnnos a field

- framework/src/main/java/org/checkerframework/framework/type/AnnotatedTypeFactory.java
- framework/tests/all-systems/Issue4083.java
- javacutil/src/main/java/org/checkerframework/javacutil/ElementUtils.java
> Fix crash when using an annotation element as a member reference.

- build.gradle
Merge with https://github.com/typetools/stubparser/pull/46.
> Update the version of the stubparser jar.

- changelog.txt
- checker/bin-devel/count-suppressions
- checker/src/main/java/org/checkerframework/checker/formatter/FormatterVisitor.java
- checker/src/main/java/org/checkerframework/checker/guieffect/GuiEffectVisitor.java
- checker/src/main/java/org/checkerframework/checker/index/upperbound/UpperBoundVisitor.java
- checker/src/main/java/org/checkerframework/checker/initialization/InitializationAnnotatedTypeFactory.java
- checker/src/main/java/org/checkerframework/checker/initialization/InitializationTransfer.java
- checker/src/main/java/org/checkerframework/checker/lock/LockVisitor.java
- checker/src/main/java/org/checkerframework/checker/nullness/NullnessAnnotatedTypeFactory.java
- checker/src/main/java/org/checkerframework/checker/signedness/SignednessAnnotatedTypeFactory.java
- dataflow/src/main/java/org/checkerframework/dataflow/cfg/builder/CFGTranslationPhaseOne.java
- dataflow/src/main/java/org/checkerframework/dataflow/expression/JavaExpression.java
- framework/src/main/java/org/checkerframework/common/aliasing/AliasingVisitor.java
- framework/src/main/java/org/checkerframework/common/basetype/BaseTypeVisitor.java
- framework/src/main/java/org/checkerframework/common/reflection/ClassValAnnotatedTypeFactory.java
- framework/src/main/java/org/checkerframework/framework/flow/CFAbstractTransfer.java
- framework/src/main/java/org/checkerframework/framework/flow/CFCFGBuilder.java
- framework/src/main/java/org/checkerframework/framework/source/SourceChecker.java
- framework/src/main/java/org/checkerframework/framework/type/AnnotatedTypeFactory.java
- framework/src/main/java/org/checkerframework/framework/type/GenericAnnotatedTypeFactory.java
- framework/src/main/java/org/checkerframework/framework/util/Heuristics.java
- framework/src/main/java/org/checkerframework/framework/util/JavaExpressionParseUtil.java
- framework/src/main/java/org/checkerframework/framework/util/dependenttypes/DependentTypesHelper.java
- framework/src/main/java/org/checkerframework/framework/util/typeinference/DefaultTypeArgumentInference.java
- framework/src/main/java/org/checkerframework/framework/util/typeinference/TypeArgInferenceUtil.java
- javacutil/src/main/java/org/checkerframework/javacutil/TreePathUtil.java
- javacutil/src/main/java/org/checkerframework/javacutil/TreeUtils.java
Merge after https://github.com/typetools/checker-framework/pull/4112.
> Create class `TreePathUtil`

- dataflow/src/main/java/org/checkerframework/dataflow/analysis/AbstractAnalysis.java
- framework/tests/all-systems/Issue4115.java
> Remove assertion.

- SKIP-REQUIRE-JAVADOC
- build.gradle
- dataflow/src/main/java/org/checkerframework/dataflow/analysis/AnalysisResult.java
- docs/examples/errorprone/build.gradle
- framework/build.gradle
- framework/src/main/java/org/checkerframework/framework/type/AnnotatedTypeCopierWithReplacement.java
- framework/src/main/java/org/checkerframework/framework/type/treeannotator/LiteralTreeAnnotator.java
- framework/src/main/java/org/checkerframework/framework/type/visitor/AnnotatedTypeScanner.java
- framework/src/main/java/org/checkerframework/framework/type/visitor/EquivalentAtmComboScanner.java
- framework/src/main/java/org/checkerframework/framework/util/defaults/QualifierDefaults.java
- framework/src/main/java/org/checkerframework/framework/util/element/ElementAnnotationUtil.java
Remove file SKIP-REQUIRE-JAVADOC after merging.
> Use Error Prone version 2.5.1

- checker-util/src/main/java/org/checkerframework/checker/signedness/util/SignednessUtil.java
- checker-util/src/main/java/org/checkerframework/checker/signedness/util/SignednessUtilExtra.java
- checker/tests/signedness/Utils.java
- docs/manual/annotating-libraries.tex
Merge together with https://github.com/typetools/jdk/pull/97
> Document methods for which a JDK 11 version exists

- checker/bin-devel/javac
I think this is related to removing the checker-qual classes from checker.jar.
> Add checker-qual to javac script

- framework/src/main/java/org/checkerframework/framework/source/SourceChecker.java
- framework/src/main/java/org/checkerframework/framework/util/AnnotatedTypes.java
- javacutil/src/main/java/org/checkerframework/javacutil/TreePathUtil.java
I don't know what they mean, and a web search doesn't turn up anything
> Remove "nninvariant" comments on assertions

- framework/src/main/java/org/checkerframework/framework/util/dependenttypes/DependentTypesHelper.java
- framework/tests/flowexpression/LambdaParameter.java
Also, correct a comment in the code and use an enum set.
> Add tests for dependent type annotations on lambda parameters.

- checker/src/main/java/org/checkerframework/checker/index/upperbound/OffsetEquation.java
Calls to these methods were removed in 6e01c284db128b31760e179320831cbc11f8d765.
> Remove methods that are no longer used.

- checker-qual/src/main/java/org/checkerframework/checker/i18nformatter/qual/I18nFormatFor.java
- checker/src/main/java/org/checkerframework/checker/i18nformatter/I18nFormatterTreeUtil.java
- checker/src/main/java/org/checkerframework/checker/i18nformatter/I18nFormatterVisitor.java
- framework/src/main/java/org/checkerframework/framework/util/JavaExpressionParseUtil.java
so, there's no need to parse.  I also some what improved the documentation.
> I18nFormatFor does not accept arbitrary JavaExpressions 

- changelog.txt
- checker/src/main/java/org/checkerframework/checker/index/lowerbound/LowerBoundTransfer.java
- checker/src/main/java/org/checkerframework/checker/index/samelen/SameLenAnnotatedTypeFactory.java
- checker/src/main/java/org/checkerframework/checker/index/samelen/SameLenTransfer.java
- dataflow/src/main/java/org/checkerframework/dataflow/expression/JavaExpression.java
- framework/src/main/java/org/checkerframework/framework/util/JavaExpressionParseUtil.java
Also, create the JavaExpression without parsing.
> Moved JavaExpressionParseUtil#fromVariableTree to JavaExpression.

- checker/bin-devel/javac
This permits running `javac -processor org.checkerframework.framework.testchecker.util.FlowTestChecker ...`
> Add framework test classes to bin-devel/javac classpath

- checker/tests/calledmethods/Postconditions.java
- dataflow/src/main/java/org/checkerframework/dataflow/cfg/builder/CFGTranslationPhaseOne.java
> Model unchecked exception types more precisely in CFG construction

- dataflow/src/main/java/org/checkerframework/dataflow/expression/ArrayAccess.java
- dataflow/src/main/java/org/checkerframework/dataflow/expression/ArrayCreation.java
- dataflow/src/main/java/org/checkerframework/dataflow/expression/BinaryOperation.java
- dataflow/src/main/java/org/checkerframework/dataflow/expression/ClassName.java
- dataflow/src/main/java/org/checkerframework/dataflow/expression/FieldAccess.java
- dataflow/src/main/java/org/checkerframework/dataflow/expression/JavaExpression.java
- dataflow/src/main/java/org/checkerframework/dataflow/expression/JavaExpressionConverter.java
- dataflow/src/main/java/org/checkerframework/dataflow/expression/JavaExpressionVisitor.java
- dataflow/src/main/java/org/checkerframework/dataflow/expression/LocalVariable.java
- dataflow/src/main/java/org/checkerframework/dataflow/expression/MethodCall.java
- dataflow/src/main/java/org/checkerframework/dataflow/expression/ThisReference.java
- dataflow/src/main/java/org/checkerframework/dataflow/expression/UnaryOperation.java
- dataflow/src/main/java/org/checkerframework/dataflow/expression/Unknown.java
- dataflow/src/main/java/org/checkerframework/dataflow/expression/ValueLiteral.java
See https://github.com/typetools/checker-framework/pull/4325 for a use.  I will also use these classes to viewpoint-adapt JavaExpressions.
> Add JavaExpressionVisitor and a subclass JavaExpressionConverter

- checker/src/main/java/org/checkerframework/checker/index/OffsetDependentTypesHelper.java
- checker/src/main/java/org/checkerframework/checker/index/inequality/LessThanTransfer.java
- checker/tests/index/ComputeConst.java
- framework/src/main/java/org/checkerframework/common/value/JavaExpressionOptimizer.java
- framework/src/main/java/org/checkerframework/common/value/ValueCheckerUtils.java
- framework/src/main/java/org/checkerframework/framework/util/dependenttypes/DependentTypesHelper.java
Also, in LessThanTransfer, call ValueChecker#optimize and print longs so they can later be parsed.
> Move another optimization into ValueCheckerUtil#optimize

- docs/manual/warnings.tex
You might want to read the changed section rather than the diffs.
> Tweak text about assertion methods

- checker/src/main/java/org/checkerframework/checker/nullness/NullnessTransfer.java
- checker/tests/nullness/Issue4372.java
> Receivers aren't just declared types.

- framework/src/main/java/org/checkerframework/framework/type/visitor/AnnotatedTypeScanner.java
This fixes the first bullet point in https://github.com/typetools/checker-framework/issues/4252
> Add note about map in AnnotatedTypeScanner.

- framework/src/main/java/org/checkerframework/framework/type/DefaultTypeHierarchy.java
- framework/tests/all-systems/Issue4384.java
> Workaround for a wildcard that should be captured.

- framework/src/main/java/org/checkerframework/common/basetype/BaseTypeVisitor.java
- framework/src/main/java/org/checkerframework/framework/flow/CFAbstractTransfer.java
This is an independent refactoring that reduces the size of the diffs in #4378.
> Reduce scope of try block

- SKIP-REQUIRE-JAVADOC
- checker/src/main/java/org/checkerframework/checker/index/upperbound/OffsetEquation.java
Remove file `SKIP-REQUIRE-JAVADOC` after the pull request is merged.
> Reduce initial capacity

- checker/src/main/java/org/checkerframework/checker/index/inequality/LessThanTransfer.java
I'm not 100% positive this is correct.  If it is not, then the test suite is missing a test. :-)
> Make `refineGT` more efficient

- checker-qual/src/main/java/org/checkerframework/common/reflection/qual/GetConstructor.java
- checker/src/main/java/org/checkerframework/checker/index/inequality/LessThanAnnotatedTypeFactory.java
- checker/src/main/java/org/checkerframework/checker/index/inequality/LessThanTransfer.java
- checker/src/main/java/org/checkerframework/checker/index/upperbound/UBQualifier.java
- checker/src/main/java/org/checkerframework/checker/nullness/KeyForValue.java
- framework/src/main/java/org/checkerframework/common/reflection/MethodValAnnotatedTypeFactory.java
- framework/src/main/java/org/checkerframework/common/reflection/ReflectionResolver.java
- framework/src/main/java/org/checkerframework/framework/type/DefaultTypeHierarchy.java
- framework/src/main/java/org/checkerframework/framework/type/SubtypeIsSubsetQualifierHierarchy.java
- framework/src/main/java/org/checkerframework/framework/type/SubtypeIsSupersetQualifierHierarchy.java
This pull request contains many small unrelated changes.  If you want me to break it up, I can do that.
> Miscellaneous documentation and style improvements

- checker/src/main/java/org/checkerframework/checker/nullness/NullnessAnnotatedTypeFactory.java
- docs/manual/nullness-checker.tex
https://github.com/jspecify/jspecify/commit/df06583fb5abfa70be112f0fdd08eeb08aa9446f#diff-f5b46e1218c9c46ef93fa299949add0fb60210696857fb41200cd376bcd08800
> Update jspecify annotations package

- changelog.txt
- checker-qual/src/main/java/org/checkerframework/common/initializedfields/qual/EnsuresInitializedFields.java
- framework/src/main/java/org/checkerframework/common/basetype/BaseTypeChecker.java
- framework/src/main/java/org/checkerframework/common/initializedfields/InitializedFieldsAnnotatedTypeFactory.java
- framework/src/main/java/org/checkerframework/framework/type/GenericAnnotatedTypeFactory.java
- framework/src/main/java/org/checkerframework/framework/util/Contract.java
- framework/src/main/java/org/checkerframework/framework/util/ContractsFromMethod.java
- javacutil/src/main/java/org/checkerframework/javacutil/AnnotationUtils.java
~~Merge after https://github.com/typetools/checker-framework/pull/4439 and https://github.com/typetools/checker-framework/pull/4440.~~
> Eliminate method `getElementValueArrayOrSingleton()`

- dataflow/src/main/java/org/checkerframework/dataflow/cfg/builder/CFGTranslationPhaseOne.java
Fixes https://github.com/typetools/checker-framework/issues/4452
> Make resolving some exception types optional in `CFGTranslationPhaseOne`

- dataflow/src/main/java/org/checkerframework/dataflow/cfg/builder/CFGTranslationPhaseOne.java
This only makes debugging easier; it does not affect correctness.
> Improve determinism in CFG construction

- changelog.txt
- framework/src/main/java/org/checkerframework/framework/type/AnnotatedTypeReplacer.java
- framework/src/main/java/org/checkerframework/framework/type/visitor/AnnotatedTypeCombiner.java
- framework/src/main/java/org/checkerframework/framework/type/visitor/DoubleAnnotatedTypeScanner.java
- framework/src/main/java/org/checkerframework/framework/util/dependenttypes/DependentTypesHelper.java
Also, rename compare to defaultAction and remove combineRs.
> Rename AnnotatedTypeComparer to DoubleAnnotatedTypeScanner.

- .editorconfig
This file seems to be out of date after the recent formatting changes.
> Update editorconfig file

- checker/bin-devel/javac
- checker/bin-devel/javac-debug
- checker/bin/javac
Sometimes WPI passes this argument to javac.
> Handle `-Xmx` argument to `javac`

- framework/src/main/java/org/checkerframework/common/value/ValueAnnotatedTypeFactory.java
No clients at present, but possibly useful.
> Define `getMinLenValue(Set)`

- docs/manual/creating-a-checker.tex
Does the new text use the correct terminology?
> Add note about putting quals/ directory in its own project

- checker-qual/src/main/java/org/checkerframework/checker/initialization/qual/FBCBottom.java
- checker/tests/nullness/init/Issue4567.java
> null should be FBCBottom.

- dataflow/src/main/java/org/checkerframework/dataflow/util/AbstractMostlySingleton.java
Merge with https://github.com/typetools/jdk/pull/108
> Fix an annotation

- dataflow/src/main/java/org/checkerframework/dataflow/expression/ClassName.java
- framework/src/main/java/org/checkerframework/framework/util/dependenttypes/DependentTypesHelper.java
This helped diagnosing #4614.  Is there a better way?
> Enable tracing where a buggy lambda came from

- build.gradle
> Don't run formatting on Java 8.

- checker/src/main/java/org/checkerframework/checker/units/UnitsVisitor.java
- checker/tests/units/Issue4549.java
> Fix compound assignments for the Units Checker.

- docs/manual/called-methods-checker.tex
This PR reduces the diff in #4687, where this change was originally proposed.
> Add additional text to the manual about @EnsuresCalledMethods

- .travis-build-without-test.sh
- build.gradle
- checker/bin-devel/build.sh
Merge with https://github.com/typetools/annotation-tools/pull/412 and https://github.com/typetools/stubparser/pull/68 .
> Take "travis" out of script names

- javacutil/src/main/java/org/checkerframework/javacutil/TreeUtils.java
```
((@NonNull Symbol) e).flags() & Flags.ANONCONSTR) != 0
```
Doesn't work with Java 16 for some reason.
> Use public APIs in isAnonymousConstructor.

- docs/manual/inference.tex
should have been removed as part of https://github.com/typetools/checker-framework/pull/4665
> remove documentation of a removed feature

- framework-test/src/main/java/org/checkerframework/framework/test/TestUtilities.java
@twistedsquare and I independently implemented this in different branches; we might as well have it in master.
> Support @below-java16-jdk-skip-test and @above-java16-skip-test" in tests

- checker/bin/wpi-many.sh
- checker/bin/wpi.sh
- docs/examples/wpi-many/wpi-many-custom-checker-example.sh
https://github.com/koalaman/shellcheck/wiki/SC2268, says it is no longer necessary.
> Don't use x-prefix in comparisons

- checker/src/main/java/org/checkerframework/checker/calledmethods/CalledMethodsAnnotatedTypeFactory.java
- checker/src/main/java/org/checkerframework/checker/nullness/NullnessAnnotatedTypeFactory.java
- framework/src/main/java/org/checkerframework/framework/type/GenericAnnotatedTypeFactory.java
> refactor pre- and postcondition inference methods to simplify overrides and reduce duplication

- framework/src/main/java/org/checkerframework/common/value/ValueTransfer.java
- framework/tests/value/StringLenConcats.java
Thanks to Sidney Monteiro for reporting the issue.
> Account for null in string concatenation

- framework/src/main/java/org/checkerframework/common/wholeprograminference/WholeProgramInference.java
- framework/src/main/java/org/checkerframework/common/wholeprograminference/WholeProgramInferenceImplementation.java
- framework/src/main/java/org/checkerframework/framework/flow/CFAbstractTransfer.java
Co-authored-by: Neil Brown <neil@twistedsquare.com>
> Remove unneeded formal parameter

- framework/src/main/java/org/checkerframework/common/wholeprograminference/WholeProgramInferenceJavaParserStorage.java
- framework/src/main/java/org/checkerframework/common/wholeprograminference/WholeProgramInferenceScenesStorage.java
Co-authored-by: Neil Brown <neil@twistedsquare.com>
> Handle enum fields specially in `getFieldAnnotations()`

- framework/src/main/java/org/checkerframework/framework/ajava/JointJavacJavaParserVisitor.java
- framework/src/main/java/org/checkerframework/framework/stub/AnnotationFileParser.java
- javacutil/src/main/java/org/checkerframework/javacutil/TreeUtils.java
Co-authored-by: Neil Brown <neil@twistedsquare.com>
> Documentation tweaks

- framework/src/main/java/org/checkerframework/framework/type/DefaultTypeHierarchy.java
- framework/tests/all-systems/Issue4876.java
> Ignore crashes in isContainedBy; fixes #4876

- framework/src/main/java/org/checkerframework/common/basetype/BaseTypeValidator.java
- framework/tests/all-systems/Issue4878.java
- framework/tests/all-systems/Issue4878Orig.java
> Some captured types are from a previous capture.

- framework/src/main/java/org/checkerframework/framework/type/AnnotatedTypeFactory.java
- framework/tests/all-systems/Issue4879.java
> Don't use assignment context for diamond trees.

- docs/manual/called-methods-checker.tex
- docs/manual/manual.bbl
also removed a duplicate line that slipped into the manual somehow
> Notes on what the Called Methods Checker is actually checking, in the manual

- checker/tests/nullness/Issue4889.java
Fixes #4889 (together with https://github.com/typetools/jdk/commit/09006ed01a7f55760fa092c00eedef97d489fe2a).
> Test case for issue #4889

- build.gradle
Merge with https://github.com/typetools/stubparser/pull/74.
> Update stubparser version to 3.23.0.

- build.gradle
Merge with https://github.com/typetools/stubparser/pull/75.
> Update to Stubparser 3.23.1.

- checker-qual/src/main/java/org/checkerframework/checker/mustcall/qual/NotOwning.java
- checker-qual/src/main/java/org/checkerframework/checker/mustcall/qual/Owning.java
- checker/tests/mustcall/OwningParams.java
> add note to documentation of Owning about why it is a declaration annotation, and fix and reenable a test for java 17

- checker/tests/nullness/NullnessIssue4996.java
- framework/src/main/java/org/checkerframework/framework/util/AnnotatedTypes.java
- framework/tests/all-systems/Issue4996.java
> Capture enclosing types.

- docs/developer/release/README-release-process.html
Also, remove note about Randoop, since dependabot should update that now.
> Add note to update Daikon.

- dataflow/src/main/java/org/checkerframework/dataflow/cfg/UnderlyingAST.java
- dataflow/src/main/java/org/checkerframework/dataflow/cfg/visualize/DOTCFGVisualizer.java
- docs/CHANGELOG.md
A lambda can be written outside of a method (e.g., in a field declaration), so `CFGLambda.method` should be `@Nullable`
> Make CFGLambda.method @Nullable

- build.gradle
Merge with https://github.com/typetools/stubparser/pull/84.
> Update stubparser to 3.24.0.

- framework/src/main/java/org/checkerframework/framework/util/typeinference/TypeArgInferenceUtil.java
- framework/tests/all-systems/Issue5008.java
> Use the type of `this` as receiver of `super()` calls.

- checker/bin/wpi.sh
- docs/CHANGELOG.md
- docs/manual/inference.tex
@Nargeshdb can you give this version of `wpi.sh` a try the next time you're running on a multi-module project, and let me know if the instructions make sense. We shouldn't merge this until that happens, so that we know the instructions are good enough for a real user to follow.
> Add option to wpi.sh that allows custom build commands

- checker/src/main/java/org/checkerframework/checker/nullness/NullnessVisitor.java
- checker/tests/nullness/java17/Greeting.java
- framework/src/main/java/org/checkerframework/common/basetype/BaseTypeVisitor.java
> Use isTypeCast safe.

- framework/src/main/java/org/checkerframework/framework/type/AnnotatedTypeFactory.java
Use type variable substitution so that the underlying type of the ground type is the same as the AnnotatedTypeMirror.
> Correct `makeGroundTargetType`

- docs/examples/errorprone/build.gradle
- docs/examples/lombok/build.gradle
Merge after new version of the plugin is released.
> Update CF plugin version number.

- checker/src/main/java/org/checkerframework/checker/signedness/SignednessAnnotatedTypeFactory.java
- checker/tests/signedness/SignednessCast.java
Follow up to https://github.com/typetools/checker-framework/pull/5082.
> Correct Signedness Checker cast code.

- build.gradle
Merge with https://github.com/typetools/stubparser/pull/88.
> Update to stubparser 3.24.2.

- checker/build.gradle
- checker/tests/ainfer-testchecker/non-annotated/InheritanceTest.java
- checker/tests/ainfer-testchecker/non-annotated/OverriddenMethodsTest.java
- checker/tests/ainfer-testchecker/non-annotated/OverriddenMethodsTestChildInAnotherCompilationUnit.java
- checker/tests/ainfer-testchecker/non-annotated/PublicFieldTest.java
- checker/tests/ainfer-testchecker/non-annotated/README.md
This PR contains no functional changes, just some refactoring. I made it to reduce the diffs in #5091.
> Put all ainfer-testchecker tests in classes that match the corresponding file name

- checker/src/main/java/org/checkerframework/checker/guieffect/GuiEffectVisitor.java
- checker/src/main/java/org/checkerframework/checker/lock/LockAnnotatedTypeFactory.java
- checker/src/main/java/org/checkerframework/checker/lock/LockVisitor.java
- framework/src/main/java/org/checkerframework/common/basetype/BaseTypeVisitor.java
- framework/src/main/java/org/checkerframework/framework/flow/CFAbstractTransfer.java
- framework/src/main/java/org/checkerframework/framework/type/AnnotatedTypeFactory.java
- framework/src/main/java/org/checkerframework/framework/type/poly/AbstractQualifierPolymorphism.java
- framework/src/main/java/org/checkerframework/framework/util/AnnotatedTypes.java
- framework/tests/all-systems/Map.java
- javacutil/src/main/java/org/checkerframework/javacutil/TreeUtils.java
- javacutil/src/main/java/org/checkerframework/javacutil/TypesUtils.java
Review in this order: 
1. framework/src/main/java/org/checkerframework/framework/type/AnnotatedTypeFactory.java
2. framework/src/main/java/org/checkerframework/framework/util/AnnotatedTypes.java
3. Everything else
> Improve constructorFromUse for anonymous classes

- checker/src/main/java/org/checkerframework/checker/signedness/SignednessAnnotatedTypeFactory.java
- checker/src/main/java/org/checkerframework/checker/signedness/SignednessVisitor.java
> Permit any comparison between non-integral types

- checker/tests/regex_poly/StringBuilderToStringPolyRegex.java
Merge after https://github.com/typetools/jdk/pull/129.
> Test case for issue #58

- checker/src/main/java/org/checkerframework/checker/resourceleak/MustCallConsistencyAnalyzer.java
- checker/tests/resourceleak/LemmaStack.java
> permit calling @CreatesMustCallFor(this) methods in constructors

- docs/examples/errorprone/build.gradle
- docs/examples/lombok/build.gradle
Merge after https://github.com/kelloggm/checkerframework-gradle-plugin/pull/203
> Use Checker Framework Gradle Plugin version 0.6.14

- checker/src/main/java/org/checkerframework/checker/i18nformatter/I18nFormatterAnnotatedTypeFactory.java
- checker/src/main/java/org/checkerframework/checker/propkey/PropertyKeyAnnotatedTypeFactory.java
- dataflow/src/main/java/org/checkerframework/dataflow/cfg/visualize/CFGVisualizeLauncher.java
- framework-test/src/main/java/org/checkerframework/framework/test/TypecheckExecutor.java
- framework-test/src/main/java/org/checkerframework/framework/test/diagnostics/JavaDiagnosticReader.java
- framework/src/main/java/org/checkerframework/common/wholeprograminference/SceneToStubWriter.java
- framework/src/main/java/org/checkerframework/common/wholeprograminference/scenelib/ASceneWrapper.java
- framework/src/main/java/org/checkerframework/framework/ajava/InsertAjavaAnnotations.java
- framework/src/main/java/org/checkerframework/framework/source/SourceChecker.java
- framework/src/main/java/org/checkerframework/framework/stub/AddAnnotatedFor.java
- framework/src/main/java/org/checkerframework/framework/stub/AnnotationFileElementTypes.java
- framework/src/main/java/org/checkerframework/framework/stub/AnnotationFileUtil.java
- framework/src/main/java/org/checkerframework/framework/type/AnnotatedTypeFactory.java
- framework/src/main/java/org/checkerframework/framework/type/AnnotationClassLoader.java
- framework/src/main/java/org/checkerframework/framework/util/CheckerMain.java
Could you check the logic of these changes, in case I made some silly mistake?
> Close more resources

- build.gradle
- settings.gradle
Note that `spotlessCheck` rejects `framework-test/src/main/java/org/checkerframework/framework/test/CheckerFrameworkWPIPerDirectoryTest.java`, but reformatting it `spotlessApply` causes the git hook formatting check to fail.
> Use the spotless plugin.

- framework/src/main/java/org/checkerframework/framework/source/SourceChecker.java
- javacutil/src/main/java/org/checkerframework/javacutil/TreePathUtil.java
- javacutil/src/main/java/org/checkerframework/javacutil/TreeUtils.java
> Use simpler loop syntax

- checker/tests/resourceleak/CloseableAndMore.java
- checker/tests/resourceleak/FilesTest.java
Merge with https://github.com/typetools/jdk/pull/148
> Add test of `java.nio.file.Files` method annotations

- checker/tests/mustcall/TryWithResourcesSimple.java
- checker/tests/resourceleak/CloseableAndMore.java
- checker/tests/resourceleak/FilesTest.java
- framework/src/main/java/org/checkerframework/framework/type/ElementAnnotationApplier.java
- framework/src/main/java/org/checkerframework/framework/type/GenericAnnotatedTypeFactory.java
- framework/src/main/java/org/checkerframework/framework/util/defaults/QualifierDefaults.java
- javacutil/src/main/java/org/checkerframework/javacutil/ElementUtils.java
- javacutil/src/main/java/org/checkerframework/javacutil/TreeUtils.java
> Treat resource variables the same as local variables.

- build.gradle
Merge with https://github.com/typetools/stubparser/pull/99.
> Update to StubParser 3.24.4

- checker/tests/nullness/Issue5245.java
- framework/src/main/java/org/checkerframework/framework/util/AnnotatedTypes.java
> Convert typevars to "uses" before substitution 

- checker/bin-devel/wpi-plumelib/bcel-util.expected
I expect CI should pass on this branch.
> Update line number in expected test output

- docs/manual/advanced-features.tex
> Remove misleading "occasionally"

- azure-pipelines.yml
This reverts commit d46496848a96a8e0cf5eec3ddf651b2ebc476df0.
> Re-enable Guava tests under JDK 17

- azure-pipelines.yml
- checker/tests/calledmethods/Issue5402.java
~Hmm, this seems to contain an unrelated change.~
@kelloggm You might already have a test case; this is in case you didn't create it yet.
> Test case for issue #5402

- build.gradle
- framework-test/build.gradle
- framework-test/src/taglet/java/org/checkerframework/taglet/ManualTaglet.java
- framework-test/src/tagletJdk8/java/org/checkerframework/taglet/ManualTaglet.java
> Add framework-test to the Javadoc that gets published.

- docs/examples/errorprone/build.gradle
- docs/examples/lombok/build.gradle
merge after https://github.com/kelloggm/checkerframework-gradle-plugin/pull/227
> Update CF Gradle plugin version.

- build.gradle
Merge with https://github.com/typetools/stubparser/pull/102
> Use Stubparser 3.24.9

- checker/src/main/java/org/checkerframework/checker/nullness/collection-object-parameters-may-be-null.readme
- checker/src/main/java/org/checkerframework/checker/nullness/sometimes-nullable.astub
- docs/CHANGELOG.md
- docs/manual/nullness-checker.tex
Merge with https://github.com/typetools/jdk/pull/153 .
> Explain conservative JDK annotations

- checker/jtreg/nullness/issue3700/Client.out
- checker/tests/ainfer-testchecker/non-annotated/OptionGroup.java
- framework/src/main/java/org/checkerframework/common/wholeprograminference/SceneToStubWriter.java
- framework/src/main/java/org/checkerframework/common/wholeprograminference/scenelib/ASceneWrapper.java
- framework/src/main/java/org/checkerframework/framework/stub/AnnotationFileParser.java
- framework/src/main/java/org/checkerframework/framework/stub/StubGenerator.java
- framework/src/main/java/org/checkerframework/framework/util/JavaParserUtil.java
Merge with https://github.com/typetools/annotation-tools/pull/541.
Replaces #5490.
> Annotation declarations are declarations

- checker/bin/wpi-many.sh
- checker/bin/wpi.sh
- docs/manual/inference.tex
Merge with https://github.com/kelloggm/do-like-javac/pull/57.
This is in support of https://github.com/SRI-CSL/do-like-javac/pull/31.
> Changes to wpi.sh and wpi-many.sh to adapt to the most recent versions of DLJC

- checker/tests/calledmethods/Issue5402.java
- framework/src/main/java/org/checkerframework/common/basetype/BaseTypeVisitor.java
> Translate 'this' to the method receiver when checking preconditions.

- checker/tests/ainfer-index/non-annotated/LongMathTest.java
- framework/src/main/java/org/checkerframework/framework/ajava/AnnotationMirrorToAnnotationExprConversion.java
> In Ajava files, print 'l' after longs.

- javacutil/src/main/java/org/checkerframework/javacutil/TypesUtils.java
This should fix the crash in https://github.com/mernst/checker-framework/tree/wpi-multi-version-control-onlyone.
> Add intersection case to simpleTypeName method

- framework/src/main/java/org/checkerframework/framework/stub/RemoveAnnotationsForInference.java
Without this change, `RemoveAnnotationsForInference` crashes on the following program, which is valid Java:
```
import org.checkerframework.checker.nullness.qual.NonNull;
public class SuppressWithName {
public static final String WARNING_KEY = "nullness:assignment";
public static void test() {
@SuppressWarnings(value = WARNING_KEY)
@NonNull Object obj = null;
}
}
```
As far as I can tell, we don't have test infrastructure for `RemoveAnnotationsForInference`, so I didn't commit this file.
With this change, the `@NonNull` annotation above is removed. I'm not sure if that's the right behavior, given that with just the parse tree we don't know that `WARNING_KEY` is effectively final.
> Avoid crash in RemoveAnnotationsForInference when @SuppressWarnings has a name expression as a key

- checker/src/main/java/org/checkerframework/checker/nullness/NullnessAnnotatedTypeFactory.java
- checker/tests/ainfer-nullness/non-annotated/Bug.java
This fixes a crash in Araknemu-branch-unannotated.
> Ignore synthetic variables

- framework/src/main/java/org/checkerframework/framework/ajava/AnnotationTransferVisitor.java
- framework/tests/all-systems/ArrayComparator.java
test case provided by @Nargeshdb
> Fix crash in WPI caused by mixing array and wildcard types

- checker/src/main/java/org/checkerframework/checker/interning/InterningAnnotatedTypeFactory.java
- checker/src/main/java/org/checkerframework/checker/nullness/NullnessChecker.java
- dataflow/src/main/java/org/checkerframework/dataflow/analysis/BackwardAnalysisImpl.java
- dataflow/src/main/java/org/checkerframework/dataflow/analysis/BackwardTransferFunction.java
- dataflow/src/main/java/org/checkerframework/dataflow/livevariable/LiveVarTransfer.java
> Minor changes

- build.gradle
Merge with https://github.com/typetools/stubparser/pull/108.
> Update to Stubparser 3.25.0

- checker-qual-android/build.gradle
Also combine `replaceAnnotations` task with `copySource` task.
> Put generated source code into build dir.

- framework/src/main/java/org/checkerframework/framework/stub/AnnotationFileElementTypes.java
This reverts the changes in https://github.com/typetools/checker-framework/pull/5545.
> Revert parsing count change.

- SKIP-REQUIRE-JAVADOC
- docs/examples/MavenExample/src/main/java/org/checkerframework/example/MavenExample.java
- framework/src/main/java/org/checkerframework/common/basetype/BaseTypeVisitor.java
- javacutil/src/main/java/org/checkerframework/javacutil/TreeUtils.java
Remove file SKIP-REQUIRE-JAVADOC after merge.
> Add util methods for MemberReference kinds

- build.gradle
merge with https://github.com/typetools/stubparser/pull/111
> Update to Stubparser to version 3.25.2.

- checker/tests/index/PrivateSameLen.java
- javacutil/src/main/java/org/checkerframework/javacutil/Resolver.java
> Allow private methods in JavaExpressions.

- docs/manual/creating-a-checker.tex
- docs/manual/must-call-checker.tex
> Notes about relationship between owning and must call

- checker/tests/signedness/JdkConstantsTest.java
- checker/tests/signedness/PolymorphicReturnType.java
Merge with https://github.com/typetools/jdk/pull/168 and https://github.com/plume-lib/plume-util/pull/284 .
> Add signedness test about JDK annotations

- framework/src/main/java/org/checkerframework/framework/type/SupertypeFinder.java
> Ignore supertypes that are error types.

- framework/src/main/java/org/checkerframework/common/wholeprograminference/WholeProgramInferenceJavaParserStorage.java
This pull request also adjusts tests to put the one-line branches first, which I think improves readability.
> Reorder a test

- checker/src/main/java/org/checkerframework/checker/nullness/KeyForAnnotatedTypeFactory.java
- javacutil/src/main/java/org/checkerframework/javacutil/AnnotationMirrorSet.java
Merge with https://github.com/plume-lib/plume-util/pull/306 .
> Remove KeyForTypeHierarchy

- framework/src/main/java/org/checkerframework/common/subtyping/SubtypingAnnotatedTypeFactory.java
- framework/src/main/java/org/checkerframework/framework/type/AnnotationClassLoader.java
> Add a better error message of -AqualsDir

- build.gradle
- checker/src/main/java/org/checkerframework/checker/lock/LockVisitor.java
- framework/src/main/java/org/checkerframework/common/basetype/BaseTypeValidator.java
- framework/src/main/java/org/checkerframework/common/basetype/BaseTypeVisitor.java
- framework/src/main/java/org/checkerframework/framework/flow/CFValue.java
- framework/src/main/java/org/checkerframework/framework/type/AnnotatedTypeFactory.java
- framework/src/main/java/org/checkerframework/framework/type/AsSuperVisitor.java
- framework/src/main/java/org/checkerframework/framework/type/GenericAnnotatedTypeFactory.java
Merging these changes will reduce the size of diffs for other pull requests.
> Documentation changes

- framework/src/main/java/org/checkerframework/framework/stub/AnnotationFileParser.java
> Improve efficiency of `stubDebug()`

- dataflow/src/main/java/org/checkerframework/dataflow/cfg/builder/CFGTranslationPhaseOne.java
- dataflow/src/main/java/org/checkerframework/dataflow/cfg/builder/CFGTranslationPhaseTwo.java
- dataflow/src/main/java/org/checkerframework/dataflow/cfg/builder/NodeWithExceptionsHolder.java
- dataflow/src/main/java/org/checkerframework/dataflow/cfg/builder/PhaseOneResult.java
- dataflow/src/main/java/org/checkerframework/dataflow/cfg/node/CatchMarkerNode.java
- dataflow/tests/busyexpr/Expected.txt
- dataflow/tests/live-variable/Expected.txt
> Make edges to catch blocks more specific

- checker/src/main/java/org/checkerframework/checker/initialization/InitializationVisitor.java
- checker/src/main/java/org/checkerframework/checker/initialization/messages.properties
- checker/tests/initialization/CastInit.java
- checker/tests/nullness-warnredundantannotations/RedundantAnnotationOptions.java
- checker/tests/nullness/ObjectArrayParam.java
- checker/tests/nullness/ObjectListParam.java
- docs/CHANGELOG.md
Merge with https://github.com/plume-lib/options/pull/282.
> Remove `initialization.cast` error; use `cast.unsafe` instead

- framework/src/main/java/org/checkerframework/framework/util/AnnotatedTypes.java
Also, loop through enclosing types, not enclosing classes.
> Correct AnnotatedTypes#outerAsSuper documention.

- build.gradle
Merge with https://github.com/typetools/stubparser/pull/114
> Use Stubparser 3.25.3

- checker/tests/tainting/TaintingIssue6060.java
- framework/src/main/java/org/checkerframework/framework/type/AnnotatedTypeFactory.java
- framework/src/main/java/org/checkerframework/framework/type/TypeFromExpressionVisitor.java
- framework/tests/Issue6060.java
> Correctly type `T.super`

- framework/src/main/java/org/checkerframework/framework/source/SourceChecker.java
Also moves methods in the file and removes backward compatibility.
> Add boolean to indicate whether initialization has been performed

- framework/src/main/java/org/checkerframework/framework/type/TypeFromTypeTreeVisitor.java
- framework/tests/all-systems/Issue6076.java
- javacutil/src/main/java/org/checkerframework/javacutil/TypesUtils.java
> Add new areSame method for TypeVariables

- framework/src/main/java/org/checkerframework/framework/source/SourceChecker.java
The changelog already contains an entry for this change.
> Remove support for `-AuseDefaultsForUncheckedCode`

- checker/src/main/java/org/checkerframework/checker/i18nformatter/I18nFormatterAnnotatedTypeFactory.java
There is no try.  There is only do, or do not.
> Remove `try` statement

- checker/src/main/java/org/checkerframework/checker/calledmethods/CalledMethodsAnnotatedTypeFactory.java
- checker/src/main/java/org/checkerframework/checker/propkey/PropertyKeyAnnotatedTypeFactory.java
- framework/src/main/java/org/checkerframework/common/initializedfields/InitializedFieldsAnnotatedTypeFactory.java
- framework/src/main/java/org/checkerframework/framework/source/SourceChecker.java
- framework/src/main/java/org/checkerframework/framework/type/AnnotatedTypeFactory.java
- framework/src/main/java/org/checkerframework/framework/type/GenericAnnotatedTypeFactory.java
- framework/src/main/java/org/checkerframework/framework/util/OptionConfiguration.java
This change makes a subsequent change smaller and easier to understand.
> Use `List`s instead of arrays

- checker/src/test/java/org/checkerframework/checker/test/junit/ainferrunners/AinferTestCheckerJaifsGenerationTest.java
- checker/src/test/java/org/checkerframework/checker/test/junit/ainferrunners/AinferTestCheckerJaifsValidationTest.java
- checker/src/test/java/org/checkerframework/checker/test/junit/ainferrunners/AinferTestCheckerStubsValidationTest.java
- checker/tests/README
- framework-test/src/main/java/org/checkerframework/framework/test/CheckerFrameworkWPIPerDirectoryTest.java
- framework/tests/README
- framework/tests/all-systems/java17/Issue6069.java
- framework/tests/all-systems/java17/SimpleRecord.java
File checker/tests/README documents this new feature.
> Add an easier way to avoid running WPI on tests.

- framework/src/main/java/org/checkerframework/framework/flow/CFAbstractTransfer.java
- framework/src/main/java/org/checkerframework/framework/type/GenericAnnotatedTypeFactory.java
- framework/tests/all-systems/Issue6104.java
> `fixedInitialStore` may be null

- checker/tests/tainting/Issue6113.java
- framework/src/main/java/org/checkerframework/framework/type/AsSuperVisitor.java
> Fix least upper bound for type variables and wildcards.

- checker-qual/src/main/java/org/checkerframework/checker/calledmethods/qual/EnsuresCalledMethods.java
- docs/manual/called-methods-checker.tex
> Improve @EnsuresCalledMethods documentation to make it clear that the annotation is repeatable

- checker/tests/tainting/Issue6116.java
- framework/src/main/java/org/checkerframework/framework/type/DefaultTypeHierarchy.java
> Reduce scope of workaround.

- checker/bin/wpi-summary.sh
> Fix 'grep' count in wpi-summary.sh

- checker/bin-devel/build.sh
- checker/bin-devel/test-cftests-all.sh
- checker/bin-devel/test-cftests-inference-part1.sh
- checker/bin-devel/test-cftests-inference-part2.sh
- checker/bin-devel/test-cftests-inference.sh
- checker/bin-devel/test-cftests-junit.sh
- checker/bin-devel/test-cftests-nonjunit.sh
- checker/bin-devel/test-daikon-part1.sh
- checker/bin-devel/test-daikon-part2.sh
- checker/bin-devel/test-daikon.sh
- checker/bin-devel/test-downstream.sh
- checker/bin-devel/test-guava-formatter.sh
- checker/bin-devel/test-guava-index.sh
- checker/bin-devel/test-guava-interning.sh
- checker/bin-devel/test-guava-lock.sh
- checker/bin-devel/test-guava-nullness.sh
- checker/bin-devel/test-guava-regex.sh
- checker/bin-devel/test-guava-signature.sh
- checker/bin-devel/test-guava.sh
- checker/bin-devel/test-misc.sh
- checker/bin-devel/test-plume-lib.sh
- checker/bin-devel/test-typecheck-part1.sh
- checker/bin-devel/test-typecheck-part2.sh
- checker/bin-devel/test-typecheck.sh
This will fix the Daikon failure.  I'll make the other improvements we discussed later.
> Move ORG_GRADLE_PROJECT_useJdk17Compiler=true to test scripts.

- dataflow/src/main/java/org/checkerframework/dataflow/cfg/builder/CFGTranslationPhaseOne.java
- framework/src/main/java/org/checkerframework/framework/flow/CFAbstractTransfer.java
> Call extendWithNode on DeconstructorPatternNode.

- docs/manual/annotating-libraries.tex
(the filenames of stub files are irrelevant, what matters is the class)
> Clarify misleading text from #6249

- build.gradle
I was suffering OOME locally; I'm hopeful this will fix the problem.
> Allocate more memory to testing

- framework/tests/all-systems/Issue6282.java
- javacutil/src/main/java/org/checkerframework/javacutil/TreeUtils.java
> Fix another place varargs disapears.

- checker/tests/nullness/java21/Issue6290.java
Fixes #6290.
Merge https://github.com/typetools/jdk/pull/185 first.
> Add test case for Issue 6290

- checker/src/main/resources/guava-assertions.astub
- docs/CHANGELOG.md
- docs/manual/annotating-libraries.tex
- docs/manual/introduction.tex
I moved these changes from https://github.com/typetools/checker-framework/pull/6355 and then made more related changes.
> Add AssertMethod annotations for Guava classes to stubfiles.

- checker-qual/src/main/java/org/checkerframework/checker/optional/qual/OptionalCreator.java
- checker-qual/src/main/java/org/checkerframework/checker/optional/qual/OptionalEliminator.java
- checker-qual/src/main/java/org/checkerframework/checker/optional/qual/OptionalPropagator.java
- checker/src/main/java/org/checkerframework/checker/optional/OptionalVisitor.java
merge with https://github.com/typetools/jdk/pull/189
> Add Optional method annotations.

- build.gradle
- gradle-mvn-push.gradle
> Always rename JavaParser classes in jar files..

- dataflow/src/main/java/org/checkerframework/dataflow/cfg/builder/CFGTranslationPhaseThree.java
- framework/tests/all-systems/Issue6433.java
Fixes #6433 
Fix taken from https://github.com/eisop/checker-framework/commit/faf33e68377774fa276fad8e8717b8bfee48c42a and adapted to fix merge conflicts
> Fix issue 6433

- framework/tests/all-systems/Issue6438.java
> Add (passing) test case for Issue 6438

- checker/bin/infer-and-annotate.sh
Merge after https://github.com/typetools/checker-framework/pull/6443.
> Set classpath when calling `insert-annotations-to-source`

- dataflow/build.gradle
> Use consistent relocate clause

- javacutil/src/main/java/org/checkerframework/javacutil/Resolver.java
> Use version-specific versions of methods reflectively

- checker/src/main/java/org/checkerframework/checker/nullness/NullnessStore.java
> Remove uid fields that shadow fields from a superclass

- checker/src/main/java/org/checkerframework/checker/resourceleak/MustCallInference.java
- checker/src/main/java/org/checkerframework/checker/resourceleak/ResourceLeakAnnotatedTypeFactory.java
- checker/tests/ainfer-resourceleak/non-annotated/GenericClassFieldCrash.java
> Fix AssertionError in MustCallInference::inferOwningField with @MustCallUnknown fields, fixes #6480

- checker/src/main/java/org/checkerframework/checker/initialization/InitializationChecker.java
- framework/src/main/java/org/checkerframework/framework/source/SourceChecker.java
> Provide a method to extend message key matching

- checker/bin-devel/wpi-plumelib/test-wpi-plumelib.sh
- checker/build.gradle
- docs/tutorial/tests/ant.xml
> Remove workaround for illegal-access warnings

- framework/src/main/java/org/checkerframework/framework/util/typeinference8/types/AbstractType.java
Unfortunately, there's another crash with that test so we can't close that issue.
> Fix stackoverflow from Issue 6421

- checker/src/main/java/org/checkerframework/checker/index/lowerbound/LowerBoundAnnotatedTypeFactory.java
- checker/tests/index/JavaxAnnotationNonnegative.java
- framework/src/main/java/org/checkerframework/common/value/ValueAnnotatedTypeFactory.java
> Add alias for Index's Checker's NonNegative annotation with javax.annotation.Nonnegative

- framework/src/main/java/org/checkerframework/framework/util/typeinference8/types/InferenceType.java
- framework/tests/all-systems/Issue6421.java
(This still doesn't fix all the crashes in #6421.)
> Correct equals method of InferenceType

- framework/src/main/java/org/checkerframework/framework/util/typeinference8/InvocationTypeInference.java
- framework/tests/all-systems/Issue6421D.java
> Fix crash with additional argument constraints.

- framework/src/main/java/org/checkerframework/framework/ajava/ExpectedTreesVisitor.java
- framework/src/main/java/org/checkerframework/framework/ajava/JointJavacJavaParserVisitor.java
- framework/tests/all-systems/EndsWithSemicolon.java
> Ignore differences in empty statements when parsing ajava files and source files together

- checker/tests/nullness/Issue4007.java
- checker/tests/optional/Marks5.java
> Clean ups.

- checker/tests/nullness/Issue6382.java
- framework/src/main/java/org/checkerframework/framework/util/typeinference8/types/VariableBounds.java
> Correct handling of qualifier only constraints

- framework/src/main/java/org/checkerframework/framework/flow/CFAbstractTransfer.java
- framework/src/main/java/org/checkerframework/framework/source/SourceChecker.java
- framework/src/main/java/org/checkerframework/framework/type/TypeFromTree.java
- framework/src/main/java/org/checkerframework/framework/util/typeinference8/DefaultTypeArgumentInference.java
- javacutil/src/main/java/org/checkerframework/javacutil/BugInCF.java
This makes it easier to see what code is causing the exception.
> Add a location to BugInCF

- framework/tests/all-systems/java21/Issue6636.java
> Add  passing test case for Issue 6636

- framework/build.gradle
- framework/src/main/java/org/checkerframework/framework/ajava/InsertAjavaAnnotations.java
- framework/src/main/java/org/checkerframework/framework/ajava/JointJavacJavaParserVisitor.java
- framework/src/main/java/org/checkerframework/framework/util/JavaParserUtil.java
- framework/tests/all-systems/java17/Figure.java
> Update to Stubparser version 3.26.1

- framework/tests/all-systems/java17/Issue6749.java
- javacutil/src/main/java/org/checkerframework/javacutil/TreePathUtil.java
> Add another place for switch expressions.

- docs/developer/developer-manual.html
Review after merging #6787 and pulling master into this branch.
> Improved Azure Pipelines quota

- dataflow/src/main/java/org/checkerframework/dataflow/cfg/builder/CFGTranslationPhaseOne.java
- framework/tests/all-systems/Issue6811.java
> Unbox captured types.

- framework/src/main/java/org/checkerframework/framework/util/typeinference8/constraint/Typing.java
- framework/tests/all-systems/Issue6725.java
> Fix problem with containment with wildcards

- framework/src/main/java/org/checkerframework/framework/util/typeinference8/constraint/Expression.java
- framework/src/main/java/org/checkerframework/framework/util/typeinference8/types/VariableBounds.java
- framework/tests/all-systems/Issue6753.java
> Check for proper type

- framework/src/main/java/org/checkerframework/framework/type/TypeFromExpressionVisitor.java
- framework/tests/all-systems/Issue6825.java
> Capture the type of field accesses.

- framework/src/main/java/org/checkerframework/framework/util/typeinference8/constraint/Typing.java
- framework/tests/all-systems/Issue6769.java
> Add a capture in type argument inference

- dataflow/build.gradle
> Remove checker-qual files from shaded dataflow jar.

- framework/src/main/java/org/checkerframework/framework/util/typeinference8/DefaultTypeArgumentInference.java
- framework/tests/all-systems/Issue6839.java
- javacutil/src/main/java/org/checkerframework/javacutil/TreePathUtil.java
> Fix crash with inner constructors.

- framework/tests/all-systems/Issue6856.java
- javacutil/src/main/java/org/checkerframework/javacutil/TreeUtils.java
> Skip parens.

- framework/src/main/java/org/checkerframework/framework/type/DefaultTypeHierarchy.java
- framework/tests/all-systems/Issue6867.java
> Expect crash due to javac bug

- framework/src/main/java/org/checkerframework/framework/util/typeinference8/types/ProperType.java
- framework/tests/all-systems/Issue6886.java
> Fix problem with captured type variables.

- framework/src/main/java/org/checkerframework/common/wholeprograminference/WholeProgramInferenceJavaParserStorage.java
- framework/src/main/java/org/checkerframework/framework/ajava/JointJavacJavaParserVisitor.java
- framework/src/main/java/org/checkerframework/framework/source/SourceChecker.java
(Sorry for multiple changes in one PR.  Each change is in a separate file.)
> Permit quoted characters; only call `format` on format strings; move tests

- docs/manual/called-methods-checker.tex
- docs/manual/manual.bbl
- docs/manual/resource-leak-checker.tex
> Fix manual text

- checker/tests/optional/Issue6970.java
c8e3e788be717ad2b6365836019e0b4836b9ac5f fixed the issue.
Fixes #6970.
> Add test case for issue #6970.

- build.gradle
- checker/build.gradle
Fixes #7001.
Merge with https://github.com/typetools/annotation-tools/pull/704.
> Force reflectionUtil to version 1.1.3

- build.gradle
- checker/build.gradle
https://github.com/typetools/annotation-tools/pull/708
> Update to latest versions of reflection-util and plume-util.

- framework/tests/all-systems/Issue6762.java
> Add now passing test.

- checker/tests/nullness/java17/Issue7029Nullness.java
- framework/src/main/java/org/checkerframework/framework/util/typeinference8/util/Resolution.java
- framework/tests/all-systems/java17/Issue7029.java
> Correct order in which inference variables are resolved 

- checker/tests/nullness/Issue6671.java
> Add passing test.

- checker/tests/nullness/Issue6623.java
- docs/manual/introduction.tex
- framework/src/main/java/org/checkerframework/common/basetype/BaseTypeVisitor.java
- framework/src/main/java/org/checkerframework/common/basetype/messages.properties
- framework/src/main/java/org/checkerframework/framework/source/SourceChecker.java
This mitigates, but does not fix, #6623.
> Warn about slow type-checking

- checker/tests/nullness/Issue6623.java
See failing CI run here: https://dev.azure.com/checkerframework/checkerframework/_build/results?buildId=18012&view=logs&j=01942496-f4e0-59ae-5df4-139825bb2b6c&t=9056da0c-0b5a-57ec-b5fc-015a97a7c93a
> Disable another test with records on JDK 11

- checker/tests/nullness/Issue6740A.java
- checker/tests/nullness/Issue7070.java
- framework/src/main/java/org/checkerframework/framework/util/typeinference8/types/UseOfVariable.java
> Deep copy ATM before modifying it.

- checker/tests/nullness/MapMerge.java
- checker/tests/nullness/MapMerge7082.java
Merge with https://github.com/typetools/jdk/pull/227 and https://github.com/plume-lib/plume-util/pull/486.
Fixes #7082.
> Add a test for `Map.merge()`

- build.gradle
- docs/developer/release/README-release-process.html
- docs/developer/release/release_push.py
- gradle-mvn-push.gradle
I've tested releasing a snapshot with these instructions and it works.
> Use new location for releasing to Maven central.

- .travis.yml
- annotation-file-utilities/scripts/insert-annotations-to-source
- checker/bin-devel/wpi-plumelib/test-wpi-plumelib.sh
- docs/examples/Makefile
> Better error message if AJAVADIR cannot be determined
