typetools/checker-framework

- framework/src/org/checkerframework/framework/flow/CFAbstractTransfer.java
- framework/tests/all-systems/Issue457.java
Make the instanceof operand the backup type when calculating mostSpecific
This a fix for https://github.com/typetools/checker-framework/issues/457
> Fix Issue #457

- framework/src/org/checkerframework/framework/stub/StubParser.java
- stubparser/src/org/checkerframework/stubparser/ASTParser.java
- stubparser/src/org/checkerframework/stubparser/ast/TypeParameter.java
- stubparser/src/org/checkerframework/stubparser/ast/visitor/DumpVisitor.java
- stubparser/src/org/checkerframework/stubparser/ast/visitor/EqualsVisitor.java
- stubparser/src/org/checkerframework/stubparser/ast/visitor/GenericVisitorAdapter.java
- stubparser/src/org/checkerframework/stubparser/ast/visitor/ModifierVisitorAdapter.java
- stubparser/src/org/checkerframework/stubparser/ast/visitor/VoidVisitorAdapter.java
- stubparser/src/org/checkerframework/stubparser/java_1_5.jj
- stubparser/test/japa/parser/ast/test/classes/DumperTestClass.java
Allows annotations on type parameters (not just bounds thereof).
> Re: [checker-framework] Stub parser fails to parse type parameters of the form <@Nullable T> (#460)

- checker/build.xml
- checker/manual/nullness-checker.tex
- checker/tests/initialization/fbc/FieldSuppressWarnings.java
- framework/src/org/checkerframework/framework/source/SourceChecker.java
This patch enables a user to suppress field initialization warnings per field instead of only per constructor or per class.
> Permit per-field suppression of field initialization warnings

- eclipse/checker-framework-eclipse-update-site/manual/index.html
- release/release_push.py
In the release process, link check the live site only after all live site updates are complete.
Fix the link to CFLogo.png in the Eclipse site.
> Release process: link check the live site only after all live site updates are complete.

- framework/src/org/checkerframework/framework/util/MultiGraphQualifierHierarchy.java
Updates the ToString method of MultiGraphQualifierHierarchy to make it visually easier to debug type hierarchy problems.
The old format clumps everything into 1 giant continuous block of text. The new format adds new lines and tab indentations to the output to visually distinguish the type qualifiers and their supertypes.
This request has been reviewed at https://github.com/wmdietl/checker-framework/pull/3 and the feedback has been incorporated.
> ToString output format change in MultiGraphQualifierHierarchy

- checker/manual/external-tools.tex
I only modified the Maven instructions file in the manual...
I've created a simple project on GitHub to test this:
https://github.com/renatoathaydes/checker-maven-demo/tree/master
If you're happy with this, then I'll also update the Gradle instructions to be in line with the Maven instructions.
> Modified instructions to use Maven to make it easier for Maven users

- framework/src/org/checkerframework/framework/type/TypeFromExpressionVisitor.java
Annotations are added to the type of "Integer.class" by:
TypeFromExpressionVisitor.visitMemberSelect(...) which calls
AnnotatedTypes.asMemberOf(...) which calls AnnotatedTypeFactory.getAnnotatedType(Element) which calls AnnotatedTypeFactory.annotateImplicit(Element, AnnotatedTypeMirror)
Annotations are added to the type of "int.class" by:
TypeFromExpressionVisitor.visitMemberSelect(...) which returns
AnnotatedTypeFactory.fromElement() to
AnnotatedTypeFactory.getAnnotatedType(Tree) which calls AnnotatedTypeFactory.annotateImplicit(Tree, AnnotatedTypeMirror)
With this change, Annotations are added to the type of "int.class" by:
TypeFromExpressionVisitor.visitMemberSelect(...) which calls
AnnotatedTypeFactory.getAnnotatedType(Element) which calls …
> Treat primitive class literals the same as other class literals.

- javacutil/src/org/checkerframework/javacutil/AnnotationUtils.java
`AnnotationUtils#areSameByClass` uses a cache of interned strings; however, it still invokes `String#intern` on values retrieved from the cache. The added overhead can be significant: my test case showed a fairly significant reduction in the number of calls to `String#intern` (from ~2500 to ~1600), which resulted in a compilation time savings of around 90 seconds
> Remove redundant calls to String#intern in AnnotationUtils

- checker/src/org/checkerframework/checker/fenum/qual/FenumBottom.java
- checker/src/org/checkerframework/checker/fenum/qual/FenumTop.java
- checker/src/org/checkerframework/checker/formatter/qual/FormatBottom.java
- checker/src/org/checkerframework/checker/i18nformatter/qual/I18nFormatBottom.java
- checker/src/org/checkerframework/checker/i18nformatter/qual/I18nUnknownFormat.java
- checker/src/org/checkerframework/checker/igj/IGJBottom.java
- checker/src/org/checkerframework/checker/initialization/qual/FBCBottom.java
- checker/src/org/checkerframework/checker/oigj/OIGJMutabilityBottom.java
- checker/src/org/checkerframework/checker/regex/classic/qual/RegexBottom.java
- checker/src/org/checkerframework/checker/regex/classic/qual/UnknownRegex.java
- checker/src/org/checkerframework/checker/signature/qual/SignatureBottom.java
- framework/src/org/checkerframework/common/reflection/qual/ClassValBottom.java
- framework/src/org/checkerframework/common/reflection/qual/MethodValBottom.java
- framework/src/org/checkerframework/common/reflection/qual/UnknownClass.java
- framework/src/org/checkerframework/common/reflection/qual/UnknownMethod.java
- framework/src/org/checkerframework/common/value/qual/BottomVal.java
- framework/src/org/checkerframework/framework/qual/Bottom.java
- framework/src/org/checkerframework/framework/qual/TargetLocations.java
Adds a new meta-annotation, \@TargetLocations, that indicates locations where a particular qualifier can be written. The absence of this meta-annotation means that the qualifier can be written anywhere.
This pull request also adds \@TargetLocations to existing Top/Bottom type qualifiers in the Checker Framework.
TODO: Verify this meta-annotation.
Tests done:
cd checker; ant all-tests
> @TargetLocations meta-annotation

- checker/manual/nullness-checker.tex
- checker/src/org/checkerframework/checker/nullness/NullnessAnnotatedTypeFactory.java
- checker/src/org/eclipse/jgit/annotations/NonNull.java
- checker/src/org/eclipse/jgit/annotations/Nullable.java
JGit versions 4.2 and newer are annotated using a custom Nullable and NonNull class.  ([1] explains why JGit didn't use one of the existing Nullable annotations.)  This patch teaches checker-framework about these so it can be used to check jgit and jgit callers for nullness errors.
JGit 4.2 hasn't been released yet, so alternatively if there is some way for it to avoid using a custom Nullable class, it's not too late to fix it.
[1] https://eclipse.googlesource.com/jgit/jgit/+/e12482deed7b
> Add org.eclipse.jgit.annotations.Nullable and NonNull to aliased annotations

- javacutil/src/org/checkerframework/javacutil/TypeAnnotationUtils.java
This change is inspired by a test case I've been dealing with: https://groups.google.com/forum/#!topic/checker-framework-discuss/O8C19Lwy49A
Using a profiler, I found a significant number of calls to `com.sun.tools.javac.util.Convert#utf2string` originating from `com.sun.tools.javac.util.Name#contentEquals` when invoked by `org.checkerframework.javacutil.TypeAnnotationUtils#isTypeCompoundContained`.
Because `TypeAnnotationUtils#isTypeCompoundContained` only compares `Name` instances to other `Name` instances, it is possible to optimize the comparison by bypassing the String conversion step and comparing the underlying byte arrays directly.
This change resulted in a 10% improvement in compilation time (from 11 minutes to 10 minutes) for the test case linked above.
> Optimize comparison of com.sun.tools.javac.util.Name instances

- framework/build.xml
- framework/tests/annotationclassloader/Makefile
- framework/tests/annotationclassloader/README
Fixed an environment variable definition bug in annotationclassloader/Makefile for the location of javac.jar
It was previously assumed that the jsr308-langtools project was located in the same directory as the checker-framework project, and it had used relative paths to point to javac.jar.
It will now receive the proper jsr308-langtools project directory from ant if called by ant script.
If it is directly executed from command line, it will still utilize the old directory (users are asked to update the makefile in such a scenario to reflect their project configurations)
Also updated readme, makefile, and build target so that the ordering is always the loading from directory test followed by the loading from jar test
> fixes for jenkins CI for the annotation class loader

- framework/src/org/checkerframework/framework/type/AnnotatedTypeFactory.java
Updated the ATF to use annotations listed in the legacy @TypeQualifiers meta-annotation before loading annotations from qual directory.
If @TypeQualifiers contains any annotation class literals, then the loading will not occur for that particular ATF subclass or checker.
> Use legacy @TypeQualifiers first

- checker/manual/advanced-features.tex
- checker/src/org/checkerframework/checker/fenum/FenumAnnotatedTypeFactory.java
- checker/src/org/checkerframework/checker/nullness/KeyForAnnotatedTypeFactory.java
- checker/src/org/checkerframework/checker/nullness/qual/NonNull.java
- checker/src/org/checkerframework/checker/nullness/qual/Nullable.java
- checker/src/org/checkerframework/checker/propkey/PropertyKeyAnnotatedTypeFactory.java
- checker/src/org/checkerframework/checker/regex/RegexChecker.java
- checker/src/org/checkerframework/checker/tainting/TaintingChecker.java
- framework/src/org/checkerframework/common/value/ValueAnnotatedTypeFactory.java
- framework/src/org/checkerframework/framework/qual/DefaultInUncheckedCodeFor.java
- framework/src/org/checkerframework/framework/qual/DefaultQualifierInHierarchyInUncheckedCode.java
- framework/src/org/checkerframework/framework/source/SourceChecker.java
- framework/src/org/checkerframework/framework/type/GenericAnnotatedTypeFactory.java
- framework/src/org/checkerframework/framework/util/defaults/QualifierDefaults.java
- framework/src/org/checkerframework/qualframework/base/CheckerAdapter.java
- framework/tests/src/tests/util/FlowTestAnnotatedTypeFactory.java
- framework/tests/src/tests/util/SubQual.java
- framework/tests/src/tests/util/SuperQual.java
- framework/tests/src/tests/util/TestChecker.java
- framework/tests/test-lubglb/lubglb/quals/B.java
- framework/tests/test-lubglb/lubglb/quals/F.java
Rename DefaultForUnannotatedCode to DefaultInUncheckedCodeFor.
Rename DefaultQualifierForUnannotatedCode to DefaultQualifierInHierarchyInUncheckedCode.
> Renamings of Default{,Qualifier}ForUnannotatedCode

- framework/src/org/checkerframework/framework/type/AnnotationClassLoader.java
- Fixed an issue where when using bin-devel/javac, qualifiers located within a sub-directory of the qual directory of a checker wouldn't be loaded
Previously, the method that loaded from the build directory did not recursively looking in sub-directories for qualifiers
- refactored a few methods as well
> AnnotationClassLoader bug fix

- framework/src/org/checkerframework/framework/type/AnnotatedTypeFactory.java
- framework/src/org/checkerframework/framework/type/GenericAnnotatedTypeFactory.java
In the scenarios where @DefaultQualifierInHierarchy or @DefaultFor(DefaultLocation.OTHERWISE) are not found in any of the qualifiers added to the supported qualifier set, or if that set is empty, the stack trace does not display how many or which qualifiers are examined. This fix updates the stack trace output to print out the number of qualifiers in the set as well as the canonical names of the qualifiers in an alphabetically sorted order. Below are some examples of the new stack trace output:
// No default qualifier:
com.sun.tools.javac.Main.main(Main.java:42)
Underlying Exception: org.checkerframework.framework.source.SourceChecker$CheckerError: GenericAnnotatedTypeFactory.createQualifierDefaults: @DefaultQualifierInHierarchy or @DefaultFor(DefaultLocation.OTHERWISE) not found. Every …
> No default qualifier stack trace output enhancement

- checker/manual/annotating-libraries.tex
Clarifies/adds limitations as discussed in Issue #568.
> Stub limitations with Inner Classes

- checker/src/org/checkerframework/checker/fenum/qual/FenumBottom.java
- checker/src/org/checkerframework/checker/fenum/qual/FenumTop.java
- checker/src/org/checkerframework/checker/formatter/qual/FormatBottom.java
- checker/src/org/checkerframework/checker/i18nformatter/qual/I18nFormatBottom.java
- checker/src/org/checkerframework/checker/i18nformatter/qual/I18nUnknownFormat.java
- checker/src/org/checkerframework/checker/igj/IGJBottom.java
- checker/src/org/checkerframework/checker/initialization/qual/FBCBottom.java
- checker/src/org/checkerframework/checker/oigj/qual/OIGJMutabilityBottom.java
- checker/src/org/checkerframework/checker/regex/classic/qual/RegexBottom.java
- checker/src/org/checkerframework/checker/regex/classic/qual/UnknownRegex.java
- checker/src/org/checkerframework/checker/signature/qual/SignatureBottom.java
- checker/src/org/eclipse/jdt/annotation/NonNull.java
- checker/src/org/eclipse/jdt/annotation/Nullable.java
- checker/src/org/eclipse/jgit/annotations/NonNull.java
- checker/src/org/eclipse/jgit/annotations/Nullable.java
- framework/src/org/checkerframework/common/aliasing/qual/Unique.java
- framework/src/org/checkerframework/common/reflection/qual/ClassBound.java
- framework/src/org/checkerframework/common/reflection/qual/ClassVal.java
- framework/src/org/checkerframework/common/reflection/qual/ClassValBottom.java
- framework/src/org/checkerframework/common/reflection/qual/MethodVal.java
- framework/src/org/checkerframework/common/reflection/qual/MethodValBottom.java
- framework/src/org/checkerframework/common/reflection/qual/UnknownClass.java
- framework/src/org/checkerframework/common/reflection/qual/UnknownMethod.java
- framework/src/org/checkerframework/common/util/report/qual/ReportUnqualified.java
- framework/src/org/checkerframework/common/value/qual/BottomVal.java
- framework/src/org/checkerframework/framework/qual/Bottom.java
- framework/src/org/checkerframework/framework/util/PurityUnqualified.java
- framework/tests/src/tests/util/MonotonicOdd.java
Type qualifiers should have ElementType.TYPE_PARAMETER in their`@Target` meta-annotation unless the qualifier should be forbidden on type parameter lower bounds and wildcard upper bounds.  
For example:
````
@TP T extends Object
````
The lower bound of `T` is `@TP null`
````
@TP ? super CharSequence
````
The upper bound of `?` is `@TP Object`
(When we reviewed and merged #533, we forgot that TYPE_PARAMETER was required.  This PR fixes that.)
> Add TYPE_PARAMETER to @Target on type qualifiers

- framework/src/org/checkerframework/framework/qual/StubFiles.java
If `@StubFiles` is inherited and a checker with this annotation is subclassed, then the `AnnotatedTypeFactory` looks for those stub files in the directory of that subclass (and the user directory) and issues an error if they do not exist.   This is currently causing the SPARTA Jenkins job to fail:
http://tern.cs.washington.edu:8080/job/sparta/4542/console
> @StubFiles should not be inherited

- framework/src/org/checkerframework/framework/source/SourceChecker.java
- framework/src/org/checkerframework/framework/type/AnnotatedTypeFactory.java
(This is a continuation of PR #597 which was merged, then reverted #598.)  
atfDoNotReadCache (don't read AnnotatedTypeFactory caches)
atfDoNotCache (don't put things in AnnotatedTypeFactory caches)
atfCacheSize=int (Set the AnnotatedTypeFactory caches' size)
The purpose of this pull request is to add options to make it easier to debug issues with caching -- not to improve caching in the AnnotatedTypeFactory or to request a code review of the current caching behavior.  Therefore, these mirror the three variables used by the AnnotateTypeFactory to control caching. 
Before these options are documented in the manual, Issue #601 needs to be fix. (Fixing that issue will likely change the caching behavior and therefore change the options that should be provided to the user.)
> Added three new debugging options

- checker/src/org/checkerframework/checker/initialization/InitializationVisitor.java
- checker/tests/nullness/AssignmentDuringInitialization.java
- checker/tests/nullness/Issue345.java
The goal of this pull request is to fix Issue #345 -- not fix or improve caching generally.  Other places in the code set shouldCache or shouldReadCache to false (but not the other).  These are probably also bugs; I'm looking into them, too.
Also, as stated in the ToDo in the code, this is a hack around a larger issue with caching fields; see Issue #601.
I checked [plume-lib](https://travis-ci.org/smillst/plume-lib-typecheck/builds/111246124) and [daikon](https://travis-ci.org/smillst/daikon-typecheck-nullness/jobs/111244072) with this change an no new errors were issued.
> Don't cache or read caches when checking (some) fields in Initialization Checker

- checker/src/org/checkerframework/checker/nullness/NullnessAnnotatedTypeFactory.java
- checker/src/org/checkerframework/checker/nullness/NullnessVisitor.java
- framework/src/org/checkerframework/common/basetype/BaseTypeVisitor.java
- framework/src/org/checkerframework/framework/type/GenericAnnotatedTypeFactory.java
- framework/src/org/checkerframework/framework/type/TypesIntoElements.java
Daikon still type-checks with this change:
https://travis-ci.org/smillst/daikon-typecheck-nullness/builds/113541950
> Remove second argument to getDefaultedAnnotatedType

- framework/src/org/checkerframework/framework/type/DefaultRawnessComparer.java
- framework/src/org/checkerframework/framework/util/typeinference/DefaultTypeArgumentInference.java
- framework/tests/all-systems/InferNullType.java
In method type argument inference, null literals should be inferred and kept as an AnnotatedNullType, and not be replaced by a AnnotatedWildcardType.
If the null literal was passed as the argument to a method such as the following,
```
<T extends Object> T toInfer(T input) {
return input;
}
```
the type argument is currently inferred as a AnnotatedNullType, but then an AnnotatedWildcardType is created and return with the AnnotatedNullType's annotations applied to its extends bound. It should remain as an AnnotatedNullType.
From the included InferNullType.java test case (and with the SuppressWarnings commented out for demonstration purposes), running it with the Nullness checker produces the following outputs:
```
// Output prior to this fix
$ javac -processor Nullness InferNullType.java …
```
> Method type argument inference fix for null literals

- checker/tests/nullness-extra/Makefile
- framework/src/org/checkerframework/framework/type/AnnotatedTypeFactory.java
- framework/src/org/checkerframework/framework/util/AnnotatedTypes.java
`isVarArgs()` should be called on a method element rather than the parameter element.
> Fixes #607

- framework/src/org/checkerframework/framework/type/AnnotatedTypeFactory.java
- framework/src/org/checkerframework/framework/type/QualifierHierarchy.java
- framework/src/org/checkerframework/framework/util/MultiGraphQualifierHierarchy.java
- framework/src/org/checkerframework/framework/util/defaults/QualifierDefaults.java
- added debug printout code for checked and unchecked code defaults
- fixed a few other typos found in the framework
A call to `defaults.toString()` in an ATF will display the defaults. Here's a sample output of the debug printout when using Formatter checker:
```
Checked Code Defaults: 
( LOCAL_VARIABLE => @org.checkerframework.checker.formatter.qual.UnknownFormat )
( RESOURCE_VARIABLE => @org.checkerframework.checker.formatter.qual.UnknownFormat )
( EXCEPTION_PARAMETER => @org.checkerframework.checker.formatter.qual.UnknownFormat )
( LOWER_BOUND => @org.checkerframework.checker.formatter.qual.FormatBottom )
( IMPLICIT_LOWER_BOUND => @org.checkerframework.checker.formatter.qual.FormatBottom )
( IMPLICIT_UPPER_BOUND => @org.checkerframework.checker.formatter.qual.UnknownFormat )
( …
```
> Debug printout for QualifierDefaults and typo fixes

- checker/src/org/checkerframework/checker/fenum/FenumVisitor.java
- checker/src/org/checkerframework/checker/initialization/InitializationVisitor.java
- checker/src/org/checkerframework/checker/lock/LockVisitor.java
- checker/src/org/checkerframework/checker/nullness/KeyForVisitor.java
- checker/src/org/checkerframework/checker/nullness/NullnessVisitor.java
- framework/src/org/checkerframework/common/aliasing/AliasingVisitor.java
- framework/src/org/checkerframework/common/basetype/BaseTypeVisitor.java
Removing dead code that was pointed out by Michael Coblenz.
The isLocalVariableAssignment parameter is now dead code after this change:
https://github.com/typetools/checker-framework/commit/54034e0db91a98b0f43d4adf24dead06d37987eb#diff-45171d06cf5f30b2b7221369fabf4a94L1589
> Remove dead code from BaseTypeVisitor

- eclipse/checker-framework-eclipse-feature/feature.xml
- eclipse/checker-framework-eclipse-plugin/META-INF/MANIFEST.MF
My only concern with these changes is that we don't have an Eclipse plug-in test suite to test them. However, they did pass the sanity test that is done before each release.
> Remove Plug-in Development Environment dependencies from the Eclipse plug-in

- maven-plugin/release/README-checker-compat-qual
- maven-plugin/release/README-checker-qual
- release/release.xml
- release/release_push.py
This addresses the primary need identified in issue #182, which is to
provide proper IDE support for the pre-defined type annotations provided
by the Checker Framework.
> Re-use checker source/javadoc JARs for checker-qual and checker-compat-qual

- checker/src/org/checkerframework/checker/guieffect/GuiEffectVisitor.java
- checker/src/org/checkerframework/checker/javari/JavariVisitor.java
- framework/src/org/checkerframework/framework/flow/CFAbstractTransfer.java
- framework/src/org/checkerframework/framework/util/defaults/QualifierDefaults.java
These changes are so that various AnnotatedTypeFactory methods can be marked non-public.
> Refactor calls to AnnotatedTypeFactory methods

- framework/src/org/checkerframework/framework/type/AnnotatedTypeFactory.java
- framework/src/org/checkerframework/framework/util/typeinference/GlbUtil.java
This change allows AnnotatedTypeFactory#toAnnotatedType to be marked protected.  (It's not changed to protected in this pull request because there are additional calls that have to be change first.)
> Move code that creates AnnotatedNullType to ATF

- framework/src/org/checkerframework/common/basetype/BaseTypeVisitor.java
- framework/src/org/checkerframework/framework/type/GenericAnnotatedTypeFactory.java
- Move code that gets the return type of a member reference constructor to
AnnotatedTypeFactory.
- Move code that checks is method type argument inference is required to private method.
> Refactor member reference code

- checker/src/org/checkerframework/checker/initialization/InitializationAnnotatedTypeFactory.java
- checker/src/org/checkerframework/checker/initialization/InitializationVisitor.java
- javacutil/src/org/checkerframework/javacutil/AnnotationUtils.java
AnnotatedTypeFactory#fromMember should not  be used to get explicit annotations.
> Initialization: get explicit annotations from Tree

- framework/src/org/checkerframework/common/basetype/BaseTypeVisitor.java
- framework/tests/polyall/TypeRefinement.java
- framework/tests/test-polyall/polyall/PolyAllAnnotatedTypeFactory.java
- framework/tests/test-polyall/polyall/PolyAllVisitor.java
- framework/tests/test-polyall/polyall/quals/H1Bot.java
- framework/tests/test-polyall/polyall/quals/H1Invalid.java
(This is an alternative to #634.)
````
@H1Top Object o = new @H1Invalid Object();
````
Two invalid type errors used to be issued for this code. One for the new Object and one for `o`.
> Validate declared type of LHS, not refined type.

- checker/tests/nullness/Issue672.java
- checker/tests/nullness/java8/Issue557.java
- framework/src/org/checkerframework/framework/util/typeinference/TypeArgInferenceUtil.java
- javacutil/src/org/checkerframework/javacutil/TreeUtils.java
Improves type agr inference for nested conditionals.  This is a rebased version
of the code reviewed in pull request #675. Plus addtional changes to fix bug
that made plume-lib-typecheck crash.  (This is the correction to f010477deb460a496d66c963593e42ac3e1e181f which was reverted in 4fb2074207cb698be9127b86d7f9fc8733f7fa91)
> (Correctly) Fixes #672

- checker/tests/nullness/Issue577.java
- framework/src/org/checkerframework/framework/util/AnnotatedTypes.java
- framework/tests/all-systems/Issue577.java
Fixes #577
AnnotatedDeclaredType#getEnclosingType is missing annotations and the qualifier framework does not implement QualifiedDeclaredType#getEnclosingType (see #724).   Because of this, this pull request causes the Regex and Tainting Checker to issue (new) false positive warnings.
> asMemberOf should substitute type variables declared in outer classes too

- checker/tests/interning/TypeVarPrimitives.java
- checker/tests/nullness/TypeVarPrimitives.java
- framework/src/org/checkerframework/framework/type/DefaultTypeHierarchy.java
- framework/tests/all-systems/ConditionalExpressions.java
- framework/tests/all-systems/TypeVarPrimitives.java
Example of when these combinations are used:
````
public class TypeVarPrimitives {
<T extends Long> void method(T tLong) {
long l = tLong;
}
<T extends Long & Cloneable> void methodIntersection(T tLong) {
long l = tLong;
}
````
(This covers 2/5 cases in issue #701)
> Add Intersection_Primitive and Typevar_Primitive combinations to isSubtype

- checker/examples/units-extension/Makefile
- framework/src/org/checkerframework/framework/util/CheckerMain.java
Fixes issue #700, "Too many classes on the bootclasspath".
> Put checker.jar on processorpath, not classpath

- checker/src/org/checkerframework/checker/guieffect/GuiEffectVisitor.java
- framework/tests/all-systems/Issue689.java
This is a candidate fix for #689.  It appears the assertion was too strong, because apparently none of the work on the ECOOP paper encountered anonymous inner classes with non-trivial (i.e., method-invoking) field initializers, which don't get visited in the context of an enclosing method structure.
A test for this is necessary as well before I close the issue, but I want this to go through CI to maybe unstick things for Monday.
> Candidate for #689

- framework/src/org/checkerframework/common/basetype/BaseTypeVisitor.java
- framework/src/org/checkerframework/framework/flow/CFAbstractStore.java
- framework/src/org/checkerframework/framework/flow/CFAbstractTransfer.java
- framework/src/org/checkerframework/framework/qual/TargetLocations.java
- framework/src/org/checkerframework/framework/util/FlowExpressionParseUtil.java
Add comments to code that handles parsing of flow expressions and storage/retrieval of their refined values as determined by dataflow analysis.
In addition to these comments, there is a summary [in this document](https://docs.google.com/document/d/10tYe0D60hDHdyLT2q9mIPmWHIzZaCU2UHS2lP-grNiQ/edit#bookmark=id.mzn7kztlxn7b) of how `BaseTypeVisitor.checkPreconditions` together with `FlowExpressionParseUtil.parse` perform viewpoint adaptation for member accesses. Please let me know if you would like me to include that text as a comment in FlowExpressionParseUtil.java.
> Add comments to flow expression parsing and dataflow

- checker/src/org/checkerframework/checker/nullness/NullnessTransfer.java
- checker/tests/nullness/init/InstanceOf.java
- framework/src/org/checkerframework/framework/flow/CFAbstractTransfer.java
However, the operand of an instance of is non-null if the instanceof is true.
This changes cause a new (legitimate) Daikon type-checking error at [this line](https://github.com/codespecs/daikon/blob/master/java/daikon/Debug.java#L530). It's a method.invocation.invaild error on `pslice.num_samples();`.
> It's unsound to refine the operand of an instanceof.

- release/release_utils.py
When pushing from the bare interm git repositories, the follow error is issued (though the release scripts thinks the push succeeds):
````
fatal: The current branch master has no upstream branch.
To push the current branch and set the remote as upstream, use
git push --set-upstream origin master
````
Use --mirror so that branches track origin branches correctly and git push works with out specifying a remote branch to push to.
> Release fix: Use --mirror

- checker/tests/nullness-extra/Makefile
- checker/tests/nullness-extra/issue594/Expected.txt
- checker/tests/nullness-extra/issue594/Issue594.java
- checker/tests/nullness-extra/issue594/Makefile
- framework/src/org/checkerframework/common/basetype/BaseTypeVisitor.java
- framework/src/org/checkerframework/framework/type/AnnotatedTypeFormatter.java
- framework/src/org/checkerframework/framework/type/AnnotatedTypeMirror.java
- framework/src/org/checkerframework/framework/type/DefaultAnnotatedTypeFormatter.java
- framework/src/org/checkerframework/qualframework/base/CheckerAdapter.java
Including printAllQualifiers and printVerboseGenerics.  This means that the
full generics information will be printed at assignment types incompatible when
the shorter toString does not differ between types. (This implements so of the
functionality discussed in #594, but not all.  In particular, https://github.com/typetools/checker-framework/issues/594#issuecomment-183120237 is not addressed.)
> AnnotatedTypeMirror.toString(true) uses all verbose settings

- checker/src/org/checkerframework/checker/fenum/FenumVisitor.java
- checker/tests/fenum/Issue692.java
isSubtype cannot be called when the underlying Java types are not subtypes.  Check the effective annotations instead.
> Fixes #692

- checker/tests/nullness/Initializer.java
- checker/tests/nullness/init/Issue779.java
- framework/src/org/checkerframework/framework/flow/CFAbstractTransfer.java
Fixes #779 
(I'm currently testing this with daikon and plume-lib.  This change could cause new errors in those code bases.)
> Fields in methods whose receiver is not fully initialized

- checker/examples/fenum-extension/Makefile
- checker/examples/subtyping-extension/Makefile
- checker/examples/units-extension/Makefile
- checker/manual/fenum-checker.tex
- checker/manual/subtyping-checker.tex
- checker/manual/units-checker.tex
- framework/src/org/checkerframework/framework/type/AnnotationClassLoader.java
- framework/tests/annotationclassloader/Makefile
Previously, the `AnnotationClassLoader` using itself's ClassLoader (which is null, usually means will using the bootstrap class loader) to load annotation Classes, which means the annotation class files need to be set in bootstrap classpath.
This will cause problems when loading an external annotation class outside of CheckerFramework. Even with correct `fullyQualifiedClassName`, the previously code will still throw ClassNotFoundException.
I changed the code to using the class loader returned by `AnnotationClassLoader#getAppClassLoader()`.
( This `getAppClassLoader()` method will return current checker's ClassLoader or return `SystemClassLoader` if checker's ClassLoader is null. )
This change will let the Checker Framework correctly loads external checker's qualifier classes, either by …
> using AppClassLoader to load Annotation classes of a checker.

- checker/tests/nullness/Issue765.java
- dataflow/src/org/checkerframework/dataflow/analysis/Analysis.java
Only the Nullness and Nullness Rawness Checkers trip the assert.  I can't figure out why that's the case, but it seems safe to remove the assert and return null instead.  (I tested this change on daikon with my other asSuper changes and it typechecked.)
> Fix for #765 (Failed assert in dataflow) 

- dataflow/src/org/checkerframework/dataflow/cfg/DOTCFGVisualizer.java
in `DOTCFGVisualizer#visualizeBlockTransferInput()`, when a transfer-input only have a regular store, the visualizer should visualise the regular store by the then-branch from line 356 to line 361 in file [DOTCFGVisualizer.java](https://github.com/typetools/checker-framework/blob/master/dataflow/src/org/checkerframework/dataflow/cfg/DOTCFGVisualizer.java#L356).
However, in line 355, the variable `thenStore` never be null because [TransferInput#getThenStore()](https://github.com/typetools/checker-framework/blob/master/dataflow/src/org/checkerframework/dataflow/analysis/TransferInput.java#L185) always returns a non-null value. Thus, current code actually always using the else-branch to visualise stores of a transfer-input, which will cause the visualizer visualize the same store twice when …
> fix bug in DOTCFGVisualizer: visualise same store twice when input only have a regular store

- checker/bin/infer-and-annotate.sh
- checker/manual/inference.tex
This change allows the `infer-and-annotate.sh` to receive as argument flags that will be used when calling `insert-annotations-to-source`. One example of such flag is `-c`, which will insert annotations in comments. These flags are optional, and must come before the preprocessor when calling `infer-and-annotate.sh`. The manual and documentation of the script were updated to explain that.
Tests:
Manual verification running `infer-and-annotate.sh` using the NullnessChecker on plume-lib, with and without the `-c` argument.
> infer-and-annotate.sh receives command-line options to insert-annotations-to-source

- checker/bin-devel/javac
- framework/src/org/checkerframework/framework/util/CheckerDevelMain.java
- framework/src/org/checkerframework/framework/util/CheckerMain.java
Small refactorings to use Lists instead of arrays.
fixes the bin-devel/javac script by @wmdietl
> Fix checker/bin-devel/javac by adding a processor path option.

- .travis-build.sh
- .travis.yml
- checker/bin-devel/Dockerfile-README
- checker/bin-devel/Dockerfile-jdk7
- checker/bin-devel/Dockerfile-jdk8
- checker/bin-devel/Dockerfile-jdkany
- checker/jdk/Makefile
- checker/jdk/Makefile.jdk
Reverts typetools/checker-framework#859
The test don't seem to actually be running.  For example the JDK7 JUnit test only took 1 min 4 sec.  Also, the tests in pull request #754 [fail](https://travis-ci.org/typetools/checker-framework/builds/147208752) on the branch, but [pass](https://travis-ci.org/typetools/checker-framework/builds/147208769) when merged to master.  Revert this change until we can fix this.
> Revert "Run some downstream tests in Travis, so they are tested for pull requests"

- changelog.txt
- framework/jtreg/issue845/checker/NotInPackageChecker.java
- framework/jtreg/issue845/checker/qual/NotInPackageTop.java
- framework/jtreg/issue845/test/Test.java
- framework/src/org/checkerframework/framework/type/AnnotationClassLoader.java
> Don't require checkers to be in a package (Fixes #854)

- checker/src/org/checkerframework/checker/nullness/KeyForAnnotatedTypeFactory.java
- framework/src/org/checkerframework/common/basetype/BaseTypeValidator.java
- framework/src/org/checkerframework/framework/flow/CFAbstractValue.java
- framework/src/org/checkerframework/framework/type/AnnotatedTypeMirror.java
- framework/src/org/checkerframework/framework/type/GeneralAnnotatedTypeFactory.java
- framework/src/org/checkerframework/framework/type/QualifierHierarchy.java
- framework/src/org/checkerframework/framework/util/AnnotatedTypes.java
- framework/src/org/checkerframework/framework/util/MultiGraphQualifierHierarchy.java
- framework/src/org/checkerframework/qualframework/base/QualifierHierarchyAdapter.java
QualifierHierarchy#getAnnotationInHierarchy used to return `@PolyAll` even if another annotation in that hierarchy is in the set.  
Also, renamed find findCorrespondingAnnotation to getCorrespondingAnnotation.  Though maybe getAnnotationInSameHierarchy would be better?
getCorrespondingAnnotation now calls getAnnotationInHierarchy rather than reimplementing the same functionality.  This uncovered a bug in QualifierHierarchyAdapter#getAnnotationInHierarchy which I fixed.
> Fixes bug in getAnnotationInHierarchy involving @PolyAll

- checker/src/org/checkerframework/checker/nullness/KeyForAnnotatedTypeFactory.java
- framework/src/org/checkerframework/common/basetype/BaseTypeValidator.java
- framework/src/org/checkerframework/framework/flow/CFAbstractValue.java
- framework/src/org/checkerframework/framework/type/AnnotatedTypeMirror.java
- framework/src/org/checkerframework/framework/type/GeneralAnnotatedTypeFactory.java
- framework/src/org/checkerframework/framework/type/QualifierHierarchy.java
- framework/src/org/checkerframework/framework/util/AnnotatedTypes.java
- framework/src/org/checkerframework/framework/util/MultiGraphQualifierHierarchy.java
- framework/src/org/checkerframework/qualframework/base/QualifierHierarchyAdapter.java
Reverts typetools/checker-framework#869
(Caused daikon-typecheck failures http://tern.cs.washington.edu:8080/job/daikon-typecheck/jdk=JDK_7/1092/console)
> Revert "Fixes bug in getAnnotationInHierarchy involving @PolyAll"

- framework/src/org/checkerframework/framework/type/TypesIntoElements.java
- framework/src/org/checkerframework/framework/util/element/SuperTypeApplier.java
This PR resolved the set different sizes issues posted in pascaliUWat/CFI:
- https://github.com/pascaliUWat/checker-framework-inference/issues/15
- https://github.com/pascaliUWat/checker-framework-inference/issues/14
Also fixed bugs caused by enabling storing extends/implements for a class element :
1. add if-check in storeClassExtends(): do nothing when the passed class symbol is an interface or java.lang.Object. This fixed a Nullpointer Exception. 
2. changed `typeOffset` in `SuperTypeAppiler#annotateSupers()` to always be -1. detail reasons are commented in code
The original review of this code is here: 
https://github.com/opprop/checker-framework/pull/5
> enable storing extends/implements in TypesIntoElements#store()

- framework/src/org/checkerframework/framework/type/TypesIntoElements.java
- framework/src/org/checkerframework/framework/util/element/SuperTypeApplier.java
Reverts typetools/checker-framework#876
Caused daikon-typecheck to fail with the Nullness Checker.   Here's a minimized example. 
````
import java.io.Serializable;
class Test implements Serializable {
}
````
````
class Other {
void foo() {
Test other = null;
}
}
````
````
javacheck -processor nullness Test.java Other.java
Other.java:3: error: [assignment.type.incompatible] incompatible types in assignment.
Test other = null;
^
found   : null
required: @Initialized @NonNull Test
1 error
````
> Revert "enable storing extends/implements in TypesIntoElements#store()"

- checker/src/org/checkerframework/checker/fenum/FenumAnnotatedTypeFactory.java
- checker/src/org/checkerframework/checker/fenum/qual/PolyFenum.java
- checker/src/org/checkerframework/checker/guieffect/GuiEffectVisitor.java
- checker/src/org/checkerframework/checker/nullness/KeyForAnnotatedTypeFactory.java
- checker/src/org/checkerframework/checker/regex/qual/PolyRegex.java
- checker/src/org/checkerframework/checker/signedness/SignednessAnnotatedTypeFactory.java
- checker/src/org/checkerframework/checker/signedness/qual/PolySignedness.java
- checker/src/org/checkerframework/checker/tainting/qual/PolyTainted.java
- checker/src/org/checkerframework/checker/tainting/qual/Tainted.java
- checker/src/org/checkerframework/checker/tainting/qual/Untainted.java
- framework/src/org/checkerframework/common/basetype/BaseTypeValidator.java
- framework/src/org/checkerframework/common/util/report/ReportVisitor.java
- framework/src/org/checkerframework/common/value/ValueAnnotatedTypeFactory.java
- framework/src/org/checkerframework/framework/flow/CFAbstractValue.java
- framework/src/org/checkerframework/framework/type/AnnotatedTypeFactory.java
- framework/src/org/checkerframework/framework/type/AnnotatedTypeMirror.java
- framework/src/org/checkerframework/framework/type/GeneralAnnotatedTypeFactory.java
- framework/src/org/checkerframework/framework/type/QualifierHierarchy.java
- framework/src/org/checkerframework/framework/util/AnnotatedTypes.java
- framework/src/org/checkerframework/framework/util/GraphQualifierHierarchy.java
- framework/src/org/checkerframework/framework/util/MultiGraphQualifierHierarchy.java
- framework/src/org/checkerframework/qualframework/base/QualifierHierarchyAdapter.java
- framework/tests/all-systems/PolyAllTypeVar.java
This includes the changes reviewed in #869 that were reverted because of daikon-typecheck failures.  Daikon still type checks with these changes.
> More @PolyAll fixes

- framework/src/org/checkerframework/framework/type/AnnotatedTypeFactory.java
This is consistent with document of `@PolyAll`
Fixes #883
> Only support PolyAll by default if a polymorphic qualifier exists

- checker/manual/constant-value-checker.tex
- framework/src/org/checkerframework/common/value/ValueAnnotatedTypeFactory.java
- framework/src/org/checkerframework/common/value/ValueChecker.java
- framework/tests/src/tests/ValueTest.java
> Only report the Constant Value Checker evaluation warns if command line option is used.

- checker/src/org/checkerframework/checker/lock/LockStore.java
- checker/tests/lock/ChapterExamples.java
- checker/tests/lock/TestTreeKinds.java
- checker/tests/lock/Update.java
Fix Lock Checker bug where expressions lost there refinement in the @GuardedBy hierarchy if they became @LockPossiblyHeld.
> Fix lost @GuardedBy refinements

- framework/src/org/checkerframework/framework/type/AnnotationClassLoader.java
- javacutil/src/org/checkerframework/javacutil/AnnotationUtils.java
- javacutil/src/org/checkerframework/javacutil/InternalUtils.java
Add an util method for obtaining class loader for a class in `javacutil.InternalUtils`.
The logic is borrowed from `AnnotationClassLoader#getAppClassLoader()`:
"it will first try to obtain the class loader of the target class, if that is not available then it will try to obtain the system class loader."
Move this logic to `javacutil` could benefit checker-framework to have a unify mechanism of obtaining the class loader --- all place that might need support loading external classes should first get the `classloader` by calling this util method and then use `Class.forname(name, ..., classloader)` to load class.
We currently put this util method in `javacutil.InternalUtils` as it seems other place would be even more not suitable for this util method.
> Add util method for obtaining class loader

- dataflow/src/org/checkerframework/dataflow/cfg/JavaSource2CFGDOT.java
The option was removed as part of JDK-8148808 [1][2]. Setting
`-XDcompilePolicy=ATTR_ONLY` provides equivalent behaviour.
[1] https://bugs.openjdk.java.net/browse/JDK-8148808
[2] http://hg.openjdk.java.net/jdk9/dev/langtools/rev/645b5debcb07
> Migrate off deprecated javac option 'attrParseOnly'

- framework/src/org/checkerframework/framework/type/GenericAnnotatedTypeFactory.java
- framework/src/org/checkerframework/framework/util/defaults/QualifierDefaults.java
Also move check for qualifier defaults into separate method. The motivation for this is so that we can override `ensureDefaultsExist` in checker-framework-inference. We run into the error after removing Unqualified as a supported Type Qualifier but when dealing with inference we don't need a default.
> Refactor GenericAnnotatedTypeFactory methods to be more finegrained.

- dataflow/src/org/checkerframework/dataflow/cfg/node/BinaryOperationNode.java
- dataflow/src/org/checkerframework/dataflow/cfg/node/BitwiseAndNode.java
- dataflow/src/org/checkerframework/dataflow/cfg/node/BitwiseComplementNode.java
- dataflow/src/org/checkerframework/dataflow/cfg/node/BitwiseOrNode.java
- dataflow/src/org/checkerframework/dataflow/cfg/node/BitwiseXorNode.java
- dataflow/src/org/checkerframework/dataflow/cfg/node/ConditionalAndNode.java
- dataflow/src/org/checkerframework/dataflow/cfg/node/ConditionalNotNode.java
- dataflow/src/org/checkerframework/dataflow/cfg/node/ConditionalOrNode.java
- dataflow/src/org/checkerframework/dataflow/cfg/node/EqualToNode.java
- dataflow/src/org/checkerframework/dataflow/cfg/node/FloatingDivisionNode.java
- dataflow/src/org/checkerframework/dataflow/cfg/node/FloatingRemainderNode.java
- dataflow/src/org/checkerframework/dataflow/cfg/node/GreaterThanNode.java
- dataflow/src/org/checkerframework/dataflow/cfg/node/GreaterThanOrEqualNode.java
- dataflow/src/org/checkerframework/dataflow/cfg/node/IntegerDivisionNode.java
- dataflow/src/org/checkerframework/dataflow/cfg/node/IntegerRemainderNode.java
- dataflow/src/org/checkerframework/dataflow/cfg/node/LeftShiftNode.java
- dataflow/src/org/checkerframework/dataflow/cfg/node/LessThanNode.java
- dataflow/src/org/checkerframework/dataflow/cfg/node/LessThanOrEqualNode.java
- dataflow/src/org/checkerframework/dataflow/cfg/node/NotEqualNode.java
- dataflow/src/org/checkerframework/dataflow/cfg/node/NumericalAdditionNode.java
- dataflow/src/org/checkerframework/dataflow/cfg/node/NumericalMinusNode.java
- dataflow/src/org/checkerframework/dataflow/cfg/node/NumericalMultiplicationNode.java
- dataflow/src/org/checkerframework/dataflow/cfg/node/NumericalPlusNode.java
- dataflow/src/org/checkerframework/dataflow/cfg/node/NumericalSubtractionNode.java
- dataflow/src/org/checkerframework/dataflow/cfg/node/SignedRightShiftNode.java
- dataflow/src/org/checkerframework/dataflow/cfg/node/StringConcatenateNode.java
- dataflow/src/org/checkerframework/dataflow/cfg/node/UnaryOperationNode.java
- dataflow/src/org/checkerframework/dataflow/cfg/node/UnsignedRightShiftNode.java
Add abstract classes `UnaryOperation` and `BinaryOperation` to categorize operations Node types into `UnaryOperation` and `BinaryOperation`.
This could reduce code duplication in dataflow-framework, and also could enable us to have conciser code expression when developing dataflow analysis.
Original PR and code review in `opprop` please see here:
https://github.com/opprop/checker-framework/pull/19
>  Add an abstract level of BinaryOperation and UnaryOperation in Node hierarchy

- framework/src/org/checkerframework/framework/test/CheckerFrameworkPerDirectoryTest.java
- framework/src/org/checkerframework/framework/test/CheckerFrameworkPerFileTest.java
- framework/src/org/checkerframework/framework/test/diagnostics/TestDiagnosticUtils.java
Also, print all lines of CheckerErrors, so that the error stack is printed.  For example:
```
[junit] While type-checking /Users/smillst/jsr308/checker-framework/checker/tests/nullness/java8/lambda/Dataflow.java, /Users/smillst/jsr308/checker-framework/checker/tests/nullness/java8/lambda/FinalLocalVariables.java, /Users/smillst/jsr308/checker-framework/checker/tests/nullness/java8/lambda/Initialization.java, /Users/smillst/jsr308/checker-framework/checker/tests/nullness/java8/lambda/Issue367.java, /Users/smillst/jsr308/checker-framework/checker/tests/nullness/java8/lambda/Issue403.java, /Users/smillst/jsr308/checker-framework/checker/tests/nullness/java8/lambda/Issue436.java, /Users/smillst/jsr308/checker-framework/checker/tests/nullness/java8/lambda/Issue572.java, …
```
> Always pass -AprintErrorStack to test class.

- framework/src/org/checkerframework/framework/type/treeannotator/PropagationTreeAnnotator.java
- framework/src/org/checkerframework/framework/type/treeannotator/TreeAnnotator.java
- framework/tests/all-systems/BigBinaryTrees.java
Also, add an all-systems test for big binary trees.
> Prevent needlessly recomputing left and right operands of binary trees

- framework/src/org/checkerframework/framework/type/AnnotatedTypeCopier.java
- framework/src/org/checkerframework/framework/type/AnnotatedTypeFactory.java
- framework/src/org/checkerframework/framework/type/AnnotatedTypeMirror.java
- framework/src/org/checkerframework/framework/type/AsSuperVisitor.java
- framework/src/org/checkerframework/framework/type/DefaultTypeHierarchy.java
- framework/src/org/checkerframework/framework/type/EqualityAtmComparer.java
- framework/src/org/checkerframework/framework/util/QualifierPolymorphism.java
- framework/src/org/checkerframework/framework/util/typeinference/DefaultTypeArgumentInference.java
- framework/tests/all-systems/Issue953.java
This pull request renames the field typeArgHack in AnnotatedWildcardType to isUninferredTypeArgument and documents it.  Also, it adds handling of uninferred type arguments to asSuper.  This fixes the first crash reported in #953.
> Correct handling of uninferred type arguments

- framework/src/org/checkerframework/framework/util/AnnotationMirrorMap.java
- framework/src/org/checkerframework/framework/util/AnnotationMirrorSet.java
- framework/src/org/checkerframework/framework/util/typeinference/DefaultTypeArgumentInference.java
- framework/src/org/checkerframework/framework/util/typeinference/GlbUtil.java
- framework/src/org/checkerframework/framework/util/typeinference/TypeArgInferenceUtil.java
- framework/src/org/checkerframework/framework/util/typeinference/solver/ConstraintMap.java
- framework/src/org/checkerframework/framework/util/typeinference/solver/ConstraintMapBuilder.java
- framework/src/org/checkerframework/framework/util/typeinference/solver/EqualitiesSolver.java
- framework/src/org/checkerframework/framework/util/typeinference/solver/InferenceResult.java
- framework/src/org/checkerframework/framework/util/typeinference/solver/InferredValue.java
- framework/src/org/checkerframework/framework/util/typeinference/solver/SubtypesSolver.java
- framework/src/org/checkerframework/framework/util/typeinference/solver/SupertypesSolver.java
- framework/src/org/checkerframework/framework/util/typeinference/solver/TargetConstraints.java
- framework/tests/all-systems/Issue953.java
- framework/tests/all-systems/Issue953b.java
- javacutil/src/org/checkerframework/javacutil/AnnotationUtils.java
This pull request only updates the classes in org.checkerframework.framework.util.typeinference.* to use the new classes.  We could update the rest of the classes if desired.  I updated type argument inference first because it using annotation mirror sets and maps caused a crash.
> Use AnnotationMirror sets and maps that don't use the equals method.

- framework/src/org/checkerframework/framework/type/AnnotatedTypeFactory.java
- framework/src/org/checkerframework/framework/type/AnnotatedTypeMirror.java
- framework/tests/all-systems/Issue988.java
- framework/tests/all-systems/RawTypeAssignment.java
Move code that creates type arguments for raw types to the AnnotatedTypeMirror. (Fixes #988.)
> Add type arguments for all raw types (Fixes #988)

- checker/jdk/nullness/src/java/sql/PreparedStatement.java
Updated annotated `java.sql.PreparedStatement` to allow most `#setXXX` calls to allow a `null` parameter.
`PreparedStatement` had previously been updated to allow `#setString` and `#setObject` to take `null` parameters.
This has been verified as allowed using the MySQL driver as a reference implementation.
Note that this commit does not update the following methods, because I could not find an actual implementation of them; I believe they may also accept `null`, but could not confirm:
- `#setArray`
- `#setRef`
- `#setRowId`
- `#setSQLXML`
> Add more @Nullable annotations to PreparedStatement

- checker/src/org/checkerframework/checker/lock/LockAnnotatedTypeFactory.java
- checker/src/org/checkerframework/checker/lock/LockVisitor.java
- checker/src/org/checkerframework/checker/lock/messages.properties
- checker/tests/lock-safedefaults/BasicTest.java
- checker/tests/lock/ChapterExamples.java
- checker/tests/lock/Constructors.java
- checker/tests/lock/Fields.java
- checker/tests/lock/FlowExpressions.java
- checker/tests/lock/GuardSatisfiedTest.java
- checker/tests/lock/Issue152.java
- checker/tests/lock/Issue524.java
- checker/tests/lock/ItselfExpressionCases.java
- checker/tests/lock/JCIPAnnotations.java
- checker/tests/lock/LockEffectAnnotations.java
- checker/tests/lock/LockExpressionIsFinal.java
- checker/tests/lock/NestedSynchronizedBlocks.java
- checker/tests/lock/Primitives.java
- checker/tests/lock/Simple.java
- checker/tests/lock/Strings.java
- checker/tests/lock/TestConcurrentSemantics1.java
- checker/tests/lock/TestTreeKinds.java
- checker/tests/lock/ThisPostCondition.java
- checker/tests/lock/ThisSuper.java
- checker/tests/lock/ViewpointAdaptation.java
- checker/tests/lock/ViewpointAdaptation2.java
- checker/tests/lock/ViewpointAdaptation3.java
- framework/src/org/checkerframework/common/basetype/BaseTypeVisitor.java
- framework/src/org/checkerframework/framework/util/ContractsUtils.java
- framework/src/org/checkerframework/framework/util/expressionannotations/ExpressionAnnotationError.java
- framework/src/org/checkerframework/framework/util/expressionannotations/ExpressionAnnotationHelper.java
The Lock Checker hacked BaseTypeVisitor's precondition code to issue a contracts.precondition.not.satisfied.field error when a lock was not held. This commit removes that hack from BaseTypeVisitor and a "lock.not.held" error is issued instead.
(Daikon type-checks with this change and takes about the same amount of time.)
> Update the Lock Checker to use the expression annotation support.

- docs/manual/figures/upperbound.svg
- docs/manual/index-checker.tex
in response to Mike's request. The figure in the upperbound section of the manual no longer says "java.lang.String" and instead says "myArray". I also made what "myArray" means explicit in the caption.
> Changed upperbound manual picture to give an example

- checker/tests/lowerbound/IndexOrLowTests.java
- checker/tests/upperbound/IndexOrLowTests.java
This pull request cleans up the tests for the IndexOrLow qualifier. In particular, it:
- removes any line that would issue a warning if the other checker was run (i.e. the upperbound test now no longer issues an `array.index.unsafe.low` warning if the lowerbound checker is run on it)
- makes types explicit where possible (note esp. the inclusion of @IndexOrHigh in both tests)
- adds some additional test cases
> IndexOrLow tests

- checker/tests/index/PrimitiveWrappers.java
This test should pass. Allows resolution of https://github.com/kelloggm/checker-framework/issues/65.
> Add test to make sure primitive wrappers work the same as primitives.

- checker/tests/index/ArrayCreationParam.java
- checker/tests/index/Offset97.java
Suzanne's offset changes fixed both kelloggm#93 and kelloggm#97. These tests should show that.
> New tests for offsets

- checker/src/org/checkerframework/checker/index/samelen/SameLenAnnotatedTypeFactory.java
- checker/src/org/checkerframework/checker/index/samelen/SameLenTransfer.java
- checker/tests/index/SameLenAssignmentTransfer.java
- checker/tests/index/SameLenManyArrays.java
- framework/src/org/checkerframework/framework/type/GenericAnnotatedTypeFactory.java
The fundamental problem is that when a programmer writes annotations, they aren't automatically symmetric. Here's a smaller test case that showcases the problem that this PR fixes:
```java
void test(int @SameLen("#2") [] a, int[] b) {
int[] c = new int[a.length];
for(int i = 0; i < c.length; i++) { // i's type is @LTL("c")
b[i] = 1; // b's type is @SameLenUnknown, so fails
int @SameLen({"a", "b", "c"}) [] d = c; // succeeds
}
}
```
SameLen types are symmetric in the sense that all the ones that are inferred are applied to both of the arrays involved. So for instance in the example above, `int [] c = new int[a.length]` results in both a and c being updated. But it doesn't update the other SameLen types that are associated with a and c - which is to say, while both a and c become …
> Makes samelen symmetric in most cases

- docs/manual/figures/upperbound.svg
LTOM and LTEL were in the wrong places in the manual figures. Mike noticed this.
> Fixed blatantly incorrect figure in the manual

- framework/src/org/checkerframework/framework/util/FlowExpressionParseUtil.java
- framework/tests/flowexpression/TestParsing.java
Is there a better way to get the element for `length` or `clone` than using the resolver?
> FlowExpressionParse should parse array lengths and clone()

- checker/src/org/checkerframework/checker/index/upperbound/UpperBoundTransfer.java
- checker/tests/index/ArrayIntroWithCast.java
Consider the following testcase:
```java
import org.checkerframework.checker.index.qual.*;
class ArrayIntroWithCast<T> {
void test(String[] a, String[] b) {
Object result = new Object[a.length + b.length];
System.arraycopy(a, 0, result, 0, a.length);
}
void test2(String[] a, String[] b) {
@SuppressWarnings("unchecked")
T[] result = (T[]) new Object[a.length + b.length];
System.arraycopy(a, 0, result, 0, a.length);
}
}
```
The first function (`test`) compiles with no warnings, but the second function (`test2`) does not in master. The only difference is the addition of the cast to a generic argument. This PR fixes this problem, allowing both versions to compile. See kelloggm#106
> Allows UB transfer to handle arrays that are cast when they're created

- checker/build.xml
- checker/tests/fenum-extension
- checker/tests/subtyping-extension
- checker/tests/units-extension
And the targets that used to refer to them.  The directories are tested via example-tests target instead individual ones.  Fixes #1053.
> Remove dangling symbolic links.

- checker/jdk/index/src/java/lang/String.java
This is causing a problem in the plume-lib case study for the index checker
> Index JDK: Comment out MinLen annotation in String because Strings aren't supported

- checker/src/org/checkerframework/checker/index/upperbound/OffsetEquation.java
- checker/src/org/checkerframework/checker/index/upperbound/UBQualifier.java
- checker/tests/index/ConstantOffsets.java
If an expression has a know value, then both the know value and the expression should be used as offsets.  This fixes the first part of https://github.com/kelloggm/checker-framework/issues/108.
> Index Checker: value offsets

- checker/src/org/checkerframework/checker/index/samelen/SameLenAnnotatedTypeFactory.java
- checker/src/org/checkerframework/checker/index/samelen/SameLenTransfer.java
- checker/tests/index/SameLenManyArrays.java
- checker/tests/index/SimpleCollection.java
Consider the following test case, from kelloggm#110:
```java
import org.checkerframework.checker.index.qual.*;
class SimpleCollection {
private int[] values;
@IndexOrHigh("values") int size() {
return values.length;
}
void interact_with_other(SimpleCollection other) {
for(int j = 0; j < other.size(); j++) {
int k = other.values[j]; // No warning from index checker
}
int[] othervalues = other.values;
for(int i = 0; i < other.size(); i++) {
int k = othervalues[i]; // Index checker issues warning
}
}
}
```
This patch fixes that extraneous warning by adding a rule so that when something is assigned into an array, that array and the thing being assigned become part of the same SameLen type. It also corrects a bug in propagateCombinedSameLen that would sometimes pass a null TreePath as the …
> Allow SameLen to correctly handle assignments.

- checker/src/org/checkerframework/checker/index/samelen/SameLenAnnotatedTypeFactory.java
- checker/tests/index/ParsingBug.java
There are probably more places this needs to be done.  I'm considering a more general fix, but this fixes the particular crash reported in kelloggm/checker-framework#111.
> SameLen: Avoid creating unparsable expressions

- checker/bin/javac.bat
Issue #1110: The solution was simple. We just had to put the offending part in double quotes.
If the expansion is `C:\Users\Vatsal Sura\Downloads\checker-framework-2.1.9\checker\bin`, then without quotes, `-jar` is only seeing up to the first space as it's argument (i.e. `-jar C:\Users\Vatsal`) and the remainder (`Sura\Downloads\checker-framework-2.1.9\checker\bin`) is a completely different argument not related to the `-jar`.
Double quotes will still allow any expansion to happen but everything within the quotes will be seen as a single item (the quotes won't be there when java sees it).
> Fixed spaces in path to javac compiler leads to error

- checker/src/org/checkerframework/checker/index/upperbound/OffsetEquation.java
- checker/src/org/checkerframework/checker/index/upperbound/UBQualifier.java
- checker/src/org/checkerframework/checker/index/upperbound/UpperBoundTransfer.java
- checker/tests/index/UpperBoundRefinement.java
If expression i has type @LTLengthOf(value = "f2", offset = "f1.length") int and expression j is less than or equal to the length of f1, then the type of i + j is @LTLengthOf("f2").
Fixes kelloggm/checker-framework#108 and fixes kelloggm/checker-framework#113
> Add refinement to Upper Bound Checker:

- checker/src/org/checkerframework/checker/index/minlen/MinLenAnnotatedTypeFactory.java
- checker/tests/index/Index115.java
> Index Checker: imprecise ArrayLen annotations no longer override precise MinLen annotations

- framework/src/org/checkerframework/common/aliasing/AliasingAnnotatedTypeFactory.java
- framework/src/org/checkerframework/common/aliasing/qual/MaybeAliased.java
- framework/src/org/checkerframework/common/aliasing/qual/Unique.java
- framework/tests/aliasing/ArrayInitializerTest.java
- framework/tests/aliasing/ForbiddenUniqueTest.java
- framework/tests/all-systems/WildcardSuper2.java
- framework/tests/src/tests/AliasingTest.java
1. New arrays are @Unique.
2. Since type arguments may not be annotated with @Unique, All bounds should be @MaybeAliased by default.
3. Run all-system tests.
> Aliasing Checker fixes

- checker/jdk/index/src/java/lang/Byte.java
- checker/jdk/index/src/java/lang/Integer.java
- checker/jdk/index/src/java/lang/Long.java
- checker/jdk/index/src/java/lang/Math.java
- checker/jdk/index/src/java/lang/Short.java
- checker/jdk/index/src/java/lang/String.java
- checker/src/org/checkerframework/checker/index/lowerbound/LowerBoundAnnotatedTypeFactory.java
- checker/src/org/checkerframework/checker/index/minlen/MinLenAnnotatedTypeFactory.java
- checker/src/org/checkerframework/checker/index/qual/PolyIndex.java
- checker/src/org/checkerframework/checker/index/qual/PolyLowerBound.java
- checker/src/org/checkerframework/checker/index/qual/PolyMinLen.java
- checker/src/org/checkerframework/checker/index/qual/PolySameLen.java
- checker/src/org/checkerframework/checker/index/qual/PolyUpperBound.java
- checker/src/org/checkerframework/checker/index/samelen/SameLenAnnotatedTypeFactory.java
- checker/src/org/checkerframework/checker/index/samelen/SameLenVisitor.java
- checker/src/org/checkerframework/checker/index/upperbound/UBQualifier.java
- checker/src/org/checkerframework/checker/index/upperbound/UpperBoundAnnotatedTypeFactory.java
- checker/src/org/checkerframework/checker/index/upperbound/UpperBoundTransfer.java
- checker/src/org/checkerframework/checker/index/upperbound/UpperBoundVisitor.java
- checker/tests/index/Polymorphic.java
- checker/tests/index/Polymorphic2.java
- checker/tests/index/Polymorphic3.java
- docs/manual/Makefile
- docs/manual/index-checker.tex
This is the same code that was in (closed) PR #1112, except the new poly qualifiers have proper Javadocs and are mentioned in the manual.  I also add `@PolyIndex` that is syntactic sugar for `@PolyUpperBound @PolyLowerBound`.
> Adds polymorphic qualifiers for the Index Checkers

- build.xml
Fixes https://github.com/typetools/checker-framework/issues/1127
> Use non-specifc base directory for Checker Framework builds.

- checker/jdk/index/src/java/util/Arrays.java
- checker/jdk/index/src/java/util/Collections.java
`binarySearch()` returns a value in the range -a.length-1 to a.length-1, inclusive.  The `@GTENegativeOne` annotations on its return type were incorrect.
> Remove incorrect annotations from binarySearch

- javacutil/src/org/checkerframework/javacutil/AnnotationUtils.java
Fixes #1108 
Mostly this is a matter of using Collections.synchronizedMap().  We also use an explicit synchronized block for when a containsKey() operation is followed by a get(), since AnnotationUtils.clear() might be called in between.
> Make caches in AnnotationUtils thread safe

- checker/src/org/checkerframework/checker/index/lowerbound/LowerBoundTransfer.java
- checker/src/org/checkerframework/checker/index/upperbound/UpperBoundTransfer.java
- checker/tests/index/CheckAgainstNegativeOne.java
- checker/tests/index/Issue58Minimization.java
- framework/src/org/checkerframework/framework/flow/CFAbstractTransfer.java
Following the example of the nullness checker, which handles this correctly.
Fixes kelloggm#58
> Allows LBC to correctly handle assignments in comparisons

- framework/src/org/checkerframework/framework/type/AnnotatedTypeFactory.java
> Clear out caches only if they are actually used; this allows usage

- checker/jdk/nullness/src/java/io/ObjectOutput.java
This will help to sync type parameters with classes implementing this interface. The parameter can be null for 
ObjectOutput.writeObject(Object ) which claims to serialize the Objects passed as parameters.
Please review this PR and suggest me the changes required.
> Fixes Issue #1189

- checker/src/org/checkerframework/checker/index/upperbound/UpperBoundAnnotatedTypeFactory.java
- checker/tests/index/MinLenOneAndLength.java
If the array's minimum length is 1 or more, then dividing it by a constant >= 2 now results in a `LTLengthOf` for the array. Before it was (conservatively) a `LTEqLengthOf`.
Fixes kelloggm#137
> Index Checker: Adds a special case when dividing an array length

- framework/src/org/checkerframework/common/value/ValueAnnotatedTypeFactory.java
- framework/tests/value/ArrayInit.java
Convert @IntRange to @IntVal before creating the corresponding @ArrayLen.
Handle @BottomVal annotated dimension by creating a @BottomVal.
Don't create annotation if the dimension is not @IntRange, @IntVal or @BottomVal.
> Fix #1198:

- checker/src/org/checkerframework/checker/index/upperbound/UpperBoundTransfer.java
Fixes a minor code quality issue noticed by @mernst
> Index Checker: Refactor UpperBoundTransfer to make method signatures consistent

- checker/src/org/checkerframework/checker/index/samelen/SameLenAnnotatedTypeFactory.java
- checker/src/org/checkerframework/checker/index/samelen/SameLenTransfer.java
- checker/tests/index/SameLenFormalParameter2.java
- docs/manual/figures/samelen.svg
- docs/manual/index-checker.tex
The SameLen subtyping rule was too broad. This change restricts it. This fixes kelloggm#133.
I discovered two other bugs that this was hiding, both false positives. Both had tests that failed already, so no new tests are added for either.
The first was SameLen's version of kelloggm#58: when `strengthenEqualTo` is called, `SameLenTranfer` failed to descend into assignments. This is fixed with a call to split assignments, which necessitated some surgery in the `SameLenAnnotatedTypeFactory` to make `createCombinedSameLen` more general; it now takes two corresponding lists instead of two corresponding pairs. I left the pairwise version as well to minimize code churn, but changed it to call the new version.
The second bug occurred when a new array is being typed by the `SameLenTreeAnnotator`. …
> Index Checker: Fixes bug in SameLen subtyping rule, and several bugs that were masked by that bug

- checker/src/org/checkerframework/checker/index/lowerbound/LowerBoundAnnotatedTypeFactory.java
- checker/src/org/checkerframework/checker/index/upperbound/UpperBoundAnnotatedTypeFactory.java
- checker/tests/index/BottomValTest.java
- checker/tests/index/RefineLT.java
Neither the LBC nor the UBC were correctly converting `@BottomVal` annotations to their respective bottom types (`@Positive` for the LBC and `@UpperBoundBottom` for the UBC).
Fixes (part of) kelloggm#147
> Index Checker: Handle `@BottomVal` annotations correctly in the Lower Bound and Upper Bound checkers

- checker/build.xml
- framework/src/org/checkerframework/framework/type/AnnotatedTypeCopier.java
- framework/src/org/checkerframework/framework/type/AnnotatedTypeFactory.java
- framework/src/org/checkerframework/framework/type/AnnotatedTypeMirror.java
- framework/src/org/checkerframework/framework/type/AnnotatedTypeReplacer.java
- framework/src/org/checkerframework/framework/type/AsSuperVisitor.java
- framework/src/org/checkerframework/framework/type/BoundsInitializer.java
Currently, `ant check-nullness` only checks the JDK annotations instead of all source files.
We already type check the JDK annotations when building the annotated JDK.
This PR type-checks the source code itself, which isn't type-checked yet.
Unfortunately, when trying to do both, either one didn't work. This PR checks the parts that we haven't checked yet.
It also uses Java 8, because the source code uses Java 8 type annotations.
We should add 'ant check-nullness' to the travis tests and ensure that there are no errors. There are currently many warnings, but only two errors, of the form:
```
[java] error: Upper bounds should never contain declarations.
[java]   type=@Initialized @NonNull Annotation
[java]   Compilation unit: .../checker-framework/checker/src/org/checkerframework/checker/gu …
```
> Make the check-nullness target actually process all source files.

- checker/src/org/checkerframework/checker/index/lowerbound/LowerBoundAnnotatedTypeFactory.java
- checker/src/org/checkerframework/checker/index/qual/LengthOf.java
- checker/src/org/checkerframework/checker/index/upperbound/UpperBoundAnnotatedTypeFactory.java
- checker/tests/index/LengthOfTest.java
- docs/manual/index-checker.tex
This improves the situation in kelloggm#151.
> Index Checker: Adds a lengthOf annotation that aliases IndexOrHigh

- checker/tests/index/Polymorphic3.java
- docs/manual/constant-value-checker.tex
- framework/src/org/checkerframework/common/value/RangeOrListOfValues.java
- framework/src/org/checkerframework/common/value/ValueAnnotatedTypeFactory.java
- framework/src/org/checkerframework/common/value/ValueCheckerUtils.java
- framework/src/org/checkerframework/common/value/ValueTransfer.java
- framework/src/org/checkerframework/common/value/ValueVisitor.java
- framework/src/org/checkerframework/common/value/qual/ArrayLenRange.java
- framework/src/org/checkerframework/common/value/qual/BottomVal.java
- framework/tests/value/ArrayInit.java
Adds an `@ArrayLenRange` annotation, which expresses that an array's length must be between the two values the annotation holds. The relationship between `@ArrayLenRange` and `@ArrayLen` is analogous to the relationship between `@IntRange` and `@IntVal`.
Fixes kelloggm#150
> Add ArrayLenRange annotation to Value Checker

- framework/src/org/checkerframework/common/value/ValueTransfer.java
- framework/tests/value/GTETransferBug.java
I didn't include a more comprehensive set of tests because typetools#1243 includes them already (so I've run them, and they pass), but those tests are needed anyway because they also test that the `@MinLen` annotation is working correctly.
> Fixes bug in Value Checker's transfer function for refining ranges when encountering a GTE

- docs/manual/external-tools.tex
As pointed out by @mernst existing maven setup truncated compiler messages.
This update helps avoiding this, by upgrading from the erroneous 3.3 plugin version to the newer 3.6.1. See also
https://issues.apache.org/jira/browse/MCOMPILER-229
> Update maven compiler plugin to 3.6.1

- framework/src/org/checkerframework/common/value/ValueTransfer.java
- framework/src/org/checkerframework/common/value/util/NumberUtils.java
- framework/tests/value/Switch.java
Override strengthenAnnotationOfEqualTo rather than visitEqual and visitNotEqual.
This way switch statements are refined as the same as ==.  Also, fixes a crash when chars are in a switch statement. 
(Blocking #1243 )
> Value Checker: override strengthenAnnotationOfEqualTo

- framework/src/org/checkerframework/common/value/ValueAnnotatedTypeFactory.java
- framework/tests/value/ArrayInit.java
- framework/tests/value/Issue1229.java
> Use the PropagationTreeAnnotator visitNewArray to correctly type new arrays.

- checker/jdk/index/src/java/io/File.java
- checker/jdk/index/src/java/lang/String.java
This is causing the Value Checker to report warnings that it shouldn't when run on Daikon (because #1243 moved the MinLen annotation into the Value Checker). The extraneous PolySameLen annos aren't causing any problems, but they should be removed anyway in case they do cause problems down the line.
> Remove extraneous MinLen and PolySameLen annotations on Strings in Index JDK

- checker/tests/index/Split.java
- framework/src/org/checkerframework/framework/type/AnnotatedTypeFactory.java
- javacutil/src/org/checkerframework/javacutil/AnnotationUtils.java
`compare` should return 0 when comparing `@IntRange(from=0, to=MAX)` and `@IntRange(to=MAX,from=0)`.  
The expected `CompletionFailure` exception issued by `checker/tests/nullness-extra/issue309` now occurs in a different method.  So I added a new catch for it.
(This was causing the following error: https://travis-ci.org/typetests/daikon-typecheck/jobs/229178124#L1038)
> Use areSame when sorting AnnotationMirrors.

- checker/tests/index/OneOrTwo.java
- checker/tests/index/PolyCrash.java
- framework/src/org/checkerframework/framework/util/defaults/QualifierDefaults.java
This happens when a type is requested from a subchecker for a synthetic tree.
> Add defaults even if an element for a tree can't be found.

- framework/src/org/checkerframework/framework/source/SourceChecker.java
- framework/src/org/checkerframework/framework/type/AnnotatedTypeFactory.java
Make one message version private and replace calls by the appropriate
existing method.
> Avoid possible ambiguity between different `message` overloads.

- checker/src/org/checkerframework/checker/index/upperbound/UpperBoundVisitor.java
- checker/tests/index/MinLenSameLenInteraction.java
When checking whether a constant index was less than the length of an array, other arrays that are known to have the same length were not being considered. This PR corrects this mistake.
> Fixes issue where SameLen didn't interact correctly with constant index checks.

- framework/src/org/checkerframework/common/value/ValueAnnotatedTypeFactory.java
- framework/src/org/checkerframework/common/value/qual/IntRange.java
- framework/tests/value/ValueCast.java
This pull request solves #1299. More generally, this PR makes the defaults for `@IntRange` annotations that have no `to` or `from` field be determined by the underlying type of the variable that the annotation applies to.
> Correct defaults for IntRange annotations on non-Long types

- framework/src/org/checkerframework/framework/util/AtmLubVisitor.java
- framework/tests/all-systems/Issue1274.java
Instead, just check that the same ATM has not been visited before.
Fixes #1274.
> Don't use VisitHistory to stop recursion in AtmLubVisitor. (Fixes #1274)

- framework/src/org/checkerframework/common/value/ValueAnnotatedTypeFactory.java
I noticed that in `ValueAnnotatedTypeFactory`, there are cases where the result of `ValueCheckerUtils.removeDuplicates` is ignored, making it a no-op.
This apparently unintended behavior is probably not observable, but the javadoc of `getIntValues`, `getDoubleValues` and `getArrayLength` requires that the returned lists are sorted and have no duplicates.
This change uses the return value of `ValueCheckerUtils.removeDuplicates` to ensure this behavior and fixes a typo in the javadoc describing it.
> Return unique values from methods in ValueAnnotatedTypeFactory

- .travis.yml
- checker/jdk/index/src/java/util/Arrays.java
- checker/tests/index/ArraysSort.java
The index checker annotation of `Arrays.sort(int[],int,int)` has an obvious typo of a missing `#`.
This change adds the missing sign and a test case. (Travis configuration is changed to build the jdk.)
> Fix index annotation of Arrays.sort(int[],int,int)

- framework/src/org/checkerframework/common/value/ValueAnnotatedTypeFactory.java
- framework/tests/value/Basics.java
> Do not replace explicit annotations on casts in Value checker

- docs/manual/advanced-features.tex
If `class MyList<@Nullable T extends @Nullable Object> {}`, then `T` can only be `@Nullable` so the two examples wouldn't compile. But if the lower bound is `@NonNull` (or omitted), then they make sense.
> Fix copypasta in "Inherited wildcard annotations"

- checker/jtreg/tainting/NewClass.java
- checker/jtreg/tainting/NewClass.out
- framework/src/org/checkerframework/common/basetype/BaseTypeVisitor.java
Otherwise, the arguments are visited twice.  (This is what [BaseTypeVisitor#visitMethodInvocation](https://github.com/typetools/checker-framework/blob/master/framework/src/org/checkerframework/common/basetype/BaseTypeVisitor.java#L939) already does.)
> Don't call super in BaseTypeVisitor#visitNewClass.

- docs/manual/external-tools.tex
Now that Android supports type annotations (https://developer.android.com/studio/preview/features/java8-support.html), change the instructions to use the standard Java 8 compiler.
> Add new instructions for configuring Android.

- docs/manual/constant-value-checker.tex
- framework/src/org/checkerframework/common/value/ReflectiveEvaluator.java
- framework/src/org/checkerframework/common/value/ValueAnnotatedTypeFactory.java
- framework/src/org/checkerframework/common/value/ValueCheckerUtils.java
- framework/src/org/checkerframework/common/value/statically-executable.astub
- framework/tests/value/ArrayInit.java
- framework/tests/value/StringValOfArrays.java
Also, several methods that use byte or char arrays are no longer statically executable, so was updated statically-executable.astub. All constructors of a primitive wrapper or String were hard coded as statically-executable, but now some of the String constructors are not.
@panacekcz is implementing treating `@StringVal("abc")` as a subtype of `@ArrayLen(3)`.
(This is a follow up to PR #1322 which removed `@StringVal` from both byte and char arrays.)
> Don't apply @StringVal to byte arrays.

- dataflow/src/org/checkerframework/dataflow/analysis/AnalysisResult.java
- dataflow/src/org/checkerframework/dataflow/cfg/DOTCFGVisualizer.java
- framework/jtreg/DOTCFGVisualizerForVarargsTest.java
When the last node of a block doesn't have tree, DOTCFGVisualizer throws NPE if it's verbose mode.
Especially visualize varargs call is always failed.
> Fix NPE in visualizataion CFG of varargs method invocation

- framework/tests/value-ignore-range-overflow/Index117.java
This test comes from kelloggm#117. That issue describes some code that can be type checked with ignore-overflow mode in the Value Checker, but cannot be type checked without it. So, I created a Value Checker test case. This should be mergable immediately once tests pass, and should close kelloggm#117.
> Add Index Checker test to Value Checker's ignore overflow mode

- framework/src/org/checkerframework/common/value/ValueCheckerUtils.java
- framework/tests/value/LongMax.java
The method `ValueCheckerUtils.getValuesFromRange` contains code that does not work properly. Furthemore, the method may cause an `OutOfMemoryError` if the upper bound of the input range is `Long.MAX_VALUE`, because in that case the condition of the loop `value<=range.to` always succeeds and the loop variable `value` overflows. Then the list of values grows until memory is exhausted.
This problem can be reproduced by running the value checker on this code:
```java
import org.checkerframework.common.value.qual.*;
public class LongMax {
public void longMaxRange() {
@IntRange(from = 9223372036854775807l, to = 9223372036854775807l) long i = 9223372036854775807l;
@IntRange(from = 9223372036854775807l, to = 9223372036854775807l) long j = i;
}
}
```
Run the checker by:
```
checker/bin/javac …
```
> Fix ValueCheckerUtils.getValuesFromRange

- dataflow/src/org/checkerframework/dataflow/analysis/FlowExpressions.java
- framework/src/org/checkerframework/framework/util/typeinference/DefaultTypeArgumentInference.java
- framework/src/org/checkerframework/framework/util/typeinference/TypeArgInferenceUtil.java
- framework/src/org/checkerframework/framework/util/typeinference/solver/ConstraintMapBuilder.java
- javacutil/src/org/checkerframework/javacutil/InternalUtils.java
- javacutil/src/org/checkerframework/javacutil/TypeAnnotationUtils.java
- javacutil/src/org/checkerframework/javacutil/TypesUtils.java
the latter will be removed in Java 9.
Implement TypeAnnotationUtils without reflection. This makes the code easier to read, but unfortunately didn't speed up execution.
> Use TypeAnnotationUtils.unannotatedType instead of Type.unannotatedType;

- checker/src/org/checkerframework/checker/lock/LockStore.java
- checker/tests/lock/Issue804.java
Hi @wmdietlGC ,
It seems to me that the cause is that we miss updating `this` type in `LockStore#updateForMethodCall`.
Could you review this?
> Fix #804: Calling a method annotated with @Holding("this") @MayReleaseLocks does not cause "this" to be released

- docs/manual/advanced-features.tex
Compare to the entry for "local variable", where we are actually
allowed to use the local variable identifier, the "formal parameter"
did not mean that we can use a formal parameter identifier.
> Tweak wording to highlight the syntax used for formal parameters.

- framework/src/org/checkerframework/framework/source/SourceChecker.java
As proposed here: https://github.com/typetools/checker-framework/issues/1111#issuecomment-317847932.
> Make it clear that a crash is from the Checker Framework.

- checker/tests/index/Issue1411.java
- framework/src/org/checkerframework/framework/util/FlowExpressionParseUtil.java
- javacutil/src/org/checkerframework/javacutil/InternalUtils.java
This is an attempt at fixing #1411. I would like to get feedback on whether this is a correct apporach. 
Previously `InternalUtils.substituteMethodReturnType` worked only in simple cases and crashed in some.
This PR uses `Types.memberType` to view the method as a member of the receiver type and then gets the return type of the method.
Notes:
- I don't know whether the casts are guaranteed to succeed.
- `JavacTypes.asMemberOf` cannot be used, because the check in that method may fail (and does for some tests).
> Fix #1411 (AssertionError in substituteMethodReturnType)

- checker/tests/index/Index165StringLiteral.java
- checker/tests/index/Index166.java
- framework/src/org/checkerframework/common/value/ValueAnnotatedTypeFactory.java
- framework/src/org/checkerframework/framework/type/GenericAnnotatedTypeFactory.java
This PR improves `ValueAnnotatedTypeFactory.getMinLenFromString` to return the length of the string if the expression is a string literal.
This fixes a warning from index checker with string support (#1413) in plume-lib ([`TestPlume.java`](https://github.com/mernst/plume-lib-check-index-new/blob/3f82f73faaf4c01bee92944a1ea16d8e854bf2fb/java/src/plume/TestPlume.java#L2585)), reported as kelloggm#166.
This can be merged independently of #1413.
> Support string literals in ValueAnnotatedTypeFactory.getMinLenFromString

- checker/build.xml
- checker/jdk/index/src/java/util/regex/Matcher.java
- checker/tests/index/RegexMatcher.java
This PR strengthens the index annotations on return values of functions in `java.util.regex.Matcher`.
The methods `start()`, `end()`, `regionStart()`, and `regionEnd()` all return `@NonNegative`.
This should eliminate some false positives.
Fixes panacekcz#8.
checker/build.xml is edited to download an annotated jdk with the change.
> Improve index annotations in java.util.regex.Matcher

- checker/build.xml
- framework/build.xml
Changes include:
1. No longer build jdk7
2. Remove references to jdk7
3. Use source 8 target 8 for compiling checker.jar and framework.jar. (checker-qual.jar and checker-compat-qual.jar still use source 7 target 7.)
Once this is merged, I can test changes to the release script, Eclipse plugin, and Maven artifacts.
> Adapt build files to Java 8 requirements.

- framework/src/org/checkerframework/common/value/ValueTransfer.java
- framework/tests/value/StartsEndsWith.java
This PR improves the feature added in #1432. That implementation worked with string literals, but not with static final fields. This PR changes the way of retrieving the value annotation of the argument so that it works with static final fields as well.
Fixes panacekcz#9.
> Improve refinement of minimum string length after startsWith and endsWith

- checker/build.xml
- checker/jdk/index/src/java/lang/Math.java
- checker/tests/index/MinMaxIndex.java
This PR adds `@PolyUpperBound` annotations to `Math.max` methods, similar to `@PolyLowerBound` annotations that are on `Math.min`.
If both arguments satisfy a certain upper bound, then the result does too.
Fixes panacekcz#20.
The file build.xml is changed to download the modified jdk.
> Add index upper bound annotations to Math.max

- checker/src/org/checkerframework/checker/index/upperbound/UBQualifier.java
- checker/src/org/checkerframework/checker/index/upperbound/UpperBoundVisitor.java
- checker/tests/index/Index167.java
This PR avoids `int` overflow in `UBQualifier.isValuePlusOffsetLessThanMinLen`. An overflow in this method caused `relaxedCommonAssignmentCheck` to return true in cases where it shouldn't. This resulted in missed upper bound warnings (see kelloggm#167).
The exposing code doesn't even contain any large integers or overflowing operations. The large integer value causing the overflow comes as a range bound from the value checker.
Fixes kelloggm#167.
> Avoid int overflow in UBQualifier.isValuePlusOffsetLessThanMinLen

- checker/jdk/nullness/src/java/lang/Class.java
`Class.getEnclosingClass()` should be annotated as `@Pure`. It returns only class object and has no visible side effects on other variable. Also the returned value is identical (according to` ==`).
> Add missing @Pure annotation for Class.getEnclosingClass()

- dataflow/src/org/checkerframework/dataflow/cfg/CFGBuilder.java
Whenever CFGBuilder$CFGTranslationPhaseOne.process is called with a
TreePath, rather than a CompilationUnitTree, then this.trees might not
be set.
Eventually, this field is dereferenced inside visitReturn(...), while
processing a lambda return expression. This will result in an NPE when
building a CFG from a TreePath that includes a returned lambda expression.
This patch simply sets CFGBuilder$CFGTranslationPhaseOne.trees to the
same value, regardless of the version of the process(...) method
invoked.
> Fix NPE on CFGBuilder$[...]PhaseOne.visitReturn() when code has lambdas.

- checker/src/org/checkerframework/checker/index/upperbound/UBQualifier.java
- checker/src/org/checkerframework/checker/index/upperbound/UpperBoundTransfer.java
- checker/tests/index/RefineNeqLength.java
This PR generalizes the refinement of upper bounds in the index checker by the `!=` operator.
Currently, if `i` is `@LTEqLengthOf("receiver")` or equivalently `@LTLengthOf(value="receiver",offset="-1")`, then after checking `i != receiver.length`, it is refined to `@LTLengthOf(value="receiver")`.
With this change, if `i` is `@LTLengthOf(value="receiver",offset=c-1)` then after checking `i != receiver.length - c`, it is refined to `@LTLengthOf(value="receiver", offset=c)` for any ~literal~ constant `c`.
Fixes panacekcz#12.
Should not be merged before #1469. ~Tests fail because of kelloggm#167 and should pass after that is merged.~
> Generalize index upper bound refinement by !=

- checker/tests/initialization/fbc/TryFinally2.java
- dataflow/src/org/checkerframework/dataflow/cfg/CFGBuilder.java
When both of `allReachableTrees` and the generated trees contain `null`, unreachable generated trees are not removed and it becomes a cause of the false positive.
> Fix #1500: Incorrect initialization and nullness in finally block

- framework/src/org/checkerframework/framework/type/SupertypeFinder.java
- framework/tests/all-systems/Issue1442.java
> Handle enclosing types correctly in SuperTypeVisitor.

- framework/src/org/checkerframework/framework/type/AnnotatedTypeFactory.java
- framework/src/org/checkerframework/framework/type/visitor/AnnotatedTypeComparer.java
- framework/src/org/checkerframework/framework/type/visitor/AnnotatedTypeScanner.java
- framework/src/org/checkerframework/framework/util/element/ElementAnnotationUtil.java
- framework/tests/all-systems/Issue1431.java
1.  `AnnotatedTypeFactory#typeVariablesFromUse` must substitute type parameters of the enclosing type, too.  This fixes #1431. 
2.  AnnotatedTypeVisitors must also visit enclosing types.  This fixes #724 by applying defaults to enclosing types.
3.  Correct how annotations on inner types are applied.
(1 caused a crash that required 2.  2 caused a crash that required 3.)
Downsteam test will pass once https://github.com/typetools/checker-framework-inference/pull/59 is merged.
> Correct handling of enclosing type in more places

- checker/src/org/checkerframework/checker/initialization/InitializationStore.java
- framework/src/org/checkerframework/common/value/ValueAnnotatedTypeFactory.java
- framework/src/org/checkerframework/framework/type/SupertypeFinder.java
- framework/src/org/checkerframework/framework/type/TypeFromExpressionVisitor.java
- framework/src/org/checkerframework/framework/type/TypesIntoElements.java
- framework/src/org/checkerframework/framework/type/typeannotator/ImplicitsTypeAnnotator.java
- framework/src/org/checkerframework/framework/type/typeannotator/IrrelevantTypeAnnotator.java
- framework/src/org/checkerframework/framework/type/visitor/AnnotatedTypeComparer.java
- framework/src/org/checkerframework/framework/type/visitor/AnnotatedTypeScanner.java
- framework/src/org/checkerframework/framework/util/QualifierPolymorphism.java
- framework/src/org/checkerframework/framework/util/dependenttypes/DependentTypesHelper.java
Simplify some code accordingly.
> Ensure only non-null types are scanned by AnnotatedTypeScanner.

- framework/src/org/checkerframework/common/wholeprograminference/WholeProgramInferenceScenes.java
- framework/src/org/checkerframework/framework/qual/IgnoreInWholeProgramInference.java
- framework/tests/whole-program-inference/non-annotated/ExpectedErrors.java
Also, implement the functionality of apply `@IgnoreInWholeProgramInference` to fields.
Fixes #1535 .
> Allow @IgnoreInWholeProgramInference to apply to fields

- checker/tests/index/MethodOverrides.java
- checker/tests/value-index-interaction/MethodOverrides.java
- framework/src/org/checkerframework/common/value/ValueVisitor.java
This fixes the issue Suzanne discovered in the Daikon build with the Value Checker. The problem existed before for `@Positive` annotations, but became apparent when `@GTENegativeOne` annotations were added, because those appear in JDK methods that Daikon overrides. This change fixes that problem while at the same time reducing code duplication.
> Fix method overriding bug in Value Checker

- checker/jtreg/stubs/Issue1542Driver.java
- checker/jtreg/stubs/issue1542/ExampleAnno.java
- checker/jtreg/stubs/issue1542/Stub.astub
- checker/jtreg/stubs/issue1542/Stub.java
- framework/src/org/checkerframework/framework/stub/StubParser.java
This addresses some of the TODOs leftover from #1547. 
1. If an annotation expressions can't be parsed because an element can't be found, don't ErrorAbort, but rather issue a stubparser warning.
2.  Also, adds more tests for the different types of annotation values. 
3. One minor bug fix in the case:  `@DoubleValue( value = 1L)` where the type of value is double.  The `1L` must be converted to a double.
> Clean up StubParser

- checker/bin-devel/Dockerfile-ubuntu-jdk8
- checker/bin-devel/Dockerfile-ubuntu-jdkany
Currently we are working on integrating Z3 as a new solver to CF Inference, which requires `ar` tool be installed during building phase. Since CF Inference uses the same dockers here to running it's travis test, could we have `binutils` (this is the package provide `ar` tool) be installed in these dockers?
I've tested updated DockerFiles locally and it works.
Thanks a lot!
> Install binutil into dockers.

- checker/src/org/checkerframework/checker/index/upperbound/UBQualifier.java
- checker/tests/index/UBPoly.java
`@PolyUpperBound` annotations were being treated as `@UpperBoundBottom` annotations by `isSubtype`. This caused false negatives, as reported in kelloggm#163.
The problem was that the static variable on the `PolyQualifier` subclass of `UpperBoundQualifier` was incorrectly instantiated as an `UpperBoundBottomQualifier`. This change fixes the error and introduces a new test case.
> Make PolyUpperBound work correctly

- checker/src/org/checkerframework/checker/index/qual/IndexFor.java
- checker/src/org/checkerframework/checker/index/qual/IndexOrHigh.java
- checker/src/org/checkerframework/checker/index/qual/IndexOrLow.java
- checker/src/org/checkerframework/checker/index/qual/LengthOf.java
These empty defaults cause crashes instead of helpful error messages. Upperbound qualifiers are meaningless without an argument, so they shouldn't allow no argument to be passed to them.
Closes kelloggm#173.
> Remove empty defaults from Upper Bound Checker qualifiers

- checker/tests/value-index-interaction/MethodOverrides3.java
- framework/src/org/checkerframework/common/basetype/BaseTypeVisitor.java
- framework/src/org/checkerframework/common/value/ValueVisitor.java
See kelloggm#171 for a description of this issue: basically, overrides of JDK methods aren't being handled correctly wrt `@IntRangeFromX` annotations.
`BaseTypeVisitor` doesn't actually expose the interface needed to fix the problem, so I made a backwards-compatible change to `BaseTypeVisitor` that splits the `checkOverride` method so that there are two entry points, one of which `ValueVisitor` needs.
> Add additional override in ValueVisitor to avoid spurious errors

- checker/src/org/checkerframework/checker/regex/RegexVisitor.java
- checker/tests/regex/MyMatchResult.java
It only occurs for implementations of java.util.regex.MatchResult.
> Avoid NPE in Regex Checker.

- checker/src/org/checkerframework/checker/index/lowerbound/LowerBoundAnnotatedTypeFactory.java
- checker/src/org/checkerframework/checker/index/lowerbound/LowerBoundTransfer.java
The Index Checker is known to suffer performance issues. This is the first step towards resolving that problem.
This PR removes code from `LowerBoundTreeAnnotator#visitBinary` and replaces the functionality with code in the transfer function. The previous version of `visitBinary` required calls to `getAnnotatedType`, which is known to be exponentially slow when processing nested binary expressions.
Running `ant index-tests` on my laptop takes 2 minutes 1 second with this PR, and 2 min 29 seconds without it (~18% faster).
Running `javac -processor lowerbound tests/index/BigBinaryExpr.java` with this PR takes 11.2 seconds, while master takes 16.0 seconds (~30% faster). Note that this test is currently commented out. I uncommented it to get these numbers.
> Remove visitBinary from Lower Bound Checker Annotated Type Factory; move functionality to Lower Bound Transfer

- framework/src/org/checkerframework/framework/type/AnnotatedTypeMirror.java
- framework/src/org/checkerframework/framework/type/BoundsInitializer.java
- framework/src/org/checkerframework/framework/type/TypeFromTypeTreeVisitor.java
- framework/tests/all-systems/Issue1587.java
- framework/tests/all-systems/Issue1587b.java
When initializing type arguments, use the mapping from type parameter to type arguments.
Fixes Issue #1587.
> Correct unbound wildcard crash.

- framework/src/org/checkerframework/framework/type/AnnotatedTypeMirror.java
- framework/src/org/checkerframework/framework/type/TypeVariableSubstitutor.java
- framework/src/org/checkerframework/framework/type/visitor/AnnotatedTypeMerger.java
- framework/tests/all-systems/Issue1587.java
The fix for #1587 caused another crash when type-checking Guava.  This pull request fixes that crash.
> Fix crash in Guava

- dataflow/src/org/checkerframework/dataflow/cfg/CFGBuilder.java
- dataflow/src/org/checkerframework/dataflow/cfg/node/AbstractNodeVisitor.java
- dataflow/src/org/checkerframework/dataflow/cfg/node/LambdaResultExpressionNode.java
- dataflow/src/org/checkerframework/dataflow/cfg/node/NodeVisitor.java
This adds a new node to the cfg, LambdaResultExpressionNode, which corresponds
to the result of a lambda expression with a single expression as its body, and
which is added at the end of the cfg when CFGBuilder is passed a CFGLambda of
this kind as the underlaying ast.
This is needed by some analyses to handle the result of a lambda expression in
the case where the body is a single ExpressionTree. The case where the body is
a block is already handled by matching ReturnNode.
> Add support on the dataflow CFG for visiting lambda result expressions

- framework/src/org/checkerframework/framework/type/AnnotatedTypeCopier.java
- framework/src/org/checkerframework/framework/type/AnnotatedTypeMirror.java
If the annotations on the AnnotatedDeclaredType or enclosing type changes or if the type arguments change, then the super types must be recomputed.  Instead of keeping track of these changes, just recompute.  
Fixes #1605.
I'm not sure if this is the best fix. It's not clear to me why the super types were stored for the AnnotatedDeclaredTypes in the first place.  (The only other types they are stored for is AnnotatedIntersectionTypes which makes sense because the super types can be directly annotated.) My guess is for performance.  I'll run this branch on ~Guava and~ the JDK to see if there is any difference.  There was no impact with Guava.
> Always recalculate direct super types for AnnotatedDeclaredTypes

- framework/src/org/checkerframework/common/basetype/BaseTypeVisitor.java
- framework/tests/all-systems/java8/memberref/MemberReferences.java
If conservativeUninferredTypeArguments is used; otherwise, never issue the warning.
> Don't issue methodref.inference.unimplemented warnings

- checker/src/org/checkerframework/checker/guieffect/GuiEffectTypeFactory.java
- checker/src/org/checkerframework/checker/guieffect/GuiEffectVisitor.java
- framework/src/org/checkerframework/framework/type/AnnotatedTypeMirror.java
- framework/src/org/checkerframework/framework/util/defaults/QualifierDefaults.java
prevent adding annotations to AnnotatedExecutableType.
> Clean up AnnotatedTypeMirror: remove commented out code and actually

- framework/src/org/checkerframework/framework/type/visitor/AnnotatedTypeScanner.java
This makes the checkers faster.
> AnnotatedTypeScanner: Only store potentially recursive types.

- checker/build.xml
Also, copy jdk.jar to dist after it is created.
> Make sure jdk exists before running tests that use it.

- framework/src/org/checkerframework/common/value/util/Range.java
- framework/tests/src/tests/RangeTest.java
- framework/tests/value/Issue1655.java
Hi @panacekcz, @mernst,
This partially fixes #1655. As discussed, I simply added the case when this range only contains non-negative values. It reuses `Range#signedShiftRight` to do the calculation. We can think about the cases when this range contains negative values if necessary.
Please kindly review. Thanks!
Jason
> Refine unsigned shift right when this range is non-negative

- framework/src/org/checkerframework/common/value/ValueAnnotatedTypeFactory.java
- framework/src/org/checkerframework/common/value/qual/StaticallyExecutable.java
- framework/src/org/checkerframework/framework/stub/StubParser.java
- javacutil/src/org/checkerframework/javacutil/AnnotationUtils.java
This fixes #1356, so the workaround for that issue is removed. 
This fix also found that `@StaticallyExecutable` was missing the `CONSTRUCTOR` target.
> StubParser: Check that an annotation is a declaration annotation

- checker/jdk/lock/src/java/util/AbstractMap.java
- checker/jdk/nullness/src/java/util/AbstractMap.java
Otherwise, the jaif files include inner-type locations in for the receivers.
I checked for other static inner classes not marked as static, but these were the only ones.
(I'm rebuilding the jdk, now.)
Fixes #1636
>  In the JDK, mark static classes as static

- checker/bin-devel/count-suppressions
Adds `samelen`, `searchindex` and `substringindex` to the count-suppressions script.
> Add index subcheckers to count-suppressions [ci skip]

- javacutil/src/org/checkerframework/javacutil/AnnotationUtils.java
This fixes the current sparta build failure. (https://travis-ci.org/typetools/sparta/builds/305055418) 
When the AnnotationValue is an annotation, the underlying object is a `com.sun.tools.javac.code.Attribute.Compound`which extends `Attribute` which extends `AnnotationValue`. `Compound#getValue` returns itself, so an infinite recursion occurs.  Since `Compound` also implements `AnnotationMirror`, use `areSame` instead.
> Stop infinite recursion in sameAnnotationValue.

- checker/tests/index/ArrayWrapper.java
- docs/manual/index-checker.tex
Users of the Index Checker will likely want to annotate their own collections so that the Index Checker treats them as if they were arrays or Strings. Since it's not obvious how to do that, this PR includes an example of doing so (and the associated test case) as a new manual section.
> Manual instructions for annotating a custom fixed-size collection

- checker/tests/tainting/Issue1705.java
- framework/src/org/checkerframework/framework/util/QualifierPolymorphism.java
Also, reduces code duplication.
Fixes #1705
> Use annotations on uninferred wildcards when substituting polymorphic qualifiers

- checker/src/org/checkerframework/checker/guieffect/GuiEffectTypeFactory.java
- checker/src/org/checkerframework/checker/guieffect/GuiEffectVisitor.java
- checker/tests/guieffect/Java8Lambdas.java
- dataflow/src/org/checkerframework/dataflow/cfg/CFGBuilder.java
- javacutil/src/org/checkerframework/javacutil/TreeUtils.java
(with limited inference)
**Summary**:
We had some Java 7 code annotated with the guieffect checker's type system, and we are in the process of porting said codebase to Java 8. As part of that process, we are converting multiple anonymous classes into lambdas. It is not clear to us whether is possible to annotate lambdas as being `@UI` when the functional interface is polymorphic on the UI effect types (`@PolyUIType` class and `@PolyUIEffect` method). Assuming we are correct on this, we would like to add support for UI-polymorphic lambda arguments, ideally with some degree of inference that doesn't require us to cast to an `@UI` version of their functional interface at use (e.g. `o.m((@UI Action) () -> { ... })` would not be preferred, instead `o.m(()->{ do_some_ui_effect() })` should be …
> Add support for @PolyUI Java 8 lambdas to guichecker

- .travis.yml
The workaround is to set fcntl, taken from travis-ci/travis-ci#8920
> Work around a bug where Travis truncates logs and fails

- framework/tests/flow2/README
The command stated in the README for flow2 tests does not work.
> Fix flow2 test readme [ci skip]

- checker/src/org/checkerframework/checker/formatter/qual/ReturnsFormat.java
- checker/src/org/checkerframework/checker/i18nformatter/qual/I18nChecksFormat.java
- checker/src/org/checkerframework/checker/i18nformatter/qual/I18nValidFormat.java
The reason is so I can build a Qualifier only JAR using a regex like "**/qual/*.java".  I'm using Bazel to build from source and Guava requires the checker framework annotations.
> Fully qualify javadoc links to remove import.

- framework/src/org/checkerframework/common/basetype/BaseTypeVisitor.java
- framework/src/org/checkerframework/common/basetype/messages.properties
- framework/tests/flow2/ContractsOverridingSubtyping.java
Fixes #1724.
- swaps the order of arguments to `isSubtype`
- fixes warning messages
> Fix contract override checks

- docs/examples/MavenExample/pom.xml
- docs/manual/external-tools.tex
This way checker.jar is not a runtime dependency.
Fixes #1734.
> Update Maven example to use annotationProcessorPaths

- checker/src/org/checkerframework/checker/nullness/qual/KeyForBottom.java
- checker/tests/nullness/Issue1712.java
> Changing the Key For default for explicit upper bounds to UnkownKeyFor.

- checker/build.xml
jdk8.jar in annotated-libraries was not updated after PR #1716. This PR applies the updated location.
> Update jdk8.jar in annotated-libraries

- framework/src/org/checkerframework/common/basetype/BaseTypeVisitor.java
When an exception is thrown while setting up the Checker Framework (say, in a checker's constructor or while reading a stub file), it can be difficult to know what happened, much less where.  This outputs a wordy stack trace.  This should only happen when there is a bug in the Checker Framework itself, so it seems acceptable.  I'm not sure whether there is a better way, however.
> Show stack trace to ease debugging

- .lgtm.yml
* The parent folder of the source checkout is not writeable in the lgtm build environment
* The lgtm build environment limits network access and permits only HTTP GET operations; as
a result git/hg clone commands fail.
To workaround these restrictions the dependencies are downloaded in the form of a source zip, and
stored in the $LGTM_WORKSPACE folder
@wmdietl
> Work around some restrictions imposed by the lgtm build environment

- checker/tests/index/LessThanLen.java
kelloggm#211 describes a test case that currently succeeds but should fail.
This PR disables the incorrect part of the test and adds a fixed version.
> Fix and disable incorrect Index Checker test

- .lgtm.yml
A last minute edit to break a long line into two was done wrongly. As a result
the 'ant' command line ended up contain some spurious \ symbols causing the build
to fail.
@wmdietl Apologies for the mistake, I really shouldn't edit  yaml files without validating them.
> lgtm.yml: fix ant command

- checker/src/org/checkerframework/checker/index/IndexUtil.java
- checker/src/org/checkerframework/checker/index/upperbound/UpperBoundVisitor.java
- checker/tests/index/NegativeIndex.java
- framework/src/org/checkerframework/common/value/ValueAnnotatedTypeFactory.java
- framework/src/org/checkerframework/common/value/ValueTransfer.java
The method `ValueAnnotatedTypeFactory.getMinLenValue(AnnotationMirror)` currently returns `null` if there is no information about the minimum length of an array. However, the minimum length is always at least 0. Callers of  this method must usually check for `null` and treat it as 0. However, in the upper bound check of array element access, it treated it differently, causing unnecessary upper bound warning on negative constant indices.
This PR changes the method and several related method to never return `null` and return 0 if the minimum length is not known. This reduces the burden on callers of this method and fixes the upper bound check.
Fixes kelloggm#216.
> Assume that minimum length of sequences is always at least 0

- checker/src/org/checkerframework/checker/index/lowerbound/LowerBoundAnnotatedTypeFactory.java
- checker/src/org/checkerframework/checker/index/upperbound/UpperBoundAnnotatedTypeFactory.java
- checker/tests/index/ShiftRight.java
This PR fixes kelloggm#214 (upper bounds for right shift) by copying the upper bound annotation from the left operand, if it is non-negative.
After this is merged, kelloggm#217 can be implemented.
> Preserve upper bound for right shift

- checker/src/org/checkerframework/checker/index/upperbound/OffsetEquation.java
- checker/tests/index/Index176.java
This PR makes the Upper Bound Checker recognize integer literals and length of string literals in offset expressions as constants.
Fixes kelloggm#176.
This PR uses a simple name comparison to recognize the string length, not `IndexMethodIdentifier` which would mean passing it as a parameter through all the expression standardization methods.
> Fold compile-time constants (integer literals and lengths of string literals) in offsets

- checker/src/org/checkerframework/checker/index/upperbound/UpperBoundTransfer.java
- checker/tests/index/RefineSubtrahend.java
This PR adds refinement to the transfer of the Upper Bound Checker, to refine the upper bound of a subtrahend in a condition such as `a.length - i > j`. Currently `j` is refined to `@LTLengthOf(value="a", offset="i")`. This refines `i` to `@LTLengthOf(value="a", offset="j")` as well.
The rules are:
- if `minuend` is `@LTLengthOf(value="a", offset="o")` and `minuend-subtrahend>offset`, then `subtrahend` is `@LTLengthOf(value="a", offset="o+offset+1")` 
- if `minuend` is `@LTLengthOf(value="a", offset="o")` and `minuend-subtrahend>=offset`, then `subtrahend` is `@LTLengthOf(value="a", offset="o+offset")` 
Fixes kelloggm#215
> Refine upper bound of a subtrahend with offset

- checker/src/org/checkerframework/checker/interning/qual/Interned.java
- checker/src/org/checkerframework/checker/lock/qual/GuardedBy.java
- checker/src/org/checkerframework/checker/nullness/qual/NonNull.java
- checker/src/org/checkerframework/checker/signedness/qual/Signed.java
- checker/src/org/checkerframework/checker/signedness/qual/SignednessBottom.java
- framework/src/org/checkerframework/common/wholeprograminference/WholeProgramInferenceScenesHelper.java
- framework/src/org/checkerframework/framework/qual/ImplicitFor.java
- framework/src/org/checkerframework/framework/qual/TypeKind.java
- framework/src/org/checkerframework/framework/type/typeannotator/ImplicitsTypeAnnotator.java
- framework/tests/src/testlib/flowexpression/qual/FEBot.java
... on Android.
Downstream tests depend on
https://github.com/typetools/checker-framework-inference/pull/68
> Fix #1781: Add an independent TypeKind enum to not create a warning.

- checker/jtreg/nullness/Issue1809.java
- framework/src/org/checkerframework/common/basetype/BaseTypeVisitor.java
- framework/src/org/checkerframework/framework/type/AnnotatedTypeFactory.java
- framework/src/org/checkerframework/framework/type/TypeFromTypeTreeVisitor.java
- framework/tests/all-systems/Issue1809.java
1. Correctly type the "qualifier expression" of a member reference, where "qualifier expression" is the type or expression before `::`.
2. Use separate caches for types for Expressions, Members, and Type Trees.  (Using a single cache masked the bug.)
> Fix Issue #1809 by determining better type for member references.

- checker/tests/nullness/Issue1797.java
- dataflow/src/org/checkerframework/dataflow/cfg/CFGBuilder.java
As described in #1797 return statements didn't have CFG edges to their enclosing finally blocks.
This actually was a bigger problem, as it also applied to break and continue statements.
This PR makes sure that there are CFG edges *into* finally blocks from all control flow statements.
Some CFG edges *out of* finally blocks still seem incorrect. This will be addressed after #293 in separate PRs. (This has no effect on type checking, but is important for other uses of dataflow.)
Fixes #1797
> Add CFG edges into finally blocks

- framework/src/org/checkerframework/framework/type/GenericAnnotatedTypeFactory.java
- framework/src/org/checkerframework/framework/util/defaults/QualifierDefaults.java
Originally, `QualifierDefault#addClimbStandardDefaults()` and `QualifierDefault#addUncheckedStandardDefaults()` ask callers to pass `tops` and `bottoms` as the default top qualifiers and default bottom qualifiers. This actually permits clients
to pass arbitrary `tops` and `bottoms` as the standard defaults, which can lead to inconsistencies.
Since `QualifierDefault` itself keeps a reference to `aTypeFactory`, a better and more consistent way of initializing `ClimbStandardDefaults` and `UncheckedStandardDefault` is to directly use the `tops` and `bottoms` from the `qualifierHierarchy` within the `aTypeFactory` that this `QualifierDefault` has been initialized with.
This PR makes this change.
Original PR review in opprop: https://github.com/opprop/checker-framework/pull/66
> QualifierDefault: Do not permit passing arbitrary tops and bottoms as standard defaults.

- checker/src/org/checkerframework/checker/i18nformatter/I18nFormatterVisitor.java
- checker/src/org/checkerframework/checker/lock/LockVisitor.java
- dataflow/src/org/checkerframework/dataflow/analysis/AnalysisResult.java
- dataflow/src/org/checkerframework/dataflow/analysis/FlowExpressions.java
- framework/src/org/checkerframework/framework/type/GenericAnnotatedTypeFactory.java
- framework/tests/all-systems/Issue1865.java
Also, removed use of getFirstNonImplicitNodeForTree in the LockVisitor, which required a minor fix in FlowExpressions.java.
Follow-up to #1826.
> Fixes #1865: change getFirstNonLambdaResultExpressionNodeForTree to require the class of node to return.

- checker/tests/lock/FullyQualified.java
- dataflow/src/org/checkerframework/dataflow/analysis/FlowExpressions.java
Previously, for a fully-qualified class name like p.q.C it used p.q as ClassName, which doesn't make sense. But maybe I misunderstood and this needs documentation.
> For a member select that refers to a class use the type of the whole tree

- checker/src/org/checkerframework/checker/index/inequality/LessThanTransfer.java
- checker/src/org/checkerframework/checker/index/lowerbound/LowerBoundAnnotatedTypeFactory.java
- checker/src/org/checkerframework/checker/index/lowerbound/LowerBoundTransfer.java
- checker/src/org/checkerframework/checker/index/samelen/SameLenAnnotatedTypeFactory.java
- checker/src/org/checkerframework/checker/index/samelen/SameLenTransfer.java
- checker/src/org/checkerframework/checker/index/searchindex/SearchIndexTransfer.java
- checker/src/org/checkerframework/checker/index/upperbound/UpperBoundAnnotatedTypeFactory.java
- checker/src/org/checkerframework/checker/index/upperbound/UpperBoundTransfer.java
Modifies and expands the documentation on each Index Checker subchecker to split out the refinement rules by cases, and provide a summary at the top of each class that implements some refinement rules.
> Document Index Checker type rules by cases

- checker/src/org/checkerframework/checker/index/qual/EnsuresLTLengthOf.java
Since there was no example in this Javadoc, and I answered a question on the mailing list about it.
> Add example to EnsuresLTLengthOf Javadoc

- .travis-build.sh
- .travis.yml
Plus move plume-lib to it's own job.   Adding Guava to the "downstream" test build makes it too close to the limit.  I could move everything in the "misc" build to the "all-tests" build if we want to stick with 4 builds.
> Add crash checking Guava to all-tests

- checker/jtreg/multipleexecutions/Main.java
The test 'multipleexecutions/Main.java' failed when running './gradlew jtreg' on the https://github.com/eisop/checker-framework
This fork of typetools uses Java 9 javac.
This pull request solves this issue.
> Fixes failing jtreg test

- util/src/main/java/org/checkerframework/framework/test/TypecheckExecutor.java
- util/src/main/java/org/checkerframework/framework/test/diagnostics/JavaDiagnosticReader.java
- util/src/main/java/org/checkerframework/framework/test/diagnostics/TestDiagnosticLine.java
This should be merged along with https://github.com/typetools/checker-framework-inference/pull/79 .
(That is the reason for the Travis failure.)
>  Rewrite JavaDiagnosticReader for clarity and simplicity

- checker/src/main/java/org/checkerframework/checker/signedness/SignednessUtil.java
- checker/src/main/java/org/checkerframework/checker/signedness/SignednessUtilExtra.java
- docs/manual/signedness-checker.tex
Android doesn't include java.awt packages, so including references to those packages cause the Android lint tool to fail.  The only references to those packages are in SignednessUtil, so this pull request moves them to a new class that isn't included in checker-qual.jar.
Fixes #1978.
> Move some methods of SignednessUtil to new class

- checker/src/main/java/org/checkerframework/checker/index/inequality/LessThanAnnotatedTypeFactory.java
- checker/tests/index/Kelloggm225.java
- framework/src/main/java/org/checkerframework/framework/type/GenericAnnotatedTypeFactory.java
Fixes https://github.com/kelloggm/checker-framework/issues/225.
The test case was failing because `bar.length` isn't in the Value Checker's store until after `0`.  So the Value Checker doesn't have a value for `bar.length`.  But is does have an ArrayRange for `bar`, so I changed the code to use that.
> Use ArrayRange and ArrayLen in LessThan Checker.

- checker/src/main/java/org/checkerframework/checker/index/lowerbound/LowerBoundTransfer.java
- checker/tests/index/Kelloggm228.java
Fixes https://github.com/kelloggm/checker-framework/issues/228.
> If a and b are non-negative and a <= b and a != b, then b is pos.

- checker/src/main/java/org/checkerframework/checker/index/inequality/LessThanAnnotatedTypeFactory.java
- checker/tests/index/LessThanCustomCollection.java
- checker/tests/index/LessThanZeroArrayLength.java
#2003 added use of the Value Checker to the Less Than Checker, so that constants are considered less than array lengths with appropriate MinLen annotations. This PR fixes an oversight in that PR, which assumed that arrays with no MinLen annotation have length `Long.MIN_VALUE`. This changes that default to `0` for array lengths, which removes some warnings in Guava. I also removed an expected warning in the test suite that should have been a suppressed warning - that warning was a false positive (it's identical to the case I'm trying to fix).
I'd normally wait for Suzanne for this, but since it's an easy fix and removes 3 false positives in Guava I figured I'd do it now. Whoever gets to it first can review it and remove the other.
> Fix an issue with #2003

- framework/src/main/java/org/checkerframework/framework/type/AnnotationClassLoader.java
Fix AnnotationClassLoader's handling of windows file paths. Normalise rootDirectory using getAbsolutePath() before comparison with filePath.
> Fix issue #2020. AnnotationClassLoader handling of Windows file paths.

- jdk8/build.gradle
The buildJdk task is an exec task.  Declaring it as a Jar task breaks gradle's dependency processing and prevents the task from running when it should.
> buildJdk task does not build on functionality of gradle's Jar type

- build.gradle
- docs/manual/troubleshooting.tex
- use `./gradlew` instead of `ant` in the manual
- for consistency, recommend using `./gradlew` in build.gradle
I don't know whether the paragraph about `maxparallel` is still relevant. In case it is not, I have removed it. If it is, you can update and add it back, or tell me what should be there.
> Update code formatting commands in manual to use gradlew [ci skip]

- checker/src/main/java/org/checkerframework/checker/initialization/InitializationAnnotatedTypeFactory.java
- checker/tests/nullness/Issue2052.java
> Use erased type to compare type frames in Initialization Checker.

- .travis-build.sh
- .travis.yml
This makes it easier to see what failed: usually checker-framework-inference.
> Separate checker-framework-inference from other downstream tests

- docs/manual/Makefile
The Gradle task `allJavadoc` builds the Javadoc in docs/api, so run that tasks if docs/api doesn't exist.
> Correct location of Javadoc when building the manual

- docs/manual/external-tools.tex
Complete command example will be more meaning & easy from user point of view while running any checker. As, `processor` as argument is specified for` javac `but for `java` it is not mentioned that clearly.
```
java [ options ] -jar file.jar [ arguments ]
arguments
The arguments passed to the main function.
```
reference links :
https://docs.oracle.com/javase/7/docs/technotes/tools/windows/javac.html
https://docs.oracle.com/javase/7/docs/technotes/tools/windows/java.html
> Minor Documentation update for Option 3 of Section 31.6

- checker/src/main/java/org/checkerframework/checker/guieffect/GuiEffectTypeFactory.java
This makes the annotation `@MainThread` imply `@UIEffect` for the `guieffect` checker. This is expected by the Rx Thread/Effect Checker at Uber and getting this plus #1977 landed would allow us to use the main-line Checker Framework as our base again.
> Treat android.support.annotation.MainThread as an alias for UIEffect

- docs/manual/annotating-libraries.tex
- framework/src/main/java/org/checkerframework/framework/source/SourceChecker.java
- framework/src/main/java/org/checkerframework/framework/stub/StubParser.java
* Add `-AstubWarnIfNotFoundIgnoresClasses`, which allows us to use `-AstubWarnIfNotFound` in a way that ignores missing classes due to packages that are distributed across more than one JAR
* Report a better error, with type and file info, when the code has a wildcard type but the stub has something else, rather than giving a generic cast error. There is probably more generic code-type to stub-type missmatch checking that could be done here, but this is the case that has bitten us before.
> StubParser warning changes (AstubWarnIfNotFoundIgnoresClasses and Wildcards)

- framework/src/main/java/org/checkerframework/common/reflection/DefaultReflectionResolver.java
- framework/tests/reflection/MethodTest.java
Verify that the first argument to an invoke call is a subtype of the possible class.
The fix for https://github.com/typetools/checker-framework/issues/2107 uncovered this bug.  The test cases with `this` were crashing that fix.  This fixes the crash.  With the crash fixed, the test case with `this` correctly issued errors.  But, since the point of those tests were to check the reflection resolution was improving the precision of the checker, I had to change them to something that would pass.
> Reflection Resolution:

- checker/src/main/java/org/checkerframework/checker/index/lowerbound/LowerBoundChecker.java
- checker/tests/index/ListLowerBound.java
>  Don't issue Lower Bound Checker Warnings on List and other classes.

- checker/src/main/java/org/checkerframework/checker/index/IndexRefinementInfo.java
- checker/src/main/java/org/checkerframework/checker/index/inequality/LessThanAnnotatedTypeFactory.java
- checker/src/main/java/org/checkerframework/checker/index/inequality/LessThanTransfer.java
- checker/src/main/java/org/checkerframework/checker/index/samelen/SameLenTransfer.java
- checker/src/main/java/org/checkerframework/checker/index/upperbound/UpperBoundAnnotatedTypeFactory.java
Future proofs against annotation order and removes the need to check that collections only contain one annotation.
At Mike's request.
> Remove uses of iterator.next() on annotation collections in the Index Checker

- framework/src/main/java/org/checkerframework/framework/type/AnnotationClassLoader.java
Supports the use of AnnotationClassLoader in a multithreaded build tool such as [Buck](https://github.com/facebook/buck) by disabling the URL connection cache so that threads don't share a connection to Jar files. This prevents `java.lang.IllegalStateException: zip file closed` from occurring, which is caused by one thread closing a shared connection to the Jar file before another thread has finished its tasks.
Fixes #2164
> AnnotationClassLoader multithread support

- checker/.classpath
- framework-test/.classpath
- framework-test/.project
- framework/.classpath
sort entries by src / con / lib / output, and by names within each kind
update output paths to correspond with gradle 4.5 outputs
update eclipse project name of `framework-test`
> update eclipse project classpaths and names

- checker/tests/nullness/Issue2171.java
- framework/src/main/java/org/checkerframework/framework/util/AnnotatedTypes.java
> When expanding varargs, copy parameters rather than using the same object. Fixes #2171

- changelog.txt
- docs/manual/external-checkers.tex
- docs/manual/manual.bbl
Adds a reference to the [Rx Thread & Effect Checker](https://github.com/uber-research/RxThreadEffectChecker) in the manual.
Note that I didn't add a citation to the paper because the BibTeX is being pulled from an [external source](https://github.com/mernst/plume-bib).  I'm happy to add the citation and send over a BibTeX entry for the paper, just wasn't sure of the process on that.
> Add external Rx Thread & Effect Checker to Manual

- framework/src/main/java/org/checkerframework/framework/source/SourceChecker.java
- javacutil/src/main/java/org/checkerframework/javacutil/BugInCF.java
Ensure that there is always a cause throwable and non-null message.
Fixes #2188.
> Improve BugInCF stack trace handling.

- framework/src/main/java/org/checkerframework/framework/type/AnnotatedTypeFactory.java
- framework/tests/framework/AnnotatedGenerics.java
Here is the pull request to fix Issue #2183. 
Note: I have run the JUnit tests in the framework project in eclipse, but have had trouble running ./gradlew allTests on my environment.
> Issue #2183. Obtain constructor annotations even if using diamond operator to infer type arguments.

- changelog.txt
- docs/manual/external-checkers.tex
Adds a short blurb to section 23 (third party checkers) about the recently-released AWS KMS compliance checker (https://github.com/awslabs/aws-kms-compliance-checker), and notes it in the change log.
> Add blurb for KMS compliance checker

- docs/manual/creating-a-checker.tex
- framework/src/main/java/org/checkerframework/framework/type/AnnotatedTypeFactory.java
- framework/src/main/java/org/checkerframework/framework/type/typeannotator/ImplicitsTypeAnnotator.java
This is an attempt to improve the misleading documentation for addComputedTypeAnnotations.
Please let me know what is correct or incorrect.
Rather than commenting on the pull request, please push commits to the branch to directly improve the text.  Thanks!
One question that should be addressed in the documentation is:  When should a type factory subclass just one of the methods, and when should it subclass both?
Also, this confusing documentation for AnnotatedTypeFactory.postAsMemberOf should be improved:
>  Overriding methods should merely change the annotations on the subtypes, without changing the types.
What are "annotations on subtypes"?  Does "the types" refer to the Java type?
> Improve documentation for addComputedTypeAnnotations

- checker/src/main/java/org/checkerframework/checker/fenum/FenumAnnotatedTypeFactory.java
- checker/src/main/java/org/checkerframework/checker/formatter/FormatterAnnotatedTypeFactory.java
- checker/src/main/java/org/checkerframework/checker/formatter/FormatterVisitor.java
- checker/src/main/java/org/checkerframework/checker/i18nformatter/I18nFormatterAnnotatedTypeFactory.java
- checker/src/main/java/org/checkerframework/checker/i18nformatter/I18nFormatterVisitor.java
- checker/src/main/java/org/checkerframework/checker/initialization/InitializationAnnotatedTypeFactory.java
- checker/src/main/java/org/checkerframework/checker/initialization/InitializationVisitor.java
- checker/src/main/java/org/checkerframework/checker/lock/LockAnnotatedTypeFactory.java
- checker/src/main/java/org/checkerframework/checker/nullness/KeyForAnnotatedTypeFactory.java
- checker/src/main/java/org/checkerframework/checker/nullness/NullnessVisitor.java
- checker/src/main/java/org/checkerframework/checker/regex/RegexAnnotatedTypeFactory.java
- checker/src/main/java/org/checkerframework/checker/units/UnitsAnnotatedTypeFactory.java
- checker/src/main/java/org/checkerframework/checker/units/UnitsRelationsTools.java
- framework/src/main/java/org/checkerframework/common/reflection/ClassValAnnotatedTypeFactory.java
- framework/src/main/java/org/checkerframework/common/reflection/MethodValAnnotatedTypeFactory.java
- framework/src/main/java/org/checkerframework/common/value/ValueAnnotatedTypeFactory.java
- framework/src/main/java/org/checkerframework/framework/type/AnnotatedTypeFactory.java
- framework/src/main/java/org/checkerframework/framework/type/AnnotatedTypeMirror.java
- framework/src/main/java/org/checkerframework/framework/util/MultiGraphQualifierHierarchy.java
- framework/src/test/java/testlib/util/FlowTestAnnotatedTypeFactory.java
- javacutil/src/main/java/org/checkerframework/javacutil/AnnotationUtils.java
This is clearer, shorter, and consistent with existing areSameByName methods.
> Rename areSameIgnoringValues to areSameByName

- framework/src/main/java/org/checkerframework/framework/util/ContractsUtils.java
No tests fail.  Is this an acceptable change to make?
> Don't call getDeclAnnotationNoAliases in ContractsUtils

- checker/src/main/java/org/checkerframework/checker/units/UnitsRelationsTools.java
Clients might depend on this behavior.
It's better for clients to not pass null, and none seem to do so now.
> Remove undocumented behavior for null arguments

- framework/src/main/java/org/checkerframework/common/basetype/BaseTypeVisitor.java
- framework/src/main/java/org/checkerframework/framework/type/AnnotatedTypeFactory.java
When checking `new @B Banana()` assuming `Banana` is defined as
```
class Banana{
@A Banana() {...}
}
```
Only issue a warning if `@B <: @A`, rather than considering the whole type. 
The crashed reported in Issue #2302 was caused by checking the whole type, so this pull request reverts the changes added to fix the crash.  (Note diamond type inference will be improved as a part of Java 8 type inference.)
> Only check the primary annotations when checking constructor invocation annotation

- checker/tests/nullness/Issue415.java
- checker/tests/nullness/KeyForDiamond.java
- checker/tests/nullness/KeyForValidation.java
- framework/src/main/java/org/checkerframework/framework/util/dependenttypes/DependentTypesHelper.java
See `checker/tests/nullness/KeyForDiamond.java` for examples that were failing.
> Correct dependent type annotations for NewClassTrees

- framework/src/main/java/org/checkerframework/framework/type/AsSuperVisitor.java
- framework/src/main/java/org/checkerframework/framework/type/poly/AbstractQualifierPolymorphism.java
- framework/tests/all-systems/Issue2370.java
- framework/tests/all-systems/Issue2371.java
Undo some of the fixes committed in https://github.com/typetools/checker-framework/pull/2193.
This pull request correctly fixes #2196 and #2190.
This pull request also fixes #2370 and fixes #2371 which has the same root cause as #2190 and #2196.
> AsSuper and QualifierPolymorphism fixes

- framework/src/main/java/org/checkerframework/framework/flow/CFCFGBuilder.java
- framework/src/main/java/org/checkerframework/framework/type/AnnotatedTypeFactory.java
- framework/src/main/java/org/checkerframework/framework/util/defaults/QualifierDefaults.java
I ended up naming it `artificialTree` (instead of the earlier discussed `generatedTree`) to be consistent with how we named this in dataflow.
> Rename pathHack and related methods to artificialTreeToEnclosingElementMap.

- framework/src/main/java/org/checkerframework/framework/util/TreePathCacher.java
When getPath is called with an artificial tree created by dataflow, null is returned.  Cache this so that the whole compilation unit isn't searched again.  (This fixes the daikon type check failure.)
> TreePathCacher: cache null when path not found

- framework/src/main/java/org/checkerframework/framework/util/typeinference/TypeArgInferenceUtil.java
- framework/tests/all-systems/TypeVarVarargs.java
Currently in the varargs case, `assignedToExecutable()` returns the varargs' array type instead of its component type, which gives an incorrect assignment context for type argument inference. For instance, in the following code
```
abstract class C {
abstract public <T> T foo();
abstract public void bar(Integer ... s);
public void m() {
bar(foo(), foo());
}
}
```
the current implementation will infer `T` as `Integer []` at both invocations of `foo()` due to this problem, and would further cause a `asSuper` crash resulted from `AbstractQualifierPolymorphism#annotate()` trying to visit the inferred type `Integer []` of `foo()` and the parameter type `Integer` expanded from `bar()`'s varargs.
This problem can be exhibited by running `./checker/bin/javac -processor …
> Fix varargs type argument inference

- framework/src/main/java/org/checkerframework/framework/type/poly/AbstractQualifierPolymorphism.java
- framework/src/main/java/org/checkerframework/framework/type/poly/QualifierPolymorphism.java
- framework/src/main/java/org/checkerframework/framework/util/AnnotatedTypes.java
- framework/src/main/java/org/checkerframework/framework/util/MultiGraphQualifierHierarchy.java
isPolymorphicQualified => hasPolymorphicQualifier
Previously, the code had isPolymorphicQualified and getPolymorphicQualifier.
I feel that parallelism between hasPolymorphicQualifier and getPolymorphicQualifier is nicer.
getPolymorphicQualifierTop => getPolymorphicQualifierElement
The new name better reflects the actual semantics.
We could instead require that the argument to @PolymorphicQualifier must be exactly
top, and in that case this renaming would not be necessary.
> Rename two methods

- checker/src/main/java/org/checkerframework/checker/signedness/jdk.astub
By this change, most of the errors will get omitted which came in the case study-
https://github.com/gokaco/Signedness-Checker-2
> Add signedness annotations for RandomAccessFile

- changelog.txt
- checker/src/main/java/org/checkerframework/checker/initialization/InitializationVisitor.java
- checker/tests/nullness/StaticInitializer.java
- checker/tests/nullness/init/Uninit12.java
- checker/tests/nullness/java8/lambda/Initialization.java
The changelog text will be:
Improved the diagnostic text for uninitialized static fields.  The new
error key is initialization.static.fields.uninitialized.
> Defer user-visible change until a subsequent release

- checker/build.gradle
- docs/developer/release/release_vars.py
> Make the checker-source.jar and checker-javadoc.jar contain all framework classes

- checker/src/main/java/org/checkerframework/checker/index/upperbound/messages.properties
Consider the following code:
```
class tryit{
public void check_it(int[] x){
x[0] = 0;
}  
}
```
Run it by typing in the terminal:
javac -processor index tryit.java
Output:
tryit.java:3: error: [array.access.unsafe.high.constant] Potentially unsafe array access: the constant index 0 could be larger than the array's bound
x[0] = 0;
^
found   : @UnknownVal int @UnknownVal []
required: @MinLen("1") -- an array guaranteed to have at least 1 elements
1 error
However, while annotating, we can't use @MinLen("1") because String cannot be converted to int, hence, we use @MinLen(1).
Hence, I removed the double inverted commas (" ") from the error message.
> removed double inverted commas from @MinLen error message

- dataflow/src/main/java/org/checkerframework/dataflow/cfg/ControlFlowGraph.java
Hello, this PR removes the duplicate code from ControlFlowGraph.java. The removed code is the same as the content of getSuccessors(), so we can use this method directly.
> Remove duplicate code from ControlFlowGraph.java.

- framework/src/main/java/org/checkerframework/framework/type/AnnotatedTypeFactory.java
- framework/src/main/java/org/checkerframework/framework/type/ElementAnnotationApplier.java
- framework/src/main/java/org/checkerframework/framework/type/TypeFromMemberVisitor.java
The changes in #2472 caused daikon-type-check to fail. 
Here's the error:
```
daikon/diff/Node.java:22: error: [assignment.type.incompatible] incompatible types in assignment.
this.userObject = userObject;
^
found   : @NonNull @NonRaw Pair<CONTENT[ extends @NonNull @NonRaw Object super @NonNull @NonRaw Void], CONTENT[ extends @NonNull @NonRaw Object super @NonNull @NonRaw Void]>
required: @NonNull @NonRaw Pair<CONTENT[ extends @NonRaw @Nullable Object super @NonNull @NonRaw Void], CONTENT[ extends @NonRaw @Nullable Object super @NonNull @NonRaw Void]>
```
Here is the relevant snippet of the Node.java file:
```
public abstract class Node<CONTENT extends @Nullable Object, CHILD> {
private List<CHILD> children = new ArrayList<CHILD>();
// Nonsensical for RootNode
private Pair<CONTENT, …
```
> Explicit annotations on type parameter upper bounds.

- checker/build.gradle
- checker/resources
- checker/src/main/resources/javadoc.astub
- docs/manual/introduction.tex
- framework/src/main/java/org/checkerframework/framework/type/AnnotatedTypeFactory.java
Also, allow it to be specified via `-Astubs=checker.jar/javadoc.astub`.
Fixes #2499.
> Put javadoc.astub in the top level of checker.jar

- framework/src/main/java/org/checkerframework/common/basetype/BaseTypeVisitor.java
- framework/src/main/java/org/checkerframework/framework/type/AnnotationClassLoader.java
- framework/src/main/java/org/checkerframework/framework/util/AnnotatedTypes.java
Also some documentation improvements.
This incorporates the working parts of https://github.com/typetools/checker-framework/pull/2376, which we can close (and delete its branch) to keep the repository clean.
> Change argument types of warnAboutTypeAnnotationsTooEarly

- changelog.txt
- checker/src/main/java/org/checkerframework/checker/nullness/Opt.java
- checker/tests/nullness/flow/TestOpt.java
Simplify signature.
Related to 8c21ebc983f60df3f0c83550a2258fe61f165472
The change to Opt.get should also be added to the changelog.
> Make get and orElseThrow consistent.

- .travis-build-without-test.sh
- build.gradle
This was added in #2124 but doesn't seem necessary.
Is there any reason to keep this around?
> Remove unnecessary download of jsr308-langtools

- checker/src/main/java/org/checkerframework/checker/nullness/NullnessVisitor.java
- checker/tests/lock/GuardSatisfiedTest.java
- framework/src/main/java/org/checkerframework/common/basetype/BaseTypeVisitor.java
BaseTypeVisitor should scan ParameterizedTypeTree so that all trees are scanned by the visitor.  This way, subclasses can implement their own logic, such as validating explicit annotations.
> BaseTypeVisitor: scan ParameterizedTypeTrees

- framework/src/main/java/org/checkerframework/framework/util/DefaultAnnotationFormatter.java
Small improvement to error messages. https://github.com/typetools/checker-framework/issues/2409
It no longer displays map entries with empty `AnnotationValue`. For example,
```
found : @LTEqLengthOf("a") int
required: @LTLengthOf(value="a", offset={}) int
```
becomes
```
found : @LTEqLengthOf("a") int
required: @LTLengthOf(value="a") int
```
> Fixed #2409

- .travis-build.sh
When our Travis jobs fail, they print out a long and usually uninformative stack trace at the end.  Here is an example:
https://travis-ci.org/mernst/checker-framework/jobs/547037634#L1367
This pull request eliminates the stack trace.
Are there cases when the stacktrace is essential for debugging?
When a test is running, the testing framework should catch the stack trace and make it available.
When compilation fails, the stack trace is not useful (except maybe if the compiler crashes?).
> Don't print stacktrace at end of failed Gradle build

- checker/src/main/java/org/checkerframework/checker/index/samelen/SameLenTransfer.java
- checker/tests/index/Issue2493.java
- checker/tests/index/SameLenOnFormalParameter.java
- checker/tests/index/SameLenOnFormalParameterSimple.java
This pull request adds defaulting so that `@SameLen` annotations on formal that refer to other parameters are symmetric. For example, the declaration:
```java
void foo(int @SameLen("#2")[] a, int[] b)
```
is defaulted to
```java
void foo(int @SameLen("#2")[] a, int @SameLen("#1")[] b)
```
Fixes #2434.
@Maxi17 contributed significantly to this PR, and I would appreciate any comments he has on it.
> Make SameLen annotations on parameters symmetric

- checker/src/main/java/org/checkerframework/checker/index/IndexUtil.java
- checker/src/main/java/org/checkerframework/checker/index/OffsetDependentTypesHelper.java
- checker/src/main/java/org/checkerframework/checker/index/upperbound/OffsetEquation.java
- checker/tests/index/IndexIntValVsConstant.java
Fixes #2484.
When an offset is calculated, IndexChecker now treats variables annotated with single-argument `@IntVal` as constant, just like literal values. 
@kelloggm
> IndexChecker treats single-argument `@IntVal` as constant value

- .travis-build-without-test.sh
When running `./gradlew cloneAndBuildDependencies`, git fails to pull recent changes from annotation-tools, due to unkown `-q` option.
This was discovered because due to recent changes, up-to-date version of annotation-tools is required, but running `cloneAndBuildDependencies` does not help.
> Fix position of -q option in git pull command

- checker/src/main/java/org/checkerframework/checker/index/lowerbound/LowerBoundTransfer.java
- checker/tests/index/CharToIntCast.java
- checker/tests/index/IndexByChar.java
- checker/tests/index/NonnegativeChar.java
- framework/src/main/java/org/checkerframework/common/value/ValueVisitor.java
Every `char` method parameter is now `@NonNegative` by default.
In an assignment, this is further improved to `@IntRange(from = 0, to = Character.MAX_VALUE)` if necessary.
Related: #1675, kelloggm#192.
Fixes #2540
Two test cases were written by @panacekcz.
@kelloggm
> Added NonNegative default annotation to `char`

- checker/tests/index/IndexConditionalReport.java
- framework/src/main/java/org/checkerframework/common/value/ValueAnnotatedTypeFactory.java
- framework/tests/value/Repo.java
In a for loop, `@IntRange` annotations can be unpredictable (#1669). In the test case, `i` had `@IntRange(from = Integer.MIN_VALUE, to = Integer.MAX_VALUE)` annotation, which was wrong to begin with (`i` is greater than 0) and redundant, because it is an `int`.
The actual problem was that the type of the conditional expression was `IntVal(-1)`, which is again wrong. It is supposed to be the LUB of true and false expressions, in this case simply `int`. Here is the bug in CF:
1. The LUB of `@IntVal(-1) int` and `int` is `int` (correct).
2. The LUB of `@IntVal(-1) int` and `@IntRange(from = Integer.MIN_VALUE, to = Integer.MAX_VALUE) int` is `@IntVal(-1) int` (wrong).
In the for loop from the test case, the second case is applied and therefore the bug.
This PR fixes this by changing the …
> Refine IntRange annotations in conditional expressions inside for loops

- .travis-build-without-test.sh
- .travis-build.sh
- checker/build.gradle
- checker/jdk/Makefile
Call this task in Travis when use a prebuilt jdk.  Also adds more information to the manifest:
```
Checker-Framework-Version: 242f33a
Checker-Framework-Commit-Author: Noone <noone@cares.com>
Creation-Date: Fri Jul 5 21:07:03 UTC 2019
Created-By: 1.8.0_131 (Oracle Corporation)
Checker-Framework-Commit-Refs: (HEAD)
```
> Add task to print jdk8.jar manifest.

- checker/src/main/java/org/checkerframework/checker/index/inequality/LessThanVisitor.java
- checker/tests/index/Issue2629.java
Fixes #2629 
Implementation is adding an exception to the common assignment check for assignments where the expected type is `@LessThan("${id} + 1")` for some identifier `${id}`, and the right hand side of the assignment is exactly the identifier tree containing id.
> Permit LessThan Checker assignments when they are tautologies

- javacutil/src/main/java/org/checkerframework/javacutil/TypesUtils.java
This should work with Java 8. With Java 9 the behavior of `types.isSameType` handles wildcards more strictly. The new order should work for both.
> Compare for same type after wildcard modifications.

- checker-qual/build.gradle
On line 36, qualifiers and other java files are copied into the `src/main/java` folder, so the `clean` task should also be target the same.
> Fix clean task in checker-qual build

- framework/src/main/java/org/checkerframework/common/value/ValueAnnotatedTypeFactory.java
- framework/tests/value/ByteArrayWithNonLiteralConstants.java
- framework/tests/value/CharArrayWithNonLiteralConstants.java
When initializing a `char[]`, check if the elements of the array are annotated with single-value `@IntVal`
Fixes #1152
I modified the test case from `byte[]` to `char[]` because of different character encodings.
> Compile-time char constants are treated as literals

- docs/manual/advanced-features.tex
- framework/src/main/java/org/checkerframework/framework/util/FlowExpressionParseUtil.java
- framework/tests/flowexpression/ArrayCreationParsing.java
- framework/tests/flowexpression/ClassLiterals.java
New parsable types:
1. Array creation expressions (`new int[2]`, `new String[] {"a", "b"}`, `new java.lang.String[2]`)
2. Class literals with primitive or void type (`int.class`, `double.class`, `void.class`).
I combined those 2 because I used class literals with primitive type to parse array creation expressions with primitive type.
I will add Javadoc soon.
> Array creation and primitive type class literals are parsable

- framework/src/main/java/org/checkerframework/common/basetype/BaseTypeVisitor.java
These diagnostics are useful for understanding checker behavior.  I did not change the code to call `commonAssignmentCheck()` directly, to avoid introducing subtle differences in error messages, etc.
> Add assignment diagnostic calls for receiver subtype check

- framework/src/main/java/org/checkerframework/framework/type/TypeFromExpressionVisitor.java
checker-framework/framework/tests/all-systems/java8/lambda/Issue573.java crashes
using Java 11 without this change.
> In Java 11, member references and lambda could be intersection types.

- framework/src/main/java/org/checkerframework/framework/flow/CFAbstractStore.java
`GenericAnnotatedType.getAnnotationWithMetaAnnotation` computes the type of the field which is time consuming, so only do it if needed.
> Don't call atypeFactory.getAnnotationWithMetaAnnotation on every field

- checker/tests/nullness/Issue2587.java
- framework/src/main/java/org/checkerframework/framework/util/FlowExpressionParseUtil.java
- framework/tests/flowexpression/InnerClasses.java
Fixes #2587 
If the annotated element is inside a static class or an enum and the field that the annotation refers to is non-static, then throw an exception.
I will try to make the code cleaner.
> Non-static fields can't be referenced from a static inner class or enum

- checker/src/main/java/org/checkerframework/checker/index/IndexUtil.java
- checker/src/main/java/org/checkerframework/checker/index/inequality/LessThanAnnotatedTypeFactory.java
- checker/src/main/java/org/checkerframework/checker/index/inequality/LessThanTransfer.java
- checker/src/main/java/org/checkerframework/checker/index/lowerbound/LowerBoundAnnotatedTypeFactory.java
- checker/src/main/java/org/checkerframework/checker/index/lowerbound/LowerBoundTransfer.java
- checker/src/main/java/org/checkerframework/checker/index/samelen/SameLenAnnotatedTypeFactory.java
- checker/src/main/java/org/checkerframework/checker/index/samelen/SameLenTransfer.java
- checker/src/main/java/org/checkerframework/checker/index/samelen/SameLenVisitor.java
- checker/src/main/java/org/checkerframework/checker/index/searchindex/SearchIndexAnnotatedTypeFactory.java
- checker/src/main/java/org/checkerframework/checker/index/searchindex/SearchIndexTransfer.java
- checker/src/main/java/org/checkerframework/checker/index/upperbound/OffsetEquation.java
- checker/src/main/java/org/checkerframework/checker/index/upperbound/UpperBoundAnnotatedTypeFactory.java
- checker/src/main/java/org/checkerframework/checker/index/upperbound/UpperBoundTransfer.java
- checker/src/main/java/org/checkerframework/checker/index/upperbound/UpperBoundVisitor.java
- checker/src/main/java/org/checkerframework/checker/signedness/SignednessAnnotatedTypeFactory.java
- framework/src/main/java/org/checkerframework/common/value/ValueCheckerUtils.java
`IndexUtil` contained a lot of Value Checker utilities. This PR moves them to the ValueChecker's own utility class.
I also added one new method: `getExactStringValue`, which is an analogue of `getExactValue` (which returns an integral value). That method will be useful to me in the Object Construction Checker: https://github.com/kelloggm/object-construction-checker/pull/89
> Move Value Checker utilities to ValueCheckerUtils

- framework/src/main/java/org/checkerframework/framework/qual/CFComment.java
Otherwise @CFComment is part of the public API and has to be exported.
And, @CFComment doesn't need to be in public API documentation.
> Remove @Documented from @CFComment

- checker/tests/nullness/Issue2721.java
- framework/src/main/java/org/checkerframework/framework/type/poly/AbstractQualifierPolymorphism.java
- framework/src/main/java/org/checkerframework/framework/util/AnnotatedTypes.java
> asMemberOf:  Substitutes uninferred type arguments for type variables. (Fixes #2721)

- framework/src/main/java/org/checkerframework/framework/util/FlowExpressionParseUtil.java
This will fail the require-javadoc check.
I think we should merge it anyway, since it adds useful documentation, even if other desirable documentation is still lacking.
> Add documentation

- build.gradle
- framework/src/main/java/org/checkerframework/framework/util/CheckerMain.java
- javacutil/src/main/java/org/checkerframework/javacutil/Resolver.java
`--add-exports` are only required when source is set to 9 or above.  
Also, target Java 8 bytecode.
> Remove --add-exports and most --add-opens.

- framework/src/main/java/org/checkerframework/framework/util/AnnotationMirrorMap.java
- framework/src/main/java/org/checkerframework/framework/util/AnnotationMirrorSet.java
The default toString() of AnnotationMirrorMap and AnnotationMirrorSet is overridden for clarity of printing internal states.
> Override toString() of AnnotationMirrorMap and AnnotationMirrorSet for debugging

- docs/manual/external-tools.tex
This fixes the documentation for using Checker Framework with Buck by linking to instructions on how to first enable the Error Prone javac compiler with Buck.  This is the final change to fix #2749
> Fix Buck documentation

- dataflow/src/main/java/org/checkerframework/dataflow/analysis/TransferInput.java
Fix typos and make the HTML special characters`&hArr;` and `&amp;` show correctly in api document.
In the current [api document](https://checkerframework.org/api/org/checkerframework/dataflow/analysis/TransferInput.html):
```
protected final S extends Store<S> store
The regular result store (or null if none is present). The following invariant is maintained:
store == null &hArr; thenStore != null &amp;&amp; elseStore != null
```
`&hArr;` and `&amp;` were not parsed.
> Improve the JavaDoc of TransferInput.java.

- docs/manual/external-tools.tex
`gradle` commands need to begin with a task. There is no `checkTypes` task, so the original directions fail with an error:
```
$ ./gradlew checkTypes
FAILURE: Build failed with an exception.
* What went wrong:
Task 'checkTypes' not found in root project 'sqlbrite-root'. Some candidates are: 'dexCheckTypes'.
* Try:
Run gradlew tasks to get a list of available tasks. Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
* Get more help at https://help.gradle.org
BUILD FAILED in 0s
```
Instead, we use the `assemble` task, which is a basic top-level Android task.
> Fixed final step of android-gradle

- checker/src/main/java/org/checkerframework/checker/units/UnitsAnnotatedTypeFactory.java
- framework/src/main/java/org/checkerframework/framework/util/MultiGraphQualifierHierarchy.java
- javacutil/src/main/java/org/checkerframework/javacutil/AnnotationUtils.java
`AnnotationUtils.areSame` includes another redundant call to `areSameByName` before finally calling `sameElementValues`. Since we already know the result of `areSameByName`, we can use `sameElementValues` directly.
> Use `sameElementValues` followed by `areSameByName` instead of `areSame`

- checker/src/main/java/org/checkerframework/checker/interning/InterningVisitor.java
- checker/tests/interning/UsesObjectEqualsTest.java
The previous implementation ignored UsesObjectEquals in stub files and did respect the `@Inherited` meta-annotation on UsesObjectEquals.
> Correct implementation of UsesObjectEquals.

- checker/jtreg/nullness/Issue2853.java
- docs/developer/release/README-release-process.html
- framework/src/main/java/org/checkerframework/common/basetype/BaseTypeVisitor.java
Calling getAnnotatedTypeLhs on a lambda parameter node is possibly expensive because caching is turned off and the type of every expression that contributes to the type of the lambda parameter is recomputed.  This should be fixed by #979.
> Don't call getAnnotatedTypeLhs on lambda parameters (Fixes #2853)

- framework/src/main/java/org/checkerframework/framework/type/DefaultAnnotatedTypeFormatter.java
Here's an example:
```
Streaming.java:9: error: [assignment.type.incompatible] incompatible types in assignment.
List<String> listA = Stream.of("A").collect(Collectors.<String>toList());
^
found   : @Initialized @NonNull  /*INFERENCE FAILED ? extends java.lang.Object*/
required: @UnknownInitialization @Nullable List<@Initialized @NonNull String>
```
> Change toString of uninferred type arguments.

- checker/src/main/java/org/checkerframework/checker/initialization/InitializationAnnotatedTypeFactory.java
This saves us from having to repeatedly convert all initialization annotation to string whenever we call `isInitializationAnnotation`.
> Cache string representation of initialization annotations

- build.gradle
When running jtreg tests, if some tests fail, we can't see the error or failure messages, it is not helpful (especially when seeing travis's log).
I suggest to change from `-verbose:summary` to `-verbose:error,fail`, which will give us more details. But we may concern that the length of the log will increase.
> Show more details about error and failure in jtreg tests.

- checker/build.gradle
- checker/jdk/nullness/src/java/security/KeyStore.java
Related PR:
- typetools/annotated-libraries#38
- typetools/jdk#20
> Use Nullness checker to annotate KeyStore.java.

- checker/tests/interning/Issue2809.java
- framework/src/main/java/org/checkerframework/framework/type/AnnotatedTypeFactory.java
AnnotatedTypeFactory.fromExpressionTreeCache will return types with outdated type variables when visiting new operators. Disable caching of NEW_CLASS could be a solution for #2809.
> #2809: disable caching of NEW_CLASS

- checker/tests/nullness/Issue2865.java
- framework/src/main/java/org/checkerframework/framework/type/AnnotatedTypeFactory.java
- framework/src/main/java/org/checkerframework/framework/util/typeinference/TypeArgInferenceUtil.java
- javacutil/src/main/java/org/checkerframework/javacutil/TreeUtils.java
Also changed `TreeUtils#getReceiverTree` to return the receiver tree of a NewClassTree. 
Fixes #2865.
> Set enclosingType for the type of NewClassTrees (Fixes 2865)

- framework/src/main/java/org/checkerframework/common/value/ValueTransfer.java
The default is ten elements when not provided but when we have the full context
of how many will be used, it saves repeated reallocation as elements are
added beyond ten.
> Preallocate array list size whenever the information is available.

- framework/src/main/java/org/checkerframework/framework/type/AnnotatedTypeFactory.java
Work being done on both branches are the same, additionally, it seems like getDeclAnnotation doesn't return `null`.
> Don't unnecessarily call getDeclAnnotation

- framework/src/main/java/org/checkerframework/common/wholeprograminference/WholeProgramInferenceScenes.java
Whole-program inference should not attempt to infer types for code presented only as bytecode. Doing so is 1) unnecessary, because whole-program inference should only be used to annotate code, not to produce stub files generally AND 2) dangerous, because actually using the outputs of WPI on unchecked code means that those annotations are trusted, but no human has ever looked at them and no typechecker has verified that they are correct.
This change should have no impact on users of jaif-based WPI if they are using `infer-and-annotate.sh`, because the jaif files that are created for classes presented as bytecode are never used.
> Only infer types for code presented as source files

- framework/src/main/java/org/checkerframework/common/basetype/BaseTypeChecker.java
The related field `immediateSubcheckers` and other lazily initialized fields in this class aren't set to null. Make the coding style consistent.
> Fix inconsistent field initialization.

- docs/manual/introduction.tex
This PR adds description to the documentation of the behavior that when multiple checkers are provided, the checking will stop when a checker detects any error. For example, `-processor nullness,interning`, when nullness errors are detected, the Interning Checker won't run, even if there exists interning errors.
> Add documentation about running multiple checkers

- framework/src/main/java/org/checkerframework/framework/type/poly/DefaultQualifierPolymorphism.java
- framework/src/main/java/org/checkerframework/framework/util/MultiGraphQualifierHierarchy.java
Rather than recomputing them.  MultiGraphQualifierHierarchy#addPolyRelations throws exceptions similar to the ones deleted in this PR.
> Use QualifierHierarchy#getPolymorphicAnnotation.

- checker/jdk/nullness/src/java/net/URL.java
- checker/jdk/nullness/src/java/text/MessageFormat.java
- checker/jdk/nullness/src/java/util/Collections.java
- checker/jdk/nullness/src/java/util/HashMap.java
- checker/jdk/nullness/src/java/util/Hashtable.java
- checker/jdk/nullness/src/java/util/IdentityHashMap.java
- checker/jdk/nullness/src/java/util/Locale.java
- checker/jdk/nullness/src/java/util/Map.java
- checker/jdk/nullness/src/java/util/Optional.java
- checker/jdk/nullness/src/java/util/TreeMap.java
- checker/jdk/nullness/src/java/util/WeakHashMap.java
- checker/jdk/nullness/src/java/util/concurrent/ConcurrentHashMap.java
- checker/jdk/nullness/src/java/util/concurrent/ConcurrentSkipListSet.java
- checker/jdk/nullness/src/java/util/jar/Attributes.java
Most overrides are already annotated that way, but I noticed that
Map.equals(Object) was not, and I grepped through for other instances.
> Annotate Object.equals(Object) overrides as accepting null.

- checker/src/main/java/org/checkerframework/checker/formatter/FormatterAnnotatedTypeFactory.java
- checker/src/main/java/org/checkerframework/checker/formatter/qual/UnknownFormat.java
- checker/src/main/java/org/checkerframework/checker/i18nformatter/I18nFormatterAnnotatedTypeFactory.java
- checker/src/test/java/testlib/lubglb/FormatterLubGlbChecker.java
- checker/src/test/java/testlib/lubglb/I18nFormatterLubGlbChecker.java
- framework/src/main/java/org/checkerframework/framework/type/AnnotatedTypeFactory.java
Also, fix the I18nFormatterLubGlb and FormatterLubGlb Checkers.
> Throw an exception if SubtypeOf meta-annotation refers to qualifier not in hierarchy.

- framework/src/main/java/org/checkerframework/framework/util/typeinference/DefaultTypeArgumentInference.java
- framework/tests/value/Issue3001.java
Type argument inference may infer a type variable that is the same as a type variable for which it is solving.
This fixes the warnings in #3001, but does not implement the feature requested.
> Allow type arg. inference to return type variable (Fixes #3001)

- checker/jdk/nullness/src/java/util/HashMap.java
- checker/jdk/nullness/src/java/util/Map.java
It is supposed to be a no-op. As such, the stub files usually omit it.
Currently, it actually changes behavior in a bad way:
https://github.com/typetools/checker-framework/issues/2995
Until that bug is fixed, this commit serves as a workaround.
> Remove explicit "extends @Nullable Object."

- framework/src/main/java/org/checkerframework/common/value/ValueTransfer.java
Tiny improvement that shortcircuits evaluating getValueAnnotation(p.getValueOfSubNode(... if not needed.
> Evaluate only when needed

- framework/src/main/java/org/checkerframework/common/value/ValueAnnotatedTypeFactory.java
This improvement is about using the one-pass for min and max in Range.create(Collection) and the  contains() where it fits.
Again, this change contains #3000 also.
> Use range create effectively. depends on #3004

- checker/tests/lock/ClassLiterals.java
- javacutil/src/main/java/org/checkerframework/javacutil/Resolver.java
> Allow Resolver#findClassInPackage Class kinds beside just CLASS. (Fixes #3018)

- framework/src/main/java/org/checkerframework/framework/type/AnnotatedTypeMirror.java
- framework/src/main/java/org/checkerframework/framework/type/DefaultTypeHierarchy.java
- framework/tests/all-systems/java8inference/Issue3032.java
This suppresses more warnings related to #979. 
This fixes #3032.
> If a type has an uninferred type arg, only check primary annotations

- framework/src/main/java/org/checkerframework/common/basetype/BaseTypeVisitor.java
I compared the comment to the implementation of `checkTypeArguments` and it looks like all missing checks have been implemented.
> Remove dead implementation comments.

- framework/src/main/java/org/checkerframework/framework/type/AnnotatedTypeMirror.java
- framework/src/main/java/org/checkerframework/framework/type/BoundsInitializer.java
- framework/tests/all-systems/Issue3055.java
Fixes #3058 
(Note, I'll open a separate pull request that adds documentation to so of the classes enclosed in BoundsInitializer.)
> Account for recursive type variables in enclosing types (Fixes #3058)

- framework/src/main/java/org/checkerframework/framework/type/DefaultTypeHierarchy.java
This PR tries to improve #3044.
I don't know why primary annotations are not checked (directly return true) when sub or supertype contains uninferred type arguments.
> Check primary annotations before checking if there are any uninferred type arguments.

- build.gradle
The Javadoc for to com.sun.tools.java.* is not publicly available, so these links are broken.  This pull request removes links to them in the Checker Framework Javadoc.
> Remove links to com.sun.tools.java in Javadoc

- framework/src/main/java/org/checkerframework/common/basetype/BaseTypeVisitor.java
- framework/src/main/java/org/checkerframework/common/basetype/messages.properties
The error message of key `inconsistent.constructor.type` seems not clear enough, thus updated to improve it.
Update: explicit show user the cause: not returning types with top qualifier
> Improve error message of inconsistent.constructor.type

- checker/build.gradle
- checker/jdk/nullness/src/java/util/Map.java
- checker/tests/nullness/MapMerge.java
Merge together with https://github.com/typetools/jdk/pull/32
> Make Map.merge annotations less flexible (but sound and usable by most clients); fixes #3046

- checker/jdk/nullness/src/java/util/SortedMap.java
- checker/jdk/nullness/src/java/util/TreeMap.java
This avoids the following kind of false positive:
```java
import java.util.TreeMap;
class Demo {
String foo(TreeMap<String, String> m) {
return m.get(m.firstKey());
}
}
```
Corresponding jdk PR: https://github.com/typetools/jdk/pull/33
> firstKey/lastKey return a key into the map.

- framework/src/main/java/org/checkerframework/common/basetype/BaseTypeVisitor.java
This change will allow me to avoid some nasty code in the Object Construction Checker that has to parse strings to construct custom error messages: https://github.com/kelloggm/object-construction-checker/blob/master/object-construction-checker/src/main/java/org/checkerframework/checker/objectconstruction/ObjectConstructionChecker.java#L87
See also https://github.com/kelloggm/object-construction-checker/issues/140
> Refactor checkMethodInvocability to allow changes to error messages

- checker/jdk/nullness/src/java/util/IdentityHashMap.java
The public APIs in this class otherwise look fully annotated, with the exception of some missing `@Nullable` annotations on `Object` parameters, which are being addressed in https://github.com/typetools/checker-framework/pull/3063
> Add `@Nullable` to return types of `IdentityHashMap`.

- checker/src/main/java/org/checkerframework/checker/nullness/KeyForPropagator.java
- framework/src/main/java/org/checkerframework/framework/stub/StubParser.java
- framework/src/main/java/org/checkerframework/framework/type/TypeFromExpressionVisitor.java
- framework/src/main/java/org/checkerframework/framework/type/visitor/AnnotatedTypeReplacer.java
@wmdietl pointed out some inconsistencies in #3193. This PR cleans up those inconsistencies, and some other ones I noticed in the process. From the comments on some of the calls to `AnnotatedTypeMerger`/`AnnotatedTypeReplacer`, it's clear to me that the old name has caused confusion before!
The only code change in this PR is in `StubParser.java`, where I removed a no-op call to `AnnotatedTypeReplacer.replace()`.
> Clean up changes from #3193

- checker/jtreg/nullness/issue824/Class2.java
- checker/jtreg/nullness/issue824/Class2.out
- checker/tests/nullness/Issue3150.java
- checker/tests/nullness/ObjectsRequireNonNullElse.java
- checker/tests/nullness/generics/MethodTypeVars.java
- checker/tests/nullness/java8inference/Issue887.java
- framework/src/main/java/org/checkerframework/framework/util/typeinference/DefaultTypeArgumentInference.java
Fixes #3150.   (~#3149~ is partially fixed by this pull request because the annotations in the JDK are wrong.  I'll fix them in a different pull request and enable the test.)
> Correct method type argument inference with null; fixes #3056; fixes #3150.

- checker/src/main/java/org/checkerframework/checker/nullness/collection-object-parameters-may-be-null.astub
This fixes the warnings reported by StubParser.
> Correct supertypes of CopyOnWriteArraySet.

- checker/src/main/java/org/checkerframework/checker/nullness/collection-object-parameters-may-be-null.astub
- Import `@Pure`.
- Fix mistake from #3234: `CopyOnWriteArraySet` has `extends AbstractSet`, not `implements Set`.
These address StubParser warnings.
> Fixes to `collection-object-parameters-may-be-null.astub`:

- checker/src/main/java/org/checkerframework/checker/nullness/collection-object-parameters-may-be-null.astub
However, note that this currently has no effect because of #3236.
> Provide a stub for `Collection.removeAll`.

- docs/manual/external-tools.tex
This addresses https://github.com/typetools/checker-framework/issues/3201, wherein following the current instructions for setting up Checker on IntelliJ was not sufficient for successful compilation.
> IntelliJ requires use of JDK 11

- azure-pipelines.yml
As #3223 discussed:
Since Daikon can compile under Java 11 now, to be consistent with travis (`daikon_jdk11` did not comment out in .travis.yml), we should enable it again.
> Enable daikon_jdk11 on Azure Pipelines

- checker/src/main/java/org/checkerframework/checker/nullness/collection-object-parameters-may-be-null.astub
This fixes warnings like:
```
warning: StubParser: annotateTypeParameters: mismatched sizes:  typeParameters (size 0)=[];  typeArguments (size 1)=[E extends Object];  decl=class AbstractCollection {      @Pure     public boolean contains(@Nullable Object o);      public boolean remove(@Nullable Object o);      @Pure     public boolean containsAll(Collection<? extends @Nullable Object> c);      public boolean removeAll(Collection<? extends @Nullable Object> c);      public boolean retainAll(Collection<? extends @Nullable Object> c); };  elt=java.util.AbstractCollection (class com.sun.tools.javac.code.Symbol$ClassSymbol).; for more details, run with -AstubDebug
```
> Add type parameters to some collection stubs.

- checker/build.gradle
Fixes #3111
The inputs are a bit conservative (it's the entire `${jdkHome}/src` directory), but I didn't see an easy way to narrow it down.
> Add inputs and outputs for copyJdk11Files task

- checker/jdk/nullness/src/java/util/Map.java
It, like `List` (https://github.com/typetools/checker-framework/issues/2047), is not covariant:
```
import java.util.HashMap;
import java.util.Map;
import org.checkerframework.checker.nullness.qual.Nullable;
class MapCovariant {
public static void main(String[] args) {
Map<String, String> map = new HashMap<String, String>();
Map<@Nullable String, String> sameMap = map;
sameMap.put(null, "");
map.keySet().iterator().next().toString(); // NPE
}
}
```
> Remove `@Covariant` from `Map`.

- javacutil/src/main/java/org/checkerframework/javacutil/ElementUtils.java
Originally part of #2871, but @wmdietl suggested it should be a separate PR.
> Don't include annotations in primitive type simple names

- build.gradle
These Gradle configuration changes allow for parallel builds and parallel execution of tests (at the test class granularity) on multicore systems.  On my 6-core Mac Mini, this change reduces the time for a clean `./gradlew build` from ~6m50s to ~4m50s.  Improvements to incremental builds will of course depend on individual workflows (and on amount of RAM available, etc.).  If framework tests are run regularly in incremental builds, my feeling is this will yield a nice win for that case.
> Allow for parallel builds and tests

- dataflow/src/main/java/org/checkerframework/dataflow/cfg/CFGBuilder.java
This pull request mainly changes the marker text of catch block by adding concrete type of exception that the catch block can handle. Take the following example, 
import java.io.IOException;
class Exceptions {
void foo() throws IOException {}
void bar() {
try {
foo();
} catch (IOException ioe) {
l("IOE");
} catch (NullPointerException e) {
l("NPE");
} finally {
l("finally");
}
}
void l(String p) {}   
}
Marker texts of the two catch blocks should be updated to "start/end of catch block for **IOException** #hashcode"  and "start/end of catch block for **NullPointerException** #hashcode" separately. 
Additionally, other occurrences of marker texts are complemented to make CFG more readable, such as
- For marker node of `"start of try statement"`, `"start of finally block for Throwable"`, …
> Improvements to CFG marker node text

- checker/src/main/java/org/checkerframework/checker/nullness/KeyForAnnotatedTypeFactory.java
This allows the `KeyForAnnotatedTypeFactory` to be reused by other checkers. 
@wmdietl
> Explicitly calling constructors in KeyForAnnotatedTypeFactory

- build.gradle
- framework/src/main/java/org/checkerframework/framework/type/AnnotatedTypeFactory.java
While polymorphic qualifiers cannot have [`SubtypeOf`](https://github.com/typetools/checker-framework/blob/11262c72ef210d756b117c186fe62dff969e0832/framework/src/main/java/org/checkerframework/framework/qual/SubtypeOf.java), it should also not appears *in* the parameters of `SubtypeOf` of any other qualifiers. Otherwise, if a user do that, when building the qualifier hierarchy for the visitor, the constructor will try to find the subtype of the polymorphic qualifier (and it does not exists in the mapping), thus result into a NPE.
> Add test for polymorphic qualifiers in SubtypeOf

- dataflow/src/main/java/org/checkerframework/dataflow/cfg/CFGBuilder.java
Tree `variable` was already marked a few lines earlier.
The line above created the new `ExpressionTree variableUse`, so I assume that that tree should be marked as artificial.
> Mark correct tree as artificial

- framework/src/main/java/org/checkerframework/framework/type/visitor/AnnotatedTypeComparer.java
- framework/src/main/java/org/checkerframework/framework/type/visitor/AnnotatedTypeReplacer.java
- framework/tests/all-systems/Issue3128.java
@smillst This is a rather ugly work-around to the problem.
Alternatively, instead of the assert in `AnnotatedTypeComparer` we could return early, possibly solving the same problem for other subtypes of ATC.
Do you see a better solution? As this is a real crash, I would like to get a fix in for the release.
> Ignore wildcard type mismatches (Fixes #3128)

- framework/build.gradle
Without this change, running `./gradlew clean :framework:delombok` leads to the following type of warning output:
```bash
> Task :framework:delombok
[ant:delombok] /home/mernst/research/types/checker-framework-branch-master/framework/tests/returnsreceiverlombok/BuilderTest.java:6: error: package org.checkerframework.common.returnsreceiver.qual does not exist
[ant:delombok] import org.checkerframework.common.returnsreceiver.qual.*;
[ant:delombok] ^
[ant:delombok] /home/mernst/research/types/checker-framework-branch-master/framework/tests/returnsreceiverlombok/BuilderTest.java:31: error: cannot find symbol
[ant:delombok]     BuilderTest.@This BuilderTestBuilder wrapperX() {
[ant:delombok]                  ^
[ant:delombok]   symbol:   class This
[ant:delombok]   location: class …
```
> Address delombok "cannot find symbol" warnings

- framework/src/main/java/org/checkerframework/common/wholeprograminference/WholeProgramInferenceScenesStorage.java
@mernst noticed the `catch` block in the removed code that didn't do anything and asked me to investigate it. It turns out that the only time the `try` block was entered at all (in our tests) leads to that empty `catch` block, which eventually leads to the `return false` - meaning that the whole section of code isn't actually accomplishing anything of value. I don't know why it was originally written, but I think we should remove it.
> Remove code that doesn't do anything in WPIScenesStorage

- docs/manual/troubleshooting.tex
When setting up the system, I noticed an outdated command in the CF manual which didn't determine JAVA_HOME correctly for Ubuntu/Linux.
I updated the one-liner to be the same as in the [`bin-devel` build script](https://github.com/typetools/checker-framework/blob/master/checker/bin-devel/build.sh#L19). I verified that this works on Ubuntu 18.04+.
> Update JAVA_HOME export cmd in docs

- dataflow/manual/content.tex
- dataflow/src/main/java/org/checkerframework/dataflow/analysis/Analysis.java
- dataflow/src/main/java/org/checkerframework/dataflow/analysis/AnalysisResult.java
- dataflow/src/main/java/org/checkerframework/dataflow/analysis/ConditionalTransferResult.java
- dataflow/src/main/java/org/checkerframework/dataflow/analysis/RegularTransferResult.java
- dataflow/src/main/java/org/checkerframework/dataflow/analysis/TransferFunction.java
- dataflow/src/main/java/org/checkerframework/dataflow/analysis/TransferInput.java
- dataflow/src/main/java/org/checkerframework/dataflow/analysis/TransferResult.java
- dataflow/src/main/java/org/checkerframework/dataflow/cfg/AbstractCFGVisualizer.java
- dataflow/src/main/java/org/checkerframework/dataflow/cfg/CFGVisualizer.java
- dataflow/src/main/java/org/checkerframework/dataflow/cfg/DOTCFGVisualizer.java
- dataflow/src/main/java/org/checkerframework/dataflow/cfg/StringCFGVisualizer.java
Currently, we both use `A extends AbstractValue<A>` and `V extends AbstractValue<V>` in dataflow framework. This PR changes all the usages of `A` to `V`.
> Make type parameter names in dataflow framework consistent.

- framework/src/main/java/org/checkerframework/framework/type/TypeFromTypeTreeVisitor.java
It was easier to refactor the method than document its previous behavior.
> Refactor private method in TypeFromTreeVisitor

- framework-test/src/main/java/org/checkerframework/framework/test/TypecheckResult.java
It was undocumented and identical to fromCompilationResults()
Merge together with https://github.com/typetools/checker-framework-inference/pull/163
> Remove TypecheckResult.fromCompilationResultsExpectedDiagnostics()

- dataflow/src/main/java/org/checkerframework/dataflow/cfg/CFGVisualizeLauncher.java
Then it can be called from outside the package, e.g., an external test file. 
This also makes `generateStringOfCFG()` and `generateDOTofCFG()` consistant.
> Change generateStringOfCFG() from protect to public.

- dataflow/src/main/java/org/checkerframework/dataflow/cfg/AbstractCFGVisualizer.java
This PR makes the CFGVisualizer's generated CFG deterministic. Previously, the ordering of the blocks in DOT or String representation may be changed at each time.
> Make the CFGVisualizer's generated CFG deterministic.

- framework/src/main/java/org/checkerframework/framework/type/AnnotatedTypeCopier.java
This change is need for AnnotatedTypeCopierWithReplacement to behave correctly for primitives.
Similar to visitNull, we want the primitives to have the annotations to be replaced.
This PR also includes a small refactoring of the AnnotatedTypeCopier.
> Replace anno for primitives as well during replacer and refactor copier

- docs/developer/developer-manual.html
There seems to be an extra step in creating an Azure pipeline not in the developer manual. I added instructions for this step (I'm not sure exactly sure if they're correct or not).
> Improve Azure instructions in developer manual

- dataflow/src/main/java/org/checkerframework/dataflow/cfg/AbstractCFGVisualizer.java
Make the behavior of `visualizeBlockTransferInputBeforeHelper` and `visualizeBlockTransferInputAfterHelper` consistent.
> A follow-up of #3395: Remove the wrong escapeString

- framework/src/main/java/org/checkerframework/common/basetype/BaseTypeChecker.java
- framework/src/main/java/org/checkerframework/framework/source/SourceChecker.java
- framework/src/main/java/org/checkerframework/framework/type/AnnotatedTypeFactory.java
- javacutil/src/main/java/org/checkerframework/javacutil/TypeSystemError.java
It's like UseError, but indicates a mistake made by a type system writer.
> Add TypeSystemError exception.

- docs/developer/gsoc-ideas.html
Images are already available locally. This change will prevent unnecessary Internet access and associated privacy concerns. (Imported from Debian packaging)
> Remove external links to images

- framework/src/main/java/org/checkerframework/common/wholeprograminference/WholeProgramInferenceScenes.java
- framework/src/main/java/org/checkerframework/common/wholeprograminference/scenelib/ASceneWrapper.java
- framework/tests/whole-program-inference/non-annotated/ExpectedErrors.java
Fixes #3428.
The mistake was that we missed one of the callsites for `storage.getAClass` that needed to be updated in #2871.
Also fixed a typo in some javadoc.
> Fix unprintable class when param types are inferred from assignments using -Ainfer=stubs

- framework/src/main/java/org/checkerframework/common/wholeprograminference/WholeProgramInferenceScenes.java
- framework/tests/whole-program-inference/non-annotated/Tempvars.java
fixes #3442 for both -Ainfer=stubs and -Ainfer=jaifs
> Do not do inference on temporary variables in whole-program inference

- framework/src/main/java/org/checkerframework/common/wholeprograminference/SceneToStubWriter.java
- framework/tests/whole-program-inference/non-annotated/LocalClassTest.java
Fixes #3461 
Local classes can't be parsed by the stub file reader, so this prevents them from being written. Even before #3441, which introduced the crash in #3461, local classes caused problems with whole program inference.
> Prevent local classes from being written to stub files

- framework/src/main/java/org/checkerframework/common/accumulation/AccumulationTransfer.java
- framework/tests/accumulation/SimpleInference.java
For some reason, we didn't have a direct test for this - it was only tested in the original Object Construction Checker as part of the predicate tests. I discovered it while working on generic predicate support, but the issue is independent of predicates.
Without the change here, the checker issues a spurious error on line 22 of `SimpleInference.java`, because it fails to accumulate both `a` and `b`.
> Fix incorrect handling of non-chained accumulations in the generic accumulation checker

- checker/tests/signedness/Issue2483.java
#2483 was fixed in https://github.com/typetools/checker-framework/pull/2614/, but wasn't closed.
> Add test case for Issue 2383.

- framework/src/main/java/org/checkerframework/framework/type/AnnotatedTypeFactory.java
`-AmergeStubsWithSource` uses GLB when merging stubs with source. For most checkers, this is the right choice - we want the "strongest" type that's true of both the stub file and source.
Custom checkers, however, might want custom logic here (and I have one in mind that does, but I can't talk about it publicly). This PR makes it possible for a new checker to change that behavior (e.g. to LUB instead of GLB).
> Make mergeStubsIntoType protected instead of private

- dataflow/src/main/java/org/checkerframework/dataflow/cfg/DOTCFGVisualizer.java
As https://github.com/typetools/checker-framework/pull/3490#discussion_r459773537 mentioned, to handle the overloaded methods, we also add parameters to the output dot file's name.
If we have two methods: `test(String a, String b)` and `test(String a, String b, String c)` in class `Test`, now the output dot files are:
~~`Test::test(String a, String b)-Nullness.dot` and~~
~~`Test::test(String a, String b, String c)-Nullness.dot`.~~
`Test-test-String,String-Nullness.dot` and
`Test-test-String,String,String-Nullness.dot` and
> Add parameters to the output dot file's name.

- dataflow/src/main/java/org/checkerframework/dataflow/cfg/block/ExceptionBlockImpl.java
I have observed two runs of CFG construction that print differently.  Although the structure of the CFG is the same, the difference in printed output is a nuisance.
> Make CFG construction more deterministic

- dataflow/src/main/java/org/checkerframework/dataflow/cfg/block/ConditionalBlock.java
I don't see any Node in it.
If this change is not correct, then the documentation should be updated to say where the Node is and how to access it.
> Remove comment about Node in ConditionalBlock

- dataflow/src/main/java/org/checkerframework/dataflow/analysis/FlowExpressions.java
- framework/src/main/java/org/checkerframework/framework/util/FlowExpressionParseUtil.java
"debugToString" makes it sound (to me, at least) like a conversion is being performed between a "debug" and a "String".  Another benefit of the renaming is that "toStringDebug" puts the most important information -- "toString" -- first.
> Rename debugToString to toStringDebug

- framework/src/main/java/org/checkerframework/framework/type/GenericAnnotatedTypeFactory.java
Make the implementation of `GenericAnnotatedTypeFactory#getStoreAfter(Node)` match the implementations of `#getStoreAfter(Tree)`, `#getStoreBefore(Node)`, and `#getStoreBefore(Tree)`.
The Checker Framework doesn't have any calls to `#getStoreAfter(Node)`, so there isn't an easy way to add a test case for this.
@msridhar I think this fixes #3566.  (Or at least with this fix, the RuntimeException in  "repro-store-bug" is not hit...). Can you confirm that this fixes the whole issue?
> Correct GenericAnnotatedTypeFactory#getStoreAfter(Node)

- framework-test/src/main/java/org/checkerframework/framework/test/TestUtilities.java
- framework-test/src/main/java/org/checkerframework/framework/test/TypecheckExecutor.java
This change may fix the following test failure: https://dev.azure.com/mernst22/checker-framework/_build/results?buildId=4940&view=logs&j=11811b1c-d14b-5529-93a4-5f2e1e50e37a&t=c6036049-c59d-531d-b0de-bbcb93026718&l=782
> Don't err if directory is concurrently created by a different thread

- framework/src/main/java/org/checkerframework/common/wholeprograminference/SceneToStubWriter.java
This was uncovered by the change in #3599, which originally included this code and is required to test it. @smillst asked me to separate the logic here out, because it's conceptually unrelated to the change in #3599.
> Correct array ordering logic in -Ainfer=stubs

- dataflow/src/main/java/org/checkerframework/dataflow/cfg/CFGBuilder.java
On [this](https://github.com/typetools/checker-framework/blob/3057728a41b1dc1d53eaa2ffeb1bb1e9ec303e57/dataflow/src/main/java/org/checkerframework/dataflow/cfg/CFGBuilder.java#L1418) line, the `exceptions` field of the `NodeWithExceptionsHolder` class is iterated over to modify the `missingExceptionalEdges` variable, which should be deterministic.
This makes the collections used to initialize that field deterministic.
> Make NodeWithExceptionsHolder deterministic

- build.gradle
- checker/build.gradle
- framework/build.gradle
This puts the easier-to-read short name first, and permits better line breaks at call sites.
> Change order of arguments to createCheckTypeTask

- checker/jtreg/sortwarnings/ErrorOrders.out
- framework/src/main/java/org/checkerframework/framework/util/DefaultAnnotationFormatter.java
PR #2970 adds default values to all AnnotationMirrors which means the default value is printed in error messages.   For example,
```
required: @UnknownInitialization(java.lang.Object.class) @NonNull Object
```
This PR makes it so an annotation value is not printed if it is equal to the default value.
> Don't print default annotation values.

- docs/manual/constant-value-checker.tex
- docs/manual/creating-a-checker.tex
- docs/manual/external-tools.tex
- docs/manual/fenum-checker.tex
- docs/manual/introduction.tex
- docs/manual/subtyping-checker.tex
- docs/manual/units-checker.tex
Fixes https://github.com/typetools/checker-framework/issues/3630.
I wonder whether we should merge this pull request, or replace it by a pull request that recommends *not* using classpath and using processorpath instead.
> Improve documentation about processorpath

- dataflow/src/main/java/org/checkerframework/dataflow/cfg/CFGBuilder.java
The trick of returning the argument makes some code more concise, but it is
confusing since the method is primarily called for side effect, and it is
used inconsistently throughout the codebase.  Removing the return type
makes clients more uniform and explicit, if a bit more verbose.
> extendWithNode is called for side effect, so don't return a value

- framework/src/main/java/org/checkerframework/common/accumulation/AccumulationAnnotatedTypeFactory.java
Encountered while porting an existing checker to use `AccumulationChecker`, was a big pain to diagnose.
> Don't crash with an NPE if an accumulator doesn't have a default value

- framework/src/main/java/org/checkerframework/common/accumulation/AccumulationAnnotatedTypeFactory.java
- framework/tests/accumulation/SimplePolymorphic.java
Fixes a crash I encountered while porting a checker to use `AccumulationChecker`, because `isSubtype` assumed that `superAnno` was an accumulator when it reached the last set of checks in `isSubtype`. Also, I fixed a typo in the error message that that crash caused :)
Without this fix, you get a stacktrace like this:
```
1 unexpected diagnostic was found:
:-1: other: error: @org.checkerframework.framework.testchecker.testaccumulation.qual.PolyTestAccumulation isn't an accumulator annotation
; The Checker Framework crashed.  Please report the crash.
Compilation unit: tests/accumulation/SimplePolymorphic.java
Last visited tree at line 19 column 9:
@PolyTestAccumulation Object obj2 = obj;
Exception: java.lang.Throwable; java.lang.Throwable
at …
```
> Avoid crash in isSubtype in AccumulationChecker when supertype is polymorphic and subtype is accumulator

- checker/tests/nullness/flow/Issue3275.java
- dataflow/src/main/java/org/checkerframework/dataflow/util/NodeUtils.java
- framework/src/main/java/org/checkerframework/framework/flow/CFAbstractTransfer.java
This is an alternative to #3698.  Fixes #3275.
> Flip stores when comparing to a constant boolean.

- .dependabot/config.yml
- docs/developer/release/README-release-process.html
See discussion on https://github.com/typetools/checker-framework/pull/3723.
> Make dependabot ignore AWS SDK updates

- .dependabot/config.yml
Fix #3730, which seems to have been caused by having the wrong version of dependabot enabled for the config script that we added. This change uses the old config script format (v1) rather than the newer v2, since we're apparently running v1.
Background: funnily enough, I wasn't able to figure out which version of dependabot we were using, so I guessed in #3724 that it was the newer version. Apparently dependabot doesn't update itself!
> Use dependabot v1 config instead of v2

- framework/src/main/java/org/checkerframework/framework/util/element/TypeVarUseApplier.java
`typeVariable.replaceAnnotation(annotation);` does exactly what the old code did.
> Annotation from elements for type variable upper bound intersections

- framework/src/main/java/org/checkerframework/framework/flow/CFTreeBuilder.java
There are no code changes.  I just removed unnecessary  `{}` and add imports for inner class such as `AnnotatedTypeMirror.AnnotatedWildcardType`.
> Make CFTreeBuilder easier to read.

- checker/src/main/java/org/checkerframework/checker/nullness/NullnessTransfer.java
- framework/src/main/java/org/checkerframework/common/basetype/BaseTypeVisitor.java
- framework/src/main/java/org/checkerframework/common/util/report/ReportVisitor.java
- framework/src/main/java/org/checkerframework/framework/source/SourceChecker.java
- framework/tests/all-systems/EqualityTests.java
- framework/tests/all-systems/StateMatch.java
An alternative to this change is to document the feature, use mixed-case throughout the examples, and encourage it for users.
> Remove undocumented feature of lowercasing user-written SuppressWarnings strings

- checker/src/main/java/org/checkerframework/checker/fenum/FenumAnnotatedTypeFactory.java
- checker/src/main/java/org/checkerframework/checker/formatter/FormatterAnnotatedTypeFactory.java
- checker/src/main/java/org/checkerframework/checker/i18nformatter/I18nFormatterAnnotatedTypeFactory.java
- checker/src/main/java/org/checkerframework/checker/lock/LockAnnotatedTypeFactory.java
- checker/src/main/java/org/checkerframework/checker/nullness/KeyForAnnotatedTypeFactory.java
- checker/src/main/java/org/checkerframework/checker/nullness/NullnessAnnotatedTypeFactory.java
- checker/src/main/java/org/checkerframework/checker/nullness/NullnessTransfer.java
- checker/src/main/java/org/checkerframework/checker/regex/RegexAnnotatedTypeFactory.java
- checker/src/main/java/org/checkerframework/checker/units/UnitsAnnotatedTypeFactory.java
- framework/src/main/java/org/checkerframework/framework/type/MostlyNoElementQualifierHierarchy.java
- framework/src/test/java/org/checkerframework/framework/testchecker/flowexpression/FlowExpressionAnnotatedTypeFactory.java
- framework/src/test/java/org/checkerframework/framework/testchecker/util/FlowTestAnnotatedTypeFactory.java
- framework/src/test/java/org/checkerframework/framework/testchecker/wholeprograminference/WholeProgramInferenceTestAnnotatedTypeFactory.java
This prevents clients from having to recompute it, but passes it redundantly to clients who don't care.
It is moitvated by #3847.
> Add argument to MostlyNoElementQualifierHierarchy operations

- checker/src/test/java/org/checkerframework/checker/test/junit/StubParserTest.java
- checker/tests/stubparser/TypeParamWithInner.astub
- checker/tests/stubparser/TypeParamWithInner.java
- framework/src/main/java/org/checkerframework/framework/stub/StubParser.java
The `StubParser` class keeps track of the type variables in scope for the elements it's processing. When processing a class, it should add the class's type parameters on entry and remove them when leaving. The current implementation clears *all* type parameters when it finishes processing a class. This means after processing an inner class, all type parameters are cleared, including those of the enclosing class.
> Don't clear type parameters in StubParser

- checker/src/main/java/org/checkerframework/checker/initialization/InitializationAnnotatedTypeFactory.java
- checker/src/main/java/org/checkerframework/checker/nullness/NullnessAnnotatedTypeFactory.java
This is important for whole-program inference, which uses GLB to combine stubs and source code.
The code for new method `greatestLowerBoundInitialization` is very similar to that for existing method `leastUpperBoundInitialization`.
> Define glb more precisely for the Nullness Checker

- checker/src/main/java/org/checkerframework/checker/index/OffsetDependentTypesHelper.java
- checker/src/main/java/org/checkerframework/checker/lock/LockAnnotatedTypeFactory.java
- framework/src/main/java/org/checkerframework/common/basetype/BaseTypeVisitor.java
- framework/src/main/java/org/checkerframework/common/wholeprograminference/WholeProgramInferenceScenes.java
- framework/src/main/java/org/checkerframework/framework/flow/CFAbstractTransfer.java
- framework/src/main/java/org/checkerframework/framework/util/dependenttypes/DependentTypesHelper.java
`updateFromReturn` transfers a type from a return expression to a method return type.  References to local variables make sense within the method body but not in the method signature.
Similar standardization might be necessary elsewhere.
Reinstate Javadoc checking after merging.
> In `updateFromReturn`, remove Java expressions that contain local variables

- javacutil/src/main/java/org/checkerframework/javacutil/ElementUtils.java
This change is motivated by the `StubTypes#declAnnosFromStubFiles`, which is a map of type `Map<String, Set<AnnotationMirror>>`. The keys are values computed by `ElementUitls#getQualifiedName`. When a stub file contains a declaration annotation on a method parameter, and also another (unannotated) method with a parameter of the same name, this map would confuse the two and return the declaration annotation if either parameter was queried. This change fixes that problem.
I'm not sure how to test this within the CF itself, because I don't know of any checkers that use declaration annotations in stub files other than the MustCall Checker. The problem came up in the context described below, and I've confirmed that this change fixes it.
Consider the following stub file, which is reduced form …
> Make ElementUtils#getQualifiedName unique for method parameters

- dataflow/src/main/java/org/checkerframework/dataflow/cfg/node/ObjectCreationNode.java
It seems these contexts should also be present when expressions are passed as a parameter to a constructor call (in addition to normal method invocations).  They would be useful for a checker we are working on.
@smillst I'm not sure how to write a test for this.  Maybe these additional contexts could be relevant to type inference?
> Add AssignmentContexts for parameters of constructor calls

- framework/src/main/java/org/checkerframework/framework/type/AnnotatedTypeMirror.java
- framework/src/main/java/org/checkerframework/framework/type/BoundsInitializer.java
These changes should have been in https://github.com/typetools/checker-framework/pull/3790.
> AnnotatedIntersectionTypes can have TypeVariable bounds

- checker/build.gradle
- framework/build.gradle
Also use standard (ISO 8601) formatting for date.
> Put dependencies in canonical order

- checker/tests/nullness/Issue3929.java
- framework/src/main/java/org/checkerframework/framework/flow/CFTreeBuilder.java
- framework/tests/all-systems/Issue3929.java
> When building a type tree, don't recur infinitely on wildcards

- checker/src/main/java/org/checkerframework/checker/nullness/NullnessAnnotatedTypeFactory.java
- checker/tests/nullness/Issue3935.java
- framework/src/main/java/org/checkerframework/common/basetype/BaseTypeVisitor.java
> Ignore declaration annotations when issuing nullness.on.primitive warning.

- changelog.txt
- checker/src/main/java/org/checkerframework/checker/calledmethods/CalledMethodsChecker.java
- checker/src/test/java/org/checkerframework/checker/test/junit/CalledMethodsDisableReturnsReceiverTest.java
- checker/tests/calledmethods-disablereturnsreceiver/SimpleFluentInference.java
> allow users to run the Called Methods Checker without the Returns Receiver Checker, if desired

- javacutil/src/main/java/org/checkerframework/javacutil/TypeAnnotationUtils.java
Fixes #3956.
To resolve the error report, it is necessary to release plume-util version 1.3.0 and make the Checker Framework use it.
> Prevent duplicate annotations in .class files; fixes #3956

- checker/tests/nullness/TryWithResources.java
- dataflow/src/main/java/org/checkerframework/dataflow/cfg/builder/CFGTranslationPhaseOne.java
Summary:
This fix is for Phase 1 of the translation.
Consider the following block:
```
try (ZipFile f = openZipFile()) {
return true;
} catch (IOException e) {
// This node is missing in CFG
log(TAG, "This `log` node is missing in CFG of the method");
}
```
where
```
private static ZipFile openZipFile() throws IOException {...}
```
This gets translated into the following CFG.
Note absence of `log(TAG, ...)`!
```
2 -> 3 EACH_TO_EACH
3 -> 4 EACH_TO_EACH
4 -> 5 EACH_TO_EACH
4 -> 1 java.io.IOException
4 -> 1 Throwable
5 -> 0 EACH_TO_EACH
2:
Process order: 1
<entry>
3:
Process order: 2
marker (start of try statement #0)   [ Marker ]
f   [ VariableDeclaration ]
Test   [ ClassName ]
Test.openZipFile   [ MethodAccess ]
4:
Process order: 3
Test.openZipFile()   [ MethodInvocation ]
5:
Process …
```
> Fix CFG builder loosing catch blocks in try-with-resource

- framework/src/main/java/org/checkerframework/framework/stub/JavaStubifier.java
Fixes a crash that I get when running `./gradlew jtregJdk11Tests` on my local machine.
> Use Java 11 for collecting Java files

- azure-pipelines.yml
This change reduces latency by giving less chance for later jobs to get their first jobs into the queue before this one's last jobs get in the queue.
> Remove the canary_jobs abstraction

- framework/src/main/java/org/checkerframework/common/basetype/BaseTypeVisitor.java
- framework/tests/all-systems/Issue3826.java
(This should be reverted when #979 is fixed.
Fixes #3826.
> Ignore crashes caused by incorrectly inferred type arguments.

- checker/src/main/java/org/checkerframework/checker/initialization/InitializationVisitor.java
- checker/tests/nullness/Issue3631.java
> Report contracts.precondition.not.satisfied when JavaExpression is unknown

- checker/bin/wpi-many.sh
- checker/bin/wpi.sh
Resolves two problems with the wpi scripts' user-facing output:
1. use of `pushd` and `popd` rather than `cd` prints directory names
2. the script to compute `results-available.txt` was broken, creating garbage output about missing files and leading that file to always be empty.
> Miscellaneous minor fixes to wpi-many.sh

- framework/src/main/java/org/checkerframework/common/wholeprograminference/SceneToStubWriter.java
The expressions `packagePart(o1)` and `packagePart(o2)` in the modified code can be `null`, which causes a `NullPointerException` when the list being sorted has multiple elements. As far as I can tell, everywhere this code is called in the test suite, the list has at most one element, so the comparison function is never called and no `NullPointerException` is thrown. I'm not sure if constructing such an example is possible, but I did encounter when working with a buggy version of the framework. This code didn't end up being the problem, but it should probably be fixed regardless.
> Handle null Strings in comparison

- build.gradle
- checker/bin/wpi.sh
- checker/build.gradle
Also fixes a minor bug in `wpi.sh`, which should have been providing the JDK version to DLJC directly via an argument. DLJC already had this functionality, but `wpi.sh` wasn't using it for some reason.
Related, I fixed how DLJC handles `-source`, `-target`, and `--release` flags; it now has different behavior depending on the value of its `--jdkVersion` argument:
* on Java 8, it uses `-source` and `-target`
* on Java 11, it always uses `--release`, even when the code is Java 8 (i.e. it uses `--release 8`).
The proximate cause of the failing WPI many tests on Java 8 JDKs was that DLJC was trying to use `--release 8` whenever the source/target level was 8, even on non-Java 11 JVMs. See https://github.com/kelloggm/do-like-javac/commit/8873d6f2987fab12723dc6ddce4b1e86d4460057.
> Re-enable WPI-many tests on JDK 8, and strengthen oracle for WPI-many tests generally

- checker/build.gradle
This should fix the failing tests on master.
I also added comments with explanations for which lines are ignored in `typecheck.out` files.
> Handle warnings caused by empty directories in WPI tests

- checker/tests/nullness/TryCatch.java
- dataflow/manual/content.tex
- dataflow/src/main/java/org/checkerframework/dataflow/cfg/builder/CFGTranslationPhaseOne.java
Summary:
Absence of exceptional edges leads to missing CFG nodes in a code like
this:
```
try {
var cls = MyClass.class;
...
} catch (NoClassDefFoundError e) {
...
}
```
According to JLS evaluating a class literal can fail in a number of
ways which are handled by this patch.
Test plan:
Added a test case under nullness to check if the types inside `catch`
get refined.
> [dataflow] Class literal nodes should have exceptional edges

- build.gradle
- framework/build.gradle
We rename all third party dependencies so they do not conflict with other versions on the classpath.
> Relocate asm dependency.

- framework/src/main/java/org/checkerframework/framework/util/JavaExpressionParseUtil.java
- javacutil/src/main/java/org/checkerframework/javacutil/Resolver.java
Before this change, fields were treated differently depending on whether
useLocalScope was true or false.
> Use one codepath for fields

- framework/src/main/java/org/checkerframework/framework/util/dependenttypes/DependentTypesHelper.java
Scanners have HashMaps that can use a lot of memory, so it's better to use fields rather than creating a new object for each use.   #3851  shows how a scanner caused problems else where.  (https://github.com/typetools/checker-framework/issues/4252 is a new issue to document this problem and find more scanners to move to fields.)
> Add fields for Scanners in DependentTypesHelper

- framework/src/main/java/org/checkerframework/common/wholeprograminference/WholeProgramInferenceScenes.java
- framework/src/main/java/org/checkerframework/framework/util/dependenttypes/DependentTypesHelper.java
Removed methods that were only called once or called with `removeErroneousExpressions` = `false`.
I also removed `standardizeForMethodSignature`.  We might want this method again in the future, but currently it's only called in two places and doesn't reduce code duplication.  (It's javadoc was also wrong; it wasn't called for contracts.)
> Add a delocalize method to DependentTypesHelper.

- docs/manual/advanced-features.tex
- framework/src/main/java/org/checkerframework/framework/util/JavaExpressionParseUtil.java
- framework/tests/flow2/flowexpression-scope/Class2.java
- framework/tests/flow2/flowexpression-scope/Issue862.java
- javacutil/src/main/java/org/checkerframework/javacutil/Resolver.java
See manual change for explantation. I also moved the code that parses identifiers to fields to a new method, so you'll see those changes, too.
Fixes #862. 
Merge with https://github.com/codespecs/daikon/pull/316
> JavaExpressionParseUtil: Parse unqualified class names correctly.

- checker/src/main/java/org/checkerframework/checker/formatter/FormatterTreeUtil.java
- checker/src/main/java/org/checkerframework/checker/nullness/CollectionToArrayHeuristics.java
- checker/src/main/java/org/checkerframework/checker/nullness/KeyForPropagationTreeAnnotator.java
- checker/src/main/java/org/checkerframework/checker/nullness/NullnessAnnotatedTypeFactory.java
- checker/src/main/java/org/checkerframework/checker/nullness/NullnessVisitor.java
- checker/src/main/java/org/checkerframework/checker/nullness/SystemGetPropertyHandler.java
- checker/src/main/java/org/checkerframework/checker/regex/RegexAnnotatedTypeFactory.java
- checker/src/main/java/org/checkerframework/checker/regex/RegexVisitor.java
- checker/src/main/java/org/checkerframework/checker/signature/SignatureAnnotatedTypeFactory.java
- checker/tests/index/ListRemove.java
- framework/src/main/java/org/checkerframework/common/basetype/BaseTypeVisitor.java
An advantage is that the code is shorter.
A disadvantage may be that automated refactoring tools might not work as well.
> Use string literals instead of method calls

- dataflow/src/main/java/org/checkerframework/dataflow/analysis/ForwardAnalysisImpl.java
Caching is added for the `EXCEPTION_BLOCK` case in the same manner as it is used for the `REGULAR_BLOCK` case.  For a checker we are building, this seems to yield a significant speedup.
> Add caching for exception block case in ForwardAnalysisImpl

- checker/tests/nullness/MethodOverloadingContractsKeyFor.java
- javacutil/src/main/java/org/checkerframework/javacutil/TreeUtils.java
Here's a code snippet taken from the test.
```
String name(ClassA classA) {...}
String name(ClassB classB) {...}
@EnsuresKeyFor(value = "name(#1)", map = "map")
void put(ClassA classA) {...}
void test(ClassB classB) {
put(classB);
}
```
At the call to `put`, `name(classB)` should refer to `name(ClassA classA)` not `name(ClassB classB)`
The test is currently fails and is therefore skipped, but it will be fixed once string expression are not parsed and viewpoint-adapted at the same time.  ~~I also add new methods to TreeUtils that will be needed for the Nullness Checker to type check the dataflow subproject.~~
> Add test for overloaded method in contract.

- docs/manual/troubleshooting.tex
Fixes https://github.com/typetools/checker-framework/issues/4358
> Update Mac OS prerequisites in 'Building from source'

- checker/tests/nullness/ParameterExpression.java
- framework/src/main/java/org/checkerframework/common/basetype/BaseTypeVisitor.java
- framework/src/main/java/org/checkerframework/common/basetype/messages.properties
When a parameter is referenced anywhere in a contract expression.
> Issue expression.unparsable.type.invalid rather than flowexpr.parse

- checker/src/main/java/org/checkerframework/checker/index/upperbound/OffsetEquation.java
- checker/src/main/java/org/checkerframework/checker/index/upperbound/UBQualifier.java
This pull request ended up being much larger than I anticipated to make `removeOffset` more efficient.
A question brought up by these changes is how OffsetEquation objects are treated by the implementation.  Are they ever changed after being put in a `UBQualifier`, or is it safe to share them between `UBQualifier`s?
> Make `removeOffset` more efficient: don't convert to and from sequences

- framework/src/main/java/org/checkerframework/framework/flow/CFAbstractStore.java
This change is trivial, but maybe it's a touch cheaper and simpler not to build the entry set.
> Tweak which set is used

- checker/tests/nullness/Issue4381.java
- dataflow/src/main/java/org/checkerframework/dataflow/cfg/builder/TryCatchFrame.java
(This is an alternative fix to the one in #4459.)
`UnionClassType` extends `ClassType` which implements `DeclaredType`.  `UnionClassType` also implements `UnionType`.  So ` expr instanceof DeclaredType` is true if `expr` is an `UnionClassType` object even though it is actually a union type.
Fixes #4381.
> Types should be compared using `getKind()` 

- framework/src/main/java/org/checkerframework/framework/stub/AnnotationFileParser.java
- framework/src/main/java/org/checkerframework/framework/type/AnnotatedTypeFactory.java
- framework/src/main/java/org/checkerframework/framework/type/AnnotatedTypeReplacer.java
- framework/src/main/java/org/checkerframework/framework/type/TypeFromExpressionVisitor.java
- framework/src/main/java/org/checkerframework/framework/type/visitor/AnnotatedTypeCombiner.java
See https://github.com/typetools/checker-framework/issues/4252 for why AnnotatedTypeScanners should be in fields.
> Keep 2 subclasses of AnnotatedTypeScanners in fields.

- build.gradle
When I run `./gradlew wholeProgramInferenceTestCheckerAjavaTests` and then `./gradlew reformat`, it attempts to format the generated ajava files, filling the terminal with messages about attempting to format a non-Java file. This is because it attempts to format all files ending in `java`, which includes ajava files. It should instead collect files ending with `.java`.
> Don't format ajava files

- checker/bin/wpi.sh
This is necessary if, for example, the argument to `--extraJavacArgs` contains a space
> Quote arguments

- framework/src/main/java/org/checkerframework/framework/type/GenericAnnotatedTypeFactory.java
Is this method worth defining?  We have no clients of it now, and it is inefficient.  But it performs a well-defined and useful purpose.
> Define `getAnnotationsFromJavaExpression()`

- framework/src/main/java/org/checkerframework/common/wholeprograminference/WholeProgramInferenceImplementation.java
I can't find a test case for which the tree is null, but removing the code will help us find one.
> Remove test for null tree

- docs/CHANGELOG.md
- docs/manual/annotating-libraries.tex
- framework/src/main/java/org/checkerframework/framework/stub/StubGenerator.java
StubGenerator only works with JDK 8.
The manual section is only commented out, and the code is retained, because one day we might reimplement StubGenerator to work with Java 9+.
> Remove StubGenerator section from manual

- framework/src/main/java/org/checkerframework/framework/stub/AnnotationFileParser.java
Maybe private members should always be ignored, not just for the JDK.  https://github.com/typetools/checker-framework/pull/4592 does that.
> Abstract out method `isPrivateInJdk`

- framework/src/main/java/org/checkerframework/framework/stub/AnnotationFileElementTypes.java
- framework/src/main/java/org/checkerframework/framework/type/AnnotatedTypeFactory.java
This feature was never documented.
> Don't read stubs from environment variable or system property

- dataflow/build.gradle
- docs/CHANGELOG.md
Except for org.checkerframework.dataflow.qual.  Those classes are compared to qualifiers written in source code that may not have been shaded.
This includes changes from #4642, merge that one first.
> In dataflow-shaded artifact,  Shade all org.checkerframework packages.

- checker/bin/wpi-many.sh
- docs/manual/inference.tex
We didn't test it, it adds complexity, its implementation was buggy, and as far as we're aware no-one is using it.
See also the comment chain here: https://github.com/typetools/checker-framework/pull/4662#discussion_r632745038
> remove the -u option from wpi-many.sh

- checker/bin/wpi-many.sh
- checker/bin/wpi.sh
These minor fixes are required for do-like-javac's CI jobs to succeed: https://github.com/kelloggm/do-like-javac/pull/40. I also added a few bits of debugging info, and cleaned up the failure state when no projects succeed.
> Small fixes to wpi-many.sh

- docs/manual/inference.tex
…thon 2.7, thanks to https://github.com/kelloggm/do-like-javac/pull/22
> update WPI docs to note that DLJC now requires python3

- checker/bin/wpi.sh
Should be merged after https://github.com/kelloggm/do-like-javac/pull/44 on which it depends.
Mike, I mentioned to you earlier that I had a lead on the failures in do-like-javac's CI. This PR and https://github.com/kelloggm/do-like-javac/pull/44 are what came of that lead; in the end, the file that this PR prints in that case contained a crash from the GUI Effect Checker, which isn't WPI related.
> add additional debug logging in wpi.sh

- docs/manual/advanced-features.tex
- docs/manual/introduction.tex
The Must Call Checker was already referenced in `introduction.tex`, but wasn't mentioned in the corresponding list in `advanced-features.tex`. Both lists were missing the Called Methods Checker.
> Add calledmethods and mustcall entries to appropriate lists in manual

- build.gradle
- checker/build.gradle
- checker/resources
The gitProperties needs to be in the checker subproject so that its task `generateGitProperties` is added as a dependency to `checker:classes`,  which is a dependency of `checker:assemble`.
Fixes #4646.
> Move gitProperties to checker project.

- .gitignore
- dataflow/build.gradle
Running `./gradlew :dataflow:liveVariableTest` from a clean checkout does not work; this pull request fixes that.
> Fix dependencies and `.gitignore` for dataflow tests

- framework/src/main/java/org/checkerframework/framework/type/GenericAnnotatedTypeFactory.java
Also updates the documentation. At all call-sites, this method was already treated as if it returned `@Nullable Value` rather than `Value`, because flow might not have actually computed a value. 
The NPE that this change avoids is that `flowResult` is `null` even if `analysis.isRunning()` returns false, in the case where the analysis has not yet started. Previously, this code appears to have assumed that the analysis has already started (so the only reason that `isRunning()` could return false would be because the analysis had finished). That assumption wasn't documented.
I believe that the change that I made here is consistent with the way the method is documented and used, but I'm not 100% sure. An alternative solution would be to change this method's documentation to indicate that it …
> Avoid NPE when reading stub/ajava files in GenericAnnotatedTypeFactory#getInferredValue

- build.gradle
- checker/bin-devel/build.sh
This is a replacement for https://github.com/typetools/checker-framework/pull/4735 with a renamed branch to match the branch in stubparser, as requested -- apologies for getting it wrong first time round.
> Update to StubParser 3.22.1 (2nd attempt)

- framework/src/main/java/org/checkerframework/framework/stub/AnnotationFileParser.java
This problem was discovered when DLJC's CI failed in [this PR](https://github.com/kelloggm/do-like-javac/pull/49), when we tried to remove the `-AmergeStubsWithSource` option from WPI after switching WPI to use `.ajava` files exclusively. This PR must be merged before that one, and only if that one's tests are passing.
> the absence of -AmergeStubsWithSource should not impact the results of parsing Ajava files, even when parsing them AS stub files

- dataflow/src/main/java/org/checkerframework/dataflow/cfg/builder/CFGTranslationPhaseOne.java
The call to `TreePath.getPath()` was showing up as taking measurable time in some NullAway profiles.  This change should avoid it.
> Improve performance of CFGTranslationPhaseOne.visitReturn

- framework/src/main/java/org/checkerframework/framework/stub/AnnotationFileElementTypes.java
This method is only called when `receiverType` is nonnull.  So, therefore the method must have a receiver.
> In getFakeOverride, remove code that isn't needed.

- docs/manual/inference.tex
- docs/manual/manual.bbl
Also clarify a point in the preceding paragraph.
The out-of-date documentation that this new paragraph replaces was removed in https://github.com/typetools/checker-framework/pull/4764.
> Re-add corrected version of paragraph on how to annotate target projects of the wpi-many.sh script

- checker/bin/wpi-many.sh
- checker/build.gradle
Before, all that was checked was:
* one or more `*-typecheck.out` files are produced, and
* each such file contains no unexpected errors.
This test is incomplete, because if the first test runs and succeeds then the others might or might not run at all. In fact, such an error was introduced: at some point, `wpi.sh` started consuming `stdin` unexpectedly, and we didn't notice. This PR:
* corrects the test, so that it checks that the number of `*-typecheck.out` files matches the number of lines in the input file, and
* fixes the bug in `wpi-many.sh` that permitted `wpi.sh` to consume the input file
> wpiManyTest should require that the expected number of *-typecheck.out files are produced

- checker/tests/wpi-many/testin.txt
when this branch is pulled into #4677, I expect the wpi-many tests to pass
> use updated versions of wpi-many test repos that should build on Java 16

- checker/src/main/java/org/checkerframework/checker/resourceleak/MustCallConsistencyAnalyzer.java
- checker/tests/resourceleak/Issue4815.java
This fixes the crash reported in #4815. I think it would be best not to report an error at all, but the Called Methods store doesn't have any information about `object` when it goes out of scope. I think that's a separate problem.
> Resource Leak Checker should not crash when checking the obligations of type variables

- checker-qual/src/main/java/org/checkerframework/checker/nullness/qual/RequiresNonNull.java
- checker/tests/nullness/RepeatedRequiresNonNull.java
This isn't strictly necessary (since `@RequiresNonNull` can already take multiple arguments), but it makes the annotation more consistent with `@RequiresQualifier`, which does permit both multiple arguments and multiple annotations per declaration.
This PR will be useful if we start using `-Ainfer` with the Nullness Checker, because right now it emits each precondition as its own annotation (which works with `@RequiresQualifier`, but would not work with `@RequiresNonNull` without this PR).
I considered adding a special test case for `-Ainfer`'s interaction with this PR, but decided that was probably not necessary. If you think it is, I can write one (or you can).
> Make @RequiresNonNull repeatable

- docs/manual/troubleshooting.tex
The conflict no longer exists as of NullAway 0.9.2, which was released today.
> Update manual's discussion of conflict with NullAway

- checker/tests/nullness/java-unsound/Figure3.java
- checker/tests/nullness/java-unsound/Figure3NC.java
- framework/src/main/java/org/checkerframework/framework/type/TypeFromExpressionVisitor.java
- framework/tests/all-systems/Issue4829.java
> The type of a method invocation is the return type after capture conversion.

- checker/src/main/java/org/checkerframework/checker/resourceleak/MustCallConsistencyAnalyzer.java
- checker/tests/resourceleak/MultipleMethodParamsMustCallAliasTest.java
Fixes [#4785](https://github.com/typetools/checker-framework/issues/4785).
In this PR, methods and constructors are allowed to have Multiple @MustCallAlias arguments like:
`public @MustCallAlias SequenceInputStream(@MustCallAlias InputStream s1, @MustCallAlias InputStream s2) {...}`
If a call has @MustCallAlias annotation, then for each argument passed in the @MustCallAlias position, it creates a set containing the argument and it's resource aliases and add it to the set of obligations. Consider the following example:
`SequenceInputStream s3 = new SequenceInputStream(s1, s2)`
It creates two sets {s1, s3} and {s2, s3}, and then adds them to the set of obligations.
> Allow for multiple method parameters to be @MustCallAlias in Resource Leak Checker; fixes #4785

- framework/src/main/java/org/checkerframework/framework/stub/AnnotationFileElementTypes.java
- framework/src/main/java/org/checkerframework/framework/type/AnnotatedTypeFactory.java
Co-authored-by: Neil Brown <neil@twistedsquare.com>
> Make the return type of `getFakeOverride()` more specific

- framework/src/main/java/org/checkerframework/framework/type/AnnotatedTypeFactory.java
- framework/src/main/java/org/checkerframework/framework/type/SupertypeFinder.java
- framework/tests/all-systems/Issue4849.java
> Initializes all fields of newly created ATM before substituting type vars.

- dataflow/src/main/java/org/checkerframework/dataflow/analysis/BackwardAnalysisImpl.java
- dataflow/tests/live-variable/Expected.txt
- dataflow/tests/live-variable/Test.java
> Fix handling of exception edges in backward analysis

- checker/tests/nullness/Issue4853Nullness.java
- framework/src/main/java/org/checkerframework/framework/type/SupertypeFinder.java
- framework/tests/all-systems/Issue4853.java
> Substitute type parameters from super types of enclosing classes.

- checker/src/main/java/org/checkerframework/checker/calledmethods/CalledMethodsAnalysis.java
- checker/src/main/java/org/checkerframework/checker/calledmethods/CalledMethodsAnnotatedTypeFactory.java
- checker/src/main/java/org/checkerframework/checker/calledmethods/CalledMethodsTransfer.java
- checker/src/main/java/org/checkerframework/checker/resourceleak/ResourceLeakTransfer.java
- checker/tests/calledmethods/EnsuresCalledMethodsIfTest.java
- checker/tests/calledmethods/Postconditions.java
- checker/tests/resourceleak/MultipleMethodParamsMustCallAliasTest.java
- dataflow/src/main/java/org/checkerframework/dataflow/analysis/AbstractAnalysis.java
- dataflow/src/main/java/org/checkerframework/dataflow/analysis/BackwardAnalysisImpl.java
- dataflow/src/main/java/org/checkerframework/dataflow/analysis/ForwardAnalysisImpl.java
Fixes #4843
The Called Methods Checker assumes that the checked code is free of NullPointerExceptions (this property should be verified by the Nullness Checker).  This PR enhances the Called Methods Checker's type inference to ignore control flow due to NullPointerExceptions, enabling it to verify more code.  See https://github.com/typetools/checker-framework/issues/4843#issuecomment-889263475 for more context.
The change is implemented by enhancing the dataflow framework to allow for ignoring exceptional control flow for particular exception types.
We may want to ignore more exception types in the future; we can add that in a follow-up PR.
> Ignore control flow due to NullPointerExceptions in Called Methods Checker

- framework/src/main/java/org/checkerframework/framework/type/AnnotatedTypeFactory.java
- framework/tests/all-systems/Issue4852.java
> Correct capture type variable method.

- checker/src/main/java/org/checkerframework/checker/resourceleak/MustCallConsistencyAnalyzer.java
- checker/src/main/java/org/checkerframework/checker/resourceleak/messages.properties
This PR adds the name of the method to which the error applies to the error text for the `reset.not.owning`, `missing.creates.mustcall.for`, and `incompatible.creates.mustcall.for` errors.
This was based on an old suggestion from Mike when he was double-checking my work on Zookeeper that's been sitting on my todo list since.
> Improve error message text for the RLC

- framework/src/main/java/org/checkerframework/framework/type/AnnotatedTypeMirror.java
This pull request checks for this.
> If a declared type is not a uses, then its type arguments must be type variables.

- docs/CHANGELOG.md
- framework/src/main/java/org/checkerframework/framework/type/AnnotatedTypeFactory.java
This method was only used by the Quals Framework and should have been removed then.
> Removed `AnnotatedTypeFactory#postTypeVarSubstitution`

- checker/src/main/java/org/checkerframework/checker/mustcall/MustCallAnnotatedTypeFactory.java
- checker/src/main/java/org/checkerframework/checker/resourceleak/MustCallConsistencyAnalyzer.java
- checker/tests/resourceleak/BibtexCleanReport.java
- checker/tests/resourceleak/TryWithResourcesFP.java
- checker/tests/resourceleak/TryWithResourcesMultiResources.java
RLC reported a false positive for this [line](https://github.com/kelloggm/wpi-many-tests-bibtex-clean/blob/703c0190ab7d7436a5be6e160667f194da44fdee/src/main/java/org/plumelib/bibtex/BibtexClean.java#L60-L61). That was because assignments to resource variables are handled in Must Call Checker which doesn't have any information about resource aliases. This PR removes the set of rhs obligations if lhs is a resource variable and must call type of rhs only contains `close()` method.
Reported error:
`try (PrintWriter out = new PrintWriter(UtilPlume.bufferedFileWriter(outFile.toString()));                                                                       
The type of object is: java.io.BufferedWriter.
Reason for going out of scope: possible exceptional exit due to new EntryReader(filename) …
> Fix false positive in Resource Leak Checker related to try-with-resources

- checker/src/main/java/org/checkerframework/checker/index/upperbound/UpperBoundTransfer.java
- dataflow/src/main/java/org/checkerframework/dataflow/cfg/builder/CFGTranslationPhaseOne.java
- dataflow/src/main/java/org/checkerframework/dataflow/cfg/node/CaseNode.java
- framework/src/main/java/org/checkerframework/framework/flow/CFAbstractTransfer.java
Previously, this expression was referred to as the "switch expression", but now "switch expression" are expressions that are switches.  So, use the newer term from [the JLS "selector expression"](https://docs.oracle.com/javase/specs/jls/se17/html/jls-14.html#jls-14.11).
For example:
```
switch (selectorExpression) { ... }
```
I also moved the code that builds the selector expression node(s) to its own method and added documentation.
> Use the  term "selector expression".

- framework/src/main/java/org/checkerframework/framework/util/CheckerMain.java
> CheckerMain: don't crash on nonexistent directories

- framework/src/main/java/org/checkerframework/common/basetype/BaseTypeVisitor.java
- framework/src/main/java/org/checkerframework/framework/ajava/DefaultJointVisitor.java
- framework/src/main/java/org/checkerframework/framework/ajava/ExpectedTreesVisitor.java
- framework/src/main/java/org/checkerframework/framework/ajava/JointJavacJavaParserVisitor.java
- framework/src/main/java/org/checkerframework/framework/ajava/JointVisitorWithDefaultAction.java
- framework/src/main/java/org/checkerframework/framework/ajava/TreeScannerWithDefaults.java
- javacutil/src/main/java/org/checkerframework/javacutil/TreeUtils.java
JavaParsers crashes on some yields and also parses some to objects other than YieldStmts. ( javaparser/javaparser#3364)
Fixes the last bullet point in #4977.
> JointJavacJavaParserVisitor now handles switch expressions 

- docs/developer/release/README-release-process.html
An alternative to this pull request is to change Randoop's `build.gradle` file so that it always uses the latest version of the Checker Framework.  Although this means that a Randoop build might suddenly start failing due to a change in the Checker Framework, I consider that acceptable.
> When releasing, make Randoop use the latest version of the Checker Framework

- dataflow/src/main/java/org/checkerframework/dataflow/cfg/builder/CFGTranslationPhaseOne.java
- dataflow/src/main/java/org/checkerframework/dataflow/cfg/node/LambdaResultExpressionNode.java
I think this code was modeled on that in `ReturnNode`, where the result can be `null` (for a statement `return;` with no value).  But if a lambda has an expression body, it cannot be empty; so here the result should be `@NonNull`.
> Make result of LambdaResultExpressionNode non-null

- build.gradle
An alternative to #5022.  If the latest version of ErrorProne starts behaving differently than version 2.10.0, we will want to just disable it.  This pull request show how to disable ErrorProne on JDK 8.
> Disable Error Prone on JDK 8

- dataflow/src/main/java/org/checkerframework/dataflow/analysis/BackwardTransferFunction.java
- dataflow/src/main/java/org/checkerframework/dataflow/analysis/ForwardTransferFunction.java
- dataflow/src/main/java/org/checkerframework/dataflow/constantpropagation/ConstantPropagationTransfer.java
- dataflow/src/main/java/org/checkerframework/dataflow/livevariable/LiveVarTransfer.java
- framework/src/main/java/org/checkerframework/framework/flow/CFAbstractTransfer.java
The dataflow code always initializes these lists with a non-null value; in cases where there are no parameters or return nodes (like a CFG for a field initializer), an empty list is used.  Declaring the corresponding parameters as `@NonNull` lets interface implementors avoid unnecessary null checks.
> Make parameter and return node lists for initial stores non-null

- framework/src/main/java/org/checkerframework/framework/util/AnnotatedTypes.java
With out this change code crashes in my type inference branch. I couldn't reproduce on master because that bounds that cause a crash only arise during type inference.
> Capture bounds of intersection types in `asMemberOf`

- checker/tests/nullness/Issue5042.java
- dataflow/src/main/java/org/checkerframework/dataflow/cfg/builder/CFGTranslationPhaseOne.java
- framework/src/main/java/org/checkerframework/framework/flow/CFAbstractTransfer.java
- framework/tests/all-systems/Issue5042.java
Fixes #5042.
(I didn't change `CFAbstractTransfer#initialStore` because I think that method is doing something different with initializer  blocks.)
> Fix `CFGTranslationPhaseOne#findOwner()` for lambdas

- checker/tests/ainfer-testchecker/non-annotated/CrazyEnum.java
- framework/src/main/java/org/checkerframework/common/wholeprograminference/WholeProgramInferenceJavaParserStorage.java
the test case `CrazyEnums.java` is copied from the all-systems tests. There are still other crashes elsewhere in the all-systems tests; if we manage to fix all of those, we can consider removing `CrazyEnums.java` from this test suite (should I add a TODO item?)
> add support to WPI for enum constants with class bodies

- dataflow/src/main/java/org/checkerframework/dataflow/expression/LocalVariable.java
**Summary**:
I've been profiling my checker that uses Dataflow, and
LocalVariable.hashCode came out **very hot** both on CPU and memory
allocation profiles.
`equals/hashCode` methods build a bunch of strings which is very 
expensive when you e.g. put your LocalVariables into a HashMap.
The new implementation of equals compares `Name name` and `Symbol owner`
using their intrinsic equality. Which should be fine with Names since
these are all interned. I'm not 100% sure about Symbols but it looks
like those are also properly unique.
The implementation of hashCode now follows that of equal. Note that I
dropped `TypeAnnotationUtils.unannotatedType(vs.type)` from `hashCode`
as it seems to be redundant and produces a new type that may be
structurally equivalent but not referentially equal to …
> Optimize LocalVariable#hashCode/equals

- checker/src/main/java/org/checkerframework/checker/signedness/SignednessAnnotatedTypeFactory.java
- checker/tests/signedness/AdditionWithChar.java
- checker/tests/signedness/CharCastedToInt.java
- checker/tests/signedness/CharComparisons.java
- checker/tests/signedness/CompareChars.java
- checker/tests/signedness/CompoundAssignmentsSignedness2.java
- checker/tests/signedness/Issue3710.java
- checker/tests/signedness/SignednessAssignments.java
- checker/tests/signedness/WideningConversion.java
- checker/tests/signedness/WideningInitialization.java
From the [JLS](https://docs.oracle.com/javase/specs/jls/se17/html/jls-5.html#jls-5.1.2)
> A widening conversion of a char to an integral type T zero-extends the representation of the char value to fill the wider format.
```
@Unsigned char s = ...;
@Signed int i = s; // this should be legal
```
(This reverts part of the changes from https://github.com/typetools/checker-framework/pull/5048.)
> Widen a char to an int or long should be `@SignedPositiveFromUnsigned`

- checker/tests/interning/InternUnbox.java
- checker/tests/signedness/Desugar.java
- dataflow/src/main/java/org/checkerframework/dataflow/analysis/AbstractAnalysis.java
- framework/src/main/java/org/checkerframework/framework/type/GenericAnnotatedTypeFactory.java
When getting the type of a tree, if dataflow does not have a value for the "post-conversion" (aka "desugared") node corresponding to the tree, use the node corresponding to the tree itself.
> Correct when to use the "pre-conversion" node's value.

- checker/tests/ainfer-testchecker/non-annotated/LambdaParamCrash.java
- framework/src/main/java/org/checkerframework/common/wholeprograminference/WholeProgramInferenceImplementation.java
Based on a crash encountered by @Nargeshdb. The previous logic was too stringent: there is not a guarantee that the existence of a formal parameter Element implies the existence of an enclosing ExecutableElement for which that Element is a parameter, because lambda expressions are not represented by Elements, but their parameters are.
> WPI: do not crash when a lambda parameter is re-assinged

- checker/src/main/java/org/checkerframework/checker/signedness/SignednessAnnotatedTypeFactory.java
- checker/src/main/java/org/checkerframework/checker/signedness/SignednessVisitor.java
- checker/tests/signedness/SignednessNumberCasts.java
In the Signedness Checker, casts to non-number, non-char types are defaulted to `@Signed`, if the type of the expression is not `@Unsigned`.
> Signedness Checker: non-number, non-char casts are @Signed

- checker/build.gradle
- checker/tests/ainfer-testchecker/non-annotated/AnonymousAndInnerClass.java
- framework/src/main/java/org/checkerframework/common/wholeprograminference/WholeProgramInferenceImplementation.java
- framework/src/main/java/org/checkerframework/common/wholeprograminference/WholeProgramInferenceJavaParserStorage.java
- framework/src/main/java/org/checkerframework/common/wholeprograminference/WholeProgramInferenceScenesStorage.java
This problem was discovered by running stub-based WPI on the all-systems tests. There are a few remaining issues there other than this one, but they all seem pretty minor, and all seem to be related to purity. (They seem especially minor compared to the problems we encountered when we tried the same thing with ajava-based WPI.)
> Fix varargs-related IndexOutOfBoundsException during WPI

- framework/src/main/java/org/checkerframework/framework/type/AnnotatedTypeFactory.java
- framework/src/main/java/org/checkerframework/framework/type/DefaultTypeHierarchy.java
This fixes a crash in my java8inference branch where the Checker Framework has a different type than javac.
> Use a different work around for a captured type variable javac bug.

- checker/tests/nullness/PreconditionFieldNotInStore.java
- framework/src/main/java/org/checkerframework/common/basetype/BaseTypeVisitor.java
I encountered this problem when running WPI on BCELUtil (hence the new test case), but it appears to be general: when no information is available in the store about a field at a method's call site, an error is issued about a violated precondition if such a precondition exists for that field. This doesn't make sense - the store doesn't always track all fields, so I think the declared type should be used instead when there is no information in the store.
This change causes a Nullness Checker test to fail (and possibly others - I haven't run anything but the Nullness tests). I'd like to get a discussion going around that test and what the expected behavior is, because IMO the current expected warnings don't match the documentation of `@RequiresNonNull`. In particular, the failure is:
```
2 …
```
> When no information about a field is in the store, use top when deciding whether a precondition is met

- checker/src/main/java/org/checkerframework/checker/resourceleak/MustCallConsistencyAnalyzer.java
This PR cache the store after each node in MustCallConsistencyAnalyzer.
> Cache the result of TypeFactory.getStoreAfter() in MustCallConsistencyAnalyzer

- docs/manual/creating-a-checker.tex
The fully-qualified name changed to ` org.checkerframework.dataflow.cfg.visualize.CFGVisualizeLauncher` but the manual was not updated.
> Fix fully-qualified name of CFGVisualizeLauncher in manual

- checker/src/test/java/org/checkerframework/checker/test/junit/ainferrunners/AinferTestCheckerAjavaTest.java
- checker/src/test/java/org/checkerframework/checker/test/junit/ainferrunners/AinferTestCheckerJaifsTest.java
- checker/src/test/java/org/checkerframework/checker/test/junit/ainferrunners/AinferTestCheckerStubsTest.java
- checker/tests/ainfer-testchecker/input-annotation-files/ExistingPurityAnnotations-org.checkerframework.checker.testchecker.ainfer.AinferTestChecker.ajava
- checker/tests/ainfer-testchecker/input-annotation-files/ExistingPurityAnnotations-org.checkerframework.checker.testchecker.ainfer.AinferTestChecker.astub
- checker/tests/ainfer-testchecker/input-annotation-files/README.md
- checker/tests/ainfer-testchecker/non-annotated/ExistingPurityAnnotations.java
- framework/src/main/java/org/checkerframework/common/basetype/BaseTypeVisitor.java
I expect that merging this PR will fix the currently-failing master CI build, which is caused by WPI only outputting inferred purity annotations every other round (i.e., when those purity annotations aren't already in its input stub/ajava file).
> During WPI, always include all true purity annotations in WPI output, even if that annotation is already known to be true

- javacutil/src/main/java/org/checkerframework/javacutil/TypesUtils.java
**Summary**:
The previous version would return incorrect lub in some cases, e.g.:
```
TypesUtils.leastUpperBound(t1=Integer, t2=int) == int
```
This is because int and Integer are assignable **to each other** according to `Types#isAssignableTo`, 
so just checking assignability is not enough to figure out which type to return.
**Test plan**:
I tested the change in my project. Not sure whether/what tests I should add to CF as `javacutil` doesn't have its own test suite.
> Fix handling of primitives in TypesUtils#leastUpperBound

- docs/examples/errorprone/build.gradle
- docs/examples/lombok/build.gradle
The test should pass after https://github.com/kelloggm/checkerframework-gradle-plugin/pull/196 is merged.
> Update Checker Framework Gradle plugin version numbers.

- checker/src/main/java/org/checkerframework/checker/resourceleak/ResourceLeakAnnotatedTypeFactory.java
- checker/tests/resourceleak/HDFSReport.java
Fixes [#5136](https://github.com/typetools/checker-framework/issues/5136)
> Resource Leak Checker: Add a check to avoid mapping multiple keys to a ternary expression for tempVarToTree

- checker/src/main/java/org/checkerframework/checker/resourceleak/MustCallConsistencyAnalyzer.java
- checker/tests/resourceleak/HDFSReport2.java
I encountered this problem when running RLC on Hadoop project.
> Resource Leak Checker: Fix ClassCastException when rhs of an assignment in try-with-resources is a field

- docs/manual/introduction.tex
- framework/src/main/java/org/checkerframework/common/wholeprograminference/WholeProgramInferenceJavaParserStorage.java
- framework/src/main/java/org/checkerframework/framework/source/SourceChecker.java
- framework/src/main/java/org/checkerframework/framework/type/AnnotatedTypeFactory.java
This option is useful because it permits `diff`ing between the `.ajava` files produced by WPI and the originals. Without this option, `diff`ing is difficult because there are usually many formatting differences.
I'm not sure how (or whether) to write a test for this. I tested it manually on the icalavailable project from plume-lib and it worked as expected.
> Add -AinferOutputOriginal option

- dataflow/src/main/java/org/checkerframework/dataflow/cfg/builder/Label.java
This enables greater extensibility in CFG construction; see https://github.com/typetools/checker-framework/issues/5151#issuecomment-1148026783
> Make the Label class public

- framework/src/main/java/org/checkerframework/framework/type/TypeFromExpressionVisitor.java
Sometimes javac types an expression as the upper bound of a captured type variable instead of the captured type variable itself.  Detect this case and match the annotated type to the java type.
> Work around a javac bug.

- dataflow/src/main/java/org/checkerframework/dataflow/analysis/AnalysisResult.java
This fixes a crash in NullAway discovered when trying to update to 3.23.0; see https://github.com/uber/NullAway/issues/623.  It is a follow-up to https://github.com/typetools/checker-framework/pull/5178.  In that change I missed a case where the maps inside `AnalysisResult` need to be copied (see code comments for details).
I am open to suggestions on how to add a test for this.  I think the Checker Framework tests passed before because Checker Framework checkers almost always end up calling `AnalysisResult.combine()`, which ends up copying the maps anyway; NullAway does not call this method.
> Add more map copying to AnalysisResult

- build.gradle
- dataflow/build.gradle
- dataflow/src/main/java/org/checkerframework/dataflow/cfg/visualize/CFGVisualizeLauncher.java
- dataflow/src/main/java/org/checkerframework/dataflow/constantpropagation/ConstantPropagationStore.java
- dataflow/src/test/java/constantpropagation/ConstantPropagation.java
- dataflow/tests/constant-propagation/Expected.txt
- dataflow/tests/constant-propagation/Test.java
Currently we only have dataflow tests for backward analysis; constant propagation covers the forward analysis case.  The code is based heavily on the existing dataflow tests.
This was originally written in the hopes of having a test exposing the issue addressed by #5210.  It doesn't do that, unfortunately (that failure relies on more complex transfer functions), but I think it's still useful.
> Add a dataflow test for constant propagation

- checker/src/main/java/org/checkerframework/checker/resourceleak/MustCallConsistencyAnalyzer.java
- checker/tests/resourceleak/MultipleIdenticalReturns.java
The caches in `MustCallConsistencyAnalyzer` must be `IdentityHashMap`s to avoid caching the wrong result for a `Node`.
> Fix issue with multiple identical Nodes in MustCallConsistencyAnalyzer

- checker/build.gradle
Maybe a better approach would be for the `wpi*` scripts to default CHECKERFRAMEWORK to scriptsdirectory/../.. .
> Set environment variable before invoking `wpi-many.sh`

- docs/developer/developer-manual.html
`assemble` is a standard Gradle task that builds all of the jars of a project including Javadoc jars.  If you just want to build enough of the jars to use checker/bin/javac, run `./gradlew copyJarsToDist`.
> Add copyJarToDist to developer manual.

- checker/src/main/java/org/checkerframework/checker/guieffect/GuiEffectTypeFactory.java
Calls to it were removed in d7149190dc06ab63c71af0bb7a07cf13db18b6b4 and replaced with calls to ` AnnotatedTypes#overriddenMethods`.
> Remove method that isn't called anymore.

- framework/tests/framework/AnnotatedVoidMethod.java
This doesn't test anything useful about the Checker Framework, and the test is flaky because different versions of javac use slightly different error message text (e.g., this test fails under JDK 18).
> Remove test of javac

- checker/src/main/java/org/checkerframework/checker/index/samelen/SameLenAnnotatedTypeFactory.java
- checker/tests/ainfer-index/non-annotated/ContainsSubstring.java
- framework/src/main/java/org/checkerframework/common/wholeprograminference/WholeProgramInferenceImplementation.java
- framework/src/main/java/org/checkerframework/framework/ajava/AnnotationMirrorToAnnotationExprConversion.java
This PR actually (partially) addresses three related bugs, all of which are triggered by the new test case I added (ContainsString.java):
* ajava-based WPI generated malformed annotations when an annotation value contained a string literal with escapable characters such as ". The specific cause of this was `@SameLen(""Hamburg"")` being generated; that should have been `@SameLen("\"Hamburg\"")`.
* The SameLen Checker shouldn't have been inferring annotations with manifest string literals in the first place. I fixed that here, too, and also modified the test to force the Value Checker to elicit the above bug without the fix in this PR.
* The test still fails without a warning suppression, because WPI isn't correctly viewpoint adapting to the method when inferring parameter types. I didn't …
> Fix ajava-based WPI generating malformed annotation with String constants containing escapable characters

- build.gradle
This fixed the problem with configuring the spotless plugin that was exposed by https://github.com/typetools/checker-framework/pull/5308.
> Fix problem with configuring the spotless plugin.

- build.gradle
> Temporarily disable running spotlessCheck with the build task.

- build.gradle
~I added the changes in https://github.com/typetools/checker-framework/pull/5325 to this PR to test that they fix the bug exposed by this PR.  Merge https://github.com/typetools/checker-framework/pull/5325  first.~
> Don't run Java formatting under JDK 8

- framework/src/main/java/org/checkerframework/framework/type/AnnotatedTypeFactory.java
I couldn't easily create a small, reproducible test case, but I am hopeful that this fixes #5323.
> Avoid crash in `AnnotatedTypeMirror.fromExpression`; fixes #5323

- docs/developer/release/release_build.py
- docs/developer/release/release_push.py
Instead, run the AFU tests with the Checker Framework tests in the release_push.py script.  This step can be skipped, so there's no need for an option.
> Remove the --notest option to release_build.py

- docs/developer/release/release_push.py
- docs/developer/release/release_vars.py
Is there anyway to test this before I make the next release?
> Delete /cse/www2/types/checker-framework/api/ just before copying new release.

- checker/tests/ainfer-index/non-annotated/RequireJavadocCrash.java
- framework/src/main/java/org/checkerframework/framework/util/dependenttypes/DependentTypesHelper.java
Fixes a regression introduced in #5321, based on a crash discovered by @dd482IT when running WPI on require-javadoc.
> Fix WPI crash when delocalizing deterministic method calls

- framework/src/test/java/org/checkerframework/framework/testchecker/util/FlowTestAnnotatedTypeFactory.java
- framework/src/test/java/org/checkerframework/framework/testchecker/util/ValueTypeAnno.java
- framework/tests/flow/CustomContractWithArgs.java
- framework/tests/flow/MetaPostcondition.java
- framework/tests/flow/MetaPrecondition.java
- framework/tests/flow/Postcondition.java
- framework/tests/flow/Precondition.java
- framework/tests/flow/Values.java
This eliminates the need to format all occurrences of `@Value` as type annotations.
> Rename `@Value` test annotation to `@ValueTypeAnno`

- build.gradle
I tried using -linkoffline when using JDK 9+, but I got `error: Error reading file: -protected/element-list`, so just don't link on JDK 9+.
> Avoid Javadoc warning.

- checker-qual/src/main/java/org/checkerframework/checker/calledmethods/qual/EnsuresCalledMethods.java
- checker/tests/calledmethods/EnsuresCalledMethodsRepeatable.java
The motivation for this is two-fold:
* other `@EnsuresX` annotations (e.g., `@EnsuresNonNull`, `@EnsuresQualifier`) are repeatable
* WPI sometimes produces more than one `@EnsuresCalledMethods` annotation for the same method. It would be possible to merge them at the WPI stage, but that would be more complicated
> Make @EnsuresCalledMethods repeatable

- checker/src/main/java/org/checkerframework/checker/index/upperbound/UBQualifier.java
- checker/tests/ainfer-index/non-annotated/DelocalizeAtCallsites.java
- framework/src/main/java/org/checkerframework/framework/util/dependenttypes/DependentTypesHelper.java
In #5321, we added the ability for WPI to viewpoint adapt annotations at callsites by delocalizing arguments. That PR used `null` to represent annotation arguments that could not be delocalized. Unfortunately, I failed to notice that for annotations with arguments with more complex expression types (like binary expressions, array accesses, field accesses, etc) this would cause null-pointer exceptions as local variables in those expressions are converted to null. This PR handles all these cases safely by converting the whole expression to null if any of its constituent parts are null. It's a bit ugly in that I ended up re-implementing about half of `JavaExpressionConverter` to include null-handling, but it works as intended.
> WPI: Fix crash caused by delocalizeAtCallsite not handling possible nulls caused by out-of-scope variables in annotations

- framework/src/main/java/org/checkerframework/common/wholeprograminference/WholeProgramInferenceJavaParserStorage.java
The crash occurs in the code that supports inferring declaration annotations with ajava-based WPI. @Nargeshdb, can you review this? (I've asked @mernst to add you as a member of the organization so that I can officially assign you as a reviewer.)
> Fix crash in WPI when running MustCallInferenceLogic

- checker/tests/tainting/Issue5435.java
- framework/src/main/java/org/checkerframework/common/basetype/BaseTypeVisitor.java
- framework/src/main/java/org/checkerframework/framework/ajava/DoubleJavaParserVisitor.java
- framework/src/main/java/org/checkerframework/framework/ajava/JointJavacJavaParserVisitor.java
- framework/src/main/java/org/checkerframework/framework/type/TypeFromExpressionVisitor.java
- framework/src/main/java/org/checkerframework/framework/type/TypeFromTreeVisitor.java
- framework/src/main/java/org/checkerframework/framework/util/JavaParserUtil.java
> Handle annotations in TypeFromExpressionVisitor; fixes #5435

- framework/src/main/java/org/checkerframework/framework/type/AnnotatedTypeReplacer.java
I don't have a minimized test case, unfortunately. @dd482IT encountered this crash when running WPI + the Nullness Checker on [randoop](github.com/randoop/randoop) with this (partial) stack trace:
```
Exception: java.util.ConcurrentModificationException; java.util.ConcurrentModificationException
at java.base/java.util.TreeMap$PrivateEntryIterator.nextEntry(TreeMap.java:1208)
at java.base/java.util.TreeMap$KeyIterator.next(TreeMap.java:1262)
at java.base/java.util.Collections$UnmodifiableCollection$1.next(Collections.java:1047)
at org.checkerframework.framework.type.AnnotatedTypeReplacer.resolvePrimaries(AnnotatedTypeReplacer.java:149)
```
It looks to me like the problem is that `to.getAnnotations()` iterates over the annotations in `to`, but `removeAnnotation` removes an annotation from …
> Avoid concurrent modification exception

- checker/src/test/java/org/checkerframework/checker/testchecker/ainfer/AinferTestAnnotatedTypeFactory.java
- checker/src/test/java/org/checkerframework/checker/testchecker/ainfer/qual/AinferTreatAsSibling1.java
- checker/tests/ainfer-testchecker/non-annotated/IShouldBeSibling1.java
- checker/tests/ainfer-testchecker/non-annotated/TreatAsSibling1InferenceTest.java
- checker/tests/ainfer-testchecker/non-annotated/TreatAsSibling1Test.java
- framework/src/main/java/org/checkerframework/common/wholeprograminference/SceneToStubWriter.java
- framework/src/main/java/org/checkerframework/common/wholeprograminference/WholeProgramInference.java
- framework/src/main/java/org/checkerframework/common/wholeprograminference/WholeProgramInferenceImplementation.java
- framework/src/main/java/org/checkerframework/common/wholeprograminference/WholeProgramInferenceJavaParserStorage.java
- framework/src/main/java/org/checkerframework/common/wholeprograminference/WholeProgramInferenceScenesStorage.java
- framework/src/main/java/org/checkerframework/common/wholeprograminference/WholeProgramInferenceStorage.java
This PR is based on work by @Nargeshdb in [this branch](https://github.com/Nargeshdb/checker-framework/tree/inference). I copied over the code implementing the APIs themselves and have added inference logic and test cases to the `AinferTestChecker` to test the two new APIs.
The goal of these APIs is to support inference of `@MustCall` annotations on class declarations and `@Owning` annotations on method parameters, respectively. @Nargeshdb will follow this PR with implementations of those features.
Getting these APIs to pass the tests required two small bug fixes, both related to stub-based WPI:
* `SceneToStubWriter` printed class declaration annotations after the `class`, which is the wrong place: the annotations should be before the `class` keyword. Previously, we didn't have a test for …
> Add APIs to WPI for inferring 1) annotations on class declarations and 2) formal parameter annotations

- framework/src/main/java/org/checkerframework/common/value/ValueAnnotatedTypeFactory.java
- framework/tests/value/TooWideRange.java
> Ensure inferred IntRange annos are no wider than is possible for the Java type.

- checker/tests/ainfer-nullness/non-annotated/Bug.java
- framework/src/main/java/org/checkerframework/common/wholeprograminference/WholeProgramInferenceImplementation.java
This should fix https://github.com/mernst/checker-framework/tree/wpi-multi-version-control-onlyone.
> Don't infer contract annotations about instance fields on static methods.

- checker/tests/ainfer-resourceleak/non-annotated/HadoopCrash.java
- framework/src/main/java/org/checkerframework/common/wholeprograminference/WholeProgramInferenceImplementation.java
The crash occurs in `updateInferredExecutableParameterTypes` when it tries to get the annotations for the receiver type of static method calls.
> Fix crash in WPI when receiver type is null

- framework/src/main/java/org/checkerframework/common/wholeprograminference/WholeProgramInferenceJavaParserStorage.java
No test for this, because out-of-compilation-unit tests are difficult/impossible to write as unit tests. Based on a report from @Nargeshdb of a crash when running WPI on HBase. Despite the lack of tests, I'll note that `parameterTypes` is specified as `@MonotonicNonNull List<@Nullable AnnotatedTypeMirror>`, so it's clear that null-checking an element from it is clearly the right thing to do.
> WPI: Avoid NPE due to out-of-compilation-unit inference

- docs/CHANGELOG.md
- framework/src/main/java/org/checkerframework/framework/type/ElementQualifierHierarchy.java
- framework/src/main/java/org/checkerframework/framework/type/treeannotator/TreeAnnotator.java
- framework/src/main/java/org/checkerframework/framework/util/DefaultQualifierKindHierarchy.java
- framework/src/main/java/org/checkerframework/framework/util/QualifierKindHierarchy.java
> `getQualifierKind()` throws an exception rather than returning null.

- checker/tests/ainfer-testchecker/non-annotated/EnumMapCrash.java
- framework/src/main/java/org/checkerframework/common/wholeprograminference/WholeProgramInferenceJavaParserStorage.java
This bug was exposed by #5590, which enabled this capability. Without this change, ajava-based WPI stores inferred types using the LHS' type, which might be an instantiation of a type variable (instead of the type variable itself).
This fix assumes that no annotations are inferred on type variable bounds. This is true right now, but it would require a change here in the future.
> WPI: Avoid crashing in asSuper when inferring annotations on fields with typevar types

- checker/build.gradle
Some of the files it referenced are from a different test suite. Also, some of the spacing was odd.
> Cleanup Ainfer Nullness Jaifs test

- checker/build.gradle
- checker/src/test/java/org/checkerframework/checker/testchecker/ainfer/AinferTestAnnotatedTypeFactory.java
- checker/src/test/java/org/checkerframework/checker/testchecker/ainfer/qual/AinferTreatAsSibling1.java
- checker/tests/ainfer-testchecker/non-annotated/InnerClassFieldDeclAnno.java
- docs/manual/creating-a-checker.tex
- framework/src/main/java/org/checkerframework/common/wholeprograminference/WholeProgramInferenceJavaParserStorage.java
- framework/src/main/java/org/checkerframework/common/wholeprograminference/WholeProgramInferenceScenesStorage.java
correct:
```
@DeclAnno
public Outer.Inner foo;
```
incorrect (this is the behavior prior to this PR):
```
public Outer.@DeclAnno Inner foo;
```
The latter is right for type annotations, but declaration annotations need to be attached higher up in the AST.
The test infra for this PR is kind of involved, and I'm not that confident that it would catch all variants of this that are wrong. You can check the output in the generated `.ajava` file for the new test case to confirm that this does the right thing.
> WPI: place inferred field declaration annotations on fields with Outer.Inner-style types properly

- build.gradle
This is so that when build Javadocs with JDK 17 the links to Java API link to the Java 17 docs and are not broken.
> Don't use source 8 when building Javadoc.

- checker/tests/nullness/Issue3929.java
- checker/tests/nullness/MisuseProperties.java
- checker/tests/nullness/RawTypesUses.java
- checker/tests/nullness/generics/Issue269.java
- framework/src/main/java/org/checkerframework/common/basetype/BaseTypeVisitor.java
- framework/src/main/java/org/checkerframework/framework/util/AnnotatedTypes.java
- framework/tests/all-systems/Issue3785.java
- framework/tests/all-systems/Issue5436.java
- framework/tests/framework/BridgeMethods.java
Basically if a method is invoke with a raw receiver method, all types of the method signature are erased.  (This doesn't fix #635 because there are other places where raw types are ignored besides and the type of a receiver expression.)
Fixes #5436 and #3785.
> Correct treatment of methods whose receiver is raw.

- framework-test/src/main/java/org/checkerframework/framework/test/PerDirectorySuite.java
This makes it so that the test case name is the full path to the directory of the test java files that are being checked. For example: 
`org.checkerframework.checker.test.junit.NullnessTest > run[/Users/smillst/jsr308/checker-framework/checker/tests/nullness/java8]`
> Correct test case name in Junit tests

- checker/src/test/java/org/checkerframework/checker/test/junit/ainferrunners/AinferTestCheckerAjavaValidationTest.java
- framework/src/main/java/org/checkerframework/common/basetype/BaseTypeVisitor.java
- framework/tests/purity-suggestions/PuritySuggestionsClass.java
- javacutil/src/main/java/org/checkerframework/javacutil/TreeUtils.java
This issue was causing a large number of spurious warnings in WPI. This PR also fixes the WPI tests so that they actually check the purity suggestions that WPI produces. (In real WPI runs, this problem is easy to observe, because -Ainfer implies purity checking, but WPI validation tests don't actually run with -Ainfer, which is why we didn't notice the problem before.)
> Methods that return "void" cannot be pure, so -AsuggestPurity should not suggest that they are

- build.gradle
This version causes `./gradlew publishToMavenLocal` to fail.
> Revert updating the shadow plugin.

- checker/src/main/java/org/checkerframework/checker/mustcall/MustCallAnnotatedTypeFactory.java
- checker/src/main/java/org/checkerframework/checker/mustcall/MustCallTransfer.java
- checker/src/main/java/org/checkerframework/checker/resourceleak/MustCallConsistencyAnalyzer.java
- checker/tests/resourceleak/ConnectingSockets2.java
- javacutil/src/main/java/org/checkerframework/javacutil/ElementUtils.java
> RLC: Resource variables are @Owning for the purposes of issuing reset.not.owning errors

- javacutil/src/main/java/org/checkerframework/javacutil/Resolver.java
google-java-format recently changed formatting of throws clauses.  Adding this Javadoc prevents errors in other pull requests.
> Javadoc for `buildMethodContext()`

- build.gradle
- docs/CHANGELOG.md
Merge together:
https://github.com/typetools/jdk/pull/173
https://github.com/codespecs/daikon/pull/474
https://github.com/plume-lib/multi-version-control/pull/221
https://github.com/plume-lib/plume-util/pull/295
> The receiver type of `Object.hashCode()` is now `@UnknownSignedness`

- checker/src/main/java/org/checkerframework/checker/mustcall/MustCallAnnotatedTypeFactory.java
- checker/src/main/java/org/checkerframework/checker/mustcall/MustCallVisitor.java
- checker/src/main/java/org/checkerframework/checker/resourceleak/MustCallConsistencyAnalyzer.java
- checker/tests/resourceleak/MustCallAliasImplWrong2.java
- checker/tests/resourceleak/MustCallAliasLocal.java
- checker/tests/resourceleak/MustCallAliasNotThis.java
- checker/tests/resourceleak/MustCallAliasNullConstructor.java
- checker/tests/resourceleak/MustCallAliasPassthroughWrong2.java
- checker/tests/resourceleak/MustCallAliasPassthroughWrong3.java
fixes #5777 
This implementation does introduce some false positives (see the test cases), but I think they'll only occur in very unusual code. I'm open to suggestions on how to prevent them; long-term, I think the solution is to decouple `@MustCallAlias` checking from `@PolyMustCall`.
> Fix soundness issue when checking that an @MustCallAlias parameter is correctly assigned to an owning field

- framework/src/main/java/org/checkerframework/framework/type/AnnotatedTypeMirror.java
> Can't shallow copy wildcards or type variables.

- checker/bin-devel/wpi-plumelib/bcel-util.expected
- checker/jtreg/sortwarnings/ErrorOrders.out
- checker/jtreg/stubs/issue2147/WithStub.out
- checker/jtreg/stubs/issue2147/WithoutStub.out
- checker/jtreg/tainting/NewClass.out
- checker/src/main/java/org/checkerframework/checker/formatter/FormatterVisitor.java
- checker/src/main/java/org/checkerframework/checker/guieffect/GuiEffectVisitor.java
- checker/src/main/java/org/checkerframework/checker/i18nformatter/I18nFormatterVisitor.java
- checker/tests/command-line/issue618/expected.txt
- docs/CHANGELOG.md
- docs/examples/fenum-extension/Expected.txt
- docs/examples/lombok/Makefile
- docs/examples/subtyping-extension/Expected.txt
- framework/jtreg/variablenamedefault/UseTest1.out
- framework/jtreg/variablenamedefault/UseTest2.out
- framework/src/main/java/org/checkerframework/common/basetype/BaseTypeVisitor.java
- javacutil/src/main/java/org/checkerframework/javacutil/ElementUtils.java
If you want to merge this before the release, we need to edit the changelog (either in this pull request, or when making the release).
> Deprecate `ElementUtils.getSimpleNameOrDescription()` in favor of `getSimpleDescription()`

- build.gradle
This makes the logs shorter and easier to see which test failed.  
Here's an example log with test failures: 
https://dev.azure.com/smillst/checker-framework/_build/results?buildId=2836&view=logs&j=b53dbc13-46ec-5e04-a8ed-e1947e1a55a7&t=ae6fdf58-1b39-5626-fe20-47bffdcb43fc
> Don't print test summary.

- framework/src/main/java/org/checkerframework/framework/type/AsSuperVisitor.java
- framework/src/main/java/org/checkerframework/framework/type/DefaultTypeHierarchy.java
- framework/src/main/java/org/checkerframework/framework/type/TypeHierarchy.java
- javacutil/src/main/java/org/checkerframework/javacutil/TypesUtils.java
This fixes a problem in https://github.com/typetools/checker-framework/pull/5862.
> Instead of calling asSuper, box/unbox/narrow types in isSubtype 

- framework/src/main/java/org/checkerframework/framework/type/GenericAnnotatedTypeFactory.java
This has been broken for 2 years.  It also does not work if the constructor is protected.  Should we just remove the reflective code?
> Correct reflective invocation of Analysis constructors.

- docs/manual/troubleshooting.tex
AdoptOpenJDK is now the Eclipse Adoptium project:
https://blog.adoptopenjdk.net/2021/03/transition-to-eclipse-an-update/
The JDK that they distribute is called Temurin.
> Switch to Temurin from AdoptOpenJDK in build instructions

- framework/src/main/java/org/checkerframework/framework/type/DefaultAnnotatedTypeFormatter.java
For example:
```java
import java.util.List;
import org.checkerframework.checker.nullness.qual.NonNull;
public class RawTypePrinting<T,S extends List,Q extends CharSequence>{
void method(){
@NonNull RawTypePrinting myClass = null;
}
}
```
```
javacheck -processor nullness ../testcases/src/RawTypePrinting.java
../testcases/src/RawTypePrinting.java:7: error: [assignment] incompatible types in assignment.
@NonNull MyClass myClass = null;
^
found   : null (NullType)
required: @UnknownInitialization @NonNull MyClass</*RAW*/>
1 error
```
With ` -AprintVerboseGenerics`
```
javacheck -processor nullness ../testcases/src/RawTypePrinting.java  -AprintVerboseGenerics
../testcases/src/RawTypePrinting.java:6: error: [assignment] incompatible types in assignment.
@NonNull RawTypePrinting myClass = null; …
```
> Don't print `INFERENCE FAILED for:` when printing raw types.

- checker/src/main/java/org/checkerframework/checker/resourceleak/MustCallConsistencyAnalyzer.java
- checker/tests/resourceleak/Issue6030.java
- checker/tests/resourceleak/OwningMCU.java
This PR only fixes the crash, not the fact that no warning is issued.
No warning is issued about the owning field because of #5908. #5912 will fix that issue, and will presumably also require a change in this test case.
> Fix crash in RLC

- framework/src/main/java/org/checkerframework/framework/source/SourceChecker.java
@mernst This seem to be the cleanest way to do this, since we were already checking for the version for SNAPSHOT.
> Only add `dirty=true` if the version is a snapshot snapshot or the branch isn't master.

- checker/build.gradle
- checker/src/test/java/org/checkerframework/checker/test/junit/ainferrunners/AinferTestCheckerJaifsGenerationTest.java
- checker/src/test/java/org/checkerframework/checker/test/junit/ainferrunners/AinferTestCheckerJaifsValidationTest.java
- checker/src/test/java/org/checkerframework/checker/test/junit/ainferrunners/AinferTestCheckerStubsValidationTest.java
- framework/src/main/java/org/checkerframework/framework/type/AnnotatedTypeMirror.java
- framework/src/main/java/org/checkerframework/framework/type/SupertypeFinder.java
- framework/tests/all-systems/java17/Issue6069.java
> java.lang.Record is a super type of all records.

- build.gradle
- checker-qual/build.gradle
- checker/build.gradle
- dataflow/build.gradle
One warning remains:
```
> Configure project :checker-qual
The AbstractTask.getConvention() method has been deprecated. This is scheduled to be removed in Gradle 9.0. Consult the upgrading guide for further information: https://docs.gradle.org/8.2/userguide/upgrading_version_8.html#deprecated_access_to_conventions
```
It's from the biz.aQute.bnd plugin: see https://github.com/bndtools/bnd/issues/5714.
> Fix Gradle deprecation warnings

- docs/examples/MavenExample/pom.xml
- docs/manual/external-tools.tex
This change includes multiple adjustments:
- Instead of adding `com.google.errorprone:javac` as a dependency, copy it to the output folder.  This is important to ensure that your project does not accidentally import and use any of the classes in that jar.  It will also reduce the size of your project's dependency tree.  Furthermore, this is only relevant in the JDK 8 profile.
- Removed unused property `errorProneJavac`.
- Removed (now-)unused use of `maven-dependency-plugin:properties`.
- Converted deprecated `<compilerArguments>` to `<compilerArgs>`.
- Removed explicit dependency on `org.checkerframework:checker`, which is not necessary because it is also present in the `<annotationProcessorPaths>` block.  This will also reduce the size of your project's dependency tree (you probably …
> Improve the suggested Maven configuration

- framework/src/main/java/org/checkerframework/common/wholeprograminference/WholeProgramInferenceJavaParserStorage.java
The annotation in `k -> new TreeSet<@BinaryName String>()` isn't needed when type argument inference is implemented.
> Add Signature annotations instead of suppressing warnings.

- dataflow/src/main/java/org/checkerframework/dataflow/cfg/builder/ExtendedNode.java
- dataflow/src/main/java/org/checkerframework/dataflow/cfg/builder/Label.java
In #5955, the `ExtendedNode` and `Label` classes from the dataflow framework were changed from public to package-private.  However, NullAway relies on these classes being public (see https://github.com/typetools/checker-framework/pull/5156, https://github.com/typetools/checker-framework/pull/5152, and https://github.com/uber/NullAway/pull/608).  This PR makes the classes public again and adds an explanatory comment.
> Make `ExtendedNode` and `Label` public again

- checker/src/main/java/org/checkerframework/checker/resourceleak/MustCallConsistencyAnalyzer.java
- checker/tests/resourceleak/AccumulationValueFieldTest.java
This PR checks AccumulationValue to support fields with type variable in RLC.
> Enable accumulation checkers to accumulate facts on type variables for fields

- dataflow/src/main/java/org/checkerframework/dataflow/cfg/builder/ExtendedNode.java
- dataflow/src/main/java/org/checkerframework/dataflow/cfg/builder/Label.java
No idea how this happened, but it seems in #6130 I neglected to add `public` keywords to the relevant classes.
> Make `ExtendedNode` and `Label` public (really)

- framework/src/main/java/org/checkerframework/common/wholeprograminference/WholeProgramInferenceJavaParserStorage.java
Most parts of the Checker Framework use 1-indexing for formal parameters, to emphasize that the receiver is a formal parameter.  I wonder whether WPI should use that convention, too.
> Document 0-indexing

- docs/manual/inference.tex
The format of the GitHub repository URL and git hash pairs provided as input to `wpi-many.sh` is not clear. The current documentation, i.e.,
> Use wpi-many.sh to run whole-program inference on every Ant, Gradle, or Maven project in a list of (GitHub repository URL, git hash) pairs.
Available [here](https://checkerframework.org/manual/#wpi-many) suggests that the the elements of the pairs should be comma-separated, when it in fact should be whitespace-separated.
> Updating inference.tex (wpi-many.sh docs)

- build.gradle
- checker/bin-devel/build.sh
- framework/build.gradle
- framework/tests/annotationclassloader/Makefile
I've released a snapshot version of the StubParser (See https://github.com/typetools/stubparser/pull/116).  This pull request uses the snapshot version instead of building a new one.   
The point of this is so that the CI jobs don't have to build StubParser and can therefore use JDK 21 as the default JDK. 
So, this branch plus mernst/jdk21-test (plus suppressing the new lint warnings) gets the tests to pass on JDK 21.  I've merges them together here:
https://github.com/smillst/checker-framework/tree/jdk21-test-use-stuparser-artifact
> Use an artifact version of the stubparser.

- checker/src/main/java/org/checkerframework/checker/resourceleak/ResourceLeakAnnotatedTypeFactory.java
- checker/src/main/java/org/checkerframework/checker/resourceleak/ResourceLeakVisitor.java
- checker/tests/resourceleak/MultipleOwnedResources.java
- checker/tests/resourceleak/MultipleOwnedResourcesOfDifferentTypes.java
Fixes #5911.
Please let me know if there is a shorter or more canonical way to write `getEnsuresCalledMethodsAnnotations`; this seems like something a lot of checkers have to do, but I couldn't find an appropriate helper method.
> Handle EnsuresCalledMethods.List when checking field ownership

- build.gradle
Running `./gradlew checkNullness` runs the Nullness Checker on each subproject and should pass on each project.  For the framework and checker subprojects, only files marked `@AnnotatedFor("nullness")` are checked.
> Remove `checkNullnessOnlyAnnotatedFor` task.

- checker/src/main/java/org/checkerframework/checker/optional/OptionalVisitor.java
- checker/tests/optional/Marks7.java
After a discussion in a research meeting with @mernst, the `optional.collection` compile-time error should instead be a compile-time warning.
The reason for this change is that using an `Optional` to wrap a collection is a matter of style and not necessarily one of correctness.
> Change `optional.collection` error to warning

- docs/manual/introduction.tex
- docs/manual/optional-checker.tex
The Optional Checker currently issues errors and not warnings in cases where `.get()` or `.orElseThrow(...)` is called on a `MaybePresent`
e.g.,
```txt
/scratch/jmsy/outdir/21-points-9942264aa97089e646fd2beef968bf49adc627e9/21-points/src/main/java/org/jhipster/health/security/DomainUserDetailsService.java:42: error: [method.invocation]
.orElseThrow(() -> new UsernameNotFoundException("User with email " + login + " was not found in the database"));
^
found   : @MaybePresent Optional</*RAW*/>
required: @Present Optional</*RAW*/>
```
> Update Optional Checker manual

- .travis-build.sh
- build.gradle
- checker/bin-devel/build.sh
- checker/bin-devel/clone-related.sh
- checker/bin-devel/test-cftests-all.sh
- checker/bin-devel/test-cftests-inference-part1.sh
- checker/bin-devel/test-cftests-inference-part2.sh
- checker/bin-devel/test-cftests-inference.sh
- checker/bin-devel/test-cftests-junit.sh
- checker/bin-devel/test-cftests-nonjunit.sh
- checker/bin-devel/test-daikon-part1.sh
- checker/bin-devel/test-daikon-part2.sh
- checker/bin-devel/test-daikon.sh
- checker/bin-devel/test-downstream.sh
- checker/bin-devel/test-guava-formatter.sh
- checker/bin-devel/test-guava-index.sh
- checker/bin-devel/test-guava-interning.sh
- checker/bin-devel/test-guava-lock.sh
- checker/bin-devel/test-guava-nullness.sh
- checker/bin-devel/test-guava-regex.sh
- checker/bin-devel/test-guava-signature.sh
- checker/bin-devel/test-guava.sh
- checker/bin-devel/test-misc.sh
- checker/bin-devel/test-plume-lib.sh
- checker/bin-devel/test-typecheck-part1.sh
- checker/bin-devel/test-typecheck-part2.sh
- checker/bin-devel/test-typecheck.sh
- docs/manual/troubleshooting.tex
- settings.gradle
`./gradlew assemble` is sufficient to build the Checker Framework. (It runs `checker/bin-devel/clone-related.sh` to clone annotation-tools and jdk.) 
Adds a new scripts `checker/bin-devel/clone-related.sh` has the same contents as the old `build.sh`, but doen't call `./gradlew assemble`.
> Deprecate `checker/bin-devel/build.sh`

- .gitignore
- dataflow/build.gradle
- dataflow/src/main/java/org/checkerframework/dataflow/cfg/ControlFlowGraph.java
- dataflow/src/main/java/org/checkerframework/dataflow/cfg/builder/CFGTranslationPhaseThree.java
- dataflow/src/main/java/org/checkerframework/dataflow/cfg/visualize/CFGVisualizeLauncher.java
- dataflow/src/test/java/cfgconstruction/CFGConstruction.java
- dataflow/tests/cfgconstruction/Test.java
I observed some nondeterministic behavior from the Resource Leak Checker on a real project.  The root cause appears to be a defect in the code that merges adjacent blocks in CFGTranslationPhaseThree.  The original code did not correctly handle the case where there are three or more adjacent blocks that can be merged.
For instance, suppose the CFG contains:
... \                        /> ...
... --> b1 -> b2 -> b3 -> b4 -> ...
... /                        \> ...
When the original loop visited b1, it would move all of b2's nodes into b1 and update the successor/predecessor pointers:
... \                        /> ...
... --> b1 -------> b3 -> b4 -> ...
... /               ^        \> ...
b2
However, b2 remains in the worklist of blocks to visit.  If b2 were the next visited block, the …
> Correctly merge adjacent CFG blocks

- checker/src/main/java/org/checkerframework/checker/calledmethods/CalledMethodsTransfer.java
- checker/tests/calledmethods/ExceptionalPath2.java
The call to `s.insertValue` may silently do nothing if the new annotation is not a super- or sub-type of the existing one.  This can actually happen in some cases.
For example, in the new test case, at the call to `r.b()`:
- The incoming transfer input lists {"a"} as the called methods.
- The result of the transfer function for the regular path produces only {"b"} as the called methods (since the call to `b()` may modify `r`, invalidating the set of called methods).
- The exceptional store handling begins with every exceptional store equal to the input store. When it tries to insert {"b"} over the input value {"a"}, nothing happens since neither value is more specific.
This change makes the accumulation completely overwrite the exceptional output with the regular output instead of …
> Improve exception handling in `CalledMethodsTransfer.accumulate`

- docs/manual/annotating-libraries.tex
- docs/manual/introduction.tex
> Instructions on how to write a stub file by hand

- checker/src/main/java/org/checkerframework/checker/calledmethods/CalledMethodsAnnotatedTypeFactory.java
- checker/src/main/java/org/checkerframework/checker/mustcall/MustCallAnnotatedTypeFactory.java
- checker/src/main/java/org/checkerframework/checker/nullness/NullnessVisitor.java
- checker/tests/nullness/Exceptions.java
- checker/tests/nullness/TryCatch.java
- dataflow/src/main/java/org/checkerframework/dataflow/cfg/ControlFlowGraph.java
- framework/src/main/java/org/checkerframework/common/basetype/BaseTypeVisitor.java
- framework/src/main/java/org/checkerframework/framework/type/GenericAnnotatedTypeFactory.java
This should fix the errors in https://github.com/typetools/checker-framework/pull/6221.
> Don't issue warnings on dead code

- docs/examples/MavenExample/pom.xml
- docs/manual/external-tools.tex
I've found that with maven-compiler-plugin 3.10.1, many Error Prone and NullAway warnings are not printed; see https://github.com/google/error-prone/pull/4162.  This may affect Checker Framework warnings as well.
> Suggest use of maven-compiler-plugin 3.11.0

- checker-qual/src/main/java/org/checkerframework/checker/calledmethods/qual/EnsuresCalledMethods.java
- checker-qual/src/main/java/org/checkerframework/checker/calledmethods/qual/RequiresCalledMethods.java
- checker/tests/calledmethods/EnsuresCalledMethodsIfRepeatable.java
- checker/tests/calledmethods/EnsuresCalledMethodsIfSubclass.java
- checker/tests/calledmethods/EnsuresCalledMethodsRepeatable.java
- checker/tests/calledmethods/EnsuresCalledMethodsSubclass.java
- checker/tests/calledmethods/RequiresCalledMethodsRepeatable.java
- checker/tests/calledmethods/RequiresCalledMethodsSubclass.java
The Called Methods Checker pre- and postcondition annotations were missing some meta-annotations to make them properly repeatable and correctly inherited.  This commit adds the missing annotations along with a fairly complete set of tests.
> Add missing meta-annotations to Called Methods Checker

- checker/src/main/java/org/checkerframework/checker/calledmethods/CalledMethodsAnalysis.java
- checker/src/main/java/org/checkerframework/checker/resourceleak/MustCallConsistencyAnalyzer.java
- checker/src/main/java/org/checkerframework/checker/resourceleak/ResourceLeakAnalysis.java
- checker/src/main/java/org/checkerframework/checker/resourceleak/ResourceLeakAnnotatedTypeFactory.java
- checker/src/main/java/org/checkerframework/checker/resourceleak/ResourceLeakChecker.java
- checker/src/main/java/org/checkerframework/checker/resourceleak/SetOfTypes.java
- checker/src/test/java/org/checkerframework/checker/test/junit/ResourceLeakCustomIgnoredExceptionsTest.java
- checker/src/test/java/org/checkerframework/checker/test/junit/ResourceLeakExtraIgnoredExceptionsTest.java
- checker/tests/resourceleak-customignoredexceptions/BasicTest.java
- checker/tests/resourceleak-extraignoredexceptions/BasicTest.java
- docs/manual/resource-leak-checker.tex
Fixes #6218.
This change is admittedly overwrought, but
- I want the ability to ignore all subtypes of an exception type and
- I want to preserve the current behavior where subtypes of the default ignored exceptions are _not_ themselves ignored.
To meet those constraints I added a new data structure (`SetOfTypes`) and some funky syntax for specifying the set of ignored exceptions.
I'm not particularly attached to the syntax, and we should probably discuss improvements because it will be difficult to change later.
I picked the option name "resourceLeakIgnoredExceptions", but I'm happy to rename it if there is some sort of option naming pattern to follow.
> Add `-AresourceLeakIgnoredExceptions` option

- gradle.properties
https://docs.gradle.org/current/userguide/build_cache.html
This can reduce local build times, e.g., when you are switching locally between multiple branches, since the task outputs for all branches are stored in the build cache.  For custom tasks, a bit of care is required to ensure all task inputs are properly declared before making the task cacheable.  But, since tasks need to opt-in to caching, I don't think this is too risky.
Note that if we land this, running `./gradlew clean` may not be sufficient to force a task to run; you may also need to add the `--no-build-cache` argument.
> Enable Gradle build cache

- checker-qual/src/main/java/org/checkerframework/checker/mustcall/qual/MustCallAlias.java
- checker-qual/src/main/java/org/checkerframework/checker/mustcall/qual/PolyMustCall.java
- checker/src/main/java/org/checkerframework/checker/mustcall/MustCallAnnotatedTypeFactory.java
- checker/src/main/java/org/checkerframework/checker/resourceleak/MustCallConsistencyAnalyzer.java
- checker/src/main/java/org/checkerframework/checker/resourceleak/ResourceLeakAnnotatedTypeFactory.java
- checker/tests/mustcall/PolyMustCallDifferentNames.java
- checker/tests/resourceleak/CreatesMustCallForTwoAliases.java
- checker/tests/resourceleak/MustCallAliasDifferentMethodNames.java
Fixes #4947 
The fix works by customizing how polymorphic types are instantiated at call sites for the Must Call Checker, along with some adjustments in `MustCallConsistencyAnalyzer` to account for different resource aliases in the same `Obligation` having different `@MustCall` methods.  See the code and docs for further details.
> RLC: allow wrapper types to have a differently-named @MustCall method from wrapped type

- checker/src/main/java/org/checkerframework/checker/resourceleak/ResourceLeakVisitor.java
- checker/tests/resourceleak/OwningFieldStringComparison.java
- checker/tests/resourceleak/SneakyDestructor.java
fixes #6276
sorry in advance for the mildly annoying merge with #6271 @Calvin-L
> Owning fields should not be compared with string containment

- checker-qual/src/main/java/org/checkerframework/checker/calledmethods/qual/EnsuresCalledMethods.java
- checker-qual/src/main/java/org/checkerframework/checker/calledmethods/qual/EnsuresCalledMethodsOnException.java
- checker/src/main/java/org/checkerframework/checker/calledmethods/CalledMethodsAnnotatedTypeFactory.java
- checker/src/main/java/org/checkerframework/checker/calledmethods/CalledMethodsTransfer.java
- checker/src/main/java/org/checkerframework/checker/calledmethods/CalledMethodsVisitor.java
- checker/src/main/java/org/checkerframework/checker/calledmethods/EnsuredCalledMethodOnException.java
- checker/src/main/java/org/checkerframework/checker/calledmethods/EnsuresCalledMethodOnExceptionContract.java
- checker/src/main/java/org/checkerframework/checker/calledmethods/messages.properties
- checker/src/main/java/org/checkerframework/checker/resourceleak/IOUtils.astub
- checker/src/main/java/org/checkerframework/checker/resourceleak/ResourceLeakAnnotatedTypeFactory.java
- checker/src/main/java/org/checkerframework/checker/resourceleak/ResourceLeakVisitor.java
- checker/tests/calledmethods/EnsuresCalledMethodsOnExceptionRepeatable.java
- checker/tests/calledmethods/EnsuresCalledMethodsOnExceptionSubclass.java
- checker/tests/calledmethods/EnsuresCalledMethodsOnExceptionTest.java
- checker/tests/calledmethods/FinallyClose.java
- checker/tests/resourceleak/CloseSuper.java
- checker/tests/resourceleak/FinallyClose.java
- checker/tests/resourceleak/MultipleMethodParamsMustCallAliasTest.java
- checker/tests/resourceleak/OwnershipWithExceptions.java
- checker/tests/resourceleak/OwningAndEnsuresCalledMethodsOnException.java
- checker/tests/resourceleak/ReplicaInputStreams.java
- checker/tests/resourceleak/TwoResourcesECM.java
- docs/manual/called-methods-checker.tex
- docs/manual/resource-leak-checker.tex
- framework/src/main/java/org/checkerframework/common/basetype/BaseTypeVisitor.java
Fixes #6204 and adds a useful feature to the Called Methods Checker.
See also [this comment](https://github.com/typetools/checker-framework/issues/5734#issuecomment-1769708754).
**Motivation**
It is very common for resource-handling code to close owned resources even on exceptional return. The existing annotations like `@EnsuresCalledMethods` and `@Owning` only describe what happens on normal return, and there is no way to write a stronger contract that says a method _always_ closes a resource. (As far as I know, this limitation is common to all post-condition annotations in the Checker Framework.)
This PR adds `@EnsuresCalledMethodsOnException`, a new post-condition annotation that says what the method guarantees when it throws (subclasses of) `java.lang.Exception`.
**Why a new …
> Add `@EnsuresCalledMethodsOnException`

- checker/src/main/java/org/checkerframework/checker/optional/OptionalVisitor.java
Which was introduced by https://github.com/typetools/checker-framework/pull/6341.
> Fix Optional Checker Crash.

- checker/src/main/java/org/checkerframework/checker/optional/OptionalVisitor.java
- checker/tests/optional/Marks1Partial.java
- javacutil/src/main/java/org/checkerframework/javacutil/TreeUtils.java
(I'm working on improving the documentation of the overloads of BaseTypeVisitor#commonAssignementCheck that would prevent the mistake in the future.)
> Improve Optional Checkers null literal warning

- checker/src/main/java/org/checkerframework/checker/resourceleak/MustCallConsistencyAnalyzer.java
- checker/tests/resourceleak/InputOutputStreams.java
- checker/tests/resourceleak/MustCallAliasInitializeWithOwningParameter.java
In PR #6241 (commit 5b5c9e53) I was very cautious about the value of the `whenToEnforce` field on obligations.  It is always safe to use `MethodExitKind.ALL`, and so in most cases that's what I used.
However, having had some time to code with the new change, it's clear that `MethodExitKind.ALL` is too strong for (pseudo) assignments.  The left hand side should have the same `whenToEnforce` as the right-hand side.
See the new test case `MustCallAliasInitializeWithOwningParameter`. The pattern there is (in my experience) relatively common, but it does not verify with the latest Checker Framework release.
This change alters the behavior of a few of the `InputOutputStreams` test cases, since those tests take `@Owning` arguments instead of allocating new objects.  I have added copies of the …
> At (pseudo) assignments, use the existing strength of any obligations

- checker/tests/resourceleak/MustCallAliasNormalExit.java
Relates to #5658.  Fix a bad use of `@MustCallAlias`, and clarify why our checker reports a false positive.
> Update an RLC regression test

- build.gradle
Fixes #6297 
We make two key changes:
1. Split formatting of `.java` source files among individual sub-projects, so formatting / checking for each sub-project can run in parallel.
2. Remove exclusion patterns that start in `**`, which are expensive to evaluate.
With these changes, `./gradlew spotlessCheck` (which runs in the pre-commit script) runs much faster for me (on my M1 Mac the running time is reduced from ~9.2 seconds before this PR to ~2 seconds after).
To test, we add tasks named `printSpotlessTaskInputs` that print which files are being formatted.  Using these tasks I confirmed that exactly the same files are being checked and formatted before and after this PR.
> Speed up Spotless formatting

- framework/build.gradle
To see the problem on the current master branch, run:
```
./gradlew clean :framework:copyAndMinimizeAnnotatedJdkFiles --console=plain --no-parallel --no-daemon --no-build-cache
```
This causes a failure:
```
> Task :framework:copyAndMinimizeAnnotatedJdkFiles
Exception in thread "main" java.lang.NoClassDefFoundError: org/checkerframework/javacutil/BugInCF
at org.checkerframework.framework.stub.JavaStubifier.process(JavaStubifier.java:71)
at org.checkerframework.framework.stub.JavaStubifier.main(JavaStubifier.java:56)
Caused by: java.lang.ClassNotFoundException: org.checkerframework.javacutil.BugInCF
at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
at …
```
> Add missing dependencies for copyAndMinimizeAnnotatedJdkFiles task

- build.gradle
I ran several CI builds with parallel tests disabled on #6419 and none of them had the weird timeout failure we have been observing recently.  So I'm hoping this will address the problem.  As to _why_ this fixes the problem, I'm not really sure.  My best guess is that when tests run in parallel, if the wrong tests run simultaneously, the allocation rate is too high for the garbage collector to handle and things freeze up.  If we land some optimizations we should try reverting this change to see if the timeouts return.
> Disable parallel tests on CI to address flakiness

- build.gradle
The folder exclusion for `returnsreceiverdelomboked` was in the wrong place and had a typo
> Fix spotless rule

- framework/src/main/java/org/checkerframework/framework/source/SourceChecker.java
The documentation of `report()` states that `source` may be null, but the method crashes if null is passed.  Should we make this change, or should we change the documentation to forbid null as a source (which seems to have worked fine so far)?
> Don't permit source to be null

- framework/src/main/java/org/checkerframework/common/wholeprograminference/WholeProgramInferenceJavaParserStorage.java
- framework/src/main/java/org/checkerframework/framework/stub/AnnotationFileUtil.java
`isEmpty()` was only introduced in Java 11.  Since we are still trying to preserve Java 8 compatibility (I think), we should use `isPresent()` instead.
> Don't call Optional.isEmpty(), for Java 8 compatibility

- dataflow/src/main/java/org/checkerframework/dataflow/analysis/AbstractAnalysis.java
- dataflow/src/main/java/org/checkerframework/dataflow/cfg/visualize/AbstractCFGVisualizer.java
- dataflow/src/main/java/org/checkerframework/dataflow/cfg/visualize/DOTCFGVisualizer.java
- dataflow/src/main/java/org/checkerframework/dataflow/cfg/visualize/StringCFGVisualizer.java
- docs/CHANGELOG.md
- docs/manual/creating-a-checker.tex
- docs/manual/manual-style.tex
- docs/manual/manual.bbl
- framework/src/main/java/org/checkerframework/framework/flow/CFAbstractStore.java
Merge after https://github.com/typetools/checker-framework/pull/6461.
> Rename `AbstractCFGVisualizer.visualizeBlockHelper()` to `visualizeBlockWithSeparator()`

- checker/src/main/java/org/checkerframework/checker/mustcall/MustCallTransfer.java
Found this pattern while implementing a similar refinement in the Non-Empty Checker, did not want to make this change as part of that work.
> Use `CFAbstractStore.replaceValue` in `MustCallTransfer`

- framework/src/main/java/org/checkerframework/framework/source/SourceChecker.java
> Remove duplicated option

- checker/tests/optional/OptionalClosureTest.java
With all the changes I'm making over in the Side Effects Only Checker (particularly wrt. unrefinement and lambda expressions), I want to add some test cases that can catch regressions that we should really care about.
> Add test case for closing over an `Optional` value

- framework/src/main/java/org/checkerframework/framework/util/JavaParserUtil.java
- framework/tests/all-systems/UnicodeEscape.java
Fixes #6631.
Only the change at line 90 is actually required for the test to pass. However, it seemed like we'd want to use this option all the time, to match javac's behavior (JLS 3.3: javac removes all unicode escapes before it invokes the lexer). The downside of this change is that it could make error-reporting slightly less useful: problems in annotation files with unicode escapes will be reported at the "post-unicode preprocessing" location rather than the location before unicode preprocessing (which is a JavaParser limitation, and the reason that JavaParser has this option off by default even though it is the correct behavior from the JLS' perspective).
> Preprocess unicode escapes when parsing using JavaParser

- build.gradle
Without this, when a test fails it doesn't show which test class failed:
https://dev.azure.com/checkerframework/checkerframework/_build/results?buildId=15642&view=logs&j=e43dad68-5e3b-5c73-4a4a-12eda19916b0&t=fbbfbd16-76f1-5ebc-8cbf-485046fc23ef&l=2411
> Make it so that you can tell which test failed.

- docs/manual/troubleshooting.tex
I am experimenting with the Checker Framework at work, and needed to make a clean installation on macOS.
`graphviz` is needed to create CFG visualizations after running with `-Aflowdotdir`, but isn't included in the list of developer documentation for macOS.
Not sure if the same issue persists for Linux systems, but I'm happy to update the list of dependencies there, too.
> Add `graphviz` to list of dev dependencies for macOS

- checker/src/main/java/org/checkerframework/checker/formatter/FormatterAnnotatedTypeFactory.java
- checker/tests/formatter/Issue6641.java
> Formatter Checker: ignore literals in type argument inference.

- checker/tests/resourceleak/InputStreamWrapper.java
- docs/manual/resource-leak-checker.tex
This shows how to combine our annotations to create a wrapper type.  Also add the example as a test case.
> Add a complete example of a resource wrapper type to the manual

- framework/tests/all-systems/Issue6664.java
- framework/tests/all-systems/Issue6664B.java
- javacutil/src/main/java/org/checkerframework/javacutil/TreeUtils.java
> Correct type argument inference for method references with var args.

- framework/src/main/java/org/checkerframework/framework/util/typeinference8/InvocationTypeInference.java
- framework/src/main/java/org/checkerframework/framework/util/typeinference8/bound/BoundSet.java
- framework/src/main/java/org/checkerframework/framework/util/typeinference8/constraint/ConstraintSet.java
- framework/src/main/java/org/checkerframework/framework/util/typeinference8/constraint/TypeConstraint.java
- framework/tests/all-systems/DiamondMethodRef.java
- framework/tests/all-systems/Issue6652.java
> Fix order that constraints/variables are resolved in type arg inference

- dataflow/src/main/java/org/checkerframework/dataflow/cfg/builder/CFGTranslationPhaseOne.java
- framework/tests/all-systems/Issue6743.java
> Don't crash on  b ? null : null;.

- docs/manual/creating-a-checker.tex
- docs/manual/introduction.tex
- framework/src/main/java/org/checkerframework/framework/source/SourceChecker.java
- framework/tests/all-systems/Issue6725.java
You can run the following to test it:
```
javacheck -processor tainting -AexceptionLineSeparator=** framework/tests/all-systems/Issue6725.java
```
> Add an option to turn exception messages into a single line.

- framework/src/main/java/org/checkerframework/common/basetype/BaseTypeVisitor.java
- framework/src/main/java/org/checkerframework/common/basetype/messages.properties
- framework/src/main/java/org/checkerframework/framework/type/AnnotatedTypeFactory.java
- framework/src/main/java/org/checkerframework/framework/util/AnnotatedTypes.java
- framework/src/main/java/org/checkerframework/framework/util/typeinference8/DefaultTypeArgumentInference.java
- framework/src/main/java/org/checkerframework/framework/util/typeinference8/InferenceResult.java
If type argument inference crashes, the crash is caught and an error is reported, but the underlying java type of the method expression may be incorrect and cause further crashes.  In this case, use the Java computed method call expression type to created an annotated type of the method call.  This way the rest of the framework won't crash.
> Avoid a crashing when inference crashed.

- dataflow/src/main/java/org/checkerframework/dataflow/cfg/builder/CFGTranslationPhaseOne.java
- dataflow/src/main/java/org/checkerframework/dataflow/cfg/node/MethodInvocationNode.java
When an enhanced-for-loop over an Iterable (as opposed to over an array) is desugared by the CFG translation phase one, the translator logic sets a field for the MethodInvocationNode corresponding to the loop update statement (Iterator.next()), which is the ExpressionTree AST-node corresponding to the Iterable.
This PR now adds a reference to the EnhancedForLoopTree AST-node as well.
This additional desugaring information is required by the loop-body-analysis of the RLC4Collections.
> Add desugaring information to MethodInvocationNode

- checker/src/main/java/org/checkerframework/checker/resourceleak/MustCallConsistencyAnalyzer.java
- checker/tests/resourceleak/CastBeforeFinallyBlock.java
- checker/tests/resourceleak/SafeCast.java
The reason for the false positive is essentially:
- At `x = (Integer) getInt()`, the variable `y` is still in-scope. (The dataflow framework seems a bit sloppy about scopes in ways that don't matter to most checkers.)  There is an obligation to close `y`, but `y` has type `@CalledMethods("close")`, so there is no violation yet.
- There is a special rule that cast nodes ALWAYS propagate obligations.  So, the obligation for `y` gets propagated to the successor, which is a marker node at the start of the `finally` block.  (Normally this wouldn't happen, because `y` is not in-scope in the successor block.)
- When propagating that obligation from the marker node to the first "real" node in the `finally` block (the condition node `x != null`), the checker reports a spurious violation because
1. …
> Fix a resource leak false positive due to a cast

- framework/src/main/java/org/checkerframework/framework/type/AnnotatedTypeFactory.java
The `getAnnotatedType` method is one of the most-called in the Checker Framework.  It spends a lot of time and allocates a lot of bytes calling `TreeUtils.toStringTruncated`, but the results of those calls are only used when an internal debug flag is enabled (uncommon).
To fix the problem, this commit makes the call to `toStringTruncated` automatic in `logGat`, so the call sites do not need to do the string conversion and truncation themselves.
This optimization opportunity was discovered by profiling on a small project (50-100 source files).  For that workload,
- `toStringTruncated` contributed roughly 5% of total run time, and most of those calls came from `getAnnotatedType`.
- `toStringTruncated` contributed roughly 25% (!!!) of total allocated bytes.
I don't yet know if this change …
> Skip `TreeUtils.toStringTruncated` when debugging is disabled

- docs/manual/troubleshooting.tex
Users who wish to locally-build and develop the Checker Framework on macOS are asked to run the following command:
```sh
brew tap homebrew/cask-versions
```
Which appears to be deprecated as per the output:
```sh
Error: homebrew/cask-versions was deprecated. This tap is now empty and all its contents were either deleted or migrated.
```
An alternative is to run:
```sh
brew tap homebrew/homebrew-core
```
But homebrew suggests that it isn't necessary:
```sh
brew tap homebrew/homebrew-core
Error: Tapping homebrew/core is no longer typically necessary.
```
> Updating macOS installation instructions

- checker/src/main/java/org/checkerframework/checker/calledmethods/CalledMethodsChecker.java
- checker/src/main/java/org/checkerframework/checker/resourceleak/ResourceLeakChecker.java
- checker/src/test/java/org/checkerframework/checker/test/junit/ResourceLeakReturnsReceiverTest.java
- checker/tests/resourceleak-returns-receiver/ReturnsReceiverExamples.java
- checker/tests/resourceleak/ACMethodInvocationTest.java
- checker/tests/resourceleak/ACRegularExitPointTest.java
- docs/CHANGELOG.md
Fixes #6434
We separate test cases that require the Returns Receiver Checker to be enabled and only run those tests with the new flag.
> Disable Returns Receiver Checker by default for RLC

- checker/tests/mustcall/FunctionalInterfaces.java
- framework/src/main/java/org/checkerframework/framework/type/AnnotatedTypeFactory.java
- framework/tests/h1h2checker/AnonymousClasses.java
(This only fixes the anonymous test case in #6823.)
> Lub annotations on anonymous constructors

- dataflow/src/main/java/org/checkerframework/dataflow/cfg/builder/CFGTranslationPhaseOne.java
- dataflow/src/main/java/org/checkerframework/dataflow/cfg/node/ArrayAccessNode.java
For ArrayAccessNode's desugared from enhanced for loops, add the EnhancedForLoopTree AST node as a field. This allows us to traverse the CFG and detect enhanced for loops. Will be used in the MustCallOnElements checker.
> Augment arrayaccess node

- framework/src/main/java/org/checkerframework/framework/type/TypeFromExpressionVisitor.java
- framework/src/main/java/org/checkerframework/framework/util/typeinference8/types/InferenceType.java
- framework/src/main/java/org/checkerframework/framework/util/typeinference8/types/ProperType.java
- framework/src/main/java/org/checkerframework/framework/util/typeinference8/types/UseOfVariable.java
- framework/tests/all-systems/Issue6825.java
This seems to be what javac is doing.  (This crash the crash in annotation-tools.)
> Only capture fields that. are not on the LHS of assignments

- framework/src/main/java/org/checkerframework/framework/util/AnnotatedTypes.java
- framework/tests/all-systems/Issue6810.java
> Fix problem with GLB.

- checker/src/main/java/org/checkerframework/checker/interning/InterningAnnotatedTypeFactory.java
- checker/tests/interning/UnboxUninterned.java
Fixes #6371.
The interning checker does not apply `@Interned` to every occurrence of every primitive type.  This allows some language constructs to fabricate non-interned primitive values, leading to false positives.
For instance, in the new `loopVariables` test, the loop variable `i` was assigned the type `@UnknownInterned long`.  Thus `i` could not be used as an argument to `addExact` which requires interned arguments.
> All primitive types are `@Interned`

- checker-qual/src/main/java/org/checkerframework/checker/optional/qual/EnsuresPresent.java
- docs/manual/optional-checker.tex
Helps to avoid overloaded use of "non-empty" with future checkers (e.g., the Non-Empty Checker)
> Updating docs: "non-empty" to "present" `Optional`

- docs/developer/developer-manual.html
- framework/src/main/java/org/checkerframework/framework/flow/CFAbstractStore.java
I tried to create a standalone test case, but I was not able to.
> Handle SuperReference

- checker/src/main/java/org/checkerframework/checker/resourceleak/MustCallInference.java
Based on some suggestions from @mernst.
> [RLC Inference] Handle non-localvar entries in the tempvar map

- build.gradle
exec with a closure :
```
exec { ... }
```
Has been deprecated 
https://docs.gradle.org/8.12/userguide/upgrading_version_8.html#deprecated_project_exec
And appears to not be working in Gradle version 8.12.  (See https://github.com/typetools/checker-framework/pull/6937
) I'm working to remove all the uses, but I need to rewrite each use.
> Fix manual Gradle task

- settings.gradle
There is another problem:  The standard output and standard error are only printed if the command succeeds.  We want to see them regardless.  Here is an example execution: https://dev.azure.com/mernstdaikon/b8079554-0ed5-466e-9205-8aceed9390e7/_apis/build/builds/1840/logs/270
> Output standard error as well as standard output

- checker/src/main/java/org/checkerframework/checker/resourceleak/MustCallConsistencyAnalyzer.java
- checker/tests/resourceleak/FinallyThrowsException.java
- checker/tests/resourceleak/IfBranch.java
This commit fixes a subtle unsoundness in the resource leak checker concerning try-finally blocks where the `finally` block might throw an exception.
The simplest variant of this confusing control flow is shown in the first test case in FinallyThrowsException.java:
try {
return alloc();
} finally {
throw new IOException();
}
The allocated resource will be leaked because the method does not return; it throws an exception.  Previously the resource leak checker would accept that code because _all_ obligations were cleared at return statements.  Instead, only normal-return-obligations should be cleared at return statements, and exceptional-exit-obligations should remain unsatisfied in case a post-return-finally-block ends up throwing.
This change also affects try-with-resources blocks, where …
> Fix resource leak unsoundness due to `finally { throw }`

- .azure/azure-pipelines.yml
Since the September 2022 Azure DevOps update, the default fetch depth is 1, instead of unlimited. This affects pipelines created after this date. As a result, the misc jobs fail if the branch contains more than one commit, since no common ancestor can be found.
One can disable this shallow fetch by explicitly setting the fetchDepth to 0, which again fetches the full commit history.
As per: 
https://learn.microsoft.com/en-us/azure/devops/pipelines/yaml-schema/steps-checkout?view=azure-pipelines (under shallow fetch).
> explicitly set fetchDepth to 0 for misc jobs, disabling shallow fetch

- dataflow/src/main/java/org/checkerframework/dataflow/cfg/node/AnyPatternNode.java
- dataflow/src/main/java/org/checkerframework/dataflow/cfg/node/DeconstructorPatternNode.java
- dataflow/tests/java22/unnamed-pattern/Expected.txt
Without this, the default `toString()` includes some non-deterministic object id, which can cause the new dataflow test case to fail:
https://dev.azure.com/checkerframework/checkerframework/_build/results?buildId=17676&view=logs&j=1082351f-0229-59e0-d5d1-f10d4a9093e1&t=a5668178-fe8d-5b50-d740-18fc5de8f723&l=1464
> Add toString() for DeconstructorPatternNode and AnyPatternNode

- framework/src/main/java/org/checkerframework/framework/util/typeinference8/util/CheckedExceptionsUtil.java
- framework/tests/all-systems/java8inference/Issue6887.java
Fixes #6887.  In a few positions, the type inference code was trying to obtain the type of `throw E` rather than the type of `E`.
Also fixes another latent bug: the Checker Framework would throw NPE on the line
new Issue6887<>(() -> {});
because with no body statements, the various tree visitors in `CheckedExceptionsUtil` return null.
This commit includes test code written by @veikokaap.
> Fix two possible type inference crashes

- dataflow/src/main/java/org/checkerframework/dataflow/analysis/AbstractAnalysis.java
Along some code paths to `setNodeValues()`, `in == this.nodeValues`.  When that happens, the call to `nodeValues.clear()` actually clears _both_ maps, meaning the method deletes all knowledge about CFG nodes.
The main path to this misbehavior is through `GenericAnnotatedTypeFactory.getStoreAfter(node)`, which reads `analysis.getNodeValues()`.  That value is passed through several other layers of abstraction and eventually reaches `setNodeValues()`.
I found this while working on some unrelated improvements that weren't working how I expected.  Although I believe this fix doesn't change any user-visible behavior, I still think it is important.  Right now the Resource Leak Checker seems to work entirely by accident, and small changes to when it calls `getStoreAfter(node)` cause havoc.
> Fix a latent bug in `AbstractAnalysis.setNodeValues()`

- checker/src/main/java/org/checkerframework/checker/calledmethods/CalledMethodsTransfer.java
- checker/tests/resourceleak/TemporaryVariables.java
- dataflow/src/main/java/org/checkerframework/dataflow/analysis/ConditionalTransferResult.java
- dataflow/src/main/java/org/checkerframework/dataflow/analysis/RegularTransferResult.java
- dataflow/src/main/java/org/checkerframework/dataflow/analysis/TransferResult.java
Previously, the RLC would report an error on this code:
try {
alloc().close();
} catch (IOException e) {
throw e;
}
It would report that the result of `alloc()` was not closed if `close()` throws IOException, which is clearly incorrect.
That test case is meant to be handled by `visitMethodInvocation()` in `RLCCalledMethodsTransfer`, which looks at whether the receiver of a method call has a corresponding temporary variable (which will be true for expressions like `alloc()` that are not normally tracked by flow analysis).
However, the `visitMethodInvocation()` override did not consider exceptional paths.  These were ignored due to an awkward construct in CalledMethodsTransfer.java: a private `exceptionalStores` field enabled `accumulate()` to record information along exceptional control …
> Fix a false positive in the Resource Leak Checker

- dataflow/src/main/java/org/checkerframework/dataflow/cfg/builder/CFGTranslationPhaseOne.java
- dataflow/src/main/java/org/checkerframework/dataflow/cfg/node/AssignmentNode.java
Enhanced for loops over arrays include a desugared assignment of a temporary array to the array iterated over in the CFG. This PR marks assignments created from this desugaring as such in the cfg translation phase 1.
The collection ownership checker has to special case such assignments (rhs will remain the owner in this case), and needs this desugaring information.
> mark desugared assignments of temporary array to traverse enhanced for loop
